/**
 * M13 Batch 4 — Mata, THT, dan Saraf (tier rujuk).
 *
 * Delapan kasus yang semuanya WAJIB dirujuk, tetapi bukan "klik rujuk lalu
 * selesai": yang dinilai adalah mengenali tanda bahaya, mengerjakan yang MEMANG
 * kewenangan FKTP sebelum merujuk (visus, antibiotik dosis-1, akses vena,
 * puasa), menahan diri dari yang di luar lingkup, dan memilih spesialis yang
 * benar.
 */

import type { KasusKlinis, Persona } from '../types'
import type { LabArchetypeSpec } from './batch1'
import { buatKasusLab, type LabQuestionSpec } from './labCaseFactory'

const PPK_FLOOR = 'PPK Dokter FKTP KMK 1186/2022 menjadi floor; terapi disesuaikan dengan pedoman yang lebih baru bila relevan.'

/**
 * `LabQuestionSpec` (labCaseFactory) belum mengenal field `variasi`: batch 1-3
 * ditulis tanpa suara persona sama sekali, lalu diretrofit lewat lapisan
 * `lab/enrichment.ts`. Kontrak sebenarnya sudah mendukungnya —
 * `PertanyaanAnamnesis.variasi` — dan `buatKasusLab` menyalin tiap pertanyaan
 * apa adanya (`...item`), sehingga variasi yang ditulis di sini tetap utuh
 * sampai ke kasus jadi. Batch ini ditulis kaya sejak awal, jadi variasinya
 * ditaruh langsung di kasus dasar; helper di bawah hanya melebarkan pengecekan
 * tipe di titik penulisan, tanpa mengubah perilaku apa pun saat dijalankan.
 *
 * Aman terhadap lapisan pengayaan: `applyLabEnrichment` sengaja me-merge
 * `{ ...q.variasi, ...e.variasi[id] }`, sehingga persona yang ditulis di sini
 * menjadi dasar yang bisa ditambah — bukan ditimpa diam-diam.
 */
const tanya = (q: LabQuestionSpec & { variasi?: Partial<Record<Persona, string>> }): LabQuestionSpec => q

export const LAB_BATCH_4_MTS_CASES: KasusKlinis[] = [
  buatKasusLab({
    id: 'lab_katarak_matur',
    nama: 'Katarak Senilis Lanjut dengan Gangguan Visual Berat',
    icd10: 'H25.9',
    skdi: '2',
    kategori: 'mata',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'tinggi',
    spesialisRujukan: 'mata',
    keluhanUtama: 'Penglihatan saya makin lama makin berkabut putih, Dok, sekarang sudah tidak bisa membaca dan tidak kenal wajah orang.',
    demografi: { usiaMin: 60, usiaMax: 80 },
    vital: { td: '138/82', nadi: 76, rr: 18, suhu: 36.6, spo2: 98 },
    pembuka: {
      tanya: 'Boleh diceritakan bagaimana penglihatan Bapak/Ibu berubah selama ini?',
      jawab: 'Pelan-pelan, Dok, sudah bertahun-tahun. Awalnya cuma seperti berkabut tipis, sekarang seperti melihat lewat kaca yang diembuni terus.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_perlahan',
        kategori: 'rps',
        tanya: 'Apakah kaburnya datang mendadak dalam hitungan jam, atau memberat pelan-pelan?',
        jawab: 'Pelan sekali. Tidak ada satu hari pun yang tiba-tiba gelap; memburuknya seperti tidak terasa.',
        esensial: true,
        oldcarts: ['onset', 'durasi'],
        variasi: {
          lansia: 'Pelan-pelan, Nak... pelan sekali. Tidak pernah mendadak. Dari dulu memang begitu, makin lama makin buram, makin lama makin buram.',
          polos: 'Ndak mendadak, Dok. Ngalon-alon wae. Wis suwe banget.',
        },
      }),
      tanya({
        id: 'q_silau',
        kategori: 'rps',
        tanya: 'Apakah mata terasa silau, terutama siang hari atau kena lampu kendaraan malam hari?',
        jawab: 'Sangat silau. Kalau siang saya lebih suka duduk di dalam rumah, dan malam hari kena lampu motor rasanya menyilaukan sekali sampai tidak kelihatan apa-apa.',
        esensial: true,
        oldcarts: ['agravasi', 'waktu'],
        variasi: {
          lansia: 'Silau, Nak, silau sekali... Kalau siang saya di dalam saja. Kena lampu motor malam itu rasanya seperti disorot, tidak kelihatan apa-apa.',
        },
      }),
      tanya({
        id: 'q_aktivitas',
        kategori: 'rps',
        tanya: 'Sekarang masih bisa membaca, mengenali wajah, atau berjalan sendiri di luar rumah?',
        jawab: 'Sudah tidak bisa membaca sama sekali. Kalau orang datang saya baru tahu siapa setelah dia bersuara. Jalan ke luar rumah harus dipegangi.',
        esensial: true,
        oldcarts: ['keparahan'],
        variasi: {
          lansia: 'Ndak bisa, Nak... baca sudah lama tidak bisa. Orang datang saya tidak tahu siapa, baru tahu kalau sudah bersuara. Jalan pun harus dituntun.',
        },
      }),
      {
        id: 'q_nyeri_merah',
        kategori: 'rps',
        tanya: 'Matanya ada nyeri, merah, berair, atau sakit kepala hebat disertai mual?',
        jawab: 'Tidak ada sama sekali. Matanya tenang, tidak sakit, tidak merah. Hanya tidak bisa melihat saja.',
        esensial: true,
      },
      tanya({
        id: 'q_second_sight',
        kategori: 'rps',
        tanya: 'Beberapa waktu lalu, apakah sempat ada masa penglihatan dekat justru terasa membaik tanpa kacamata?',
        jawab: 'Betul, Dok, aneh sekali. Kira-kira dua tahun lalu saya tiba-tiba bisa membaca lagi tanpa kacamata baca, saya kira sembuh sendiri. Tapi tidak lama, habis itu makin berkabut sampai sekarang.',
        oldcarts: ['waktu'],
        variasi: {
          lansia: 'Iya, Nak, itu yang saya heran... dulu saya sempat bisa baca lagi tanpa kacamata. Saya pikir sudah sembuh. Ternyata cuma sebentar, habis itu tambah putih.',
        },
      }),
      {
        id: 'q_dm_ht',
        kategori: 'rpd',
        tanya: 'Ada kencing manis, darah tinggi, atau penyakit lain yang rutin diobati?',
        jawab: 'Darah tinggi ada, minum obat teratur dari Puskesmas. Kencing manis tidak ada, terakhir diperiksa gulanya bagus.',
        esensial: true,
      },
      tanya({
        id: 'q_tetes_warung',
        kategori: 'rpd',
        tanya: 'Selama ini sudah pakai obat tetes mata apa saja, dari mana belinya?',
        jawab: 'Sudah bertahun-tahun saya pakai tetes mata yang dibilang bisa menghilangkan katarak, beli sendiri di apotek. Tetangga juga menyarankan yang sama. Tidak ada perubahan, Dok.',
        esensial: true,
        variasi: {
          lansia: 'Banyak, Nak... tetes mata macam-macam sudah saya coba. Katanya bisa menghilangkan kataraknya. Sudah bertahun-tahun, ya begini saja, tidak ada bedanya.',
        },
      }),
      {
        id: 'q_trauma_operasi',
        kategori: 'rpd',
        tanya: 'Matanya pernah kena benturan, terkena benda, atau pernah dioperasi?',
        jawab: 'Tidak pernah. Belum pernah dioperasi apa pun.',
      },
      {
        id: 'q_distraktor_asap',
        kategori: 'sosial',
        tanya: 'Apakah Bapak/Ibu sering terkena asap dapur atau debu di rumah?',
        jawab: 'Ya masak pakai kayu memang masih, Dok, tapi sudah dari muda begitu. Anak-anak yang lain tidak apa-apa matanya.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_tv',
        kategori: 'sosial',
        tanya: 'Apakah kebiasaan menonton televisi terlalu dekat atau membaca di tempat remang membuat ini terjadi?',
        jawab: 'Kata orang-orang begitu, Dok, makanya sekarang saya tidak berani nonton dekat-dekat. Tapi ya tetap saja tidak membaik.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'mata', temuan: 'Manik mata tampak putih keabuan pada kedua mata, kanan lebih padat; refleks fundus hilang sehingga dasar mata tidak dapat dinilai. Mata tenang dan tidak merah.', relevan: true },
      { region: 'umum', temuan: 'Lansia mandiri sebagian, harus dituntun saat berjalan ke ruang periksa; tidak tampak sakit.', relevan: true },
      { region: 'neurologis', temuan: 'Tidak ada kelumpuhan, bicara jelas, lapang pandang kasar sulit dinilai karena penglihatan yang sangat turun.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada benjolan, tidak ada nyeri tekan.', relevan: false },
      { region: 'jantung', temuan: 'Bunyi jantung normal, irama teratur, tanpa bising.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['H25.9', 'H40.2', 'H36.0'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'air_mata_buatan', alasan: 'Air mata buatan hanya melembapkan permukaan mata dan tidak mengubah lensa yang sudah keruh sama sekali. Bahayanya bukan pada obatnya, melainkan pada rasa "sudah diobati" yang membuat pasien dan dokter menunda operasi selama bertahun-tahun.', bahaya: 'nonPrimer' },
        { id: 'kloramfenikol_tetes_mata', alasan: 'Mata tenang tanpa merah, kotoran, atau nyeri: tidak ada infeksi yang diobati. Antibiotik tetes di sini murni salah sasaran dan menambah tekanan resistansi tanpa manfaat.', bahaya: 'nonPrimer' },
        { id: 'timolol_tetes_mata', alasan: 'Penurun tekanan bola mata diberikan "untuk berjaga-jaga" padahal tidak ada bukti tekanan bola mata meninggi. Timolol adalah penyekat beta yang terserap sistemik dan dapat memperlambat denyut jantung serta memicu sesak pada lansia.', bahaya: 'kontraindikasi' },
      ],
      prosedur: ['uji_visus_refraksi'],
      edukasi: ['persiapan_rujukan_operatif', 'perlindungan_mata', 'tanda_bahaya_mata', 'kontrol_rutin'],
      edukasiKritis: ['persiapan_rujukan_operatif'],
    },
    clue: 'Penurunan penglihatan perlahan bertahun-tahun, silau berat, kekeruhan lensa putih-keabuan, dan hilangnya refleks fundus mendukung katarak senilis lanjut dengan gangguan fungsi berat. Tidak ada tetes mata, obat, atau suplemen yang melarutkan kekeruhan lensa; terapi definitif adalah operasi katarak setelah asesmen spesialis. Tugas FKTP adalah mengukur tajam penglihatan dan dampak fungsional, menyingkirkan tanda mata akut merah-nyeri, lalu menghubungkan pasien ke layanan mata.',
    panduanResmi: `${PPK_FLOOR} PPK 1186/2022 dan PNPK Katarak Dewasa 2026 menempatkan deteksi, penilaian tajam penglihatan serta fungsi, dan rujukan sebagai peran FKTP. Gangguan penglihatan yang bermakna atau katarak lanjut dirujuk agar spesialis menentukan kelayakan, waktu, dan teknik operasi; tidak ada terapi farmakologis yang menggantikan operasi.`,
    catatanRealita: 'Profil sukmaju_middle_v1 tidak mengasumsikan layanan operasi mata di Puskesmas. Rujukan belum selesai hanya dengan mencetak surat: pastikan jalur layanan mata, pendamping, transportasi, dan hambatan pasien tercatat, lalu berikan safety-net bila mata menjadi merah-nyeri atau penglihatan turun mendadak.',
    mutiaraEbm: 'Keputusan operasi katarak tidak ditentukan oleh warna lensa atau satu angka visus saja, melainkan dampak penglihatan terhadap fungsi, tujuan pasien, penyakit mata penyerta, serta manfaat-risiko operasi. "Second sight" dapat terjadi ketika perubahan indeks lensa membuat penglihatan dekat sementara terasa lebih baik; itu bukan tanda katarak sembuh.',
    konsekuensi: {
      narasi: 'Pada cabang simulasi ini, pasien terus diberi tetes mata tanpa jalur rujukan. Disabilitas penglihatannya menetap, aktivitas harian makin bergantung pada keluarga, dan ia kemudian jatuh saat berjalan sendiri di rumah.',
      kembaliHariMin: 60,
      kembaliHariMax: 180,
      kondisiKembali: 'Kembali setelah jatuh dengan memar dan ketakutan berjalan sendiri; katarak masih belum tertangani. Mata merah-nyeri akut tetap dijelaskan sebagai tanda bahaya yang mungkin terjadi pada komplikasi lensa, bukan akibat yang pasti muncul dalam beberapa minggu.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022; PNPK Katarak Dewasa KMK 67/2026; WHO Quality of Care in Cataract Surgery Management 2026',
    },
  }),

  buatKasusLab({
    id: 'lab_ablasio_retina',
    nama: 'Ablasio Retina Regmatogen — Tirai Hitam Tanpa Nyeri',
    icd10: 'H33.0',
    skdi: '2',
    kategori: 'mata',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'mata',
    keluhanUtama: 'Mata kanan saya mendadak seperti ada tirai hitam naik dari bawah menutupi pandangan, Dok, tapi sama sekali tidak sakit.',
    demografi: { usiaMin: 45, usiaMax: 70 },
    vital: { td: '134/80', nadi: 78, rr: 18, suhu: 36.7, spo2: 98 },
    pembuka: {
      tanya: 'Coba ceritakan persis apa yang Bapak/Ibu lihat dan sejak kapan?',
      jawab: 'Kemarin sore tiba-tiba ada kilatan seperti petir kecil di pinggir mata kanan, lalu muncul bintik-bintik hitam banyak sekali melayang. Tadi pagi bagian bawah pandangan seperti ditutup kain hitam, dan sekarang kainnya sudah naik sampai setengah.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_kilatan_floaters',
        kategori: 'rps',
        tanya: 'Kilatan cahaya dan bintik melayangnya muncul lebih dulu atau bersamaan dengan tirainya?',
        jawab: 'Kilatan dan bintik-bintiknya duluan, kemarin sore. Tirai hitamnya baru tadi pagi. Bintiknya banyak sekali, seperti hujan jelaga.',
        esensial: true,
        oldcarts: ['onset', 'waktu', 'karakter'],
        variasi: {
          cemas: 'Duluan yang kilatan, Dok, kemarin sore! Seperti ada petir kecil di pojok mata, saya kira mau pingsan. Terus muncul bintik hitam banyak sekali seperti jelaga beterbangan, saya sampai tidak bisa tidur. Ini kenapa, Dok? Saya mau buta ya?',
          terpelajar: 'Urutannya jelas, Dok: kemarin sekitar pukul lima sore muncul kilatan di sisi luar mata kanan, lalu bintik-bintik hitam yang melayang mengikuti gerakan mata. Tirai gelapnya baru tadi pagi sekitar pukul enam.',
        },
      }),
      {
        id: 'q_arah_tirai',
        kategori: 'rps',
        tanya: 'Tirainya menutup dari arah mana, dan apakah masih bertambah?',
        jawab: 'Dari bawah naik ke atas. Kemarin baru sedikit di pinggir bawah, sekarang sudah sampai tengah. Bagian tengah pandangan masih bisa lihat, tapi makin sempit.',
        esensial: true,
        oldcarts: ['lokasi', 'keparahan'],
      },
      {
        id: 'q_nyeri_merah',
        kategori: 'rps',
        tanya: 'Matanya nyeri, merah, atau ada sakit kepala dan mual?',
        jawab: 'Sama sekali tidak. Itu yang bikin saya sempat menunda ke sini, karena tidak sakit sedikit pun dan matanya kelihatan biasa saja.',
        esensial: true,
      },
      tanya({
        id: 'q_miopia',
        kategori: 'rpd',
        tanya: 'Kacamatanya minus berapa, dan sejak kapan pakai kacamata?',
        jawab: 'Minus tinggi, Dok, minus delapan. Sudah pakai kacamata sejak SMP, tebal sekali kacanya.',
        esensial: true,
        variasi: {
          terpelajar: 'Minus delapan pada mata kanan dan minus tujuh setengah di kiri, Dok. Sudah sejak SMP saya berkacamata, dan tiap beberapa tahun bertambah.',
        },
      }),
      {
        id: 'q_trauma',
        kategori: 'rpd',
        tanya: 'Belakangan ini matanya pernah terbentur, atau ada kegiatan mengangkat beban berat?',
        jawab: 'Tidak ada benturan. Cuma tiga hari lalu saya bantu angkat lemari di rumah anak saya.',
        esensial: true,
      },
      {
        id: 'q_operasi_mata',
        kategori: 'rpd',
        tanya: 'Mata yang ini atau sebelahnya pernah dioperasi, misalnya operasi katarak?',
        jawab: 'Belum pernah dioperasi sama sekali, Dok.',
      },
      {
        id: 'q_mata_sebelah',
        kategori: 'rps',
        tanya: 'Mata kiri bagaimana, ada kilatan atau bintik melayang juga?',
        jawab: 'Mata kiri masih baik. Tidak ada kilatan, tidak ada bintik.',
      },
      {
        id: 'q_dm',
        kategori: 'rpd',
        tanya: 'Ada kencing manis atau darah tinggi?',
        jawab: 'Tidak ada. Terakhir cek gula dan tensi di Posbindu semuanya bagus.',
      },
      {
        id: 'q_distraktor_gadget',
        kategori: 'sosial',
        tanya: 'Apakah akhir-akhir ini terlalu lama menatap layar ponsel atau komputer?',
        jawab: 'Lumayan sering, Dok, apalagi kalau malam. Apa gara-gara itu ya? Anak saya juga bilang begitu.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_darah_tinggi_keluarga',
        kategori: 'rpk',
        tanya: 'Di keluarga ada yang punya darah tinggi atau kolesterol?',
        jawab: 'Bapak saya dulu darah tinggi. Tapi saya sendiri tensinya selalu normal.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'mata', temuan: 'Mata kanan putih dan tenang: tidak ada kemerahan atau kotoran. Lapang pandang uji konfrontasi kanan hilang pada separuh bawah. Refleks pupil langsung kanan tampak lebih lambat dibanding kiri. Mata kiri dalam batas normal.', relevan: true },
      { region: 'umum', temuan: 'Tampak tenang dan tidak kesakitan sama sekali; kooperatif, berjalan sendiri.', relevan: true },
      { region: 'neurologis', temuan: 'Bicara jelas, kekuatan keempat anggota gerak penuh, tidak ada wajah mencong; lapang pandang mata kiri utuh sehingga kelainan terbatas pada satu mata saja.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada nyeri tekan di sekitar mata dan pelipis; tidak teraba benjolan.', relevan: false },
      { region: 'jantung', temuan: 'Irama teratur, tidak ada bising.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['H33.0', 'H43.1', 'H34.1'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'timolol_tetes_mata', alasan: 'Urutan kilatan-floaters-tirai pada mata putih tanpa nyeri menunjuk ke segmen posterior, bukan serangan glaukoma sudut tertutup. Timolol tidak menempelkan retina dan percobaan tetes mata hanya menunda pemeriksaan retina serta rujukan yang mendesak.', bahaya: 'kontraindikasi' },
        { id: 'kloramfenikol_tetes_mata', alasan: 'Tidak ada tanda infeksi apa pun: mata putih, tenang, tanpa kotoran. Meresepkannya menciptakan ilusi bahwa keluhan sudah ditangani dan menunda rujukan yang hitungannya jam.', bahaya: 'nonPrimer' },
        { id: 'air_mata_buatan', alasan: 'Keluhan bintik melayang sering disalahartikan sebagai "mata kering". Pelumas permukaan mata tidak berpengaruh sedikit pun pada robekan retina di dalam bola mata.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['uji_visus_refraksi'],
      edukasi: ['tanda_bahaya_mata', 'perlindungan_mata', 'kontrol_rutin'],
      edukasiKritis: ['tanda_bahaya_mata'],
    },
    clue: 'Kilatan cahaya dan hujan bintik melayang yang mendadak, diikuti tirai gelap progresif pada mata putih tanpa nyeri, sangat mencurigakan ablasio retina regmatogen, terlebih pada miopia tinggi. Penglihatan sentral yang masih tersisa membuat makula mungkin belum terlibat, tetapi status macula-on tidak boleh dipastikan tanpa pemeriksaan retina pupil lebar. Yang benar di FKTP: dokumentasikan tajam penglihatan dan lapang pandang kasar, jangan mencoba tetes mata, lalu atur penilaian spesialis mata pada hari yang sama.',
    panduanResmi: 'Tidak ditemukan bab diagnosis-spesifik di PPK 1186/2022. Pada kompetensi SKDI 2, dokter FKTP mengenali sindrom penurunan penglihatan mendadak pada mata tenang dan merujuk segera. AAO PPP 2024 menempatkan kilatan atau floaters akut sebagai pemicu pemeriksaan retina perifer dengan dilatasi untuk menyingkirkan robekan atau ablasio; pemeriksaan tersebut tidak digantikan oleh tonometri, obat tetes, atau observasi di rumah.',
    catatanRealita: 'Profil sukmaju_middle_v1 tidak mengasumsikan oftalmoskopi retina perifer, ultrasonografi mata, atau bedah vitreoretina siap di Puskesmas. Hubungi jejaring rujukan pada hari yang sama untuk memastikan fasilitas tujuan dapat menilai retina dan menerima pasien; bila kapasitas pertama tidak tersedia, eskalasi ke jejaring berikutnya alih-alih menunda kontrol lokal.',
    mutiaraEbm: 'Mata putih dan tanpa nyeri bukan tanda aman. Kilatan baru, lonjakan floaters, atau bayangan seperti tirai dapat mendahului kehilangan penglihatan sentral; pemeriksaan konfirmasi membutuhkan visualisasi retina perifer dengan dilatasi. Pertanyaan kunci FKTP bukan "berapa tekanan bolanya", melainkan "apakah ada sindrom robekan atau ablasio yang harus dinilai retina hari ini?"',
    konsekuensi: {
      narasi: 'Pada cabang simulasi ini, pasien diberi tetes mata dan diminta kontrol minggu berikutnya karena matanya tidak merah atau nyeri. Dalam dua hari bayangan mencapai pusat penglihatan sebelum ia memperoleh pemeriksaan retina.',
      kembaliHariMin: 1,
      kembaliHariMax: 3,
      kondisiKembali: 'Kembali dengan penurunan tajam penglihatan sentral yang berat. Pemeriksaan spesialis menunjukkan ablasio telah melibatkan makula; operasi tetap diperlukan, tetapi peluang pemulihan penglihatan sentral kini lebih buruk dan hasil akhirnya tidak dapat dijanjikan.',
      guideline: 'AAO Preferred Practice Pattern 2024 — Posterior Vitreous Detachment, Retinal Breaks, and Lattice Degeneration',
    },
  }),

  buatKasusLab({
    id: 'lab_retinopati_diabetik_proliferatif',
    nama: 'Suspek Retinopati Diabetik Mengancam Penglihatan',
    icd10: 'H36.0',
    skdi: '2',
    kategori: 'mata',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'mata',
    keluhanUtama: 'Penglihatan saya makin kabur beberapa bulan ini, Dok, kadang ada bercak merah kehitaman yang melayang-layang.',
    demografi: { usiaMin: 45, usiaMax: 65 },
    vital: { td: '148/88', nadi: 84, rr: 18, suhu: 36.6, spo2: 98, gds: 268 },
    pembuka: {
      tanya: 'Sejak kapan penglihatannya kabur, dan bercak melayang itu seperti apa?',
      jawab: 'Kaburnya sudah sekitar enam bulan, makin lama makin. Bercaknya seperti benang merah atau asap yang melayang, muncul beberapa kali lalu hilang sendiri setelah beberapa hari. Kemarin muncul lagi lebih banyak.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_lama_dm',
        kategori: 'rpd',
        tanya: 'Sudah berapa lama kena kencing manis, dan obatnya apa saja?',
        jawab: 'Sudah dua belas tahun, Dok. Minum obat gula dari Puskesmas, tapi jujur saja sering putus. Kalau badan enak saya berhenti dulu, nanti kalau sudah lemas baru minum lagi.',
        esensial: true,
        oldcarts: ['durasi'],
        variasi: {
          terpelajar: 'Terdiagnosis sejak tahun 2014, Dok, jadi kurang lebih dua belas tahun. Obatnya metformin dua kali sehari dari Puskesmas. Terus terang kepatuhan saya buruk: sering saya hentikan sendiri kalau merasa badan sudah enak.',
          polos: 'Wis suwe, Dok, sepuluh tahunan lebih. Obate diminum nek kelingan wae. Nek awak kepenak yo ora tak minum.',
        },
      }),
      {
        id: 'q_kontrol_gula',
        kategori: 'rpd',
        tanya: 'Terakhir periksa gula darah kapan dan berapa hasilnya?',
        jawab: 'Sudah lama, Dok, mungkin setahun lalu. Waktu itu tinggi, dua ratus sekian. Setelah itu saya tidak pernah kontrol lagi.',
        esensial: true,
      },
      tanya({
        id: 'q_skrining_mata',
        kategori: 'rpd',
        tanya: 'Selama dua belas tahun kena kencing manis, apakah pernah sekali pun matanya diperiksa oleh dokter mata?',
        jawab: 'Tidak pernah sama sekali, Dok. Tidak ada yang pernah menyuruh. Saya kira kalau mata tidak sakit ya tidak perlu diperiksa.',
        esensial: true,
        variasi: {
          terpelajar: 'Belum pernah, Dok, tidak sekali pun. Dan sejujurnya tidak ada yang pernah menganjurkan. Saya baru tahu sekarang bahwa kencing manis bisa merusak mata.',
          skeptis: 'Tidak pernah. Buat apa? Mata saya waktu itu tidak ada keluhan apa-apa. Kalau tiap tahun disuruh periksa mata padahal tidak sakit, itu namanya cari-cari kerjaan.',
        },
      }),
      {
        id: 'q_bercak_melayang',
        kategori: 'rps',
        tanya: 'Bercak melayangnya muncul mendadak lalu hilang sendiri, atau menetap?',
        jawab: 'Mendadak muncul, Dok, biasanya pagi begitu bangun tidur. Lalu memudar sendiri dalam beberapa hari. Sudah tiga kali begini dalam tiga bulan.',
        esensial: true,
        oldcarts: ['onset', 'waktu', 'karakter'],
      },
      {
        id: 'q_tirai_gelap',
        kategori: 'rps',
        tanya: 'Pernah ada tirai gelap yang menutup, atau kilatan cahaya?',
        jawab: 'Tidak ada tirai. Kilatan juga tidak. Cuma kabur merata dan bercak melayang itu.',
        esensial: true,
      },
      {
        id: 'q_nyeri_merah',
        kategori: 'rps',
        tanya: 'Matanya nyeri atau merah?',
        jawab: 'Tidak, Dok. Tidak pernah sakit, tidak pernah merah.',
      },
      {
        id: 'q_ginjal_kaki',
        kategori: 'rpd',
        tanya: 'Ada kaki kesemutan, luka yang sulit sembuh, atau bengkak di kaki?',
        jawab: 'Kaki sering kesemutan dan kebas, Dok, terutama malam. Bengkak tidak ada. Luka juga belum pernah.',
        esensial: true,
      },
      {
        id: 'q_merokok',
        kategori: 'sosial',
        tanya: 'Masih merokok?',
        jawab: 'Masih, Dok, sekitar sepuluh batang sehari. Sudah dari muda.',
      },
      {
        id: 'q_distraktor_wortel',
        kategori: 'sosial',
        tanya: 'Apakah pola makannya kurang sayur dan wortel?',
        jawab: 'Ya, jarang makan sayur, Dok. Istri saya juga bilang ini gara-gara kurang wortel. Perlu saya minum vitamin mata tidak?',
        distraktor: true,
      },
      {
        id: 'q_distraktor_kacamata',
        kategori: 'rps',
        tanya: 'Apakah sudah coba ganti kacamata baru untuk mengatasi kaburnya?',
        jawab: 'Sudah, Dok, dua kali ganti dalam setahun ini. Di optik dibilang minusnya berubah-ubah terus. Tapi diganti pun tetap kabur.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'mata', temuan: 'Kedua mata putih dan tenang, tidak nyeri. Lensa masih cukup jernih. Manik mata bereaksi normal terhadap cahaya. Dasar mata tidak dapat dinilai memadai dengan alat yang tersedia; tampak keruh ringan pada mata kanan seolah ada kabut merah di depan dasar mata.', relevan: true },
      { region: 'ekstremitas', temuan: 'Rasa raba dan getar menurun simetris pada kedua telapak kaki; denyut nadi kaki masih teraba; tidak ada luka.', relevan: true },
      { region: 'umum', temuan: 'Bentuk badan gemuk sedang, tampak tidak sakit berat.', relevan: true },
      { region: 'jantung', temuan: 'Irama teratur, tidak ada bising, tidak ada bengkak di tungkai.', relevan: false },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['H36.0', 'H43.1', 'H33.0'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'vitamin_b_kompleks', alasan: 'Diberikan sebagai "obat saraf mata" atau vitamin penguat penglihatan. Tidak ada bukti bahwa vitamin B mengubah perjalanan retinopati diabetik, dan pemberiannya memperkuat keyakinan pasien bahwa matanya sudah ditangani sehingga rujukan terasa tidak perlu.', bahaya: 'nonPrimer' },
        { id: 'kloramfenikol_tetes_mata', alasan: 'Mata putih dan tenang tanpa tanda infeksi sedikit pun. Antibiotik tetes di sini murni salah sasaran.', bahaya: 'nonPrimer' },
        { id: 'asam_traneksamat_500_inj', alasan: 'Refleks "ada perdarahan maka beri antiperdarahan" tidak berlaku di sini: perdarahan berasal dari pembuluh darah baru yang rapuh akibat retina yang kekurangan oksigen, dan hanya laser atau anti-VEGF yang mengatasi sumbernya. Pada penyandang diabetes lama dengan pembuluh darah yang sudah sakit, obat ini menambah risiko sumbatan pembuluh tanpa satu pun manfaat yang terbukti.', bahaya: 'kontraindikasi' },
      ],
      prosedur: ['uji_visus_refraksi'],
      edukasi: ['skrining_retinopati_diabetik', 'tanda_bahaya_mata', 'diet_dm', 'kepatuhan_obat', 'berhenti_merokok', 'perawatan_kaki_diabetik'],
      edukasiKritis: ['skrining_retinopati_diabetik'],
    },
    clue: 'Diabetes tipe 2 lama dengan kendali buruk, penurunan penglihatan, dan episode bercak merah-kehitaman yang muncul-memudar menimbulkan kecurigaan retinopati diabetik yang mengancam penglihatan dengan kemungkinan perdarahan vitreus. Karena dasar mata tidak dapat dinilai memadai, dokter FKTP tidak boleh mengunci stadium proliferatif atau menganggap semua perdarahan vitreus pasti berasal dari diabetes; robekan dan ablasio retina tetap harus disingkirkan oleh dokter mata. Tindakan saat ini adalah ukur visus, rujuk segera untuk pemeriksaan retina, dan jadwalkan tinjauan DM komprehensif terpisah — bukan menjadikan satu resep metformin atau statin sebagai terapi akut mata.',
    panduanResmi: `${PPK_FLOOR} PPK 1186/2022 dan PNPK Retinopati Diabetika 2023 menempatkan deteksi, pengendalian faktor risiko sistemik, dan rujukan sebagai peran FKTP; stadium retina memerlukan visualisasi fundus yang memadai. ADA Standards of Care 2026 meminta pemeriksaan mata saat diagnosis DM tipe 2, interval 1–2 tahun hanya dapat dipertimbangkan setelah satu atau lebih pemeriksaan normal dengan glikemia dalam sasaran, sekurang-kurangnya tahunan bila retinopati ada, dan lebih sering bila progresif atau mengancam penglihatan. Rujuk segera bila ada retinopati sedang-berat, edema makula, atau dugaan PDR.`,
    catatanRealita: 'Profil sukmaju_middle_v1 tidak menganggap kamera fundus, funduskopi dilatasi, OCT, atau HbA1c selalu siap. Kenali risiko dari temuan yang ada dan hubungkan pasien ke pemeriksaan retina tervalidasi; foto yang tak dapat dinilai atau abnormal tetap perlu pemeriksaan langsung. Tinjauan obat DM dilakukan terpisah setelah menilai fungsi ginjal, risiko hipoglikemia, kepatuhan, komorbid, dan regimen aktual.',
    mutiaraEbm: 'Retinopati yang mengancam penglihatan dapat lama tanpa gejala, sehingga skrining tidak boleh menunggu mata sakit atau kabur. Penurunan HbA1c yang cepat pada orang dengan retinopati memang dapat disertai perburukan awal sementara, tetapi retinopati bukan alasan mempertahankan hiperglikemia: nilai retina ketika terapi glukosa diintensifkan, koordinasikan tindak lanjut mata, dan tetap kejar kendali metabolik jangka panjang secara individual.',
    konsekuensi: {
      narasi: 'Pada cabang simulasi ini, pasien pulang dengan vitamin mata tanpa rujukan karena matanya tidak merah atau nyeri. Perdarahan vitreus berikutnya lebih padat dan menutup penglihatan sebelum retina dapat dinilai serta diterapi.',
      kembaliHariMin: 30,
      kembaliHariMax: 90,
      kondisiKembali: 'Kembali dengan mata kanan mendadak sangat gelap akibat perdarahan vitreus padat. Spesialis harus menilai retina dengan modalitas yang sesuai dan menentukan apakah diperlukan laser, anti-VEGF, atau vitrektomi; prognosis bergantung pada penyebab, kondisi makula, traksi, dan ketepatan waktu penanganan.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022; PNPK Retinopati Diabetika KMK 1914/2023; ADA Standards of Care in Diabetes 2026',
    },
  }),

  buatKasusLab({
    id: 'lab_otitis_media_supuratif_kronik_komplikata',
    nama: 'OMSK Tipe Bahaya — Curiga Kolesteatoma',
    icd10: 'H66.3',
    skdi: '3A',
    kategori: 'tht',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'tht',
    keluhanUtama: 'Telinga kiri saya sudah bertahun-tahun keluar cairan bau busuk, Dok, tapi belakangan pendengarannya turun drastis dan kepala saya sering nyeri.',
    demografi: { usiaMin: 15, usiaMax: 40 },
    vital: { td: '118/76', nadi: 88, rr: 18, suhu: 37.4, spo2: 98 },
    pembuka: {
      tanya: 'Sudah berapa lama telinganya berair, dan apa yang berubah belakangan ini?',
      jawab: 'Sudah dari kecil, Dok, hilang timbul bertahun-tahun. Baunya busuk sekali sampai orang di sebelah saya bisa mencium. Yang berubah tiga bulan ini: pendengarannya turun cepat sekali, dan kepala saya sering nyeri di sisi kiri.',
      oldcarts: ['onset', 'durasi', 'karakter', 'penyerta'],
    },
    pertanyaan: [
      tanya({
        id: 'q_sifat_cairan',
        kategori: 'rps',
        tanya: 'Cairannya seperti apa, dan apakah baunya menetap meski sudah dibersihkan?',
        jawab: 'Kental, agak kekuningan, sedikit tapi terus-menerus. Baunya busuk sekali dan tidak hilang walau saya bersihkan tiap hari. Kadang ada gumpalan putih seperti remah.',
        esensial: true,
        oldcarts: ['karakter'],
        variasi: {
          polos: 'Kentel, Dok, kuning-kuning dikit-dikit tapi terus. Mambune banger tenan. Kadang ada putih-putih kayak remahan kerak gitu.',
        },
      }),
      tanya({
        id: 'q_pendengaran',
        kategori: 'rps',
        tanya: 'Penurunan pendengarannya seberapa cepat, dan sudah sampai tingkat apa?',
        jawab: 'Dulu masih bisa dengar walau berkurang. Tiga bulan ini turun cepat sekali. Sekarang kalau orang bicara di sisi kiri saya hampir tidak dengar, harus menoleh.',
        esensial: true,
        oldcarts: ['onset', 'keparahan'],
        variasi: {
          terpelajar: 'Dulu penurunannya bertahap dan masih bisa saya siasati, Dok. Tapi tiga bulan terakhir jelas berbeda: cepat sekali. Sekarang kalau orang bicara di sisi kiri, saya praktis tidak menangkap apa pun, harus menoleh supaya telinga kanan yang menerima.',
          skeptis: 'Ya menurun. Tapi orang tua saya juga pendengarannya berkurang, itu wajar kan? Memang tiga bulan ini agak cepat. Bukan berarti harus dioperasi, kan?',
        },
      }),
      {
        id: 'q_nyeri_kepala',
        kategori: 'rps',
        tanya: 'Nyeri kepalanya seperti apa, dan apakah berbeda dari sakit kepala biasa?',
        jawab: 'Di sisi kiri, di belakang telinga sampai ke atas. Bukan seperti sakit kepala biasa, ini terasa dalam dan makin sering. Kadang bangun tidur sudah nyeri.',
        esensial: true,
        oldcarts: ['lokasi', 'karakter', 'waktu'],
      },
      {
        id: 'q_pusing_berputar',
        kategori: 'rps',
        tanya: 'Pernah pusing berputar, terutama saat telinganya dibersihkan atau kemasukan air?',
        jawab: 'Iya, Dok! Sebulan ini beberapa kali. Kalau saya korek atau kena air, ruangan terasa berputar beberapa detik lalu berhenti.',
        esensial: true,
      },
      {
        id: 'q_wajah',
        kategori: 'rps',
        tanya: 'Ada wajah yang terasa mencong, sulit menutup mata, atau air minum bocor dari sudut bibir?',
        jawab: 'Belum ada. Wajah saya masih normal.',
        esensial: true,
      },
      {
        id: 'q_demam_kaku',
        kategori: 'rps',
        tanya: 'Ada demam tinggi, leher kaku, mual muntah menyembur, atau kejang?',
        jawab: 'Tidak ada. Badan cuma agak hangat kadang-kadang.',
        esensial: true,
      },
      tanya({
        id: 'q_pengobatan',
        kategori: 'rpd',
        tanya: 'Selama bertahun-tahun ini sudah diobati apa saja?',
        jawab: 'Bolak-balik ke Puskesmas dan klinik, Dok. Tiap kali dikasih antibiotik minum, kering seminggu dua minggu, lalu kambuh lagi. Sudah entah berapa kali. Belum pernah dirujuk.',
        esensial: false,
        variasi: {
          terpelajar: 'Sudah berkali-kali, Dok, saya sampai hafal polanya: diberi antibiotik minum, telinga kering sekitar satu-dua minggu, lalu berair lagi. Begitu terus sejak SD. Tidak pernah ada yang menyarankan saya ke dokter spesialis.',
          polos: 'Wis kerep, Dok. Saben mrene dikeki antibiotik ngombe, garing seminggu rong minggu, mengko kumat maneh. Ngono terus. Ora tau dikongkon nang dokter spesialis.',
        },
      }),
      {
        id: 'q_tetes_telinga',
        kategori: 'rpd',
        tanya: 'Pernah pakai obat tetes telinga? Yang mana?',
        jawab: 'Pernah beberapa kali beli sendiri di apotek, katanya tetes telinga antibiotik. Dipakai beberapa hari saja lalu berhenti.',
      },
      {
        id: 'q_distraktor_cotton_bud',
        kategori: 'sosial',
        tanya: 'Apakah sering membersihkan telinga dengan cotton bud atau korek kuping?',
        jawab: 'Sering, Dok, hampir tiap hari. Habis mandi pasti saya korek biar kering. Apa gara-gara itu ya?',
        distraktor: true,
      },
      {
        id: 'q_distraktor_alergi',
        kategori: 'rpd',
        tanya: 'Apakah punya alergi debu atau sering bersin-bersin di pagi hari?',
        jawab: 'Kalau pagi memang suka bersin-bersin, Dok, apalagi kalau nyapu. Sudah dari dulu begitu.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Liang telinga kiri berisi sekret kental kekuningan berbau sangat busuk. Setelah dibersihkan tampak lubang pada gendang telinga di bagian ATAS-PINGGIR (bukan di tengah), dengan jaringan granulasi rapuh di tepinya dan gumpalan putih seperti serpihan kulit di dalam rongga. Telinga kanan tenang, gendang telinga utuh.', relevan: true },
      { region: 'kepala_leher', temuan: 'Daerah belakang telinga kiri tidak bengkak, tidak merah, dan tidak nyeri ditekan; lekukan di belakang daun telinga masih terlihat jelas dan daun telinga tidak terdorong.', relevan: true },
      { region: 'neurologis', temuan: 'Saraf wajah kiri masih berfungsi penuh: dahi berkerut simetris, mata dapat menutup rapat, sudut bibir simetris. Tidak ada kaku kuduk. Kesadaran penuh, tidak ada kelumpuhan anggota gerak.', relevan: true },
      { region: 'umum', temuan: 'Tampak sehat, gizi cukup, tidak tampak sakit berat.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Hb 13,8 g/dL, leukosit 9.200/uL, trombosit 288.000/uL.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['H66.3', 'H60.3', 'H70.0'],
    tatalaksana: {
      obatBenar: [],
      prosedur: ['pembersihan_telinga_kering_pra_rujuk'],
      obatSalahUmum: [
        { id: 'gentamisin_tetes_mata', alasan: 'Tetes mata gentamisin bukan sediaan otik yang tervalidasi untuk kasus ini. Pada membran timpani yang berlubang, aminoglikosida dapat mencapai telinga tengah dan membawa risiko ototoksisitas. Bila antibiotik topikal diperlukan, gunakan sediaan non-ototoksik yang memang tersedia dan disepakati dalam protokol; jangan mengimprovisasi tetes mata atau aminoglikosida.', bahaya: 'kontraindikasi' },
        { id: 'amoxicillin_500', alasan: 'Antibiotik sistemik dapat diperlukan bila ada eksaserbasi berat atau infeksi sistemik, tetapi pasien ini tidak demam tinggi atau toksik dan masalah utamanya adalah dugaan kolesteatoma berkomplikasi. Amoksisilin empiris berulang tanpa pemeriksaan, perawatan telinga, dan rujukan tidak menghilangkan kolesteatoma serta menciptakan rasa aman palsu.', bahaya: 'nonPrimer' },
        { id: 'karbogliserin_tetes', alasan: 'Diberikan karena tampak "ada kotoran menumpuk di liang telinga". Obat ini adalah pelunak kotoran telinga, bukan terapi infeksi, dan yang menumpuk di sini bukan serumen melainkan serpihan kolesteatoma. Selain salah sasaran, obat ini justru membasahi telinga yang seharusnya dijaga tetap kering.', bahaya: 'nonPrimer' },
      ],
      tindakanSalahUmum: [
        { id: 'ekstraksi_serumen', alasan: 'Membersihkan telinga dengan penyemprotan air (irigasi) adalah tindakan baku untuk kotoran telinga pada gendang yang UTUH. Di sini gendang telinga berlubang: air bertekanan masuk langsung ke telinga tengah, menyiram rongga yang sudah terinfeksi, memicu pusing berputar hebat karena telinga dalam terangsang dingin, dan berisiko mendorong kuman lebih dalam. Pada telinga berlubang, pembersihan dikerjakan kering (diusap/disedot), bukan disemprot.', bahaya: 'berbahaya' },
      ],
      edukasi: ['jaga_telinga_kering', 'tanda_bahaya', 'kontrol_rutin'],
      edukasiKritis: ['jaga_telinga_kering'],
    },
    clue: 'Otore kronik berbau, perforasi atik atau marginal, granulasi, debris putih, penurunan pendengaran progresif, nyeri kepala, dan vertigo menimbulkan kecurigaan kuat OMSK tipe bahaya dengan kolesteatoma serta kemungkinan komplikasi labirin. Vertigo saat tekanan atau manipulasi meningkatkan kecurigaan fistula labirin, tetapi tidak membuktikan erosi tulang tanpa evaluasi spesialis dan pencitraan. Di FKTP: nilai saraf wajah dan tanda intrakranial, bersihkan sekret secara kering tanpa irigasi, jaga telinga tetap kering, hindari tetes ototoksik atau produk yang kontraindikasi pada perforasi, dan rujuk cepat ke THT. Kolesteatoma memerlukan penilaian bedah; antibiotik hanya menangani infeksi penyerta, bukan menghilangkan lesinya.',
    panduanResmi: `${PPK_FLOOR} PPK 1186/2022 memisahkan OMSK aman dari tipe bahaya dan mewajibkan rujukan pada kolesteatoma atau komplikasi. Namun rekomendasi PPK untuk asam asetat 2% tidak dipakai pada vignette ini karena label produk DailyMed 2025 yang sudah tersimpan dalam registry proyek mencantumkan membran timpani perforasi sebagai kontraindikasi. Queensland Health CSOM Criteria, diperbarui 2025, menganjurkan dry mopping, menjaga telinga kering, kuinolon topikal non-ototoksik bila tersedia, dan rujukan untuk dugaan kolesteatoma; kasus dengan vertigo, nyeri kepala, atau defisit saraf memerlukan jalur lebih mendesak.`,
    catatanRealita: 'Fornas 1199/2025 mencantumkan asam asetat 2% tetapi tidak menyediakan kuinolon otik pada daftar yang dipakai proyek. Karena pasien ini memiliki perforasi dan tanda komplikasi, Sukamaju tidak mengimprovisasi pengganti: lakukan pembersihan kering, proteksi dari air, dan percepat rujukan. Ketersediaan tetes non-ototoksik di jejaring harus dikonfirmasi, bukan diasumsikan.',
    mutiaraEbm: 'OMSK berbahaya dapat tampak deceptively tenang: nyeri dan demam bisa minimal meski kolesteatoma merusak struktur sekitar. Bau, lokasi perforasi, debris atau polip, gangguan pendengaran progresif, vertigo, paresis fasialis, dan gejala intrakranial lebih penting daripada banyaknya cairan. Telinga yang sementara kering setelah antibiotik juga tidak membuktikan kolesteatoma berhenti tumbuh.',
    konsekuensi: {
      narasi: 'Pasien kembali diberi antibiotik minum tanpa rujukan. Telinga mengering sebentar, tetapi kolesteatoma yang tidak tertangani dapat terus merusak tulang ke arah saraf wajah, labirin, atau rongga intrakranial.',
      kembaliHariMin: 30,
      kembaliHariMax: 60,
      kondisiKembali: 'Kembali dengan wajah kiri mencong, mata kiri tidak bisa menutup rapat, dan nyeri kepala hebat disertai demam tinggi serta kesadaran yang mulai menurun — kolesteatoma sudah melumpuhkan saraf wajah dan menembus ke dalam rongga tengkorak. Dirawat sebagai abses otak; pendengaran telinga kiri tidak dapat dikembalikan dan kelumpuhan wajah hanya pulih sebagian.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Otitis Media Supuratif Kronik, SKDI 3A); WHO Chronic Suppurative Otitis Media — Burden of Illness and Management Options',
    },
  }),

  buatKasusLab({
    id: 'lab_mastoiditis_akut',
    nama: 'Mastoiditis Akut pada Anak',
    icd10: 'H70.0',
    skdi: '3B',
    kategori: 'tht',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'tht',
    keluhanUtama: 'Anak saya demam tinggi terus, Dok, dan belakang telinga kirinya bengkak merah sampai kupingnya terdorong ke depan.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 3, usiaMax: 5 },
    vital: { td: '100/62', nadi: 128, rr: 26, suhu: 39.2, spo2: 98 },
    pembuka: {
      tanya: 'Boleh diceritakan sejak kapan bengkaknya muncul dan bagaimana awalnya?',
      jawab: 'Dua minggu lalu dia sakit telinga dan demam, lalu mendapat antibiotik minum untuk seminggu. Baru diminum empat hari sudah terlihat membaik sehingga saya hentikan. Empat hari lalu demamnya kembali lebih tinggi, dan tiga hari ini belakang telinganya bengkak merah serta makin menonjol.',
      oldcarts: ['onset', 'durasi', 'keparahan', 'penyerta'],
    },
    pertanyaan: [
      tanya({
        id: 'q_riwayat_oma',
        kategori: 'rpd',
        tanya: 'Obat dari kunjungan sebelumnya diminum bagaimana, dan adakah kesulitan menyelesaikannya?',
        jawab: 'Etiketnya seminggu, Dok. Baru empat hari dia sudah tidak demam dan tidak mengeluh sakit telinga lagi, jadi saya simpan sisanya. Saya kira sudah sembuh.',
        esensial: true,
        variasi: {
          wali_anak: 'Kata petugas seminggu, Dok. Tapi baru empat hari anaknya sudah lari-lari lagi, tidak demam, dan tidak mengeluh kupingnya. Saya hentikan lalu sisanya saya simpan. Saya tidak tahu gejalanya bisa kembali.',
          cemas: 'Aduh, Dok, baru empat hari saya hentikan karena kelihatan sudah sembuh. Apakah ini gara-gara saya? Anak saya kenapa, Dok, apakah berbahaya?',
        },
      }),
      tanya({
        id: 'q_bengkak_sifat',
        kategori: 'rps',
        tanya: 'Bengkak di belakang telinganya nyeri kalau disentuh? Kupingnya sejak kapan terdorong ke depan?',
        jawab: 'Nyeri sekali, Dok. Disentuh sedikit saja dia menjerit dan menepis tangan saya. Kupingnya mulai terdorong dua hari ini, sekarang jelas sekali menonjol ke depan dan ke bawah dibanding yang kanan.',
        esensial: true,
        oldcarts: ['lokasi', 'karakter', 'keparahan'],
        variasi: {
          wali_anak: 'Nyeri sekali, Dok. Saya mau usap saja dia menjerit dan menepis tangan saya. Kupingnya mulai maju dua hari ini. Coba Dokter bandingkan dengan yang kanan, kelihatan sekali yang kiri lebih menonjol ke depan dan agak ke bawah.',
          cemas: 'Nyeri banget, Dok! Disentuh dikit saja dia menjerit sampai saya tidak berani pegang lagi! Dan kupingnya itu lho, makin hari makin maju ke depan, tidak seperti yang kanan. Itu kenapa, Dok? Kok bisa kupingnya bergeser? Ada apa di dalamnya?',
        },
      }),
      tanya({
        id: 'q_keluar_cairan',
        kategori: 'rps',
        tanya: 'Ada cairan atau nanah yang keluar dari lubang telinganya?',
        jawab: 'Ada, Dok, sejak seminggu lalu keluar cairan kental kekuningan. Anehnya begitu keluar cairannya, dia malah tidak mengeluh sakit telinga lagi, jadi saya makin yakin sudah sembuh.',
        esensial: true,
        variasi: {
          wali_anak: 'Ada, Dok, seminggu lalu keluar cairan kental kuning, bantalnya sampai basah. Tapi justru sejak cairannya keluar dia berhenti mengeluh sakit telinga. Saya pikir itu tandanya kotorannya sudah keluar dan sembuh, Dok. Ternyata malah begini.',
          polos: 'Ana, Dok, seminggu kepungkur metu banyu kentel kuning. Aneh e, bar metu banyune bocahe malah ora sambat lara kuping maneh. Tak kira wis mari.',
        },
      }),
      {
        id: 'q_kesadaran_kejang',
        kategori: 'rps',
        tanya: 'Ada kejang, muntah menyembur, leher kaku, atau anaknya jadi sangat mengantuk dan sulit dibangunkan?',
        jawab: 'Tidak ada kejang, tidak muntah menyembur. Lehernya biasa saja. Cuma dia jadi rewel terus dan tidak mau main, tapi masih menjawab kalau dipanggil.',
        esensial: true,
      },
      {
        id: 'q_wajah',
        kategori: 'rps',
        tanya: 'Wajahnya ada yang mencong, atau matanya sulit menutup saat tidur?',
        jawab: 'Tidak ada, Dok. Wajahnya masih simetris.',
        esensial: true,
      },
      {
        id: 'q_makan_minum',
        kategori: 'rps',
        tanya: 'Masih mau makan dan minum? Buang air kecilnya bagaimana?',
        jawab: 'Makannya turun banyak, tapi minum masih mau. Pipisnya masih seperti biasa, popoknya tetap basah.',
        esensial: true,
      },
      {
        id: 'q_telinga_kanan',
        kategori: 'rps',
        tanya: 'Telinga kanannya bagaimana, ada keluhan juga?',
        jawab: 'Yang kanan tidak apa-apa, Dok. Cuma yang kiri.',
      },
      {
        id: 'q_riwayat_berulang',
        kategori: 'rpd',
        tanya: 'Sebelumnya sering sakit telinga berulang, atau ini yang pertama?',
        jawab: 'Setahun ini sudah tiga kali sakit telinga, Dok. Tapi biasanya sembuh sendiri setelah minum obat.',
      },
      {
        id: 'q_distraktor_imunisasi',
        kategori: 'rpd',
        tanya: 'Imunisasinya lengkap?',
        jawab: 'Lengkap, Dok, sesuai buku KIA semua. Tidak pernah bolong.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_kolam',
        kategori: 'sosial',
        tanya: 'Apakah anaknya sering berenang atau main air?',
        jawab: 'Sesekali saja main air di ember, Dok. Berenang jarang, mungkin sebulan sekali.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'kepala_leher', temuan: 'Daerah belakang telinga kiri bengkak, merah, teraba hangat dan sangat nyeri ditekan, dengan bagian tengah yang terasa lunak berisi cairan. Lekukan di belakang daun telinga MENGHILANG. Daun telinga kiri jelas terdorong ke arah depan-bawah dibanding telinga kanan.', relevan: true },
      { region: 'tht_mulut', temuan: 'Liang telinga kiri sempit karena dinding belakang-atasnya menggantung turun; tampak sekret kental kekuningan. Gendang telinga kiri menggembung dengan lubang kecil yang mengalirkan nanah. Telinga kanan normal.', relevan: true },
      { region: 'umum', temuan: 'Anak rewel, tampak sakit sedang-berat, badan teraba panas; masih menjawab saat dipanggil dan masih mau minum. Mata tidak cekung, waktu pengisian kapiler kurang dari dua detik.', relevan: true },
      { region: 'neurologis', temuan: 'Kesadaran penuh. Tidak ada kaku kuduk, tidak ada wajah mencong, manik mata sama besar dan bereaksi terhadap cahaya, tidak ada kelumpuhan anggota gerak.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru, tidak ada tarikan dinding dada.', relevan: false },
      { region: 'abdomen', temuan: 'Perut lemas, tidak nyeri, hati dan limpa tidak teraba membesar.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Leukosit 19.800/uL dengan dominasi neutrofil; Hb 11,6 g/dL; trombosit 402.000/uL.', flag: 'tinggi', relevan: true },
    ],
    diagnosisBanding: ['H70.0', 'H66.0', 'L04.0'],
    tatalaksana: {
      obatBenar: ['paracetamol_sirup'],
      terapiKritis: ['antibiotik_parenteral_mastoiditis_anak_protokol'],
      obatSalahUmum: [
        { id: 'amoxicillin_sirup', alasan: 'Antibiotik oral untuk OMA tanpa komplikasi tidak cukup sebagai terapi tunggal pada mastoiditis dengan fluktuasi retroaurikuler. Mengulang resep pulang akan menunda antibiotik parenteral, evaluasi THT, pencitraan selektif, dan source control yang mungkin dibutuhkan.', bahaya: 'nonPrimer' },
        { id: 'cefixime_100', alasan: 'Label "generasi ketiga" tidak membuat sefiksim oral menjadi pengganti jalur mastoiditis akut. Kasus ini memerlukan terapi parenteral berbasis berat badan dan protokol lokal serta penilaian rumah sakit, bukan eskalasi antibiotik oral lalu pulang.', bahaya: 'nonPrimer' },
        { id: 'dexamethasone_05', alasan: 'Kortikosteroid bukan terapi rutin yang menggantikan antibiotik parenteral atau source control pada mastoiditis. Perbaikan nyeri atau bengkak sementara tidak boleh dipakai untuk membatalkan rujukan; manfaat tambahan harus diputuskan tim rumah sakit untuk indikasi yang jelas.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['pasang_infus', 'antibiotik_parenteral_mastoiditis_anak_protokol', 'pemantauan_ketat_vital'],
      tindakanSalahUmum: [
        { id: 'insisi_abses', alasan: 'Fluktuasi retroaurikuler pada mastoiditis bukan bisul kulit untuk diinsisi di FKTP. Drainase abses subperiosteal, miringotomi atau pemasangan grommet, dan operasi mastoid adalah pilihan source control yang ditentukan THT menurut pemeriksaan serta pencitraan; mastoidektomi tidak otomatis diperlukan pada setiap anak.', bahaya: 'berbahaya' },
      ],
      edukasi: ['tanda_bahaya', 'persiapan_rujukan_operatif', 'kepatuhan_obat'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Demam tinggi, nyeri dan fluktuasi postaurikular, hilangnya lekukan retroaurikular, serta protrusi aurikula setelah OMA sangat mendukung mastoiditis akut dengan dugaan abses subperiosteal. Riwayat obat yang tidak selesai penting untuk stewardship, tetapi tidak membuktikan keluarga menyebabkan komplikasi: mastoiditis juga dapat terjadi meski terapi awal diberikan. Di FKTP, nilai sepsis dan tanda intrakranial, pasang akses bila tidak menunda, berikan antibiotik parenteral berbasis berat badan sesuai protokol jejaring, analgesia, monitoring, dan transfer segera. CT serta pilihan antara antibiotik saja, drainase, grommet, atau operasi mastoid ditentukan tim THT/rumah sakit; tidak semua anak otomatis memerlukan mastoidektomi.',
    panduanResmi: `${PPK_FLOOR} PPK 1186/2022 memberi konteks komplikasi otitis tetapi tidak memiliki algoritme mastoiditis anak yang lengkap. Children's Mercy Acute Mastoiditis Clinical Pathway 2026 mendefinisikan tanda utama berupa protrusi aurikula dan/atau fluktuasi, nyeri, edema, atau eritema postaurikular; meminta antibiotik empiris, rawat inap dan konsultasi THT; serta menyerahkan kebutuhan operasi kepada THT. BSAC Paediatric Pathway juga membedakan infeksi sedang/berat, terapi IV, imaging pada red flag, dan source control selektif.`,
    catatanRealita: 'Tombol antibiotik mewakili regimen parenteral berbasis berat badan dan pola kuman/protokol jejaring, bukan satu vial seftriakson 1 g universal. Akses IV, laboratorium, CT, dan ambulans tidak diasumsikan selalu ready; kegagalan akses berulang atau ketiadaan pemeriksaan tidak boleh menunda koordinasi transfer. Rute alternatif dan dosis pertama diputuskan sesuai protokol lokal serta kondisi anak.',
    mutiaraEbm: 'Perforasi gendang dapat menurunkan tekanan dan nyeri OMA, sehingga berhentinya keluhan telinga tidak selalu berarti proses selesai. Namun mastoiditis tidak boleh diajarkan sebagai hukuman pasti karena orang tua menghentikan antibiotik: tanda postaurikular dan kondisi sistemiklah yang mengubah diagnosis dan urgensi. Riwayat durasi, dosis, kepatuhan, serta respons obat dipakai untuk memilih terapi berikutnya tanpa menyalahkan keluarga.',
    stabilisasiWajib: ['antibiotik_parenteral_mastoiditis_anak_protokol', 'pemantauan_ketat_vital'],
    konsekuensi: {
      narasi: 'Anak dipulangkan dengan antibiotik minum dan penurun panas karena "masih sadar dan masih mau minum". Nanah di dalam mastoid terus menekan dan mencari jalan keluar ke arah rongga tengkorak.',
      kembaliHariMin: 1,
      kembaliHariMax: 3,
      kondisiKembali: 'Dibawa kembali dalam keadaan sangat mengantuk dan sulit dibangunkan, demam 40 derajat, leher kaku, dan muntah menyembur; bengkak di belakang telinga sudah pecah mengalirkan nanah. Dirawat di PICU sebagai radang selaput otak dengan trombosis pembuluh balik otak. Anak selamat setelah mastoidektomi darurat, tetapi telinga kirinya tuli menetap.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Mastoiditis / Komplikasi Otitis Media Akut, SKDI 3B); WHO Pocket Book of Hospital Care for Children',
    },
  }),

  buatKasusLab({
    id: 'lab_benda_asing_esofagus',
    nama: 'Benda Asing Esofagus pada Anak — Baterai Kancing',
    icd10: 'T18.1',
    skdi: '3B',
    kategori: 'tht',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'tht',
    keluhanUtama: 'Anak saya tadi menelan sesuatu, Dok, sekarang tidak mau makan sama sekali, ngiler terus, dan katanya sakit kalau menelan.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 2, usiaMax: 8 },
    vital: { td: '100/64', nadi: 118, rr: 24, suhu: 36.9, spo2: 98 },
    pembuka: {
      tanya: 'Tolong ceritakan kejadiannya: apa yang ditelan, jam berapa, dan siapa yang melihat?',
      jawab: 'Sekitar tiga jam lalu, Dok. Dia main sendiri di ruang tamu dekat toples uang receh dan remote TV yang rusak. Kakaknya lihat dia tersedak lalu menangis. Kami pikir uang logam karena toplesnya terbuka dan isinya berhamburan.',
      oldcarts: ['onset', 'waktu', 'karakter'],
    },
    pertanyaan: [
      tanya({
        id: 'q_benda_apa',
        kategori: 'rps',
        tanya: 'Apakah ada yang benar-benar melihat benda itu masuk ke mulutnya? Remote TV yang rusak itu baterainya masih ada?',
        jawab: 'Tidak ada yang lihat persis, Dok. Kami cuma dengar dia tersedak. Soal remote... aduh, saya baru sadar. Tutup baterainya memang sudah lepas dari kemarin dan ada baterai bulat pipih di dalamnya. Saya belum cek masih ada atau tidak.',
        esensial: true,
        variasi: {
          cemas: 'Tidak ada yang lihat, Dok! Kami cuma dengar dia tersedak terus nangis kencang! Remote itu... ya Allah, tutupnya lepas dari kemarin, ada baterai bulat pipih di situ. Saya tidak cek! Bahaya ya, Dok? Bahaya ya?',
          wali_anak: 'Tidak ada yang lihat, Dok. Cuma dengar tersedak. Remote-nya memang rusak, tutup baterainya lepas. Baterainya yang bulat pipih itu. Saya belum periksa masih ada apa tidak.',
        },
      }),
      {
        id: 'q_ngiler_menelan',
        kategori: 'rps',
        tanya: 'Ngilernya seberapa banyak, dan apakah ludahnya bisa ditelan?',
        jawab: 'Ngiler terus, Dok, sampai bajunya basah semua. Ludahnya seperti tidak bisa ditelan, dikeluarkan terus. Diberi air minum dia mau, tapi langsung dimuntahkan lagi.',
        esensial: true,
        oldcarts: ['karakter', 'keparahan'],
      },
      {
        id: 'q_napas',
        kategori: 'rps',
        tanya: 'Napasnya bagaimana? Ada bunyi ngik, suara serak, batuk terus, atau kebiruan?',
        jawab: 'Napasnya biasa saja, Dok, itu yang bikin kami agak tenang. Tidak ada bunyi aneh, tidak biru, suaranya juga normal waktu menangis.',
        esensial: true,
      },
      tanya({
        id: 'q_tindakan_rumah',
        kategori: 'rps',
        tanya: 'Di rumah sudah diberi atau dilakukan apa saja untuk mengeluarkannya?',
        jawab: 'Nenek menyuruh telan pisang sepotong besar biar terdorong, tapi dimuntahkan lagi. Lalu disuruh makan nasi kepal, sama saja. Terus mau dikorek pakai jari tapi dia meronta jadi tidak jadi.',
        esensial: true,
        variasi: {
          wali_anak: 'Kata nenek suruh telan pisang biar terdorong ke bawah, Dok, sudah dicoba tapi dimuntahkan. Terus nasi kepal, sama saja. Ada yang bilang suruh minum air hangat banyak. Mana yang betul, Dok?',
          polos: 'Wis dikeki gedhang sak potong gedhe ben mudhun, Dok, ning dimutahke. Terus sega dikepel, podho wae. Arep dikorek nganggo jari, bocahe mbrontak.',
        },
      }),
      {
        id: 'q_nyeri_lokasi',
        kategori: 'rps',
        tanya: 'Kalau ditanya sakitnya di mana, dia menunjuk ke bagian mana?',
        jawab: 'Dia selalu menunjuk ke bawah leher, di cekungan dekat tulang selangka. Sambil menangis kalau disuruh menelan.',
        esensial: true,
        oldcarts: ['lokasi'],
      },
      {
        id: 'q_muntah_darah',
        kategori: 'rps',
        tanya: 'Ada muntah bercampur darah, atau ludah yang kemerahan?',
        jawab: 'Belum ada darah, Dok. Ludahnya bening saja, cuma banyak sekali.',
        esensial: true,
      },
      {
        id: 'q_demam',
        kategori: 'rps',
        tanya: 'Ada demam, atau nyeri di dada dan punggung?',
        jawab: 'Tidak demam. Dia tidak bilang sakit dada, cuma leher bawah itu tadi.',
      },
      {
        id: 'q_riwayat_telan',
        kategori: 'rpd',
        tanya: 'Sebelumnya pernah menelan benda lain, atau ada masalah menelan sejak bayi?',
        jawab: 'Belum pernah, Dok. Makannya selama ini lancar-lancar saja.',
      },
      {
        id: 'q_distraktor_alergi_makanan',
        kategori: 'rpd',
        tanya: 'Apakah anaknya punya alergi makanan tertentu?',
        jawab: 'Tidak ada, Dok. Dia makan apa saja tidak pernah bentol atau gatal.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_cacing',
        kategori: 'sosial',
        tanya: 'Apakah anaknya sering main tanah tanpa alas kaki dan sudah minum obat cacing?',
        jawab: 'Main tanah sering, Dok. Obat cacing terakhir enam bulan lalu di Posyandu.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Anak rewel dan menangis, air liur menetes terus membasahi baju. Tidak biru, tidak tampak sesak, masih menolak dan meronta dengan tenaga penuh.', relevan: true },
      { region: 'tht_mulut', temuan: 'Rongga mulut dan bagian belakang tenggorok bersih: tidak tampak benda asing, tidak ada luka, amandel tidak membesar dan tidak merah. Air liur menggenang banyak di dasar mulut.', relevan: true },
      { region: 'kepala_leher', temuan: 'Leher tidak bengkak, tidak merah, dan tidak teraba gelembung udara di bawah kulit; tidak ada nyeri tekan di sisi leher. Anak menunjuk cekungan di atas tulang dada saat ditanya lokasi nyeri.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas terdengar sama dan bersih di kedua sisi, tanpa bunyi ngik dan tanpa suara napas berbunyi kasar saat menarik napas. Tidak ada tarikan dinding dada.', relevan: true },
      { region: 'abdomen', temuan: 'Perut lemas, tidak kembung, tidak nyeri ditekan, bising usus normal.', relevan: false },
      { region: 'jantung', temuan: 'Denyut cepat teratur sesuai usia dan tangisan, tidak ada bising.', relevan: false },
    ],
    lab: [
      { id: 'foto_toraks', hasil: 'Tampak bayangan cakram padat (opak) melintang setinggi pintu masuk rongga dada, sekitar setinggi tulang selangka. Pada gambar dari depan, cakram itu memperlihatkan GAMBARAN CINCIN GANDA (lingkaran di dalam lingkaran / tanda halo); pada gambar dari samping, tepinya TIDAK rata melainkan bertingkat seperti anak tangga. Tidak tampak udara bebas di leher maupun rongga dada. Kedua paru mengembang normal.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['T18.1', 'T17.9', 'J03.9'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'domperidon_10', alasan: 'Diberikan dengan harapan "mendorong benda itu turun ke lambung". Obat pelancar gerakan lambung tidak mendorong benda padat melewati penyempitan esofagus, dan yang lebih penting: pada baterai kancing, mendorongnya turun bukanlah tujuan — mengeluarkannya dalam hitungan jam-lah tujuannya. Setiap menit yang dipakai menunggu obat bekerja adalah menit tambahan bagi luka bakar di dinding esofagus.', bahaya: 'nonPrimer' },
        { id: 'ondansetron_4', alasan: 'Diberikan untuk menghentikan muntah dan ngilernya. Justru ngiler dan muntah itulah penanda klinis bahwa jalur menelan tersumbat; meredamnya menghapus tanda pemantauan tanpa menyentuh penyebabnya, dan membuat anak tampak lebih tenang daripada keadaan sebenarnya.', bahaya: 'nonPrimer' },
        { id: 'antasida_doen', alasan: 'Muncul dari penalaran keliru bahwa luka bakar baterai adalah luka bakar asam lambung yang bisa "dinetralkan". Kerusakan baterai kancing bukan kerusakan asam melainkan kerusakan basa akibat arus listrik yang memecah cairan tubuh di sekitarnya; antasida tidak menyentuh proses itu sedikit pun dan hanya menambah isi lambung menjelang tindakan pembiusan.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['pemantauan_ketat_vital'],
      tindakanSalahUmum: [
        { id: 'bilas_lambung', alasan: 'Memasukkan selang lalu menyiram dan menyedot isi lambung pada benda asing padat di esofagus adalah tindakan berbahaya: selang harus melewati benda itu lebih dulu — berisiko mendorongnya lebih dalam atau menusuk dinding yang sudah terbakar — sementara cairan yang disiramkan membanjiri jalur menelan yang tersumbat sehingga sangat mudah masuk ke paru. Bilas lambung tidak pernah menjadi cara mengeluarkan benda asing esofagus; jalannya adalah endoskopi.', bahaya: 'berbahaya' },
        { id: 'dekompresi_ngt', alasan: 'Memasang selang lambung terasa masuk akal untuk "mengosongkan lambung sebelum rujukan". Pada benda asing esofagus, selang itu harus menerobos melewati benda tersebut secara membuta: ia dapat mendorong baterai lebih dalam, mengubah letaknya sehingga menyulitkan endoskopi, atau menembus dinding esofagus yang jaringannya sudah dilunakkan oleh luka bakar. Pengosongan lambung bukan prioritas di sini; pengeluaran bendanya yang prioritas.', bahaya: 'berbahaya' },
      ],
      edukasi: ['puasa_sambil_rujuk', 'tanda_bahaya', 'cegah_baterai_kancing'],
      edukasiKritis: ['puasa_sambil_rujuk', 'cegah_baterai_kancing'],
    },
    clue: 'Anak yang tersedak lalu menolak makan, ngiler karena ludahnya tidak bisa ditelan, dan menunjuk cekungan di atas tulang dada mengalami benda asing esofagus. Napas yang baik tidak menyingkirkannya. Cincin ganda pada foto depan dan tepi bertingkat pada foto samping menandai baterai kancing, yang dapat menimbulkan luka bakar serius dalam dua jam. Jangan mendorongnya dengan pisang/nasi, menginduksi muntah, atau memasang selang secara membuta; rujuk untuk pengeluaran endoskopik segera. Madu 10 mL tiap 10 menit maksimal enam dosis hanya dipertimbangkan bila usia minimal 12 bulan, tertelan kurang dari 12 jam, dan anak mampu menelan. Anak ini tidak mampu menelan ludah maupun air, sehingga JANGAN paksa madu: pertahankan NPO dan berangkat. Madu tidak pernah menggantikan atau menunda pengeluaran baterai.',
    panduanResmi: 'Tidak ditemukan bab PPK FKTP diagnosis-spesifik pada crosswalk 167 bab. National Capital Poison Center Button Battery Guideline menjadi grounding langsung: curigai baterai pada setiap benda berbentuk koin, cari double-rim/halo dan step-off, jangan memicu muntah, serta keluarkan baterai esofagus segera karena luka berat dapat terjadi dalam dua jam. Selain madu yang memenuhi seluruh syarat ketat, pasien dipertahankan NPO sampai posisi baterai esofagus disingkirkan. Ketidakmampuan menelan pada vignette ini menutup opsi madu.',
    catatanRealita: 'Skenario memberi hasil foto polos agar pemain belajar tanda halo, tetapi Puskesmas Sukamaju tidak diasumsikan memiliki rontgen. Dugaan baterai disertai ngiler dan penolakan minum sudah cukup untuk puasa dan transfer; jangan menunggu foto lokal. Edukasi pencegahan kini khusus baterai kancing, bukan topik benda asing hidung yang sebelumnya salah konteks.',
    mutiaraEbm: 'Setiap hal yang menenangkan pada kasus ini adalah jebakan. Napas yang baik, tidak biru, tanpa bunyi ngik, dan anak yang masih meronta bertenaga membuat kasus ini terasa seperti keluhan tersedak biasa — padahal baterai kancing tidak membunuh lewat sumbatan napas melainkan lewat luka bakar listrik-basa yang senyap, dan anak bisa tampak baik-baik saja tepat pada jam-jam ketika esofagusnya sedang terbakar. Perangkap kedua adalah keyakinan keluarga: mereka menyebut uang logam dengan yakin, padahal tidak seorang pun melihat kejadiannya — dan uang logam serta baterai kancing sama-sama cakram padat yang mirip di foto, sehingga hanya tanda cincin ganda dan tepi bertingkat yang memisahkan barang yang boleh ditunggu semalam dari barang yang harus keluar dalam dua jam. Karena itu setiap cakram padat di esofagus anak diperlakukan sebagai baterai sampai foto membuktikan sebaliknya.',
    konsekuensi: {
      narasi: 'Anak dipulangkan dengan obat mual dan pesan "kalau belum keluar besok kontrol lagi", karena napasnya baik dan dia masih aktif. Arus listrik baterai terus bekerja di dinding esofagus sepanjang malam.',
      kembaliHariMin: 1,
      kembaliHariMax: 2,
      kondisiKembali: 'Dibawa kembali dengan demam tinggi, nyeri dada tembus ke punggung, leher yang teraba berkeretak karena udara bocor ke bawah kulit, dan air liur bercampur darah — dinding esofagus sudah berlubang. Dirawat di PICU dengan radang rongga dada; anak selamat setelah operasi berkepanjangan, tetapi esofagusnya menyempit karena jaringan parut sehingga harus dilebarkan berulang kali selama bertahun-tahun.',
      guideline: 'National Capital Poison Center Button Battery Ingestion Triage and Treatment Guideline (akses 2026); jalur endoskopi emergensi jejaring THT/bedah anak.',
    },
  }),

  buatKasusLab({
    id: 'lab_tia_serangan_iskemik_sesaat',
    nama: 'TIA — Serangan Iskemik Sesaat yang Sudah Pulih',
    icd10: 'G45.9',
    skdi: '3B',
    kategori: 'saraf',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'saraf',
    keluhanUtama: 'Tadi pagi bicara saya tiba-tiba pelo dan tangan kanan lemas sekitar dua puluh menit, Dok, tapi sekarang sudah normal lagi — saya ke sini cuma karena dipaksa keluarga.',
    demografi: { usiaMin: 55, usiaMax: 75 },
    vital: { td: '168/96', nadi: 92, rr: 18, suhu: 36.6, spo2: 98 },
    pembuka: {
      tanya: 'Coba ceritakan persis apa yang terjadi tadi pagi, dari awal sampai pulih.',
      jawab: 'Sekitar jam tujuh pagi saya lagi minum kopi. Tiba-tiba bicara saya jadi pelo, istri saya tidak paham saya ngomong apa. Bersamaan itu tangan kanan saya lemas, cangkirnya sampai jatuh. Kira-kira dua puluh menit lalu hilang sendiri, pelan-pelan normal lagi. Sekarang sudah tidak ada apa-apa, lihat sendiri Dok, saya baik-baik saja.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_durasi_pulih',
        kategori: 'rps',
        tanya: 'Pulihnya bertahap atau sekaligus? Sekarang benar-benar tidak ada sisa sedikit pun?',
        jawab: 'Pelan-pelan, Dok, mungkin lima menit terakhir. Sekarang tidak ada sisa apa-apa. Tangan saya kuat, bicara saya jelas. Makanya saya bilang tidak perlu ke sini.',
        esensial: true,
        oldcarts: ['durasi', 'keparahan'],
        variasi: {
          skeptis: 'Pelan-pelan hilangnya. Dan sekarang sudah tidak ada apa-apa sama sekali — coba Dokter lihat, saya bisa genggam kuat, bicara saya jelas. Jadi buat apa saya di sini? Cuma kecapekan itu. Kalau memang stroke ya saya sudah lumpuh sekarang, betul tidak?',
          cemas: 'Pelan-pelan, Dok, tapi saya takut sekali waktu itu! Sekarang memang sudah normal tapi kalau kambuh lagi bagaimana? Kalau pas saya sendirian? Ini kenapa, Dok? Saya mau stroke ya?',
        },
      }),
      {
        id: 'q_gejala_lain',
        kategori: 'rps',
        tanya: 'Waktu itu ada wajah yang mencong, satu mata mendadak gelap seperti ditutup tirai, atau kaki kanan ikut lemas?',
        jawab: 'Kata istri saya mulut saya agak turun sebelah kanan. Mata tidak ada yang gelap. Kaki tidak ikut lemas, saya masih bisa berdiri.',
        esensial: true,
      },
      tanya({
        id: 'q_pertama_kali',
        kategori: 'rpd',
        tanya: 'Ini pertama kali, atau sebelumnya pernah ada kejadian serupa walau lebih singkat?',
        jawab: 'Sebenarnya... tiga hari lalu pernah, Dok. Tangan kanan kesemutan dan lemas sekitar lima menit, terus hilang. Saya kira ketindihan waktu tidur, jadi tidak saya pikirkan.',
        esensial: true,
        oldcarts: ['waktu'],
        variasi: {
          skeptis: 'Kalau dihitung, ya tiga hari lalu pernah sebentar. Tangan kesemutan lemas lima menit terus hilang. Tapi itu jelas ketindihan waktu tidur, Dok, saya memang suka tidur miring. Tidak usah dibesar-besarkan.',
        },
      }),
      tanya({
        id: 'q_hipertensi',
        kategori: 'rpd',
        tanya: 'Punya darah tinggi? Obatnya diminum teratur?',
        jawab: 'Darah tinggi sudah delapan tahun, Dok. Obatnya... jujur saja tidak teratur. Saya minum kalau kepala pusing atau tengkuk pegal saja. Kalau enak badan ya tidak minum.',
        esensial: true,
        variasi: {
          skeptis: 'Ada, delapan tahun. Obatnya saya minum kalau perlu saja — kalau tengkuk pegal atau kepala nyut-nyutan. Buat apa minum obat tiap hari kalau badan enak? Malah rusak ginjal nanti.',
        },
      }),
      {
        id: 'q_jantung_berdebar',
        kategori: 'rps',
        tanya: 'Pernah merasa jantung berdebar tidak beraturan, seperti melompat-lompat atau kadang berhenti sesaat?',
        jawab: 'Sering, Dok, sudah setahunan. Kadang dadanya seperti bergetar sendiri, tidak teratur. Saya kira karena kopi. Belum pernah diperiksa jantungnya.',
        esensial: true,
      },
      {
        id: 'q_aman_asetosal',
        kategori: 'rpd',
        tanya: 'Ada alergi aspirin/asetosal, perdarahan aktif, muntah darah atau BAB hitam, atau sedang minum pengencer darah?',
        jawab: 'Tidak ada alergi obat, tidak sedang berdarah, dan belum pernah minum aspirin maupun obat pengencer darah.',
        esensial: true,
      },
      {
        id: 'q_nyeri_kepala',
        kategori: 'rps',
        tanya: 'Waktu kejadian tadi ada sakit kepala hebat mendadak, muntah, atau kejang?',
        jawab: 'Tidak ada. Kepala tidak sakit sama sekali, tidak muntah, tidak kejang.',
        esensial: true,
      },
      {
        id: 'q_dm_kolesterol',
        kategori: 'rpd',
        tanya: 'Ada kencing manis atau kolesterol tinggi?',
        jawab: 'Kolesterol pernah dibilang tinggi dua tahun lalu, tapi saya tidak minum obat apa-apa. Kencing manis tidak ada.',
      },
      {
        id: 'q_merokok',
        kategori: 'sosial',
        tanya: 'Merokok? Berapa lama dan berapa banyak?',
        jawab: 'Masih, Dok. Sehari sebungkus, sudah dari umur dua puluh.',
      },
      {
        id: 'q_distraktor_kecapekan',
        kategori: 'sosial',
        tanya: 'Akhir-akhir ini apakah kurang tidur, banyak pikiran, atau kelelahan?',
        jawab: 'Nah itu dia, Dok! Seminggu ini saya memang kurang tidur, banyak urusan. Pasti gara-gara itu kan? Cuma kecapekan saja kan?',
        distraktor: true,
      },
      {
        id: 'q_distraktor_urut',
        kategori: 'sosial',
        tanya: 'Apakah sudah dibawa ke tukang urut atau minum jamu untuk keluhan ini?',
        jawab: 'Belum, tapi tetangga menyarankan diurut saja katanya angin duduk. Bagus tidak, Dok?',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'neurologis', temuan: 'SELURUHNYA NORMAL saat ini: kesadaran penuh, bicara jelas dan lancar, wajah simetris termasuk saat menyeringai, kekuatan keempat anggota gerak penuh dan simetris, rasa raba normal, tidak ada gangguan keseimbangan berjalan. Tidak ada kaku kuduk.', relevan: true },
      { region: 'jantung', temuan: 'Denyut jantung IREGULER-IREGULER, tidak ada pola sama sekali, laju sekitar 92 per menit; bunyi jantung satu dengan kuat yang berubah-ubah. Tidak ada bising, tidak ada bengkak tungkai.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak terdengar bunyi desiran pada kedua pembuluh leher; denyut nadi leher teraba sama kuat di kedua sisi.', relevan: true },
      { region: 'umum', temuan: 'Tampak sehat dan bugar, duduk santai, berulang kali menyatakan ingin segera pulang karena merasa tidak ada masalah.', relevan: true },
      { region: 'mata', temuan: 'Manik mata sama besar dan bereaksi terhadap cahaya; gerakan bola mata bebas ke segala arah.', relevan: false },
      { region: 'ekstremitas', temuan: 'Denyut nadi tangan dan kaki teraba; tidak ada luka maupun perubahan warna kulit.', relevan: false },
    ],
    lab: [
      { id: 'ekg', hasil: 'FIBRILASI ATRIUM dengan laju respons ventrikel sekitar 92 per menit: tidak tampak gelombang P, jarak antar-denyut sama sekali tidak teratur. Tidak ada elevasi segmen ST. Tampak tanda pembesaran otot bilik kiri.', flag: 'abnormal', relevan: true },
      { id: 'gds', hasil: '138 mg/dL.', flag: 'normal', relevan: true },
    ],
    diagnosisBanding: ['G45.9', 'I63.9', 'E16.2'],
    tatalaksana: {
      obatBenar: ['asetosal_loading_320'],
      obatOpsional: ['simvastatin_20'],
      obatSalahUmum: [
        { id: 'nifedipin_10', alasan: 'Godaan klasik: tekanan darah 168/96 pada pasien yang "baru kena serangan otak" terasa harus segera diturunkan, dan nifedipin kerja cepat menurunkannya dalam menit. Justru inilah bahayanya. Pada fase akut gangguan pembuluh darah otak, tekanan darah yang agak tinggi adalah upaya tubuh mempertahankan aliran ke jaringan otak yang pasokannya rawan; menurunkannya mendadak dan tanpa kendali dapat mengubah serangan sesaat yang sudah pulih menjadi infark yang menetap. Pengendalian tekanan darah pada TIA adalah proyek jangka panjang, bukan tindakan menit ini.', bahaya: 'kontraindikasi' },
        { id: 'betahistin_6', alasan: 'Keluhan sesaat pada lansia sering dibaca sebagai "kurang darah ke otak" atau vertigo lalu diberi betahistin. Obat ini bekerja pada organ keseimbangan telinga dalam dan tidak menurunkan risiko stroke sama sekali. Kerugian sebenarnya bukan pada obatnya, melainkan pada cerita yang dibawa pulang pasien: ia merasa penyakitnya sudah bernama dan sudah diobati, tepat pada 48 jam ketika ia paling mungkin terkena stroke.', bahaya: 'nonPrimer' },
        { id: 'vitamin_b_kompleks', alasan: 'Diberikan sebagai "obat saraf" untuk keluhan pelo dan lemas. Tidak ada bukti bahwa vitamin B mencegah stroke pada pasien ini, dan resep ini menyempurnakan rasa aman palsu: pasien yang sejak awal sudah yakin dirinya tidak sakit kini pulang membawa bukti bahwa dokter pun sependapat.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['tanda_bahaya', 'kepatuhan_obat', 'kontrol_rutin', 'diet_rendah_garam', 'berhenti_merokok'],
      edukasiKritis: ['tanda_bahaya'],
      terapiKritis: ['asetosal_loading_320'],
    },
    clue: 'Gejala neurologis fokal mendadak yang pulih total, disertai gula darah normal, adalah suspek TIA dan tetap merupakan kegawatan. Setelah kontraindikasi disaring, berikan asetosal 320 mg dengan mengunyah empat tablet tidak bersalut 80 mg, lalu rujuk segera untuk penilaian spesialis dalam 24 jam; jangan menunggu gejala kambuh dan jangan memakai ABCD2 untuk menurunkan urgensi. EKG pada skenario ini menemukan fibrilasi atrium, tetapi regimen antikoagulasi jangka panjang diputuskan setelah evaluasi spesialis. Simvastatin dapat dipertimbangkan untuk faktor risiko, namun tidak menggantikan aspirin dan transfer. Jangan menurunkan tekanan darah secara mendadak dengan nifedipin kerja cepat.',
    panduanResmi: `${PPK_FLOOR} PPK 1186/2022 menempatkan TIA pada kompetensi 3B dan menuntut penanganan cepat serta rujukan. PNPK Stroke KMK 304/2026 memberi konteks stroke terkait, bukan pengganti algoritme TIA first-contact. AHA 2023 Scientific Statement on Diagnosis, Workup, Risk Reduction of TIA menegaskan bahwa gejala yang sudah pulih tetap memerlukan evaluasi emergensi, workup etiologi cepat, dan jalur stroke regional. NICE NG128 rekomendasi 1.1.2 dan 1.1.4-1.1.6 meminta eksklusi hipoglikemia, aspirin 300 mg segera bila tidak ada kontraindikasi, rujukan langsung untuk penilaian dalam 24 jam, serta larangan memakai ABCD2 untuk menentukan urgensi. Fibrilasi atrium mengarahkan pencegahan sekunder ke antikoagulasi setelah evaluasi perdarahan, pencitraan, dan timing yang tepat; jangan mengimprovisasi regimen di FKTP.`,
    catatanRealita: 'Fornas 1199/2025 mencantumkan asetosal tablet 80 mg di fasilitas tingkat pertama; empat tablet tidak bersalut memberi loading 320 mg yang dapat dikunyah. Vignette juga menyatakan EKG dan petugasnya ready. Bila EKG tidak tersedia atau gagal berfungsi, kecurigaan TIA klinis, pemeriksaan gula, aspirin bila aman, dan transfer tetap berjalan tanpa menunggu pemeriksaan jejaring.',
    mutiaraEbm: 'Pemulihan sempurna adalah temuan paling menyesatkan dalam neurologi. Pemeriksaan yang seluruhnya normal di hadapan Anda terasa seperti bukti bahwa tidak ada yang perlu dicemaskan — padahal justru pemulihan itulah yang menamai penyakitnya, dan penyakit itu adalah peringatan bahwa stroke sedang bersiap. Perangkap kedua bersifat kelembagaan: bila pasien terlanjur dirujuk dan menjalani CT kepala, hasilnya kemungkinan besar normal — dan CT normal pada TIA adalah temuan yang DIHARAPKAN, bukan tanda aman; ia sama sekali tidak mengubah kegentingannya. Perangkap ketiga ada pada denyut nadi: fibrilasi atrium sering tidak bergejala dan tidak akan ketahuan bila nadi hanya dihitung sepuluh detik lalu dikalikan enam — ia harus diraba cukup lama untuk merasakan ketidakteraturannya, dan dipastikan dengan EKG.',
    konsekuensi: {
      narasi: 'Pasien pulang tanpa rujukan, membawa vitamin saraf dan pesan "kalau kambuh baru datang lagi", karena semua pemeriksaannya normal dan ia sendiri bersikeras sudah sehat. Fibrilasi atriumnya terus melontarkan bekuan.',
      kembaliHariMin: 1,
      kembaliHariMax: 3,
      kondisiKembali: 'Dibawa keluarga dalam keadaan tidak dapat bicara sama sekali dan lengan serta tungkai kanan lumpuh total sejak bangun tidur — sehingga waktu pasti mulainya serangan tidak diketahui dan jendela terapi penghancur bekuan sudah tertutup. Stroke iskemik luas di belahan otak kiri. Pasien bertahan hidup dengan kelumpuhan sisi kanan yang menetap dan kesulitan bicara, bergantung pada keluarga untuk kegiatan sehari-hari.',
      guideline: 'PPK FKTP KMK 1186/2022; PNPK Tata Laksana Stroke KMK 304/2026; AHA 2023 Scientific Statement on Diagnosis, Workup, Risk Reduction of TIA in the Emergency Department',
    },
  }),

  buatKasusLab({
    id: 'lab_meningitis_bakterial_suspek',
    nama: 'Suspek Meningitis Bakterial',
    icd10: 'G00.9',
    skdi: '3B',
    kategori: 'saraf',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'saraf',
    keluhanUtama: 'Kepala saya sakit hebat sekali sejak kemarin, Dok, demam tinggi, leher rasanya kaku, dan tadi muntah menyembur.',
    demografi: { usiaMin: 15, usiaMax: 30 },
    vital: { td: '108/64', nadi: 122, rr: 26, suhu: 39.6, spo2: 96 },
    pembuka: {
      tanya: 'Sejak kapan sakit kepalanya, dan seberapa berat dibanding sakit kepala yang pernah dirasakan?',
      jawab: 'Mulai kemarin siang, makin lama makin hebat. Ini sakit kepala paling parah seumur hidup saya, Dok. Rasanya kepala mau pecah dan tidak berkurang sama sekali walau sudah minum obat warung. Tadi pagi muntah sampai menyembur jauh, padahal perut saya tidak mual.',
      oldcarts: ['onset', 'durasi', 'keparahan', 'penyerta'],
    },
    pertanyaan: [
      {
        id: 'q_leher_kaku',
        kategori: 'rps',
        tanya: 'Lehernya kaku bagaimana? Bisa menunduk sampai dagu menyentuh dada?',
        jawab: 'Tidak bisa, Dok. Kalau saya coba menunduk rasanya tertahan dan sakit sekali sampai ke belakang kepala. Menoleh ke samping masih bisa, tapi menunduk tidak.',
        esensial: true,
        oldcarts: ['karakter'],
      },
      tanya({
        id: 'q_silau',
        kategori: 'rps',
        tanya: 'Apakah cahaya terasa menyakitkan? Suara ribut bagaimana?',
        jawab: 'Silau sekali, Dok. Dari tadi saya tutup mata terus, kalau tirai dibuka rasanya menusuk. Suara ribut juga bikin kepala tambah sakit. Tolong lampunya jangan dinyalakan.',
        esensial: true,
        variasi: {
          terpelajar: 'Sangat, Dok. Cahaya terasa seperti menusuk sampai ke dalam kepala, jadi sejak kemarin saya menutup mata terus dan minta tirai kamar ditutup. Suara ribut juga menambah sakitnya. Maaf, boleh lampunya jangan dinyalakan?',
          polos: 'Silau nemen, Dok... mripat tak tutup terus. Nek gordene dibukak rasane koyo ditusuk. Suoro rame yo nggarai sirah tambah mumet. Lampune ampun diurupke, Dok.',
        },
      }),
      {
        id: 'q_ruam',
        kategori: 'rps',
        tanya: 'Ada bintik atau bercak merah di kulit yang muncul belakangan ini?',
        jawab: 'Kata teman kos saya tadi ada bintik-bintik merah kecil di kaki saya, muncul sejak tadi pagi. Saya sendiri belum lihat, dari tadi saya tidak kuat bangun.',
        esensial: true,
      },
      tanya({
        id: 'q_kesadaran',
        kategori: 'rps',
        tanya: 'Apakah sempat bingung, mengigau, tidak mengenali orang, atau kejang?',
        jawab: 'Kejang tidak ada. Tapi kata teman saya, dari tadi siang saya susah dibangunkan dan ngomongnya kacau. Saya sendiri... jujur agak bingung sekarang, Dok, ini hari apa ya?',
        esensial: true,
        variasi: {
          cemas: 'Kejang tidak ada, Dok, tapi teman saya bilang saya ngomong ngelantur dan susah dibangunkan dari siang! Saya sendiri sekarang bingung, ini hari apa sih? Kenapa saya jadi begini, Dok? Saya takut, tolong saya...',
          terpelajar: 'Tidak ada kejang, Dok. Tapi teman sekamar saya bilang sejak siang saya sulit dibangunkan dan bicara saya melantur — dan terus terang saya sendiri tidak ingat sebagian siang tadi. Sekarang pun saya harus berpikir keras untuk menjawab. Ini hari apa ya, Dok?',
        },
      }),
      {
        id: 'q_demam',
        kategori: 'rps',
        tanya: 'Demamnya sejak kapan, dan ada menggigil sampai gemetar?',
        jawab: 'Sejak kemarin siang bersamaan dengan sakit kepalanya. Semalam menggigil hebat sampai gigi saya beradu, selimut dua lapis tetap dingin.',
        esensial: true,
        oldcarts: ['onset', 'durasi'],
      },
      {
        id: 'q_kontak_asrama',
        kategori: 'sosial',
        tanya: 'Tinggal di kos atau asrama? Ada teman sekamar yang sakit serupa?',
        jawab: 'Saya tinggal di kos-kosan padat, Dok, sekamar berdua dan satu kamar mandi dipakai bersama sepuluh orang. Belum ada yang sakit seperti saya setahu saya.',
        esensial: true,
      },
      {
        id: 'q_sumber_infeksi',
        kategori: 'rpd',
        tanya: 'Sebelum ini ada telinga berair, sakit gigi berat, atau sinus yang sering nyeri?',
        jawab: 'Tidak ada, Dok. Telinga saya baik, gigi tidak ada yang sakit.',
      },
      {
        id: 'q_daya_tahan',
        kategori: 'rpd',
        tanya: 'Ada penyakit yang menurunkan daya tahan tubuh, minum obat jangka panjang, atau limpa pernah diangkat?',
        jawab: 'Tidak ada. Saya selama ini sehat, tidak pernah dirawat, tidak minum obat apa pun rutin.',
      },
      tanya({
        id: 'q_distraktor_begadang',
        kategori: 'sosial',
        tanya: 'Apakah akhir-akhir ini sering begadang atau banyak pikiran karena ujian?',
        jawab: 'Iya, Dok, minggu ini memang saya begadang terus, ada ujian. Mungkin cuma kecapekan dan masuk angin ya?',
        distraktor: true,
        variasi: {
          terpelajar: 'Betul, Dok, minggu ini saya begadang hampir tiap malam karena ujian akhir. Apa mungkin ini cuma kelelahan berat? Teman-teman saya juga bilang begitu.',
          cemas: 'Iya, Dok, saya begadang terus minggu ini! Tolong bilang ini cuma kecapekan ya, Dok? Cuma masuk angin kan? Kan cuma kurang tidur?',
        },
      }),
      {
        id: 'q_distraktor_migren',
        kategori: 'rpd',
        tanya: 'Apakah dari dulu sering sakit kepala sebelah, misalnya kalau telat makan?',
        jawab: 'Kadang-kadang kalau telat makan kepala saya nyut-nyutan sebelah, Dok. Tapi yang sekarang ini beda jauh, tidak ada apa-apanya dibanding ini.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Tampak sakit berat, mengantuk berat tetapi masih dapat dibangunkan dan menjawab pertanyaan singkat dengan kacau; badan teraba sangat panas, kulit lembap. Berbaring meringkuk membelakangi jendela dan menutup mata dengan lengan.', relevan: true },
      { region: 'neurologis', temuan: 'Kaku kuduk JELAS: dagu tidak dapat didekatkan ke dada. Kernig dan Brudzinski positif. Manik mata sama besar dan bereaksi terhadap cahaya. Tidak ada kelumpuhan satu sisi, tidak ada wajah mencong. Kesadaran menurun ringan.', relevan: true },
      { region: 'kulit', temuan: 'Tampak bercak dan bintik merah keunguan kecil di kedua tungkai bawah dan badan, TIDAK MEMUCAT saat ditekan dengan gelas; beberapa mulai menyatu menjadi bercak yang lebih besar.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada nyeri tekan di daerah sinus; gendang telinga kedua sisi utuh dan tidak meradang; gigi-geligi tidak ada yang berlubang besar atau bernanah.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru, tidak ada ronki, napas cepat tanpa tarikan dinding dada.', relevan: false },
      { region: 'abdomen', temuan: 'Perut lemas, tidak nyeri ditekan, hati dan limpa tidak teraba membesar, bising usus normal.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Leukosit 21.400/uL dengan dominasi neutrofil dan pergeseran ke kiri; Hb 13,2 g/dL; TROMBOSIT 118.000/uL (menurun).', flag: 'tinggi', relevan: true },
      { id: 'gds', hasil: '112 mg/dL.', flag: 'normal', relevan: true },
    ],
    diagnosisBanding: ['G00.9', 'I61.9', 'A01.0'],
    tatalaksana: {
      obatBenar: ['ceftriaxone_1g_inj'],
      terapiKritis: ['ceftriaxone_1g_inj'],
      obatOpsional: ['paracetamol_500', 'ondansetron_4'],
      obatSalahUmum: [
        { id: 'diazepam_2', alasan: 'Diberikan untuk "menenangkan" pasien yang gelisah dan mengigau. Ini menutup satu-satunya alat pemantauan yang tersisa selama perjalanan rujukan: tingkat kesadaran. Setelah diazepam, tidak ada yang bisa membedakan pasien yang tenang karena obat dari pasien yang kesadarannya jatuh karena tekanan dalam kepala meninggi — dan benzodiazepin sendiri menekan pusat napas pada pasien yang kesadarannya sudah turun.', bahaya: 'kontraindikasi' },
        { id: 'natrium_diklofenak_50', alasan: 'Dipilih karena "lebih kuat" untuk sakit kepala hebat dan demam tinggi. Pada pasien ini keliru berlapis: demam dan nyeri kepala adalah penanda perburukan yang justru sedang dipantau; ginjal sedang menghadapi awal sepsis dengan tekanan darah yang sudah di batas bawah; dan trombosit yang turun ke 118.000 dengan bercak perdarahan di kulit menandakan pembekuan darah mulai kacau, keadaan ketika obat yang mengganggu fungsi keping darah adalah hal terakhir yang dibutuhkan. Untuk demam dan nyeri, parasetamol sudah memadai dan aman.', bahaya: 'kontraindikasi' },
        { id: 'amoxicillin_500', alasan: 'Antibiotik MINUM pada pasien yang muntah menyembur dan kesadarannya menurun: sebagian besar dosisnya tidak akan terserap, dan amoksisilin menembus selaput otak dengan buruk sehingga tidak pernah mencapai kadar yang membunuh kuman di cairan otak. Kerugian terbesarnya adalah waktu — resep ini melahirkan perasaan "antibiotik sudah diberikan" pada penyakit yang setiap jam penundaannya berbayar nyawa.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['pasang_infus', 'oksigen', 'pemantauan_ketat_vital'],
      edukasi: ['tanda_bahaya', 'profilaksis_kontak_meningokokus', 'etika_batuk'],
      edukasiKritis: ['tanda_bahaya', 'profilaksis_kontak_meningokokus'],
    },
    stabilisasiWajib: [],
    clue: 'Demam tinggi, sakit kepala hebat, kaku kuduk, fotofobia, muntah, penurunan kesadaran, dan ruam tidak memucat sangat mencurigakan meningitis bakterial/meningokokus. Rujuk emergensi lebih dulu. WHO 2025 membuat antibiotik pra-rujuk bersyarat: berikan ceftriaxone parenteral bila kecurigaan kuat DAN keterlambatan transfer bermakna diperkirakan terjadi; jangan memberikannya indiscriminately bila fasilitas tujuan dapat dicapai cepat. Pada skenario ini perjalanan sekitar tiga jam, sehingga dosis awal ceftriaxone dewasa 2 g IV layak diberikan; bila akses IV tidak segera didapat, gunakan IM dan jangan menahan ambulans demi infus sempurna. Pungsi lumbal tidak boleh menunda terapi. Parasetamol hanya suportif, bukan resep wajib. Laporkan dugaan meningokokus dan koordinasikan penilaian kontak erat untuk kemoprofilaksis melalui jejaring kesehatan masyarakat.',
    panduanResmi: 'Tidak ditemukan bab PPK FKTP diagnosis-spesifik pada crosswalk 167 bab. WHO Guidelines on Meningitis 2025 menjadi grounding langsung: rujuk ke fasilitas yang mampu melakukan pungsi lumbal dan menangani penyakit berat; pertimbangkan antibiotik parenteral pra-rujuk bila meningitis bakterial sangat dicurigai dan transfer diperkirakan terlambat. Rute IV diutamakan, tetapi IM digunakan bila jalur IV belum aman. Pedoman Penggunaan Antibiotik Kemenkes 2021 mencantumkan ceftriaxone dewasa 2 g IV tiap 12 jam untuk meningitis bakterial; permainan hanya menilai pilihan obat dosis awal, bukan menyimulasikan regimen rawat inap lengkap.',
    catatanRealita: 'Perjalanan rujukan skenario sekitar tiga jam, sehingga antibiotik pra-rujuk masuk akal. Bila ceftriaxone tidak tersedia, berangkat tanpa menundanya; bila IV sulit, gunakan IM. Hitung darah/GDS bukan syarat transfer. Penilaian dan kemoprofilaksis kontak erat dikoordinasikan lewat RS/dinas kesehatan, bukan memakai topik skabies atau resep massal pemain.',
    mutiaraEbm: 'Trias klasik demam, kaku kuduk, dan penurunan kesadaran lengkap hanya pada sekitar separuh penderita meningitis bakterial — sehingga menunggu ketiganya muncul berarti melewatkan separuh pasien. Yang lebih menjebak: Kernig dan Brudzinski, dua tanda yang paling percaya diri diajarkan, ternyata sensitivitasnya rendah (sekitar 5% pada beberapa penelitian) sehingga hasil NEGATIF sama sekali tidak menyingkirkan meningitis; keduanya berguna bila positif dan tidak berarti apa-apa bila negatif. Pasien ini kebetulan menunjukkan tanda yang lengkap — pasien berikutnya mungkin hanya datang dengan demam, sakit kepala, dan terasa "tidak seperti biasanya", dan justru pasien itulah yang paling sering pulang membawa parasetamol. Perangkap ketiga khas Indonesia: demam tinggi dengan sakit kepala hebat pada dewasa muda hampir selalu dibaca sebagai tifus atau demam berdarah lebih dulu, dan sudut pandang itu bertahan bahkan setelah leher kaku ditemukan.',
    konsekuensi: {
      narasi: 'Antibiotik ditahan agar "tidak mengaburkan pemeriksaan cairan otak di rumah sakit", dan pasien diberangkatkan hanya dengan penurun panas. Perjalanan memakan tiga jam, dan kuman terus berkembang biak di dalam selaput otak tanpa perlawanan.',
      kembaliHariMin: 1,
      kembaliHariMax: 2,
      kondisiKembali: 'Tiba di rumah sakit dalam keadaan tidak sadar, tekanan darah jatuh, dan bercak perdarahan sudah menyatu memenuhi kedua tungkai. Dirawat di ICU sebagai syok berat dengan pembekuan darah yang kacau. Bertahan hidup setelah dua minggu perawatan, dengan tuli menetap pada kedua telinga dan ujung jari kaki yang harus diamputasi karena mati jaringan.',
      guideline: 'WHO Guidelines on Meningitis 2025 (pre-referral antibiotic therapy); Permenkes 28/2021 Pedoman Penggunaan Antibiotik; jalur surveilans dan respons meningokokus setempat.',
    },
  }),
]

export const LAB_BATCH_4_MTS_ARCHETYPE_SPECS: Record<string, LabArchetypeSpec> = {
  lab_katarak_matur: { conceptId: 'concept:advanced_age_related_cataract', credits: ['clinical:lab_katarak_matur'] },
  lab_ablasio_retina: { conceptId: 'concept:rhegmatogenous_retinal_detachment', credits: ['clinical:lab_ablasio_retina'] },
  lab_retinopati_diabetik_proliferatif: { conceptId: 'concept:sight_threatening_diabetic_retinopathy', credits: ['clinical:lab_retinopati_diabetik_proliferatif'] },
  lab_otitis_media_supuratif_kronik_komplikata: { conceptId: 'concept:csom_complicated', credits: ['clinical:lab_otitis_media_supuratif_kronik_komplikata'] },
  lab_mastoiditis_akut: { conceptId: 'concept:acute_mastoiditis', credits: ['clinical:lab_mastoiditis_akut'] },
  lab_benda_asing_esofagus: { conceptId: 'concept:esophageal_foreign_body', credits: ['clinical:lab_benda_asing_esofagus'] },
  lab_tia_serangan_iskemik_sesaat: { conceptId: 'concept:transient_ischemic_attack', credits: ['clinical:lab_tia_serangan_iskemik_sesaat'] },
  lab_meningitis_bakterial_suspek: { conceptId: 'concept:suspected_bacterial_meningitis', credits: ['clinical:lab_meningitis_bakterial_suspek'] },
}
