import type { KasusKlinis } from '../types'
import { buatKasusFktpLab } from './labCaseFactory'

const PPK = 'PPK Dokter FKTP KMK 1186/2022 menjadi floor keputusan klinis kasus ini.'

export const LAB_BATCH_2_CASES: KasusKlinis[] = [
  buatKasusFktpLab({
    id: 'lab_kejang_demam_sederhana', nama: 'Kejang Demam Sederhana', icd10: 'R56.0', kategori: 'saraf', prevalensi: 'sedang',
    keluhanUtama: 'Anak saya tadi kejang saat demam, sekarang sudah sadar lagi.', keluhanUtamaOlehPendamping: true, usia: [1, 5], vital: { nadi: 112, rr: 24, suhu: 39.1, spo2: 98 },
    pembuka: ['Boleh ceritakan kejangnya dari awal sampai berhenti?', 'Seluruh badan kaku-kelojot sekitar tiga menit, berhenti sendiri, lalu menangis dan sekarang mengenali saya.'],
    pertanyaan: [
      ['q_durasi', 'rps', 'Berapa lama dan apakah berulang dalam 24 jam?', 'Sekitar tiga menit dan baru satu kali.', true],
      ['q_fokal', 'rps', 'Kejang seluruh badan atau hanya satu sisi?', 'Seluruh badan, tidak hanya satu sisi.', true],
      ['q_infeksi_ssp', 'rps', 'Ada kaku kuduk, muntah menyemprot, sulit dibangunkan, atau ruam ungu?', 'Tidak ada; sekarang anak sadar dan mau minum.', true],
      ['q_riwayat', 'rpd', 'Pernah kejang tanpa demam atau gangguan perkembangan?', 'Tidak pernah dan tumbuh kembangnya sesuai usia.', false],
    ],
    fisik: [['umum', 'Sadar, menangis kuat, perfusi baik; tidak lagi kejang.'], ['neurologis', 'GCS sesuai usia, kaku kuduk negatif, tanpa defisit fokal.'], ['tht_mulut', 'Faring hiperemis ringan tanpa fokus infeksi berat.', true]],
    diagnosisBanding: ['R56.0', 'G40.9', 'G00.9'],
    tatalaksana: { obatBenar: [], obatOpsional: ['paracetamol_sirup'], obatSalahUmum: [{ id: 'diazepam_rektal_10', alasan: 'Obat rescue tidak diberikan rutin setelah kejang singkat sudah berhenti dan anak sadar.', bahaya: 'nonPrimer' }], edukasi: ['pertolongan_kejang', 'kompres_demam', 'tanda_bahaya'], edukasiKritis: ['pertolongan_kejang'] },
    clue: 'Usia 6 bulan-5 tahun, kejang umum <15 menit, hanya sekali/24 jam, pulih penuh, dan tanpa tanda infeksi SSP mendukung kejang demam sederhana. Cari sumber demam dan ajarkan pertolongan kejang; antipiretik meningkatkan kenyamanan tetapi tidak menjamin mencegah kekambuhan.',
    panduanResmi: `${PPK} Rujuk bila kejang kompleks, penurunan kesadaran menetap, rangsang meningeal, atau diagnosis meragukan.`,
  }),

  buatKasusFktpLab({
    id: 'lab_tetanus_generalisata_awal', nama: 'Tetanus Generalisata - Stabilisasi dan Rujuk', icd10: 'A35', kategori: 'infeksi',
    keluhanUtama: 'Rahang saya kaku dan badan mulai kejang kalau mendengar suara keras.', usia: [20, 65], vital: { td: '138/84', nadi: 108, rr: 24, suhu: 38.0, spo2: 96 }, harusDirujuk: true, spesialisRujukan: 'penyakit_dalam',
    pembuka: ['Keluhan kaku dan kejang ini mulai bagaimana?', 'Tiga hari rahang sulit dibuka, lalu punggung menegang setiap ada suara atau sentuhan.'],
    pertanyaan: [
      ['q_luka', 'rps', 'Ada luka sebelum keluhan ini?', 'Delapan hari lalu telapak kaki tertusuk paku dan hanya saya cuci sendiri.', true],
      ['q_imunisasi', 'rpd', 'Kapan terakhir vaksin tetanus?', 'Saya tidak ingat pernah mendapat booster setelah dewasa.', true],
      ['q_napas', 'rps', 'Ada sulit menelan, tersedak, atau sesak?', 'Menelan mulai sulit tetapi saya belum sesak.', true],
      ['q_obat', 'rpd', 'Ada obat yang dapat menimbulkan kaku atau riwayat kejang?', 'Tidak ada.', false],
    ],
    fisik: [['umum', 'Trismus, risus sardonicus ringan, sadar penuh.'], ['neurologis', 'Spasme generalisata terpicu rangsang, tanpa defisit fokal.'], ['ekstremitas', 'Luka tusuk plantar dengan jaringan nekrotik kecil.', true]],
    diagnosisBanding: ['A35', 'G00.9', 'F44.5'],
    tatalaksana: { obatBenar: [], prosedur: ['minim_stimulus_tetanus', 'perawatan_luka'], edukasi: ['rawat_luka_tetanus', 'tanda_bahaya'] },
    stabilisasiWajib: ['minim_stimulus_tetanus'],
    clue: 'Trismus dan spasme terpicu rangsang setelah luka berisiko dengan imunisasi tidak jelas adalah tetanus sampai terbukti lain. Minimalkan rangsang, amankan jalan napas, rawat luka tanpa manuver agresif, dan transfer segera untuk imunoglobulin, antimikroba, kontrol spasme, serta monitoring intensif.',
    panduanResmi: `${PPK} Tetanus memerlukan tata laksana komprehensif dan pemantauan jalan napas di fasilitas rujukan.`,
    catatanRealita: 'TIG, ventilasi, dan sedasi kontinu tidak diasumsikan tersedia di Sukamaju; ketiadaan itu memperkuat transfer, bukan alasan menunda.',
  }),

  buatKasusFktpLab({
    id: 'lab_hiv_tanpa_komplikasi', nama: 'HIV Tanpa Komplikasi - Inisiasi Program', icd10: 'Z21', kategori: 'infeksi', prevalensi: 'sedang',
    keluhanUtama: 'Saya datang mengambil hasil tes HIV dan ingin segera mulai pengobatan.', usia: [18, 55], vital: { td: '118/76', nadi: 82, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: ['Apa yang membuat Anda melakukan tes dan bagaimana kondisi sekarang?', 'Pasangan saya terdiagnosis HIV; saya merasa sehat dan tidak punya keluhan berat.'],
    pertanyaan: [
      ['q_oi', 'rps', 'Ada batuk lama, demam, penurunan berat badan, diare lama, sakit kepala berat, atau sesak?', 'Tidak ada; berat badan stabil.', true],
      ['q_obat', 'rpd', 'Pernah memakai ARV atau obat rutin lain?', 'Belum pernah ARV dan tidak ada obat rutin.', true],
      ['q_tb', 'rps', 'Ada kontak TB atau gejala TB?', 'Tidak ada batuk lama, keringat malam, atau kontak TB.', true],
      ['q_kesiapan', 'sosial', 'Siapa yang dapat mendukung minum obat setiap hari?', 'Pasangan saya mendukung dan kami siap kontrol bersama.', false],
    ],
    fisik: [['umum', 'Status gizi baik, tidak tampak infeksi oportunistik.'], ['kepala_leher', 'Tidak ada kandidiasis oral atau limfadenopati bermakna.'], ['toraks_paru', 'Suara napas normal.', false]],
    lab: [['tes_hiv_serial', 'Tiga tes cepat serial reaktif sesuai algoritma nasional.', 'abnormal'], ['darah_rutin', 'Hb 13,6 g/dL; leukosit dan trombosit normal.', 'normal'], ['fungsi_ginjal', 'Kreatinin 0,9 mg/dL.', 'normal']],
    diagnosisBanding: ['Z21', 'B20', 'F43.2'],
    tatalaksana: { obatBenar: ['arv_tld'], edukasi: ['kepatuhan_arv', 'cegah_ims_pasangan', 'kontrol_rutin'], edukasiKritis: ['kepatuhan_arv'] },
    konfirmasiWajib: 'tes_hiv_serial',
    clue: 'Diagnosis HIV harus mengikuti algoritma tes nasional, kemudian skrining TB/infeksi oportunistik, kesiapan, fungsi ginjal, interaksi obat, dan inisiasi ARV secepatnya melalui layanan yang berwenang. Kondisi tanpa komplikasi tidak berarti terapi boleh ditunda.',
    panduanResmi: `${PPK} Tes dan terapi berjalan dalam program HIV; kerahasiaan, konseling, dan kesinambungan ARV wajib dijaga.`,
    catatanRealita: 'Fornas membolehkan ARV di FKTP yang ditunjuk. Skenario ini menyatakan Sukamaju memiliki jejaring dan kewenangan layanan ARV.',
  }),

  buatKasusFktpLab({
    id: 'lab_gangguan_somatoform', nama: 'Gangguan Somatoform', icd10: 'F45', kategori: 'jiwa', prevalensi: 'sedang',
    keluhanUtama: 'Dada sering berdebar dan badan terasa sakit berpindah-pindah, tapi pemeriksaan sebelumnya normal.', usia: [20, 55], vital: { td: '124/78', nadi: 84, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Keluhan mana yang paling mengganggu dan sudah berapa lama?', 'Enam bulan ini nyeri berpindah, mual, dan berdebar; saya takut ada penyakit yang belum ditemukan.'],
    pertanyaan: [
      ['q_pola', 'rps', 'Apakah keluhan berkaitan dengan aktivitas, makan, atau situasi tertentu?', 'Lebih sering saat masalah keluarga memuncak, tetapi rasanya benar-benar fisik.', true],
      ['q_redflag', 'rps', 'Ada pingsan saat aktivitas, berat badan turun, demam lama, perdarahan, atau kelemahan satu sisi?', 'Tidak ada.', true],
      ['q_fungsi', 'sosial', 'Seberapa jauh keluhan mengganggu kerja dan rumah?', 'Saya sering izin kerja dan berulang kali berpindah klinik.', true],
      ['q_mood', 'rps', 'Ada rasa sedih berat, serangan panik, atau pikiran menyakiti diri?', 'Cemas, tetapi tidak ingin menyakiti diri.', true],
    ],
    fisik: [['umum', 'Tampak cemas namun kooperatif; pemeriksaan umum normal.'], ['jantung', 'Irama reguler, tanpa murmur.'], ['neurologis', 'Status neurologis normal.', false]],
    diagnosisBanding: ['F45', 'F41.1', 'E03.9'],
    tatalaksana: { obatBenar: [], obatSalahUmum: [{ id: 'diazepam_2', alasan: 'Benzodiazepin rutin tidak menyelesaikan pola gejala dan berisiko ketergantungan.', bahaya: 'nonPrimer' }], edukasi: ['perawatan_terjadwal_somatik', 'manajemen_stres', 'tanda_bahaya'] },
    clue: 'Keluhan fisik persisten, distress nyata, pemeriksaan wajar, pola terkait stres, dan penggunaan layanan berulang mendukung gangguan somatoform setelah red flag disaring. Validasi pengalaman pasien, sepakati satu dokter dan kontrol terjadwal, fokus fungsi, serta hindari investigasi dan obat berulang tanpa indikasi.',
    panduanResmi: `${PPK} Diagnosis tidak boleh menjadi jalan pintas sebelum evaluasi klinis memadai dan asesmen risiko psikologis.`,
  }),

  buatKasusFktpLab({
    id: 'lab_benda_asing_konjungtiva', nama: 'Benda Asing Konjungtiva Superfisial', icd10: 'T15.9', kategori: 'mata',
    keluhanUtama: 'Mata kanan terasa mengganjal setelah sekam tertiup angin saat berkebun tadi pagi.', usia: [18, 60], vital: { td: '122/76', nadi: 80, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Apa yang terjadi pada mata dan apakah memakai pelindung?', 'Serpihan sekam kecil tertiup ke mata; saya tidak memakai kacamata pelindung.'],
    pertanyaan: [
      ['q_visus', 'rps', 'Penglihatan turun, nyeri berat, atau silau hebat?', 'Penglihatan tetap jelas, hanya mengganjal dan berair.', true],
      ['q_kimia', 'rps', 'Ada bahan kimia, pukulan, atau serpihan berkecepatan tinggi?', 'Tidak ada; hanya sekam yang tertiup angin.', true],
      ['q_lensa', 'rpd', 'Memakai lensa kontak atau pernah operasi mata?', 'Tidak.', false],
    ],
    fisik: [['mata', 'Visus setara kedua mata; benda asing superfisial tampak di konjungtiva tarsal, pupil normal, Seidel negatif.'], ['umum', 'Kondisi umum baik.', false]],
    diagnosisBanding: ['T15.9', 'S05.0', 'H16.0'],
    tatalaksana: { obatBenar: [], obatOpsional: ['kloramfenikol_tetes_mata'], prosedur: ['ekstraksi_benda_asing_konjungtiva'], edukasi: ['perlindungan_mata', 'tanda_bahaya'] },
    clue: 'Benda asing superfisial dengan visus normal dan tanpa tanda penetrasi dapat diirigasi lalu diekstraksi secara visual. Eversi kelopak dan periksa abrasi; jangan melakukan probing bila benda tertanam, mekanisme berkecepatan tinggi, pupil tidak normal, atau Seidel positif.',
    panduanResmi: `${PPK} Penurunan visus, benda tertanam, penetrasi, atau kegagalan ekstraksi adalah alasan rujuk mata.`,
  }),

  buatKasusFktpLab({
    id: 'lab_perdarahan_subkonjungtiva', nama: 'Perdarahan Subkonjungtiva Spontan', icd10: 'H11.3', kategori: 'mata', prevalensi: 'sedang',
    keluhanUtama: 'Putih mata saya tiba-tiba merah seperti darah, tetapi tidak sakit.', usia: [25, 75], vital: { td: '146/88', nadi: 78, rr: 18, suhu: 36.5, spo2: 99 },
    pembuka: ['Kapan merahnya terlihat dan apa yang dirasakan?', 'Bangun tidur tadi terlihat bercak darah; tidak nyeri, tidak silau, dan penglihatan normal.'],
    pertanyaan: [
      ['q_trauma', 'rps', 'Ada benturan, mengucek kuat, batuk, muntah, atau mengejan?', 'Kemarin batuk keras beberapa kali.', true],
      ['q_visus', 'rps', 'Ada penglihatan turun, nyeri, sekret, atau silau?', 'Tidak ada semuanya.', true],
      ['q_obat', 'rpd', 'Minum pengencer darah atau mudah memar/berdarah?', 'Tidak minum pengencer darah dan tidak mudah memar.', true],
    ],
    fisik: [['mata', 'Bercak merah berbatas tegas di bawah konjungtiva bulbi; kornea jernih, pupil normal, visus utuh.'], ['jantung', 'Tekanan darah sedikit meningkat; irama reguler.', true]],
    diagnosisBanding: ['H11.3', 'H10.9', 'H15.1'],
    tatalaksana: { obatBenar: [], obatSalahUmum: [{ id: 'gentamisin_tetes_mata', alasan: 'Tidak ada infeksi bakteri; antibiotik tetes tidak mempercepat resorpsi darah.', bahaya: 'nonPrimer' }], edukasi: ['kontrol_rutin', 'tanda_bahaya'] },
    clue: 'Bercak darah tanpa nyeri, fotofobia, sekret, atau penurunan visus khas perdarahan subkonjungtiva dan umumnya pulih sendiri 1-2 minggu. Ukur tekanan darah serta telusuri trauma, antikoagulan, atau gangguan perdarahan bila berulang.',
    panduanResmi: `${PPK} Rujuk bila trauma berat, gangguan visus, nyeri, kekambuhan, atau kecurigaan gangguan sistemik.`,
  }),

  buatKasusFktpLab({
    id: 'lab_mata_kering', nama: 'Mata Kering', icd10: 'H04.1', kategori: 'mata', prevalensi: 'tinggi',
    keluhanUtama: 'Kedua mata terasa berpasir dan cepat lelah saat bekerja di depan layar.', usia: [25, 70], vital: { td: '120/76', nadi: 76, rr: 18, suhu: 36.5, spo2: 99 },
    pembuka: ['Kapan rasa mengganjal muncul dan apa pemicunya?', 'Makin terasa sore setelah menatap layar dan berada di ruangan ber-AC.'],
    pertanyaan: [
      ['q_redflag', 'rps', 'Ada nyeri tajam, silau berat, sekret kental, atau penglihatan mendadak turun?', 'Tidak ada.', true],
      ['q_obat', 'rpd', 'Memakai lensa kontak atau obat antihistamin/antikolinergik?', 'Kadang minum obat alergi dan tidak memakai lensa kontak.', true],
      ['q_sistemik', 'rpd', 'Ada mulut sangat kering, nyeri sendi, atau penyakit autoimun?', 'Tidak ada.', false],
    ],
    fisik: [['mata', 'Visus baik; tear meniscus berkurang, hiperemia ringan bilateral, kornea jernih.'], ['kepala_leher', 'Mukosa mulut lembap; tidak ada pembesaran kelenjar.', false]],
    diagnosisBanding: ['H04.1', 'H10.9', 'H01.0'],
    tatalaksana: { obatBenar: ['air_mata_buatan'], edukasi: ['perlindungan_mata', 'kontrol_rutin'] },
    clue: 'Gejala bilateral berpasir yang memburuk saat screen-time/AC tanpa red flag mendukung dry eye. Gunakan lubrikan, jeda berkedip, koreksi faktor lingkungan dan obat; rujuk bila nyeri, defek kornea, atau refrakter.',
    panduanResmi: `${PPK} Air mata buatan dan modifikasi faktor pencetus menjadi terapi awal.`,
  }),

  buatKasusFktpLab({
    id: 'lab_blefaritis_anterior', nama: 'Blefaritis Anterior', icd10: 'H01.0', kategori: 'mata', prevalensi: 'sedang',
    keluhanUtama: 'Kelopak mata gatal dan berkerak setiap bangun tidur.', usia: [18, 75], vital: { td: '118/74', nadi: 76, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Bagaimana keluhan pada kelopak dan sejak kapan?', 'Dua minggu tepi kelopak gatal, terasa panas, dan ada kerak di pangkal bulu mata.'],
    pertanyaan: [
      ['q_visus', 'rps', 'Ada nyeri dalam mata, silau, atau penglihatan turun?', 'Tidak; hanya tepi kelopak yang mengganggu.', true],
      ['q_kulit', 'rpd', 'Ada ketombe, rosasea, atau keluhan berulang?', 'Saya memang berketombe dan pernah kambuh ringan.', true],
      ['q_kontak', 'sosial', 'Memakai riasan mata atau lensa kontak?', 'Sering memakai riasan mata.', false],
    ],
    fisik: [['mata', 'Skuama dan krusta di pangkal bulu mata bilateral, hiperemia tepi palpebra, kornea jernih.'], ['kulit', 'Skuama seboroik ringan di kulit kepala.', true]],
    diagnosisBanding: ['H01.0', 'H00.0', 'H10.9'],
    tatalaksana: { obatBenar: [], obatOpsional: ['air_mata_buatan'], edukasi: ['higiene_kelopak_mata', 'kontrol_rutin'] },
    clue: 'Krusta tepi kelopak kronik dengan kornea dan visus normal mendukung blefaritis. Terapi utama adalah kompres hangat dan higiene kelopak konsisten; antibiotik topikal tidak rutin dan hanya dipertimbangkan pada komponen bakterial terpilih.',
    panduanResmi: `${PPK} Evaluasi kelainan kornea dan rujuk bila tidak membaik atau terjadi komplikasi.`,
  }),

  buatKasusFktpLab({
    id: 'lab_trikiasis', nama: 'Trikiasis Tanpa Komplikasi Kornea', icd10: 'H02', kategori: 'mata',
    keluhanUtama: 'Bulu mata bawah seperti menusuk mata dan membuat berair.', usia: [35, 80], vital: { td: '126/78', nadi: 76, rr: 18, suhu: 36.5, spo2: 99 },
    pembuka: ['Sejak kapan terasa tertusuk dan apakah penglihatan berubah?', 'Seminggu ini terasa menggesek saat berkedip; penglihatan tetap jelas.'],
    pertanyaan: [
      ['q_redflag', 'rps', 'Ada nyeri berat, silau, atau penglihatan turun?', 'Tidak ada.', true],
      ['q_riwayat', 'rpd', 'Pernah operasi kelopak, trauma, atau infeksi mata berulang?', 'Tidak pernah operasi; pernah radang kelopak beberapa kali.', true],
      ['q_satu', 'rps', 'Satu atau banyak bulu mata yang mengarah ke dalam?', 'Tampaknya dua helai di kelopak bawah.', false],
    ],
    fisik: [['mata', 'Dua silia palpebra inferior mengarah ke kornea; visus normal, fluorescein tanpa defek epitel.']],
    diagnosisBanding: ['H02', 'H01.0', 'H16.0'],
    tatalaksana: { obatBenar: ['air_mata_buatan'], prosedur: ['epilasi_trikiasis'], edukasi: ['perlindungan_mata', 'tanda_bahaya'] },
    clue: 'Silia yang menggesek permukaan mata dengan posisi kelopak normal adalah trikiasis. Epilasi memberi kelegaan sementara; evaluasi kornea dan rujuk untuk terapi definitif bila berulang atau luas.',
    panduanResmi: `${PPK} Kerusakan kornea atau kelainan palpebra kompleks memerlukan layanan mata.`,
  }),

  buatKasusFktpLab({
    id: 'lab_episkleritis_ringan', nama: 'Episkleritis Sederhana', icd10: 'H15.1', kategori: 'mata',
    keluhanUtama: 'Sebagian putih mata kiri merah dan agak ngilu sejak kemarin.', usia: [20, 60], vital: { td: '120/74', nadi: 78, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Merahnya menyeluruh atau setempat, dan seberapa sakit?', 'Hanya satu sektor, rasa tidak nyaman ringan, tidak sampai sakit dalam.'],
    pertanyaan: [
      ['q_visus', 'rps', 'Ada silau berat atau penglihatan menurun?', 'Tidak ada.', true],
      ['q_sekret', 'rps', 'Ada kotoran mata kental atau kelopak lengket?', 'Tidak ada.', true],
      ['q_autoimun', 'rpd', 'Ada nyeri sendi, sariawan berulang, atau penyakit autoimun?', 'Tidak ada.', false],
    ],
    fisik: [['mata', 'Injeksi sektoral superfisial, nyeri tekan minimal, kornea jernih, pupil dan visus normal.']],
    diagnosisBanding: ['H15.1', 'H10.9', 'H15.0'],
    tatalaksana: { obatBenar: [], obatOpsional: ['air_mata_buatan', 'ibuprofen_400'], edukasi: ['kontrol_rutin', 'tanda_bahaya'] },
    clue: 'Kemerahan sektoral superfisial dengan rasa tidak nyaman ringan dan visus normal mendukung episkleritis, yang sering pulih sendiri. Sakit dalam, fotofobia, rona keunguan, atau penurunan visus mengarah ke skleritis/uveitis dan memerlukan evaluasi mata segera.',
    panduanResmi: `${PPK} Terapi simptomatik dapat diberikan; telusuri penyakit sistemik pada kekambuhan.`,
  }),

  ...[
    {
      id: 'lab_hipermetropia', nama: 'Hipermetropia', icd10: 'H52.0', usia: [8, 45] as const,
      keluhan: 'Mata cepat lelah dan kepala sakit saat membaca dekat.', pembuka: 'Keluhan terutama saat membaca; melihat jauh masih cukup jelas.',
      fisik: 'Visus dekat menurun dan membaik dengan lensa sferis plus; segmen anterior normal.', banding: ['H52.0', 'H52.4', 'H52.2'],
      clue: 'Keluhan dekat dengan perbaikan lensa plus mendukung hipermetropia. Koreksi optik ditentukan melalui refraksi, bukan sekadar memilih kacamata baca acak.',
    },
    {
      id: 'lab_miopia_ringan', nama: 'Miopia Ringan', icd10: 'H52.1', usia: [8, 35] as const,
      keluhan: 'Tulisan di papan tampak kabur, tetapi membaca dekat jelas.', pembuka: 'Kabur terutama saat melihat jauh dan membaik bila menyipitkan mata.',
      fisik: 'Visus jauh menurun dan membaik dengan pinhole/lensa sferis minus; mata lain normal.', banding: ['H52.1', 'H52.0', 'H52.2'],
      clue: 'Kabur jauh yang membaik dengan pinhole dan lensa minus mendukung miopia. Perubahan cepat, anisometropia berat, atau kelainan fundus memerlukan evaluasi mata.',
    },
    {
      id: 'lab_astigmatisme_ringan', nama: 'Astigmatisme Ringan', icd10: 'H52.2', usia: [10, 50] as const,
      keluhan: 'Tulisan jauh dan dekat tampak berbayang dan mata cepat lelah.', pembuka: 'Garis tertentu tampak lebih kabur dan sakit kepala muncul setelah membaca.',
      fisik: 'Visus membaik sebagian dengan pinhole dan terkoreksi dengan lensa silinder; kornea jernih.', banding: ['H52.2', 'H52.1', 'H52.0'],
      clue: 'Distorsi pada berbagai jarak dan koreksi lensa silinder mendukung astigmatisme. Refraksi objektif/subjektif diperlukan untuk resep yang presisi.',
    },
    {
      id: 'lab_presbiopia', nama: 'Presbiopia', icd10: 'H52.4', usia: [42, 75] as const,
      keluhan: 'Saya harus menjauhkan tulisan agar bisa dibaca.', pembuka: 'Keluhan dekat memburuk perlahan sejak usia pertengahan, sedangkan jauh tetap jelas.',
      fisik: 'Visus jauh baik; titik dekat menjauh dan membaik dengan adisi lensa plus sesuai usia.', banding: ['H52.4', 'H52.0', 'H52.1'],
      clue: 'Penurunan akomodasi progresif setelah usia sekitar 40 tahun dengan visus jauh baik adalah presbiopia. Tentukan adisi setelah menilai refraksi jauh dan kebutuhan kerja.',
    },
  ].map((refraksi) => buatKasusFktpLab({
    id: refraksi.id, nama: refraksi.nama, icd10: refraksi.icd10, kategori: 'mata', prevalensi: 'tinggi',
    keluhanUtama: refraksi.keluhan, usia: refraksi.usia, vital: { td: '120/76', nadi: 76, rr: 18, suhu: 36.5, spo2: 99 },
    pembuka: ['Kapan penglihatan kabur paling terasa?', refraksi.pembuka],
    pertanyaan: [
      ['q_redflag', 'rps', 'Ada nyeri, mata merah, kilatan cahaya, atau penurunan mendadak?', 'Tidak ada; perubahan berlangsung perlahan.', true],
      ['q_kacamata', 'rpd', 'Pernah memakai kacamata atau ada perubahan resep cepat?', 'Belum pernah dan tidak ada perubahan mendadak.', true],
      ['q_fungsi', 'sosial', 'Aktivitas apa yang paling terganggu?', 'Membaca dan pekerjaan harian menjadi lebih lambat.', false],
    ],
    fisik: [['mata', refraksi.fisik]], diagnosisBanding: refraksi.banding,
    tatalaksana: { obatBenar: [], prosedur: ['uji_visus_refraksi'], edukasi: ['adaptasi_kacamata', 'tanda_bahaya'] },
    clue: refraksi.clue, panduanResmi: `${PPK} Ukur visus dan lakukan koreksi optik; rujuk bila koreksi tidak memperbaiki atau ada kelainan organik.`,
    catatanRealita: 'Refraksi dan pembuatan lensa dapat dijadwalkan atau dilakukan melalui jejaring optometri; game tidak menganggap seluruh Puskesmas memiliki optik lengkap.',
  })),

  buatKasusFktpLab({
    id: 'lab_buta_senja_defisiensi_vitamin_a', nama: 'Buta Senja karena Defisiensi Vitamin A', icd10: 'H53.6', kategori: 'mata',
    keluhanUtama: 'Anak saya sering menabrak benda saat hari mulai gelap.', keluhanUtamaOlehPendamping: true, usia: [6, 12], vital: { nadi: 88, rr: 20, suhu: 36.7, spo2: 99 },
    pembuka: ['Sejak kapan penglihatan malam terganggu?', 'Dua bulan ini ia sulit melihat saat senja, tetapi siang hari masih bisa sekolah.'],
    pertanyaan: [
      ['q_diet', 'sosial', 'Bagaimana pola makan anak?', 'Sangat pilih-pilih dan hampir tidak pernah makan telur, hati, susu, atau sayur berwarna.', true],
      ['q_mata', 'rps', 'Mata kering, berbusa, nyeri, atau penglihatan siang turun?', 'Mata tampak agak kering, tidak nyeri.', true],
      ['q_diare', 'rpd', 'Ada diare lama, penyakit hati, atau sulit menyerap makanan?', 'Tidak ada diare lama.', false],
    ],
    fisik: [['mata', 'Konjungtiva kering ringan, bercak Bitot kecil temporal, kornea masih jernih.'], ['umum', 'Berat badan menurut umur sedikit rendah.', true]],
    diagnosisBanding: ['H53.6', 'E50.5', 'H35.5'],
    tatalaksana: { obatBenar: ['vitamin_a_kapsul'], edukasi: ['gizi_seimbang', 'tanda_bahaya'] },
    clue: 'Sulit melihat saat senja disertai xerosis/Bitot dan diet miskin vitamin A mendukung xeroftalmia dini. Beri vitamin A sesuai usia/protokol dan perbaiki gizi; keterlibatan kornea memerlukan evaluasi mata pada hari yang sama.',
    panduanResmi: `${PPK} Buta senja memerlukan evaluasi defisiensi vitamin A dan penyebab mata/retina lain.`,
  }),

  buatKasusFktpLab({
    id: 'lab_infeksi_umbilikus_neonatus', nama: 'Infeksi Umbilikus dengan Tanda Sistemik', icd10: 'P38', kategori: 'kia',
    keluhanUtama: 'Tali pusat bayi bernanah, kulit sekitarnya merah, dan sejak pagi sulit menyusu.', keluhanUtamaOlehPendamping: true, usia: [0, 0], usiaBulan: [0, 1], vital: { nadi: 170, rr: 58, suhu: 38.1, spo2: 96 }, harusDirujuk: true, spesialisRujukan: 'anak',
    pembuka: ['Sejak kapan tali pusat berubah dan bagaimana minumnya?', 'Dua hari berbau dan bernanah; hari ini kemerahan melebar dan bayi hanya minum sedikit.'],
    pertanyaan: [
      ['q_bahaya', 'rps', 'Ada kejang, sangat mengantuk, muntah semua, kebiruan, atau napas berhenti?', 'Bayi lebih mengantuk tetapi tidak kejang atau kebiruan.', true],
      ['q_lahir', 'rpd', 'Lahir cukup bulan dan bagaimana persalinannya?', 'Lahir cukup bulan di fasilitas kesehatan.', true],
      ['q_perawatan', 'sosial', 'Apa yang dioleskan pada tali pusat?', 'Nenek menaburkan bubuk ramuan sejak pulang.', true],
    ],
    fisik: [['umum', 'Neonatus letargis ringan, perfusi memanjang 3 detik.'], ['abdomen', 'Pus dan bau dari umbilikus; eritema meluas sekitar 2 cm ke kulit periumbilikal.'], ['toraks_paru', 'Napas cepat tanpa retraksi berat.', true]],
    diagnosisBanding: ['P38', 'P36.9', 'L03.3'],
    tatalaksana: { obatBenar: [], prosedur: ['akses_iv_resusitasi', 'antibiotik_parenteral_neonatus_protokol', 'perawatan_tali_pusat'], edukasi: ['perawatan_tali_pusat_kering', 'tanda_bahaya'], edukasiKritis: ['tanda_bahaya'] },
    stabilisasiWajib: ['akses_iv_resusitasi', 'antibiotik_parenteral_neonatus_protokol'],
    clue: 'Pus umbilikus, eritema meluas, demam, sulit menyusu, dan letargi pada neonatus adalah infeksi serius/omfalitis dengan risiko sepsis. Mulai tata laksana awal sesuai protokol neonatus dan rujuk segera; jangan mengandalkan obat oles atau antibiotik oral.',
    panduanResmi: `${PPK} Kemerahan meluas atau tanda sistemik pada neonatus memerlukan antibiotik parenteral dan rujukan.`,
  }),

  buatKasusFktpLab({
    id: 'lab_gonore_uretritis_pria', nama: 'Gonore Uretra Tanpa Komplikasi', icd10: 'A54.9', kategori: 'infeksi', prevalensi: 'sedang',
    keluhanUtama: 'Keluar nanah dari penis dan perih saat kencing sejak dua hari.', usia: [18, 55], jenisKelamin: 'L', vital: { td: '122/78', nadi: 82, rr: 18, suhu: 37.2, spo2: 99 },
    pembuka: ['Bagaimana cairan dan nyeri kencingnya?', 'Cairan kuning kental keluar spontan, terutama pagi, dan kencing terasa terbakar.'],
    pertanyaan: [
      ['q_pajanan', 'sosial', 'Kapan hubungan seksual terakhir dan apakah memakai kondom?', 'Lima hari lalu dengan pasangan baru tanpa kondom.', true],
      ['q_komplikasi', 'rps', 'Ada nyeri atau bengkak testis, demam, nyeri sendi, atau ruam?', 'Tidak ada.', true],
      ['q_alergi', 'rpd', 'Ada alergi antibiotik?', 'Tidak ada alergi obat yang diketahui.', true],
    ],
    fisik: [['umum', 'Tidak demam dan kondisi umum baik.'], ['tht_mulut', 'Tidak ada lesi mukosa.', false], ['kulit', 'Sekret uretra mukopurulen; testis tidak nyeri atau bengkak.', true]],
    lab: [['tes_sifilis', 'Nonreaktif; tetap perlu ulang sesuai window period/risk.', 'normal']],
    diagnosisBanding: ['A54.9', 'N34.2', 'A51'],
    tatalaksana: { obatBenar: ['ceftriaxone_1g_inj', 'doksisiklin_100'], edukasi: ['cegah_ims_pasangan', 'kepatuhan_obat', 'tanda_bahaya'], edukasiKritis: ['cegah_ims_pasangan'] },
    clue: 'Duh uretra purulen akut setelah pajanan seksual sangat mendukung gonore. Beri seftriakson dosis tunggal dan terapi klamidia bila belum disingkirkan, tawarkan tes HIV/sifilis, tata pasangan, dan hindari hubungan sampai terapi selesai.',
    panduanResmi: `${PPK} Pendekatan sindromik tidak menghilangkan kewajiban pelacakan pasangan dan skrining IMS lain.`,
  }),

  buatKasusFktpLab({
    id: 'lab_pielonefritis_tanpa_komplikasi', nama: 'Pielonefritis Akut Tanpa Komplikasi', icd10: 'N10', kategori: 'infeksi', prevalensi: 'sedang',
    keluhanUtama: 'Demam menggigil, nyeri pinggang kanan, dan perih saat kencing.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '112/72', nadi: 102, rr: 20, suhu: 38.6, spo2: 99 },
    pembuka: ['Keluhan kencing dan nyeri pinggang mulai bagaimana?', 'Dua hari anyang-anyangan lalu demam dan pinggang kanan nyeri; saya masih bisa minum.'],
    pertanyaan: [
      ['q_hamil', 'rps', 'Apakah mungkin hamil atau haid terlambat?', 'Tidak; tes kehamilan hari ini negatif.', true],
      ['q_komplikasi', 'rpd', 'Ada batu, kelainan ginjal, diabetes, atau ISK berulang?', 'Tidak ada.', true],
      ['q_sepsis', 'rps', 'Ada bingung, pingsan, muntah semua, atau urine sangat sedikit?', 'Tidak ada; hanya mual ringan.', true],
    ],
    fisik: [['umum', 'Tampak sakit sedang, sadar penuh, hidrasi cukup.'], ['abdomen', 'Nyeri ketok CVA kanan positif, nyeri suprapubik ringan tanpa defans.']],
    lab: [['urinalisis', 'Leukosit esterase +++, nitrit positif, piuria dan bakteriuria.', 'abnormal'], ['fungsi_ginjal', 'Kreatinin 0,8 mg/dL.', 'normal'], ['tes_kehamilan', 'Negatif.', 'normal']],
    diagnosisBanding: ['N10', 'N30.0', 'N20.0'],
    tatalaksana: { obatBenar: ['ciprofloxacin_500', 'paracetamol_500'], edukasi: ['minum_air_cukup', 'kepatuhan_obat', 'tanda_bahaya'], edukasiKritis: ['tanda_bahaya'] },
    clue: 'Demam, gejala sistitis, dan nyeri CVA dengan piuria mendukung pielonefritis. Pasien tidak hamil, stabil, tanpa obstruksi/komorbid, dan dapat minum sehingga terapi rawat jalan dapat dipertimbangkan dengan evaluasi 48-72 jam; kultur/rujuk bila respons buruk.',
    panduanResmi: `${PPK} Rujuk bila urosepsis, obstruksi, kehamilan, muntah, fungsi ginjal terganggu, atau tidak membaik.`,
    catatanRealita: 'Pilihan empiris harus mengikuti pola resistensi lokal; vignette lab ini menggunakan opsi PPK pada pasien terseleksi tanpa komplikasi.',
  }),

  buatKasusFktpLab({
    id: 'lab_fimosis_patologis_ringan', nama: 'Fimosis Patologis Tanpa Retensi', icd10: 'N47.1', kategori: 'kia',
    keluhanUtama: 'Kulup anak sulit ditarik dan ujungnya menggelembung saat kencing.', keluhanUtamaOlehPendamping: true, usia: [5, 11], jenisKelamin: 'L', vital: { nadi: 84, rr: 20, suhu: 36.7, spo2: 99 },
    pembuka: ['Bagaimana aliran kencing dan sejak kapan?', 'Pancaran masih keluar tetapi mengecil; tidak pernah sampai tidak bisa kencing.'],
    pertanyaan: [
      ['q_infeksi', 'rps', 'Ada demam, nanah, nyeri berat, atau infeksi berulang?', 'Tidak ada demam; pernah merah ringan sekali.', true],
      ['q_paksa', 'sosial', 'Apakah kulup pernah ditarik paksa?', 'Kami pernah mencoba menarik kuat dan sejak itu ada cincin putih.', true],
      ['q_retensi', 'rps', 'Masih bisa kencing dan apakah kulup tersangkut di belakang kepala penis?', 'Masih bisa kencing dan kulup tidak tersangkut.', true],
    ],
    fisik: [['umum', 'Anak aktif dan tidak demam.'], ['kulit', 'Cincin preputium sempit dengan jaringan parut ringan; glans tidak dapat diekspos, tanpa edema akut.', true]],
    diagnosisBanding: ['N47.1', 'N47.2', 'N48.1'],
    tatalaksana: { obatBenar: ['betametason_krim_005'], edukasi: ['higiene_genital_lembut', 'tanda_bahaya'] },
    clue: 'Fimosis patologis dengan cincin fibrotik tetapi tanpa retensi atau infeksi berat dapat dicoba kortikosteroid topikal dan retraksi lembut terarah. Jangan menarik paksa; rujuk bila skar berat, infeksi berulang, gangguan berkemih, atau gagal terapi.',
    panduanResmi: `${PPK} Kortikosteroid topikal 0,05% selama beberapa minggu dan sirkumsisi terpilih adalah opsi.`,
  }),

  buatKasusFktpLab({
    id: 'lab_parafimosis_reduksibel', nama: 'Parafimosis Akut', icd10: 'N47.2', kategori: 'gawat',
    keluhanUtama: 'Kulup tertarik ke belakang dan tidak bisa kembali, kepala penis membengkak.', usia: [15, 70], jenisKelamin: 'L', vital: { td: '132/82', nadi: 96, rr: 20, suhu: 36.8, spo2: 99 },
    pembuka: ['Kapan kulup tersangkut dan masih bisa kencing?', 'Sejak enam jam setelah membersihkan penis; masih bisa kencing sedikit dan warna glans masih merah muda.'],
    pertanyaan: [
      ['q_iskemia', 'rps', 'Apakah warna menjadi biru/kehitaman, kebas, atau nyeri makin berat?', 'Belum; nyeri sedang dan tidak kebas.', true],
      ['q_prosedur', 'rps', 'Ada pemasangan kateter atau tindakan sebelumnya?', 'Tidak ada.', true],
      ['q_obat', 'rpd', 'Ada alergi obat atau gangguan perdarahan?', 'Tidak ada.', false],
    ],
    fisik: [['kulit', 'Preputium membentuk cincin konstriksi di belakang glans; edema sedang, glans hangat merah muda, perfusi masih baik.']],
    diagnosisBanding: ['N47.2', 'N47.1', 'N48.1'],
    tatalaksana: { obatBenar: [], obatOpsional: ['ibuprofen_400'], prosedur: ['reduksi_parafimosis'], edukasi: ['higiene_genital_lembut', 'tanda_bahaya'] },
    clue: 'Parafimosis adalah kegawatan urologi. Beri analgesia, kompresi edema, lalu reduksi manual lembut; jangan menunda bila perfusi menurun. Reduksi gagal, jaringan iskemik, atau komplikasi memerlukan transfer urologi emergensi.',
    panduanResmi: `${PPK} Reduksi manual dilakukan segera; tindakan bedah diperlukan bila gagal.`,
  }),

  buatKasusFktpLab({
    id: 'lab_sindrom_duh_genital_servisitis', nama: 'Sindrom Duh Genital - Servisitis', icd10: 'N89', kategori: 'infeksi',
    keluhanUtama: 'Keputihan kekuningan dan keluar darah sedikit setelah berhubungan.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '118/74', nadi: 82, rr: 18, suhu: 37.1, spo2: 99 },
    pembuka: ['Bagaimana cairan, bau, dan keluhan penyertanya?', 'Cairan mukus-kuning dari vagina, tidak terlalu bau, disertai perih kencing ringan.'],
    pertanyaan: [
      ['q_pid', 'rps', 'Ada demam, nyeri perut bawah, mual, atau nyeri saat berhubungan?', 'Tidak ada nyeri perut atau demam.', true],
      ['q_pajanan', 'sosial', 'Ada pasangan baru atau hubungan tanpa kondom?', 'Ada pasangan baru dan tidak selalu memakai kondom.', true],
      ['q_hamil', 'rps', 'Apakah mungkin hamil?', 'Tidak, tes kehamilan negatif.', true],
    ],
    fisik: [['abdomen', 'Tidak ada nyeri tekan suprapubik atau defans.', true], ['kulit', 'Sekret mukopurulen dari serviks dan serviks mudah berdarah; tidak ada nyeri goyang serviks.', true]],
    lab: [['tes_kehamilan', 'Negatif.', 'normal'], ['tes_sifilis', 'Nonreaktif.', 'normal']],
    diagnosisBanding: ['N89', 'A54.9', 'N76.0'],
    tatalaksana: { obatBenar: ['ceftriaxone_1g_inj', 'doksisiklin_100'], edukasi: ['cegah_ims_pasangan', 'kepatuhan_obat', 'tanda_bahaya'], edukasiKritis: ['cegah_ims_pasangan'] },
    clue: 'Duh mukopurulen serviks dan contact bleeding tanpa nyeri pelvis mendukung servisitis. Tata laksana sindromik mencakup gonore/klamidia menurut pedoman lokal, skrining IMS lain, serta tata pasangan; eskalasi bila muncul PID.',
    panduanResmi: `${PPK} Fluor albus memerlukan pemisahan servisitis dari vaginitis dan PID sebelum memilih regimen.`,
  }),

  buatKasusFktpLab({
    id: 'lab_vulvitis_iritan', nama: 'Vulvitis Iritan', icd10: 'N76.2', kategori: 'infeksi',
    keluhanUtama: 'Kulit kemaluan luar terasa perih dan merah setelah memakai sabun kewanitaan baru.', usia: [15, 65], jenisKelamin: 'P', vital: { td: '116/72', nadi: 78, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Keluhan muncul setelah paparan apa dan apakah ada keputihan?', 'Mulai sehari setelah sabun baru; tidak ada keputihan berbau atau nyeri perut.'],
    pertanyaan: [
      ['q_infeksi', 'rps', 'Ada luka, lepuh, demam, keputihan kental, atau bau amis?', 'Tidak ada.', true],
      ['q_ims', 'sosial', 'Ada pasangan baru atau risiko IMS?', 'Tidak ada pasangan baru.', true],
      ['q_dm', 'rpd', 'Ada diabetes atau antibiotik baru-baru ini?', 'Tidak ada.', false],
    ],
    fisik: [['kulit', 'Eritema ringan simetris pada vulva yang terpapar; tanpa ulkus, vesikel, edema berat, atau sekret vagina.', true]],
    diagnosisBanding: ['N76.2', 'N76.0', 'B37.3'],
    tatalaksana: { obatBenar: [], obatOpsional: ['hidrokortison_krim'], edukasi: ['higiene_genital_lembut', 'tanda_bahaya'] },
    clue: 'Pola temporal setelah iritan dengan eritema eksternal dan tanpa discharge/lesi infeksi mendukung vulvitis iritan. Hentikan pemicu, cuci lembut, jaga kering; kortikosteroid potensi rendah dapat dipakai singkat pada inflamasi ringan.',
    panduanResmi: `${PPK} Penyebab infeksi dan IMS harus disingkirkan sebelum memberi terapi simptomatik.`,
  }),

  buatKasusFktpLab({
    id: 'lab_vaginitis_kandida', nama: 'Vaginitis Kandidiasis', icd10: 'N76.0', kategori: 'infeksi', prevalensi: 'sedang',
    keluhanUtama: 'Keputihan putih kental disertai gatal hebat.', usia: [15, 55], jenisKelamin: 'P', vital: { td: '118/74', nadi: 78, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: ['Bagaimana bentuk cairan, bau, dan rasa gatalnya?', 'Putih menggumpal seperti susu basi, tidak amis, dan gatal sekali.'],
    pertanyaan: [
      ['q_pid', 'rps', 'Ada demam, nyeri perut bawah, atau nyeri saat berhubungan?', 'Tidak ada.', true],
      ['q_risiko', 'rpd', 'Ada diabetes, hamil, antibiotik baru, atau kekambuhan sering?', 'Baru selesai antibiotik; tidak hamil dan tidak berulang.', true],
      ['q_ims', 'sosial', 'Ada pasangan baru atau luka genital?', 'Tidak ada.', false],
    ],
    fisik: [['kulit', 'Vulva eritematosa; discharge putih kental melekat, tanpa bau amis atau nyeri goyang serviks.', true]],
    lab: [['mikroskopis_gram_koh', 'KOH menunjukkan budding yeast dan pseudohifa.', 'abnormal']],
    diagnosisBanding: ['N76.0', 'B37.3', 'N76.2'],
    tatalaksana: { obatBenar: ['klotrimazol_vaginal_100'], edukasi: ['higiene_genital_lembut', 'kepatuhan_obat', 'tanda_bahaya'] },
    clue: 'Pruritus, eritema, discharge putih menggumpal tanpa bau amis, dan pseudohifa mendukung kandidiasis vulvovaginal. Gunakan azol intravaginal; evaluasi diabetes/kehamilan dan rujuk bila berat, rekuren, atau gagal.',
    panduanResmi: `${PPK} Vaginitis ditatalaksana sesuai etiologi, bukan semua keputihan diberi regimen yang sama.`,
  }),

  buatKasusFktpLab({
    id: 'lab_vaginosis_bakterialis', nama: 'Vaginosis Bakterialis', icd10: 'N76.0', kategori: 'infeksi', prevalensi: 'sedang',
    keluhanUtama: 'Keputihan encer abu-abu berbau amis, terutama setelah berhubungan.', usia: [15, 55], jenisKelamin: 'P', vital: { td: '116/72', nadi: 76, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Bagaimana bau, warna, dan apakah terasa gatal?', 'Encer homogen abu-abu dan amis; hampir tidak gatal.'],
    pertanyaan: [
      ['q_pid', 'rps', 'Ada demam, nyeri perut bawah, atau nyeri hubungan?', 'Tidak ada.', true],
      ['q_hamil', 'rps', 'Apakah hamil atau mungkin hamil?', 'Tidak.', true],
      ['q_douching', 'sosial', 'Sering douching atau memakai pembersih vagina?', 'Ya, hampir setiap hari.', false],
    ],
    fisik: [['kulit', 'Discharge tipis homogen abu-abu; vulva tidak meradang dan tidak ada nyeri serviks.', true]],
    lab: [['mikroskopis_gram_koh', 'pH 5,2; whiff test positif dan clue cells ditemukan.', 'abnormal']],
    diagnosisBanding: ['N76.0', 'B37.3', 'N89'],
    tatalaksana: { obatBenar: ['metronidazol_500'], edukasi: ['higiene_genital_lembut', 'kepatuhan_obat', 'tanda_bahaya'] },
    clue: 'Tiga kriteria Amsel atau lebih mendukung vaginosis bakterialis: discharge homogen, pH >4,5, whiff positif, dan clue cells. Metronidazol adalah pilihan; hindari douching dan evaluasi kehamilan/IMS sesuai risiko.',
    panduanResmi: `${PPK} Keputihan tanpa inflamasi nyata perlu dibedakan dari kandidiasis, trikomoniasis, dan servisitis.`,
  }),

  buatKasusFktpLab({
    id: 'lab_salpingitis_pid_ringan', nama: 'Salpingitis/PID Ringan Rawat Jalan', icd10: 'N70', kategori: 'infeksi',
    keluhanUtama: 'Perut bawah nyeri, keputihan berubah, dan sakit saat berhubungan.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '112/70', nadi: 94, rr: 20, suhu: 37.9, spo2: 99 },
    pembuka: ['Sejak kapan nyeri dan keputihan berubah?', 'Empat hari nyeri kedua sisi bawah perut dengan keputihan kuning.'],
    pertanyaan: [
      ['q_berat', 'rps', 'Ada muntah, demam tinggi, pingsan, atau nyeri sangat berat?', 'Tidak; saya masih bisa minum dan berjalan.', true],
      ['q_hamil', 'rps', 'Apakah mungkin hamil?', 'Tes kehamilan negatif.', true],
      ['q_pajanan', 'sosial', 'Ada pasangan baru atau hubungan tanpa kondom?', 'Ada pasangan baru tanpa kondom.', true],
    ],
    fisik: [['abdomen', 'Nyeri tekan suprapubik bilateral tanpa defans atau massa.'], ['kulit', 'Sekret serviks mukopurulen dan nyeri goyang serviks/adneksa ringan.', true]],
    lab: [['tes_kehamilan', 'Negatif.', 'normal'], ['tes_sifilis', 'Nonreaktif.', 'normal']],
    diagnosisBanding: ['N70', 'N73.9', 'O00.9'],
    tatalaksana: { obatBenar: ['ceftriaxone_1g_inj', 'doksisiklin_100', 'metronidazol_500'], edukasi: ['cegah_ims_pasangan', 'kepatuhan_obat', 'tanda_bahaya'], edukasiKritis: ['tanda_bahaya'] },
    clue: 'Nyeri pelvis dengan cervical motion/adnexal tenderness dan faktor risiko IMS mendukung PID. Pasien stabil, tidak hamil, tanpa abses/muntah dapat ditangani rawat jalan dengan regimen kombinasi dan evaluasi 48-72 jam; rujuk bila berat atau tidak membaik.',
    panduanResmi: `${PPK} Salpingitis memerlukan terapi spektrum gonokokus, klamidia, dan anaerob serta tata pasangan.`,
  }),

  buatKasusFktpLab({
    id: 'lab_abortus_spontan_komplit', nama: 'Abortus Spontan Komplit - Stabil', icd10: 'O03.9', kategori: 'kia',
    keluhanUtama: 'Saya hamil delapan minggu, tadi keluar jaringan, sekarang darah dan mulas jauh berkurang.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '112/72', nadi: 84, rr: 18, suhu: 36.8, spo2: 99 },
    pembuka: ['Boleh ceritakan jumlah perdarahan dan jaringan yang keluar?', 'Tadi dua pembalut penuh lalu keluar jaringan utuh; sesudahnya hanya flek dan kram ringan.'],
    pertanyaan: [
      ['q_bahaya', 'rps', 'Masih perdarahan banyak, pusing, pingsan, demam, atau cairan berbau?', 'Tidak ada.', true],
      ['q_ektopik', 'rps', 'Ada nyeri tajam satu sisi atau nyeri bahu?', 'Tidak ada.', true],
      ['q_golongan', 'rpd', 'Tahu golongan darah/Rhesus dan ada penyakit perdarahan?', 'Golongan O rhesus positif; tidak ada gangguan perdarahan.', true],
    ],
    fisik: [['umum', 'Sadar, perfusi baik, tidak pucat berat.'], ['abdomen', 'Nyeri suprapubik minimal tanpa nyeri satu sisi atau defans.'], ['kulit', 'Perdarahan pervaginam minimal; serviks sudah menutup.', true]],
    lab: [['hb', 'Hb 11,4 g/dL.', 'normal'], ['golongan_darah', 'O rhesus positif.', 'normal']],
    diagnosisBanding: ['O03.9', 'O03.4', 'O00.9'],
    tatalaksana: { obatBenar: [], obatOpsional: ['paracetamol_500'], edukasi: ['tanda_bahaya_kehamilan', 'kontrol_rutin', 'gizi_seimbang'], edukasiKritis: ['tanda_bahaya_kehamilan'] },
    clue: 'Riwayat keluarnya jaringan diikuti penurunan perdarahan/nyeri, kondisi stabil, dan serviks menutup mendukung abortus komplit. Tidak ada indikasi memberi uterotonik atau misoprostol otomatis; pastikan follow-up dan rujuk/USG bila diagnosis tidak pasti, perdarahan menetap, infeksi, atau curiga ektopik.',
    panduanResmi: `${PPK} Abortus komplit stabil dapat diobservasi dengan konseling, tetapi ketidakpastian sisa jaringan atau ektopik harus dievaluasi.`,
    catatanRealita: 'USG tidak diasumsikan tersedia di Sukamaju; akses jejaring digunakan bila temuan klinis tidak meyakinkan.',
  }),

  buatKasusFktpLab({
    id: 'lab_ruptur_perineum_derajat_1', nama: 'Ruptur Perineum Derajat 1 dengan Perdarahan', icd10: 'O70.0', kategori: 'kia',
    keluhanUtama: 'Setelah persalinan normal, ada robekan dan darah terus merembes dari perineum.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '110/70', nadi: 88, rr: 18, suhu: 36.8, spo2: 99 },
    pembuka: ['Bagaimana persalinan dan jumlah darah setelah bayi lahir?', 'Bayi lahir normal; rahim keras dan darah tidak banyak, tetapi robekan perineum terus merembes.'],
    pertanyaan: [
      ['q_pph', 'rps', 'Ada pusing, lemas berat, pembalut cepat penuh, atau gumpalan besar?', 'Tidak ada.', true],
      ['q_alergi', 'rpd', 'Ada alergi anestesi lokal atau obat?', 'Tidak ada.', false],
      ['q_riwayat', 'rpd', 'Pernah mengalami robekan persalinan berat atau gangguan perdarahan?', 'Tidak pernah.', false],
    ],
    fisik: [['umum', 'Ibu sadar, uterus berkontraksi baik, perfusi baik.'], ['kulit', 'Robekan mukosa vagina dan kulit perineum dengan rembesan aktif; otot perineum dan sfingter ani utuh, tanpa hematoma.', true]],
    diagnosisBanding: ['O70.0', 'O70.1', 'O72.1'],
    tatalaksana: { obatBenar: ['paracetamol_500'], prosedur: ['jahit_perineum'], edukasi: ['perawatan_perineum', 'tanda_bahaya_kehamilan'] },
    clue: 'Derajat 1 hanya melibatkan mukosa vagina dan kulit perineum. Robekan kecil tanpa perdarahan dapat sembuh tanpa jahitan, tetapi rembesan aktif pada skenario ini memerlukan pencahayaan, anestesi, hemostasis, dan penjahitan oleh tenaga kompeten; keterlibatan otot/sfingter atau hematoma besar mengubah derajat dan disposisi.',
    panduanResmi: `${PPK} Ruptur tingkat 1-2 dapat ditangani tenaga terlatih dengan set dan anestesi yang memadai.`,
  }),

  buatKasusFktpLab({
    id: 'lab_abses_folikel_rambut', nama: 'Abses Folikel Rambut Superfisial', icd10: 'L02.9', kategori: 'kulit',
    keluhanUtama: 'Ada benjolan bernanah dan berdenyut di lipat paha.', usia: [16, 65], vital: { td: '120/76', nadi: 82, rr: 18, suhu: 36.9, spo2: 99 },
    pembuka: ['Benjolan berkembang bagaimana dan apakah demam?', 'Lima hari membesar, sekarang lunak di tengah; tidak demam.'],
    pertanyaan: [
      ['q_berat', 'rps', 'Kemerahan meluas cepat, nyeri hebat, atau banyak benjolan?', 'Tidak; hanya satu benjolan kecil.', true],
      ['q_risiko', 'rpd', 'Ada diabetes, imun lemah, atau abses berulang?', 'Tidak ada.', true],
      ['q_manipulasi', 'sosial', 'Sudah dipencet atau ditusuk?', 'Belum.', false],
    ],
    fisik: [['kulit', 'Nodul 2 cm fluktuatif dengan pustula sentral, eritema terbatas, tanpa selulitis luas.']],
    diagnosisBanding: ['L02.9', 'L73.2', 'L03.9'],
    tatalaksana: { obatBenar: [], obatOpsional: ['paracetamol_500'], prosedur: ['insisi_abses'], obatSalahUmum: [{ id: 'amoxicillin_500', alasan: 'Antibiotik rutin tidak menggantikan drainase pada abses kecil terlokalisasi tanpa selulitis atau faktor risiko.', bahaya: 'nonPrimer' }], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
    clue: 'Abses terlokalisasi yang matang/fluktuatif memerlukan insisi dan drainase dengan teknik steril. Pada skenario ini antibiotik sistemik tidak diperlukan; selulitis, gejala sistemik, lokasi/komorbid berisiko, atau kegagalan drainase mengubah keputusan.',
    panduanResmi: `${PPK} Nilai kebutuhan drainase dan rujuk bila lokasi dalam, luas, atau komplikatif.`,
  }),

  buatKasusFktpLab({
    id: 'lab_mastitis_laktasi', nama: 'Mastitis Laktasi Tanpa Abses', icd10: 'N61', kategori: 'kia', prevalensi: 'sedang',
    keluhanUtama: 'Payudara kanan merah, nyeri, dan saya demam sejak kemarin.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '112/72', nadi: 96, rr: 18, suhu: 38.3, spo2: 99 },
    pembuka: ['Bagaimana nyeri dan proses menyusu sebelum keluhan?', 'Bayi sulit melekat dan payudara sering penuh; lalu satu bagian menjadi merah berbentuk baji.'],
    pertanyaan: [
      ['q_abses', 'rps', 'Ada benjolan lunak berisi cairan atau nanah dari puting?', 'Tidak ada.', true],
      ['q_berat', 'rps', 'Ada pingsan, muntah terus, atau sangat lemah?', 'Tidak.', true],
      ['q_alergi', 'rpd', 'Ada alergi penisilin?', 'Tidak ada.', true],
    ],
    fisik: [['umum', 'Demam, sadar, hidrasi baik.'], ['kulit', 'Eritema berbentuk baji, hangat dan nyeri; tidak ada fluktuasi.'], ['kepala_leher', 'Tidak ada limfangitis luas.', false]],
    diagnosisBanding: ['N61', 'O91.1', 'C50.9'],
    tatalaksana: { obatBenar: ['cefadroxil_500'], obatOpsional: ['paracetamol_500'], prosedur: ['konseling_laktasi'], edukasi: ['dukungan_laktasi', 'kepatuhan_obat', 'tanda_bahaya'] },
    clue: 'Nyeri-demam dengan eritema sektoral pada ibu menyusui mendukung mastitis. Lanjutkan pengosongan payudara/menyusui, koreksi latch, beri antibiotik antistafilokokus yang sesuai; USG/rujuk bila fluktuasi atau tidak membaik 24-48 jam.',
    panduanResmi: `${PPK} Menghentikan menyusui tanpa indikasi memperburuk stasis; abses memerlukan drainase.`,
  }),

  buatKasusFktpLab({
    id: 'lab_puting_lecet', nama: 'Cracked Nipple karena Perlekatan Buruk', icd10: 'O92.13', kategori: 'kia', prevalensi: 'sedang',
    keluhanUtama: 'Puting lecet dan sangat sakit setiap bayi mulai menyusu.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '110/70', nadi: 78, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: ['Kapan nyeri muncul dan bagaimana perlekatan bayi?', 'Nyeri paling hebat saat awal menyusu; mulut bayi hanya menangkap ujung puting.'],
    pertanyaan: [
      ['q_infeksi', 'rps', 'Ada demam, payudara merah berbaji, nanah, atau bayi punya bercak putih mulut?', 'Tidak ada.', true],
      ['q_trauma', 'rps', 'Ada pompa dengan tekanan tinggi atau sabun keras?', 'Saya sering membersihkan puting dengan sabun.', true],
      ['q_bayi', 'rps', 'Bayi tetap BAK dan berat badannya dipantau?', 'Masih BAK cukup.', false],
    ],
    fisik: [['kulit', 'Fisura dangkal pada puting kanan tanpa pus, eritema sektoral, atau massa payudara.']],
    diagnosisBanding: ['O92.13', 'N61', 'B37.89'],
    tatalaksana: { obatBenar: [], prosedur: ['konseling_laktasi'], edukasi: ['dukungan_laktasi', 'tanda_bahaya'] },
    clue: 'Fisura puting paling sering disebabkan perlekatan dangkal. Observasi satu sesi menyusu dan koreksi posisi adalah terapi utama; hindari sabun/iritan, pertahankan menyusui atau perah nyaman, dan evaluasi infeksi bila tidak membaik.',
    panduanResmi: `${PPK} Puting lecet ditangani dengan koreksi teknik menyusui, bukan menghentikan ASI secara otomatis.`,
  }),

  buatKasusFktpLab({
    id: 'lab_puting_tenggelam_laktasi', nama: 'Inverted Nipple dengan Kesulitan Laktasi', icd10: 'O92.03', kategori: 'kia',
    keluhanUtama: 'Puting masuk ke dalam dan bayi baru lahir sulit melekat.', usia: [18, 45], jenisKelamin: 'P', vital: { td: '110/70', nadi: 76, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Apakah puting sudah masuk sejak dulu dan bagaimana minum bayi?', 'Sejak sebelum hamil; bayi baru dua hari, mencoba menyusu tetapi mudah lepas.'],
    pertanyaan: [
      ['q_bahaya_bayi', 'rps', 'Bayi sangat mengantuk, tidak BAK, atau tidak mau minum sama sekali?', 'Tidak; masih mau mencoba dan sudah BAK.', true],
      ['q_baru', 'rps', 'Apakah hanya satu sisi dan baru tertarik masuk belakangan?', 'Kedua sisi sejak lama, bukan perubahan baru.', true],
      ['q_nyeri', 'rps', 'Ada luka, massa, atau darah dari puting?', 'Tidak ada.', false],
    ],
    fisik: [['kulit', 'Puting bilateral terinversi tetapi dapat dieversi sementara; tidak ada massa, inflamasi, atau discharge patologis.']],
    diagnosisBanding: ['O92.03', 'N64.5', 'C50.9'],
    tatalaksana: { obatBenar: [], prosedur: ['konseling_laktasi'], edukasi: ['dukungan_laktasi', 'asi_eksklusif', 'tanda_bahaya'] },
    clue: 'Puting terinversi lama tanpa massa tidak mencegah laktasi bila posisi, sandwich hold, stimulasi sebelum menyusu, dan dukungan intensif diberikan. Hindari tindakan traumatik; pantau transfer ASI dan berat bayi.',
    panduanResmi: `${PPK} Pendampingan menyusui menjadi inti; inversi baru unilateral atau disertai massa perlu evaluasi lebih lanjut.`,
  }),

  buatKasusFktpLab({
    id: 'lab_dm_tipe1_stabil_prb', nama: 'Diabetes Melitus Tipe 1 Stabil', icd10: 'E10', kategori: 'metabolik',
    keluhanUtama: 'Saya diabetes tipe 1 dan datang untuk kontrol insulin; gula belakangan sedikit lebih tinggi.', usia: [15, 45], vital: { td: '116/74', nadi: 80, rr: 18, suhu: 36.6, spo2: 99, gds: 196 },
    pembuka: ['Bagaimana pola insulin, makan, dan gula harian?', 'Saya memakai NPH dan regular sesuai rencana, tetapi beberapa kali melewatkan dosis makan siang.'],
    pertanyaan: [
      ['q_dka', 'rps', 'Ada muntah, nyeri perut, napas dalam, sangat haus, atau penurunan kesadaran?', 'Tidak ada.', true],
      ['q_hipo', 'rps', 'Ada keringat dingin, gemetar, bingung, atau gula rendah?', 'Pernah ringan sebulan lalu dan membaik setelah minum manis.', true],
      ['q_teknik', 'rpd', 'Bagaimana penyimpanan insulin dan rotasi tempat suntik?', 'Disimpan sesuai petunjuk, tetapi saya sering menyuntik di tempat yang sama.', true],
    ],
    fisik: [['umum', 'Status hidrasi baik, tidak ada napas Kussmaul.'], ['kulit', 'Lipohipertrofi ringan pada lokasi suntik abdomen.'], ['ekstremitas', 'Nadi kaki baik, tanpa ulkus.', false]],
    lab: [['gds', '196 mg/dL.', 'tinggi'], ['hba1c', '7,4%.', 'tinggi'], ['urinalisis', 'Keton negatif.', 'normal']],
    diagnosisBanding: ['E10', 'E11', 'E16.2'],
    tatalaksana: { obatBenar: ['insulin_nph', 'insulin_regular'], obatSalahUmum: [{ id: 'metformin_500', alasan: 'Metformin tidak menggantikan kebutuhan insulin absolut pada DM tipe 1.', bahaya: 'nonPrimer' }], edukasi: ['keamanan_insulin', 'diet_dm', 'kontrol_rutin'], edukasiKritis: ['keamanan_insulin'] },
    clue: 'DM tipe 1 memerlukan insulin berkelanjutan; penghentian insulin berisiko ketoasidosis. Pada pasien stabil, telaah pola glukosa, teknik, lokasi suntik, hipoglikemia, dan akses insulin; perubahan dosis harus berbasis data dan rencana individual.',
    panduanResmi: `${PPK} Kasus ini adalah kontrol jejaring/rujuk balik stabil, bukan inisiasi insulin tanpa supervisi pada diagnosis baru.`,
    catatanRealita: 'Insulin membutuhkan rantai dingin, edukator, alat monitoring, dan kesinambungan stok; vignette menyatakan semua tersedia melalui jejaring PRB.',
  }),

  buatKasusFktpLab({
    id: 'lab_malnutrisi_energi_protein_sedang', nama: 'Malnutrisi Energi-Protein Sedang Tanpa Komplikasi', icd10: 'E44', kategori: 'metabolik', prevalensi: 'sedang',
    keluhanUtama: 'Anak saya tampak makin kurus dan beratnya tidak naik tiga bulan.', keluhanUtamaOlehPendamping: true, usia: [2, 5], vital: { nadi: 96, rr: 22, suhu: 36.7, spo2: 99 },
    pembuka: ['Bagaimana pertumbuhan dan pola makan anak?', 'Berat turun dari garis pertumbuhan, makan hanya dua kali sedikit, terutama nasi dan kerupuk.'],
    pertanyaan: [
      ['q_bahaya', 'rps', 'Ada edema kedua kaki, sangat lemas, tidak mau makan, muntah semua, atau demam?', 'Tidak ada; anak masih aktif dan mau makan.', true],
      ['q_penyakit', 'rpd', 'Ada diare lama, batuk lama, TB, kelainan jantung, atau infeksi berulang?', 'Tidak ada.', true],
      ['q_akses', 'sosial', 'Apakah keluarga kesulitan memperoleh sumber protein?', 'Penghasilan tidak tetap dan lauk hewani jarang tersedia.', true],
    ],
    fisik: [['umum', 'Anak kurus tetapi aktif; BB/TB z-score -2,4 SD dan LILA 12,0 cm, tanpa edema atau tanda dehidrasi.'], ['abdomen', 'Tidak ada hepatomegali atau distensi patologis.', false]],
    diagnosisBanding: ['E44', 'E43', 'R62.7'],
    tatalaksana: { obatBenar: [], edukasi: ['rehabilitasi_gizi', 'gizi_seimbang', 'kontrol_rutin'], edukasiKritis: ['rehabilitasi_gizi'] },
    clue: 'Growth faltering dengan wasting sedang, nafsu makan masih baik, tanpa edema/komplikasi dapat direhabilitasi rawat jalan: evaluasi penyebab, susun makanan padat energi-protein yang realistis, dukungan sosial, dan pantau berat terjadwal.',
    panduanResmi: `${PPK} Tanda bahaya, edema, gizi buruk berat, penyakit penyerta, atau gagal naik berat memerlukan rujukan/layanan gizi intensif.`,
  }),

  buatKasusFktpLab({
    id: 'lab_defisiensi_vitamin_b_kompleks', nama: 'Defisiensi Vitamin B Kompleks Ringan', icd10: 'E50-E56', kategori: 'metabolik',
    keluhanUtama: 'Sudut bibir sering pecah dan lidah terasa perih sejak pola makan saya sangat terbatas.', usia: [18, 70], vital: { td: '118/74', nadi: 80, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Apa perubahan pola makan dan keluhan lain?', 'Tiga bulan hanya banyak makan nasi instan; bibir pecah, lidah merah, dan mudah lelah.'],
    pertanyaan: [
      ['q_sistemik', 'rps', 'Ada kebas berat, sulit berjalan, diare lama, atau berat turun cepat?', 'Tidak ada.', true],
      ['q_alkohol', 'sosial', 'Ada konsumsi alkohol atau diet sangat restriktif?', 'Tidak alkohol; diet terbatas karena ekonomi.', true],
      ['q_obat', 'rpd', 'Ada obat atau penyakit yang mengganggu penyerapan?', 'Tidak ada.', false],
    ],
    fisik: [['tht_mulut', 'Angular cheilitis dan glositis ringan tanpa kandidiasis.'], ['neurologis', 'Refleks dan sensibilitas normal.', false]],
    diagnosisBanding: ['E50-E56', 'D50', 'B37.9'],
    tatalaksana: { obatBenar: ['vitamin_b_kompleks'], edukasi: ['gizi_seimbang', 'kontrol_rutin'] },
    clue: 'Temuan mukokutan dengan diet sangat tidak beragam mendukung defisiensi mikronutrien, tetapi tanda ini tidak spesifik. Koreksi diet adalah inti; suplementasi terarah boleh diberikan sambil mencari anemia, malabsorpsi, alkohol, atau penyakit sistemik bila menetap.',
    panduanResmi: `${PPK} Defisiensi vitamin adalah diagnosis klinis-kontekstual; hindari menjadikan multivitamin pengganti evaluasi dan pangan beragam.`,
  }),

  buatKasusFktpLab({
    id: 'lab_defisiensi_mineral_zinc', nama: 'Defisiensi Mineral - Dugaan Kekurangan Zinc', icd10: 'E58-E61', kategori: 'metabolik',
    keluhanUtama: 'Luka kecil lama sembuh, rambut mudah rontok, dan selera makan turun.', usia: [12, 50], vital: { td: '116/72', nadi: 78, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Bagaimana pola makan dan sejak kapan keluhan muncul?', 'Berbulan-bulan jarang makan protein hewani; keluhan perlahan dan tidak ada demam.'],
    pertanyaan: [
      ['q_malabsorbsi', 'rpd', 'Ada diare kronik, operasi usus, atau penyakit hati/ginjal?', 'Tidak ada.', true],
      ['q_berat', 'rps', 'Ada penurunan berat badan besar, infeksi berat, atau luka luas?', 'Tidak ada.', true],
      ['q_suplemen', 'rpd', 'Sudah memakai suplemen dosis tinggi?', 'Belum.', false],
    ],
    fisik: [['kulit', 'Dermatitis periorifisial ringan dan rambut menipis difus; tanpa infeksi luka.'], ['umum', 'Status gizi sedikit kurang.', true]],
    diagnosisBanding: ['E58-E61', 'E50-E56', 'L65.9'],
    tatalaksana: { obatBenar: [], edukasi: ['gizi_seimbang', 'kontrol_rutin'] },
    clue: 'Defisiensi zinc tidak boleh ditegakkan dari satu gejala; kombinasi diet rendah sumber zinc, dermatitis periorifisial, alopecia, dan penyembuhan lambat meningkatkan kecurigaan. Suplementasi harus terbatas dan disertai perbaikan diet serta evaluasi bila tidak respons.',
    panduanResmi: `${PPK} Defisiensi mineral adalah payung diagnosis; penyebab dan mineral spesifik perlu ditentukan sejauh fasilitas memungkinkan.`,
    catatanRealita: 'Zinc dispersibel Fornas dibatasi untuk diare anak dan tidak dijadikan jawaban wajib pada dugaan defisiensi dewasa. Konfirmasi dan suplementasi spesifik dikoordinasikan melalui jejaring bila diperlukan.',
  }),

  buatKasusFktpLab({
    id: 'lab_anemia_defisiensi_besi_nonhamil', nama: 'Anemia Defisiensi Besi pada Dewasa', icd10: 'D50', kategori: 'metabolik', prevalensi: 'sedang',
    keluhanUtama: 'Saya cepat lelah, berdebar saat naik tangga, dan tampak pucat.', usia: [18, 60], vital: { td: '108/68', nadi: 92, rr: 18, suhu: 36.6, spo2: 99 },
    pembuka: ['Sejak kapan lelah dan ada sumber kehilangan darah?', 'Tiga bulan; haid sangat banyak tujuh hari setiap bulan.'],
    pertanyaan: [
      ['q_bahaya', 'rps', 'Ada nyeri dada, pingsan, sesak saat diam, atau perdarahan aktif?', 'Tidak ada.', true],
      ['q_darah', 'rps', 'Ada BAB hitam, darah di tinja, muntah darah, atau cacingan?', 'Tidak ada.', true],
      ['q_diet', 'sosial', 'Bagaimana asupan daging, telur, dan sayur?', 'Jarang makan daging.', false],
    ],
    fisik: [['umum', 'Konjungtiva pucat, tidak ikterik.'], ['jantung', 'Takikardia ringan, tanpa murmur patologis.'], ['abdomen', 'Tidak ada hepatosplenomegali.', false]],
    lab: [['darah_rutin', 'Hb 9,6 g/dL; MCV 69 fL; MCH rendah; trombosit 470.000/uL.', 'rendah'], ['ferritin_serum', 'Ferritin 7 ng/mL.', 'rendah']],
    diagnosisBanding: ['D50', 'D56.3', 'D63.8'],
    tatalaksana: { obatBenar: ['tablet_fe'], edukasi: ['diet_zat_besi', 'kepatuhan_obat', 'kontrol_rutin'] },
    clue: 'Anemia mikrositik dengan ferritin rendah menegakkan defisiensi besi. Beri besi oral, jelaskan efek samping dan durasi sampai cadangan pulih, tetapi tetap cari dan tangani sumber kehilangan darah; rujuk bila berat, tidak respons, atau sumber mencurigakan.',
    panduanResmi: `${PPK} Respons Hb harus dipantau dan diagnosis tidak berhenti pada pemberian tablet Fe.`,
  }),

  buatKasusFktpLab({
    id: 'lab_limfadenitis_servikal_akut', nama: 'Limfadenitis Servikal Akut Bakterial', icd10: 'I88', kategori: 'infeksi',
    keluhanUtama: 'Ada benjolan nyeri di leher setelah sakit gigi dan demam ringan.', usia: [8, 12], vital: { td: '104/66', nadi: 92, rr: 20, suhu: 38.0, spo2: 99 },
    pembuka: ['Benjolan muncul kapan dan adakah sumber infeksi di sekitar kepala-leher?', 'Tiga hari setelah gigi geraham sakit; benjolan satu sisi dan nyeri.'],
    pertanyaan: [
      ['q_tb', 'rps', 'Benjolan sudah lama, tidak nyeri, disertai batuk lama, keringat malam, atau berat turun?', 'Tidak; baru tiga hari dan nyeri.', true],
      ['q_bahaya', 'rps', 'Sulit menelan/napas, leher kaku, atau demam tinggi?', 'Tidak ada.', true],
      ['q_kucing', 'sosial', 'Ada cakaran kucing atau luka kulit?', 'Tidak ada.', false],
    ],
    fisik: [['kepala_leher', 'KGB submandibula kanan 2 cm, nyeri, mobile, hangat; tidak fluktuatif. Gigi molar karies.'], ['tht_mulut', 'Tidak ada abses peritonsil atau obstruksi jalan napas.', true]],
    diagnosisBanding: ['I88', 'A18.2', 'C77.0'],
    tatalaksana: { obatBenar: ['cefadroxil_sirup_125'], obatOpsional: ['paracetamol_sirup'], edukasi: ['kepatuhan_obat', 'kontrol_rutin', 'tanda_bahaya'] },
    clue: 'KGB akut unilateral nyeri dengan fokus infeksi lokal mendukung limfadenitis bakterial. Tata sumber infeksi dan antibiotik yang sesuai; evaluasi ulang. Kronik, keras/fiksasi, supraklavikula, gejala TB/keganasan, fluktuasi, atau gagal respons memerlukan pemeriksaan lanjut.',
    panduanResmi: `${PPK} Limfadenitis harus dibedakan dari TB kelenjar, keganasan, dan abses.`,
  }),

  buatKasusFktpLab({
    id: 'lab_leptospirosis_tanpa_komplikasi', nama: 'Leptospirosis Tanpa Komplikasi', icd10: 'A27.9', kategori: 'infeksi',
    keluhanUtama: 'Demam mendadak, sakit kepala, dan betis sangat nyeri setelah membersihkan rumah kebanjiran.', usia: [15, 65], vital: { td: '112/70', nadi: 98, rr: 20, suhu: 38.7, spo2: 98 },
    pembuka: ['Kapan demam mulai dan bagaimana pajanan banjirnya?', 'Tiga hari setelah berjalan di air banjir dengan luka kecil di kaki.'],
    pertanyaan: [
      ['q_berat', 'rps', 'Ada kuning, urine berkurang, sesak, batuk darah, bingung, atau perdarahan?', 'Tidak ada; urine masih normal.', true],
      ['q_gejala', 'rps', 'Ada nyeri betis, mata merah tanpa kotoran, mual, atau sakit kepala?', 'Nyeri betis berat, mata merah, mual ringan.', true],
      ['q_obat', 'rpd', 'Ada alergi tetrasiklin atau obat rutin yang perlu diperiksa interaksinya?', 'Tidak ada.', true],
      ['q_hamil', 'rpd', 'Apakah sedang hamil atau mungkin hamil?', 'Tidak.', true, 'P'],
    ],
    fisik: [['umum', 'Demam, sadar, hidrasi cukup; tidak ikterik.'], ['mata', 'Conjunctival suffusion bilateral tanpa sekret.'], ['ekstremitas', 'Nyeri tekan otot gastroknemius.', true]],
    lab: [['darah_rutin', 'Leukosit 12.800/uL; trombosit 165.000/uL.', 'tinggi'], ['fungsi_ginjal', 'Kreatinin 1,0 mg/dL.', 'normal'], ['sgot_sgpt', 'AST 48 U/L, ALT 42 U/L.', 'tinggi']],
    diagnosisBanding: ['A27.9', 'A90', 'B54'],
    tatalaksana: { obatBenar: ['doksisiklin_100', 'paracetamol_500'], edukasi: ['cegah_leptospirosis', 'kepatuhan_obat', 'tanda_bahaya'], edukasiKritis: ['tanda_bahaya'] },
    clue: 'Demam akut, nyeri otot betis, kemerahan konjungtiva tanpa sekret, dan pajanan air banjir mendukung leptospirosis. Kasus ringan dapat diberi antibiotik dini dan dipantau ketat; ikterus, gangguan ginjal akut, perdarahan paru, rangsang meningeal, hipotensi, atau sesak memerlukan rujukan.',
    panduanResmi: `${PPK} Jangan menunggu komplikasi Weil sebelum mengenali pajanan epidemiologis dan memulai terapi yang tepat.`,
  }),

  buatKasusFktpLab({
    id: 'lab_anafilaksis_makanan', nama: 'Reaksi Anafilaktik setelah Makanan', icd10: 'T78.2', kategori: 'gawat',
    keluhanUtama: 'Setelah makan udang, bibir bengkak, suara serak, kulit bentol, dan napas berbunyi.', usia: [18, 70], vital: { td: '82/52', nadi: 126, rr: 30, suhu: 36.7, spo2: 91 }, harusDirujuk: true, spesialisRujukan: 'penyakit_dalam',
    pembuka: ['Berapa menit setelah makanan gejala muncul?', 'Sekitar sepuluh menit; bentol menyebar lalu tenggorok terasa sempit.'],
    pertanyaan: [
      ['q_sistem', 'rps', 'Ada muntah, nyeri perut, pusing, atau hampir pingsan?', 'Mual dan sangat pusing.', true],
      ['q_riwayat', 'rpd', 'Pernah reaksi serupa atau membawa epinefrin?', 'Pernah gatal ringan, belum pernah separah ini.', true],
      ['q_obat', 'rpd', 'Menggunakan beta-blocker atau punya penyakit jantung?', 'Tidak.', false],
    ],
    fisik: [['umum', 'Gelisah, perfusi buruk, urtikaria generalisata dan angioedema bibir.'], ['toraks_paru', 'Wheezing difus dan suara serak.'], ['jantung', 'Takikardia, hipotensi.', true]],
    diagnosisBanding: ['T78.2', 'J45.901', 'F41.0'],
    tatalaksana: { obatBenar: [], prosedur: ['adrenalin_im_anafilaksis', 'oksigen', 'akses_iv_resusitasi'], edukasi: ['rencana_anafilaksis', 'tanda_bahaya'], edukasiKritis: ['rencana_anafilaksis'] },
    stabilisasiWajib: ['adrenalin_im_anafilaksis', 'oksigen', 'akses_iv_resusitasi'],
    clue: 'Onset menit dengan keterlibatan kulit plus jalan napas/napas dan hipotensi adalah anafilaksis. Epinefrin IM paha adalah terapi pertama dan boleh diulang; oksigen, posisi/cairan sesuai kondisi, monitoring, dan transfer. Antihistamin atau steroid tidak boleh menunda epinefrin.',
    panduanResmi: `${PPK} Semua anafilaksis harus distabilkan segera dan dipantau karena risiko reaksi bifasik.`,
  }),
]

export const LAB_BATCH_2_ARCHETYPE_SPECS: Record<string, { conceptId: string; credits: string[] }> = {
  lab_kejang_demam_sederhana: { conceptId: 'concept:febrile_seizure', credits: ['fktp144:febrile_seizure'] },
  lab_tetanus_generalisata_awal: { conceptId: 'concept:tetanus', credits: ['fktp144:tetanus'] },
  lab_hiv_tanpa_komplikasi: { conceptId: 'concept:hiv_uncomplicated', credits: ['fktp144:hiv_uncomplicated'] },
  lab_gangguan_somatoform: { conceptId: 'concept:somatoform', credits: ['fktp144:somatoform'] },
  lab_benda_asing_konjungtiva: { conceptId: 'concept:foreign_body_conjunctiva', credits: ['fktp144:foreign_body_conjunctiva'] },
  lab_perdarahan_subkonjungtiva: { conceptId: 'concept:subconjunctival_hemorrhage', credits: ['fktp144:subconjunctival_hemorrhage'] },
  lab_mata_kering: { conceptId: 'concept:dry_eye', credits: ['fktp144:dry_eye'] },
  lab_blefaritis_anterior: { conceptId: 'concept:blepharitis', credits: ['fktp144:blepharitis'] },
  lab_trikiasis: { conceptId: 'concept:trichiasis', credits: ['fktp144:trichiasis'] },
  lab_episkleritis_ringan: { conceptId: 'concept:episcleritis', credits: ['fktp144:episcleritis'] },
  lab_hipermetropia: { conceptId: 'concept:hypermetropia', credits: ['fktp144:hypermetropia'] },
  lab_miopia_ringan: { conceptId: 'concept:myopia_mild', credits: ['fktp144:myopia_mild'] },
  lab_astigmatisme_ringan: { conceptId: 'concept:astigmatism_mild', credits: ['fktp144:astigmatism_mild'] },
  lab_presbiopia: { conceptId: 'concept:presbyopia', credits: ['fktp144:presbyopia'] },
  lab_buta_senja_defisiensi_vitamin_a: { conceptId: 'concept:night_blindness', credits: ['fktp144:night_blindness'] },
  lab_infeksi_umbilikus_neonatus: { conceptId: 'concept:umbilical_infection', credits: ['fktp144:umbilical_infection'] },
  lab_gonore_uretritis_pria: { conceptId: 'concept:gonorrhea', credits: ['fktp144:gonorrhea'] },
  lab_pielonefritis_tanpa_komplikasi: { conceptId: 'concept:pyelonephritis', credits: ['fktp144:pyelonephritis'] },
  lab_fimosis_patologis_ringan: { conceptId: 'concept:phimosis', credits: ['fktp144:phimosis'] },
  lab_parafimosis_reduksibel: { conceptId: 'concept:paraphimosis', credits: ['fktp144:paraphimosis'] },
  lab_sindrom_duh_genital_servisitis: { conceptId: 'concept:nongonococcal_genital_discharge', credits: ['fktp144:genital_discharge'] },
  lab_vulvitis_iritan: { conceptId: 'concept:vulvitis', credits: ['fktp144:vulvitis'] },
  lab_vaginitis_kandida: { conceptId: 'concept:vaginitis', credits: ['fktp144:vaginitis'] },
  lab_vaginosis_bakterialis: { conceptId: 'concept:bacterial_vaginosis', credits: ['fktp144:bacterial_vaginosis'] },
  lab_salpingitis_pid_ringan: { conceptId: 'concept:salpingitis', credits: ['fktp144:salpingitis'] },
  lab_abortus_spontan_komplit: { conceptId: 'concept:complete_abortion', credits: ['fktp144:complete_abortion'] },
  lab_ruptur_perineum_derajat_1: { conceptId: 'concept:perineal_rupture_12', credits: ['fktp144:perineal_rupture_12'] },
  lab_abses_folikel_rambut: { conceptId: 'concept:abses_folikel_rambut', credits: ['fktp144:abses_folikel_rambut'] },
  lab_mastitis_laktasi: { conceptId: 'concept:mastitis_lactation', credits: ['fktp144:mastitis_lactation'] },
  lab_puting_lecet: { conceptId: 'concept:cracked_nipple', credits: ['fktp144:cracked_nipple'] },
  lab_puting_tenggelam_laktasi: { conceptId: 'concept:inverted_nipple', credits: ['fktp144:inverted_nipple'] },
  lab_dm_tipe1_stabil_prb: { conceptId: 'concept:dm_type1', credits: ['fktp144:dm_type1'] },
  lab_malnutrisi_energi_protein_sedang: { conceptId: 'concept:pem', credits: ['fktp144:pem'] },
  lab_defisiensi_vitamin_b_kompleks: { conceptId: 'concept:vitamin_deficiency', credits: ['fktp144:vitamin_deficiency'] },
  lab_defisiensi_mineral_zinc: { conceptId: 'concept:mineral_deficiency', credits: ['fktp144:mineral_deficiency'] },
  lab_anemia_defisiensi_besi_nonhamil: { conceptId: 'concept:anemia_deficiency', credits: ['fktp144:anemia_deficiency'] },
  lab_limfadenitis_servikal_akut: { conceptId: 'concept:lymphadenitis', credits: ['fktp144:lymphadenitis'] },
  lab_leptospirosis_tanpa_komplikasi: { conceptId: 'concept:leptospirosis', credits: ['fktp144:leptospirosis'] },
  lab_anafilaksis_makanan: { conceptId: 'concept:anaphylaxis', credits: ['fktp144:anaphylaxis'] },
}
