/**
 * M13 Batch 4 — Mata, THT, dan Saraf (tier rujuk).
 *
 * Delapan kasus yang semuanya WAJIB dirujuk, tetapi bukan "klik rujuk lalu
 * selesai": yang dinilai adalah mengenali tanda bahaya, mengerjakan yang MEMANG
 * kewenangan FKTP sebelum merujuk (visus, antibiotik dosis-1, akses vena,
 * puasa), menahan diri dari yang di luar lingkup, dan memilih spesialis yang
 * benar.
 */

import type { KasusKlinis, Persona } from '../types'
import type { LabArchetypeSpec } from './batch1'
import { buatKasusLab, type LabQuestionSpec } from './labCaseFactory'

const PPK_FLOOR = 'PPK Dokter FKTP KMK 1186/2022 menjadi floor; terapi disesuaikan dengan pedoman yang lebih baru bila relevan.'

/**
 * `LabQuestionSpec` (labCaseFactory) belum mengenal field `variasi`: batch 1-3
 * ditulis tanpa suara persona sama sekali, lalu diretrofit lewat lapisan
 * `lab/enrichment.ts`. Kontrak sebenarnya sudah mendukungnya —
 * `PertanyaanAnamnesis.variasi` — dan `buatKasusLab` menyalin tiap pertanyaan
 * apa adanya (`...item`), sehingga variasi yang ditulis di sini tetap utuh
 * sampai ke kasus jadi. Batch ini ditulis kaya sejak awal, jadi variasinya
 * ditaruh langsung di kasus dasar; helper di bawah hanya melebarkan pengecekan
 * tipe di titik penulisan, tanpa mengubah perilaku apa pun saat dijalankan.
 *
 * Aman terhadap lapisan pengayaan: `applyLabEnrichment` sengaja me-merge
 * `{ ...q.variasi, ...e.variasi[id] }`, sehingga persona yang ditulis di sini
 * menjadi dasar yang bisa ditambah — bukan ditimpa diam-diam.
 */
const tanya = (q: LabQuestionSpec & { variasi?: Partial<Record<Persona, string>> }): LabQuestionSpec => q

export const LAB_BATCH_4_MTS_CASES: KasusKlinis[] = [
  buatKasusLab({
    id: 'lab_katarak_matur',
    nama: 'Katarak Matur pada Lansia',
    icd10: 'H25.2',
    skdi: '2',
    kategori: 'mata',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'tinggi',
    spesialisRujukan: 'mata',
    keluhanUtama: 'Penglihatan saya makin lama makin berkabut putih, Dok, sekarang sudah tidak bisa membaca dan tidak kenal wajah orang.',
    demografi: { usiaMin: 60, usiaMax: 80 },
    vital: { td: '138/82', nadi: 76, rr: 18, suhu: 36.6, spo2: 98 },
    pembuka: {
      tanya: 'Boleh diceritakan bagaimana penglihatan Bapak/Ibu berubah selama ini?',
      jawab: 'Pelan-pelan, Dok, sudah bertahun-tahun. Awalnya cuma seperti berkabut tipis, sekarang seperti melihat lewat kaca yang diembuni terus.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_perlahan',
        kategori: 'rps',
        tanya: 'Apakah kaburnya datang mendadak dalam hitungan jam, atau memberat pelan-pelan?',
        jawab: 'Pelan sekali. Tidak ada satu hari pun yang tiba-tiba gelap; memburuknya seperti tidak terasa.',
        esensial: true,
        oldcarts: ['onset', 'durasi'],
        variasi: {
          lansia: 'Pelan-pelan, Nak... pelan sekali. Tidak pernah mendadak. Dari dulu memang begitu, makin lama makin buram, makin lama makin buram.',
          polos: 'Ndak mendadak, Dok. Ngalon-alon wae. Wis suwe banget.',
        },
      }),
      tanya({
        id: 'q_silau',
        kategori: 'rps',
        tanya: 'Apakah mata terasa silau, terutama siang hari atau kena lampu kendaraan malam hari?',
        jawab: 'Sangat silau. Kalau siang saya lebih suka duduk di dalam rumah, dan malam hari kena lampu motor rasanya menyilaukan sekali sampai tidak kelihatan apa-apa.',
        esensial: true,
        oldcarts: ['agravasi', 'waktu'],
        variasi: {
          lansia: 'Silau, Nak, silau sekali... Kalau siang saya di dalam saja. Kena lampu motor malam itu rasanya seperti disorot, tidak kelihatan apa-apa.',
        },
      }),
      tanya({
        id: 'q_aktivitas',
        kategori: 'rps',
        tanya: 'Sekarang masih bisa membaca, mengenali wajah, atau berjalan sendiri di luar rumah?',
        jawab: 'Sudah tidak bisa membaca sama sekali. Kalau orang datang saya baru tahu siapa setelah dia bersuara. Jalan ke luar rumah harus dipegangi.',
        esensial: true,
        oldcarts: ['keparahan'],
        variasi: {
          lansia: 'Ndak bisa, Nak... baca sudah lama tidak bisa. Orang datang saya tidak tahu siapa, baru tahu kalau sudah bersuara. Jalan pun harus dituntun.',
        },
      }),
      {
        id: 'q_nyeri_merah',
        kategori: 'rps',
        tanya: 'Matanya ada nyeri, merah, berair, atau sakit kepala hebat disertai mual?',
        jawab: 'Tidak ada sama sekali. Matanya tenang, tidak sakit, tidak merah. Hanya tidak bisa melihat saja.',
        esensial: true,
      },
      tanya({
        id: 'q_second_sight',
        kategori: 'rps',
        tanya: 'Beberapa waktu lalu, apakah sempat ada masa penglihatan dekat justru terasa membaik tanpa kacamata?',
        jawab: 'Betul, Dok, aneh sekali. Kira-kira dua tahun lalu saya tiba-tiba bisa membaca lagi tanpa kacamata baca, saya kira sembuh sendiri. Tapi tidak lama, habis itu makin berkabut sampai sekarang.',
        oldcarts: ['waktu'],
        variasi: {
          lansia: 'Iya, Nak, itu yang saya heran... dulu saya sempat bisa baca lagi tanpa kacamata. Saya pikir sudah sembuh. Ternyata cuma sebentar, habis itu tambah putih.',
        },
      }),
      {
        id: 'q_dm_ht',
        kategori: 'rpd',
        tanya: 'Ada kencing manis, darah tinggi, atau penyakit lain yang rutin diobati?',
        jawab: 'Darah tinggi ada, minum obat teratur dari Puskesmas. Kencing manis tidak ada, terakhir diperiksa gulanya bagus.',
        esensial: true,
      },
      tanya({
        id: 'q_tetes_warung',
        kategori: 'rpd',
        tanya: 'Selama ini sudah pakai obat tetes mata apa saja, dari mana belinya?',
        jawab: 'Sudah bertahun-tahun saya pakai tetes mata yang dibilang bisa menghilangkan katarak, beli sendiri di apotek. Tetangga juga menyarankan yang sama. Tidak ada perubahan, Dok.',
        esensial: true,
        variasi: {
          lansia: 'Banyak, Nak... tetes mata macam-macam sudah saya coba. Katanya bisa menghilangkan kataraknya. Sudah bertahun-tahun, ya begini saja, tidak ada bedanya.',
        },
      }),
      {
        id: 'q_trauma_operasi',
        kategori: 'rpd',
        tanya: 'Matanya pernah kena benturan, terkena benda, atau pernah dioperasi?',
        jawab: 'Tidak pernah. Belum pernah dioperasi apa pun.',
      },
      {
        id: 'q_distraktor_asap',
        kategori: 'sosial',
        tanya: 'Apakah Bapak/Ibu sering terkena asap dapur atau debu di rumah?',
        jawab: 'Ya masak pakai kayu memang masih, Dok, tapi sudah dari muda begitu. Anak-anak yang lain tidak apa-apa matanya.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_tv',
        kategori: 'sosial',
        tanya: 'Apakah kebiasaan menonton televisi terlalu dekat atau membaca di tempat remang membuat ini terjadi?',
        jawab: 'Kata orang-orang begitu, Dok, makanya sekarang saya tidak berani nonton dekat-dekat. Tapi ya tetap saja tidak membaik.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'mata', temuan: 'Manik mata tampak putih keabuan pada kedua mata, kanan lebih padat; refleks fundus hilang sehingga dasar mata tidak dapat dinilai. Mata tenang, tidak merah, bola mata teraba lunak normal.', relevan: true },
      { region: 'umum', temuan: 'Lansia mandiri sebagian, harus dituntun saat berjalan ke ruang periksa; tidak tampak sakit.', relevan: true },
      { region: 'neurologis', temuan: 'Tidak ada kelumpuhan, bicara jelas, lapang pandang kasar sulit dinilai karena penglihatan yang sangat turun.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada benjolan, tidak ada nyeri tekan.', relevan: false },
      { region: 'jantung', temuan: 'Bunyi jantung normal, irama teratur, tanpa bising.', relevan: false },
    ],
    lab: [
      { id: 'gds', hasil: '104 mg/dL.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['H25.2', 'H40.2', 'H36'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'air_mata_buatan', alasan: 'Air mata buatan hanya melembapkan permukaan mata dan tidak mengubah lensa yang sudah keruh sama sekali. Bahayanya bukan pada obatnya, melainkan pada rasa "sudah diobati" yang membuat pasien dan dokter menunda operasi selama bertahun-tahun.', bahaya: 'nonPrimer' },
        { id: 'kloramfenikol_tetes_mata', alasan: 'Mata tenang tanpa merah, kotoran, atau nyeri: tidak ada infeksi yang diobati. Antibiotik tetes di sini murni salah sasaran dan menambah tekanan resistansi tanpa manfaat.', bahaya: 'nonPrimer' },
        { id: 'timolol_tetes_mata', alasan: 'Penurun tekanan bola mata diberikan "untuk berjaga-jaga" padahal tidak ada bukti tekanan bola mata meninggi. Timolol adalah penyekat beta yang terserap sistemik dan dapat memperlambat denyut jantung serta memicu sesak pada lansia.', bahaya: 'kontraindikasi' },
      ],
      prosedur: ['uji_visus_refraksi'],
      edukasi: ['persiapan_rujukan_operatif', 'perlindungan_mata', 'tanda_bahaya_mata', 'kontrol_rutin'],
      edukasiKritis: ['persiapan_rujukan_operatif'],
    },
    clue: 'Kekeruhan lensa yang memutih perlahan bertahun-tahun, silau berat, hilangnya refleks fundus, dan manik mata putih adalah katarak matur. Tidak ada obat, tetes mata, maupun suplemen mana pun yang terbukti melarutkan atau membalik kekeruhan lensa: satu-satunya terapi definitif adalah operasi pengangkatan lensa dengan penanaman lensa tanam, dan WHO menempatkan katarak sebagai penyebab kebutaan yang paling dapat dipulihkan. Tugas FKTP adalah memastikan dugaannya benar lewat uji visus sederhana serta menyingkirkan mata merah/nyeri, lalu merujuk ke spesialis mata.',
    panduanResmi: `${PPK_FLOOR} Katarak adalah kompetensi SKDI 2 bagi dokter FKTP: kemampuan yang dituntut adalah menegakkan dugaan diagnosis dan merujuk, bukan memberi terapi. PPK menetapkan pemeriksaan tajam penglihatan dan penilaian segmen depan mata sebagai pekerjaan FKTP, dengan rujukan ke spesialis mata untuk penentuan waktu dan teknik operasi. Tidak ada satu pun sediaan farmakologis yang tercantum sebagai terapi katarak.`,
    catatanRealita: 'Permainan mengandaikan rujukan mata berjalan mulus. Di lapangan antrean operasi katarak bisa berbulan-bulan, dan sebagian pasien lansia menolak dioperasi karena takut atau tidak ada pengantar, sehingga baksos operasi katarak dan penjadwalan bersama keluarga sering menjadi jalan yang lebih realistis daripada surat rujukan tunggal.',
    mutiaraEbm: 'Dua temuan di kasus ini justru menyesatkan. Pertama, mata yang tenang, tidak merah, dan tidak nyeri terasa seperti keadaan yang tidak mendesak, padahal pasien sudah nyaris buta. Kedua, "second sight": pengerasan inti lensa membuat mata bergeser menjadi lebih minus, sehingga selama beberapa bulan pasien tiba-tiba bisa membaca lagi tanpa kacamata dan mengira penyakitnya sembuh sendiri; masa itu justru penanda katarak sedang matang, bukan membaik.',
    konsekuensi: {
      narasi: 'Pasien dipulangkan dengan tetes mata dan janji kontrol tanpa rujukan. Kekeruhan berlanjut sampai lensa membengkak dan menyumbat aliran cairan mata, atau pasien terjatuh di rumah karena tidak melihat.',
      kembaliHariMin: 14,
      kembaliHariMax: 30,
      kondisiKembali: 'Kembali dituntun keluarga dengan mata kanan kini merah, nyeri hebat, dan sakit kepala disertai muntah (glaukoma akibat lensa yang membengkak), atau dengan memar dan patah tulang panggul setelah jatuh di kamar mandi.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Katarak, SKDI 2); WHO World Report on Vision',
    },
  }),

  buatKasusLab({
    id: 'lab_ablasio_retina',
    nama: 'Ablasio Retina — Tirai Hitam Tanpa Nyeri',
    icd10: 'H33.2',
    skdi: '2',
    kategori: 'mata',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'mata',
    keluhanUtama: 'Mata kanan saya mendadak seperti ada tirai hitam naik dari bawah menutupi pandangan, Dok, tapi sama sekali tidak sakit.',
    demografi: { usiaMin: 45, usiaMax: 70 },
    vital: { td: '134/80', nadi: 78, rr: 18, suhu: 36.7, spo2: 98 },
    pembuka: {
      tanya: 'Coba ceritakan persis apa yang Bapak/Ibu lihat dan sejak kapan?',
      jawab: 'Kemarin sore tiba-tiba ada kilatan seperti petir kecil di pinggir mata kanan, lalu muncul bintik-bintik hitam banyak sekali melayang. Tadi pagi bagian bawah pandangan seperti ditutup kain hitam, dan sekarang kainnya sudah naik sampai setengah.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_kilatan_floaters',
        kategori: 'rps',
        tanya: 'Kilatan cahaya dan bintik melayangnya muncul lebih dulu atau bersamaan dengan tirainya?',
        jawab: 'Kilatan dan bintik-bintiknya duluan, kemarin sore. Tirai hitamnya baru tadi pagi. Bintiknya banyak sekali, seperti hujan jelaga.',
        esensial: true,
        oldcarts: ['onset', 'waktu', 'karakter'],
        variasi: {
          cemas: 'Duluan yang kilatan, Dok, kemarin sore! Seperti ada petir kecil di pojok mata, saya kira mau pingsan. Terus muncul bintik hitam banyak sekali seperti jelaga beterbangan, saya sampai tidak bisa tidur. Ini kenapa, Dok? Saya mau buta ya?',
          terpelajar: 'Urutannya jelas, Dok: kemarin sekitar pukul lima sore muncul kilatan di sisi luar mata kanan, lalu bintik-bintik hitam yang melayang mengikuti gerakan mata. Tirai gelapnya baru tadi pagi sekitar pukul enam.',
        },
      }),
      {
        id: 'q_arah_tirai',
        kategori: 'rps',
        tanya: 'Tirainya menutup dari arah mana, dan apakah masih bertambah?',
        jawab: 'Dari bawah naik ke atas. Kemarin baru sedikit di pinggir bawah, sekarang sudah sampai tengah. Bagian tengah pandangan masih bisa lihat, tapi makin sempit.',
        esensial: true,
        oldcarts: ['lokasi', 'keparahan'],
      },
      {
        id: 'q_nyeri_merah',
        kategori: 'rps',
        tanya: 'Matanya nyeri, merah, atau ada sakit kepala dan mual?',
        jawab: 'Sama sekali tidak. Itu yang bikin saya sempat menunda ke sini, karena tidak sakit sedikit pun dan matanya kelihatan biasa saja.',
        esensial: true,
      },
      tanya({
        id: 'q_miopia',
        kategori: 'rpd',
        tanya: 'Kacamatanya minus berapa, dan sejak kapan pakai kacamata?',
        jawab: 'Minus tinggi, Dok, minus delapan. Sudah pakai kacamata sejak SMP, tebal sekali kacanya.',
        esensial: true,
        variasi: {
          terpelajar: 'Minus delapan pada mata kanan dan minus tujuh setengah di kiri, Dok. Sudah sejak SMP saya berkacamata, dan tiap beberapa tahun bertambah.',
        },
      }),
      {
        id: 'q_trauma',
        kategori: 'rpd',
        tanya: 'Belakangan ini matanya pernah terbentur, atau ada kegiatan mengangkat beban berat?',
        jawab: 'Tidak ada benturan. Cuma tiga hari lalu saya bantu angkat lemari di rumah anak saya.',
        esensial: true,
      },
      {
        id: 'q_operasi_mata',
        kategori: 'rpd',
        tanya: 'Mata yang ini atau sebelahnya pernah dioperasi, misalnya operasi katarak?',
        jawab: 'Belum pernah dioperasi sama sekali, Dok.',
      },
      {
        id: 'q_mata_sebelah',
        kategori: 'rps',
        tanya: 'Mata kiri bagaimana, ada kilatan atau bintik melayang juga?',
        jawab: 'Mata kiri masih baik. Tidak ada kilatan, tidak ada bintik.',
      },
      {
        id: 'q_dm',
        kategori: 'rpd',
        tanya: 'Ada kencing manis atau darah tinggi?',
        jawab: 'Tidak ada. Terakhir cek gula dan tensi di Posbindu semuanya bagus.',
      },
      {
        id: 'q_distraktor_gadget',
        kategori: 'sosial',
        tanya: 'Apakah akhir-akhir ini terlalu lama menatap layar ponsel atau komputer?',
        jawab: 'Lumayan sering, Dok, apalagi kalau malam. Apa gara-gara itu ya? Anak saya juga bilang begitu.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_darah_tinggi_keluarga',
        kategori: 'rpk',
        tanya: 'Di keluarga ada yang punya darah tinggi atau kolesterol?',
        jawab: 'Bapak saya dulu darah tinggi. Tapi saya sendiri tensinya selalu normal.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'mata', temuan: 'Mata kanan putih dan tenang: tidak ada kemerahan, tidak ada kotoran, bola mata teraba lunak normal. Lapang pandang uji konfrontasi kanan hilang pada separuh bawah. Refleks pupil langsung kanan tampak lebih lambat dibanding kiri. Mata kiri dalam batas normal.', relevan: true },
      { region: 'umum', temuan: 'Tampak tenang dan tidak kesakitan sama sekali; kooperatif, berjalan sendiri.', relevan: true },
      { region: 'neurologis', temuan: 'Bicara jelas, kekuatan keempat anggota gerak penuh, tidak ada wajah mencong; lapang pandang mata kiri utuh sehingga kelainan terbatas pada satu mata saja.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada nyeri tekan di sekitar mata dan pelipis; tidak teraba benjolan.', relevan: false },
      { region: 'jantung', temuan: 'Irama teratur, tidak ada bising.', relevan: false },
    ],
    lab: [
      { id: 'tonometri', hasil: 'Tekanan bola mata kanan 14 mmHg, kiri 15 mmHg.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['H33.2', 'G45.9', 'H36'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'timolol_tetes_mata', alasan: 'Diberikan karena refleks "mata mendadak buram berarti glaukoma", padahal tekanan bola mata terukur normal dan matanya tidak nyeri. Selain tidak menyentuh retina yang terlepas, penyekat beta ini terserap sistemik dan setiap menit yang dihabiskan untuk mencoba tetes adalah menit yang hilang bagi makula.', bahaya: 'kontraindikasi' },
        { id: 'kloramfenikol_tetes_mata', alasan: 'Tidak ada tanda infeksi apa pun: mata putih, tenang, tanpa kotoran. Meresepkannya menciptakan ilusi bahwa keluhan sudah ditangani dan menunda rujukan yang hitungannya jam.', bahaya: 'nonPrimer' },
        { id: 'air_mata_buatan', alasan: 'Keluhan bintik melayang sering disalahartikan sebagai "mata kering". Pelumas permukaan mata tidak berpengaruh sedikit pun pada robekan retina di dalam bola mata.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['uji_visus_refraksi'],
      edukasi: ['tanda_bahaya_mata', 'perlindungan_mata', 'kontrol_rutin'],
      edukasiKritis: ['tanda_bahaya_mata'],
    },
    clue: 'Kilatan cahaya dan hujan bintik melayang yang mendadak, diikuti tirai gelap yang merambat naik pada mata yang putih dan tidak nyeri, adalah ablasio retina sampai terbukti sebaliknya — apalagi pada miopia tinggi. Ini kegawatan mata yang ditentukan oleh jam, bukan hari: selama tirai belum mencapai titik pusat penglihatan, makula masih menempel (macula-on) dan operasi cepat masih dapat menyelamatkan tajam penglihatan sentral; begitu makula ikut terlepas (macula-off), pemulihan penglihatan sentral jauh lebih buruk berapa pun bagusnya operasi berikutnya. Yang benar di FKTP: catat tajam penglihatan dan lapang pandang, jangan berikan tetes apa pun, dan rujuk ke spesialis mata hari itu juga.',
    panduanResmi: `${PPK_FLOOR} Ablasio retina adalah kompetensi SKDI 2: dokter FKTP dituntut mengenali dan merujuk, bukan mengobati. PPK menempatkan penurunan penglihatan mendadak pada mata tenang sebagai kriteria rujukan segera ke spesialis mata. Perhatikan bahwa kotak "mata merah" dan "mata tenang" adalah dua alur yang berbeda: alur mata tenang yang mendadak justru berisi diagnosis-diagnosis yang paling mendesak.`,
    catatanRealita: 'Skenario mengandaikan rujukan mata bisa berangkat hari itu juga. Di banyak daerah, spesialis mata dengan kemampuan bedah vitreoretina hanya ada di ibu kota provinsi dan jadwalnya tidak setiap hari, sehingga menelepon lebih dulu untuk memastikan operator tersedia lebih menentukan hasil daripada surat rujukan itu sendiri.',
    mutiaraEbm: 'Semua temuan yang menenangkan di kasus ini adalah jebakan: mata putih bersih, tidak ada nyeri sama sekali, dan tekanan bola mata terukur normal. Ajaran "mata merah berarti gawat, mata tenang berarti aman" justru terbalik untuk kelompok penyakit ini — kebutaan permanen pada ablasio retina, sumbatan pembuluh darah retina, dan neuritis optik semuanya datang pada mata yang tampak paling tidak berdosa. Kilatan cahaya dan bintik melayang yang bertambah mendadak adalah tanda robekan retina, dan wajib dianggap gawat meskipun tajam penglihatan sentral masih terasa baik.',
    konsekuensi: {
      narasi: 'Pasien diberi tetes mata dan diminta kontrol minggu depan karena "matanya tenang dan tidak sakit". Robekan retina meluas dan cairan merembes sampai ke titik pusat penglihatan.',
      kembaliHariMin: 3,
      kembaliHariMax: 7,
      kondisiKembali: 'Kembali dengan mata kanan yang kini hanya bisa membedakan gelap-terang. Retina sudah terlepas total termasuk makula; operasi masih dikerjakan untuk menempelkan retina, tetapi penglihatan sentral mata kanan tidak pernah kembali.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Ablasio Retina, SKDI 2); AAO Preferred Practice Pattern — Posterior Vitreous Detachment, Retinal Breaks, and Lattice Degeneration',
    },
  }),

  buatKasusLab({
    id: 'lab_retinopati_diabetik_proliferatif',
    nama: 'Retinopati Diabetik Proliferatif',
    icd10: 'H36',
    skdi: '2',
    kategori: 'mata',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'mata',
    keluhanUtama: 'Penglihatan saya makin kabur beberapa bulan ini, Dok, kadang ada bercak merah kehitaman yang melayang-layang.',
    demografi: { usiaMin: 45, usiaMax: 65 },
    vital: { td: '148/88', nadi: 84, rr: 18, suhu: 36.6, spo2: 98, gds: 268 },
    pembuka: {
      tanya: 'Sejak kapan penglihatannya kabur, dan bercak melayang itu seperti apa?',
      jawab: 'Kaburnya sudah sekitar enam bulan, makin lama makin. Bercaknya seperti benang merah atau asap yang melayang, muncul beberapa kali lalu hilang sendiri setelah beberapa hari. Kemarin muncul lagi lebih banyak.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_lama_dm',
        kategori: 'rpd',
        tanya: 'Sudah berapa lama kena kencing manis, dan obatnya apa saja?',
        jawab: 'Sudah dua belas tahun, Dok. Minum obat gula dari Puskesmas, tapi jujur saja sering putus. Kalau badan enak saya berhenti dulu, nanti kalau sudah lemas baru minum lagi.',
        esensial: true,
        oldcarts: ['durasi'],
        variasi: {
          terpelajar: 'Terdiagnosis sejak tahun 2014, Dok, jadi kurang lebih dua belas tahun. Obatnya metformin dua kali sehari dari Puskesmas. Terus terang kepatuhan saya buruk: sering saya hentikan sendiri kalau merasa badan sudah enak.',
          polos: 'Wis suwe, Dok, sepuluh tahunan lebih. Obate diminum nek kelingan wae. Nek awak kepenak yo ora tak minum.',
        },
      }),
      {
        id: 'q_kontrol_gula',
        kategori: 'rpd',
        tanya: 'Terakhir periksa gula darah kapan dan berapa hasilnya?',
        jawab: 'Sudah lama, Dok, mungkin setahun lalu. Waktu itu tinggi, dua ratus sekian. Setelah itu saya tidak pernah kontrol lagi.',
        esensial: true,
      },
      tanya({
        id: 'q_skrining_mata',
        kategori: 'rpd',
        tanya: 'Selama dua belas tahun kena kencing manis, apakah pernah sekali pun matanya diperiksa oleh dokter mata?',
        jawab: 'Tidak pernah sama sekali, Dok. Tidak ada yang pernah menyuruh. Saya kira kalau mata tidak sakit ya tidak perlu diperiksa.',
        esensial: true,
        variasi: {
          terpelajar: 'Belum pernah, Dok, tidak sekali pun. Dan sejujurnya tidak ada yang pernah menganjurkan. Saya baru tahu sekarang bahwa kencing manis bisa merusak mata.',
          skeptis: 'Tidak pernah. Buat apa? Mata saya waktu itu tidak ada keluhan apa-apa. Kalau tiap tahun disuruh periksa mata padahal tidak sakit, itu namanya cari-cari kerjaan.',
        },
      }),
      {
        id: 'q_bercak_melayang',
        kategori: 'rps',
        tanya: 'Bercak melayangnya muncul mendadak lalu hilang sendiri, atau menetap?',
        jawab: 'Mendadak muncul, Dok, biasanya pagi begitu bangun tidur. Lalu memudar sendiri dalam beberapa hari. Sudah tiga kali begini dalam tiga bulan.',
        esensial: true,
        oldcarts: ['onset', 'waktu', 'karakter'],
      },
      {
        id: 'q_tirai_gelap',
        kategori: 'rps',
        tanya: 'Pernah ada tirai gelap yang menutup, atau kilatan cahaya?',
        jawab: 'Tidak ada tirai. Kilatan juga tidak. Cuma kabur merata dan bercak melayang itu.',
        esensial: true,
      },
      {
        id: 'q_nyeri_merah',
        kategori: 'rps',
        tanya: 'Matanya nyeri atau merah?',
        jawab: 'Tidak, Dok. Tidak pernah sakit, tidak pernah merah.',
      },
      {
        id: 'q_ginjal_kaki',
        kategori: 'rpd',
        tanya: 'Ada kaki kesemutan, luka yang sulit sembuh, atau bengkak di kaki?',
        jawab: 'Kaki sering kesemutan dan kebas, Dok, terutama malam. Bengkak tidak ada. Luka juga belum pernah.',
        esensial: true,
      },
      {
        id: 'q_merokok',
        kategori: 'sosial',
        tanya: 'Masih merokok?',
        jawab: 'Masih, Dok, sekitar sepuluh batang sehari. Sudah dari muda.',
      },
      {
        id: 'q_distraktor_wortel',
        kategori: 'sosial',
        tanya: 'Apakah pola makannya kurang sayur dan wortel?',
        jawab: 'Ya, jarang makan sayur, Dok. Istri saya juga bilang ini gara-gara kurang wortel. Perlu saya minum vitamin mata tidak?',
        distraktor: true,
      },
      {
        id: 'q_distraktor_kacamata',
        kategori: 'rps',
        tanya: 'Apakah sudah coba ganti kacamata baru untuk mengatasi kaburnya?',
        jawab: 'Sudah, Dok, dua kali ganti dalam setahun ini. Di optik dibilang minusnya berubah-ubah terus. Tapi diganti pun tetap kabur.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'mata', temuan: 'Kedua mata putih dan tenang, tidak nyeri. Lensa masih cukup jernih. Manik mata bereaksi normal terhadap cahaya. Dasar mata tidak dapat dinilai memadai dengan alat yang tersedia; tampak keruh ringan pada mata kanan seolah ada kabut merah di depan dasar mata.', relevan: true },
      { region: 'ekstremitas', temuan: 'Rasa raba dan getar menurun simetris pada kedua telapak kaki; denyut nadi kaki masih teraba; tidak ada luka.', relevan: true },
      { region: 'umum', temuan: 'Bentuk badan gemuk sedang, tampak tidak sakit berat.', relevan: true },
      { region: 'jantung', temuan: 'Irama teratur, tidak ada bising, tidak ada bengkak di tungkai.', relevan: false },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru.', relevan: false },
    ],
    lab: [
      { id: 'hba1c', hasil: '10,4%.', flag: 'tinggi', relevan: true },
      { id: 'gdp', hasil: '212 mg/dL.', flag: 'tinggi', relevan: true },
      { id: 'darah_rutin', hasil: 'Hb 13,4 g/dL, leukosit 7.800/uL, trombosit 268.000/uL.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['H36', 'H25.2', 'H33.2'],
    tatalaksana: {
      obatBenar: ['metformin_500'],
      obatOpsional: ['simvastatin_20'],
      obatSalahUmum: [
        { id: 'vitamin_b_kompleks', alasan: 'Diberikan sebagai "obat saraf mata" atau vitamin penguat penglihatan. Tidak ada bukti bahwa vitamin B mengubah perjalanan retinopati diabetik, dan pemberiannya memperkuat keyakinan pasien bahwa matanya sudah ditangani sehingga rujukan terasa tidak perlu.', bahaya: 'nonPrimer' },
        { id: 'kloramfenikol_tetes_mata', alasan: 'Mata putih dan tenang tanpa tanda infeksi sedikit pun. Antibiotik tetes di sini murni salah sasaran.', bahaya: 'nonPrimer' },
        { id: 'asam_traneksamat_500_inj', alasan: 'Refleks "ada perdarahan maka beri antiperdarahan" tidak berlaku di sini: perdarahan berasal dari pembuluh darah baru yang rapuh akibat retina yang kekurangan oksigen, dan hanya laser atau anti-VEGF yang mengatasi sumbernya. Pada penyandang diabetes lama dengan pembuluh darah yang sudah sakit, obat ini menambah risiko sumbatan pembuluh tanpa satu pun manfaat yang terbukti.', bahaya: 'kontraindikasi' },
      ],
      prosedur: ['uji_visus_refraksi'],
      edukasi: ['kontrol_rutin', 'diet_dm', 'kepatuhan_obat', 'perlindungan_mata', 'berhenti_merokok', 'perawatan_kaki_diabetik'],
      edukasiKritis: ['kontrol_rutin'],
    },
    clue: 'Penyandang diabetes tipe 2 dua belas tahun dengan kendali gula buruk (HbA1c 10,4%), penglihatan yang memburuk perlahan, dan perdarahan badan kaca berulang yang muncul-menghilang: ini retinopati diabetik proliferatif sampai dibuktikan sebaliknya. Pembuluh darah baru yang rapuh tumbuh karena retina kekurangan oksigen, dan pembuluh itulah yang berdarah. Terapinya di luar FKTP: laser panretina atau suntikan anti-VEGF ke dalam bola mata, dan itu menyelamatkan penglihatan hanya bila dikerjakan sebelum terjadi perdarahan masif atau tarikan yang melepaskan retina. Pekerjaan FKTP jelas dan tetap penting: kendalikan gula darah, tekanan darah, dan lemak darah, lanjutkan serta rapikan metformin yang selama ini putus-nyambung, hentikan rokok, lalu rujuk ke spesialis mata. Poin yang paling sering dilewatkan: skrining dasar mata seharusnya sudah dikerjakan sejak hari diagnosis diabetes tipe 2 ditegakkan dan diulang setiap tahun (ADA Standards of Care; diabetes tipe 2 sudah berjalan bertahun-tahun sebelum terdiagnosis, sehingga retinopati bisa sudah ada di kunjungan pertama) — pasien ini kehilangan dua belas kesempatan.',
    panduanResmi: `${PPK_FLOOR} Retinopati diabetik adalah kompetensi SKDI 2: dokter FKTP mengenali, mengendalikan faktor risiko metabolik, dan merujuk. PPK dan Konsensus PERKENI menempatkan pemeriksaan mata oleh spesialis mata sebagai bagian baku perawatan diabetes, bukan tindakan tambahan yang menunggu keluhan. Pengendalian gula, tekanan darah, dan lemak darah tetap kewenangan penuh FKTP dan tidak berhenti ketika pasien dirujuk. Catatan penting: perbaikan kadar gula harus bertahap — penurunan HbA1c yang terlalu cepat pada retinopati lanjut yang belum dilaser justru dapat memperburuk retinopati untuk sementara (fenomena early worsening pada DCCT), sehingga penurunan gula dan penjadwalan laser sebaiknya berjalan seiring, bukan berlomba.`,
    catatanRealita: 'Permainan mengandaikan HbA1c tersedia sekali klik. Di banyak Puskesmas HbA1c belum rutin dan pemantauan bersandar pada gula darah puasa serta dua jam setelah makan, sementara funduskopi dengan pelebaran manik mata praktis tidak dikerjakan karena keterbatasan alat dan jam praktik.',
    mutiaraEbm: 'Yang paling menyesatkan pada retinopati diabetik adalah keluhannya sendiri — atau ketiadaannya. Retinopati proliferatif bisa sudah luas sementara tajam penglihatan sentral masih terasa hampir normal, karena makula belum tersentuh; pasien merasa baik-baik saja tepat pada tahap ketika laser paling berguna. Perdarahan badan kaca yang muncul lalu memudar sendiri dalam beberapa hari juga menipu: mata "sembuh sendiri" itu justru mengumumkan adanya pembuluh darah baru yang rapuh, dan perdarahan berikutnya bisa tidak memudar lagi. Satu lagi yang sering luput: minus yang berubah-ubah sehingga kacamata berkali-kali diganti sering kali bukan urusan optik, melainkan tanda kadar gula yang naik-turun.',
    konsekuensi: {
      narasi: 'Pasien pulang dengan vitamin mata dan tanpa rujukan, karena "matanya tidak merah dan tidak sakit". Gula tetap tidak terkendali dan pembuluh darah baru terus tumbuh serta menarik retina.',
      kembaliHariMin: 30,
      kembaliHariMax: 90,
      kondisiKembali: 'Kembali dengan mata kanan mendadak gelap total sejak bangun tidur akibat perdarahan badan kaca masif; pada mata kiri retina sudah tertarik dan mulai terlepas. Laser tidak lagi bisa dikerjakan karena dasar mata tertutup darah, dan yang tersisa hanyalah operasi vitrektomi dengan harapan penglihatan yang jauh lebih kecil.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Retinopati Diabetik, SKDI 2); Konsensus PERKENI DM Tipe 2; ADA Standards of Care — Retinopathy Screening',
    },
  }),

  buatKasusLab({
    id: 'lab_otitis_media_supuratif_kronik_komplikata',
    nama: 'OMSK Tipe Bahaya — Curiga Kolesteatoma',
    icd10: 'H66.3',
    skdi: '3A',
    kategori: 'tht',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'tht',
    keluhanUtama: 'Telinga kiri saya sudah bertahun-tahun keluar cairan bau busuk, Dok, tapi belakangan pendengarannya turun drastis dan kepala saya sering nyeri.',
    demografi: { usiaMin: 15, usiaMax: 40 },
    vital: { td: '118/76', nadi: 88, rr: 18, suhu: 37.4, spo2: 98 },
    pembuka: {
      tanya: 'Sudah berapa lama telinganya berair, dan apa yang berubah belakangan ini?',
      jawab: 'Sudah dari kecil, Dok, hilang timbul bertahun-tahun. Baunya busuk sekali sampai orang di sebelah saya bisa mencium. Yang berubah tiga bulan ini: pendengarannya turun cepat sekali, dan kepala saya sering nyeri di sisi kiri.',
      oldcarts: ['onset', 'durasi', 'karakter', 'penyerta'],
    },
    pertanyaan: [
      tanya({
        id: 'q_sifat_cairan',
        kategori: 'rps',
        tanya: 'Cairannya seperti apa, dan apakah baunya menetap meski sudah dibersihkan?',
        jawab: 'Kental, agak kekuningan, sedikit tapi terus-menerus. Baunya busuk sekali dan tidak hilang walau saya bersihkan tiap hari. Kadang ada gumpalan putih seperti remah.',
        esensial: true,
        oldcarts: ['karakter'],
        variasi: {
          polos: 'Kentel, Dok, kuning-kuning dikit-dikit tapi terus. Mambune banger tenan. Kadang ada putih-putih kayak remahan kerak gitu.',
        },
      }),
      tanya({
        id: 'q_pendengaran',
        kategori: 'rps',
        tanya: 'Penurunan pendengarannya seberapa cepat, dan sudah sampai tingkat apa?',
        jawab: 'Dulu masih bisa dengar walau berkurang. Tiga bulan ini turun cepat sekali. Sekarang kalau orang bicara di sisi kiri saya hampir tidak dengar, harus menoleh.',
        esensial: true,
        oldcarts: ['onset', 'keparahan'],
        variasi: {
          terpelajar: 'Dulu penurunannya bertahap dan masih bisa saya siasati, Dok. Tapi tiga bulan terakhir jelas berbeda: cepat sekali. Sekarang kalau orang bicara di sisi kiri, saya praktis tidak menangkap apa pun, harus menoleh supaya telinga kanan yang menerima.',
          skeptis: 'Ya menurun. Tapi orang tua saya juga pendengarannya berkurang, itu wajar kan? Memang tiga bulan ini agak cepat. Bukan berarti harus dioperasi, kan?',
        },
      }),
      {
        id: 'q_nyeri_kepala',
        kategori: 'rps',
        tanya: 'Nyeri kepalanya seperti apa, dan apakah berbeda dari sakit kepala biasa?',
        jawab: 'Di sisi kiri, di belakang telinga sampai ke atas. Bukan seperti sakit kepala biasa, ini terasa dalam dan makin sering. Kadang bangun tidur sudah nyeri.',
        esensial: true,
        oldcarts: ['lokasi', 'karakter', 'waktu'],
      },
      {
        id: 'q_pusing_berputar',
        kategori: 'rps',
        tanya: 'Pernah pusing berputar, terutama saat telinganya dibersihkan atau kemasukan air?',
        jawab: 'Iya, Dok! Sebulan ini beberapa kali. Kalau saya korek atau kena air, ruangan terasa berputar beberapa detik lalu berhenti.',
        esensial: true,
      },
      {
        id: 'q_wajah',
        kategori: 'rps',
        tanya: 'Ada wajah yang terasa mencong, sulit menutup mata, atau air minum bocor dari sudut bibir?',
        jawab: 'Belum ada. Wajah saya masih normal.',
        esensial: true,
      },
      {
        id: 'q_demam_kaku',
        kategori: 'rps',
        tanya: 'Ada demam tinggi, leher kaku, mual muntah menyembur, atau kejang?',
        jawab: 'Tidak ada. Badan cuma agak hangat kadang-kadang.',
        esensial: true,
      },
      tanya({
        id: 'q_pengobatan',
        kategori: 'rpd',
        tanya: 'Selama bertahun-tahun ini sudah diobati apa saja?',
        jawab: 'Bolak-balik ke Puskesmas dan klinik, Dok. Tiap kali dikasih antibiotik minum, kering seminggu dua minggu, lalu kambuh lagi. Sudah entah berapa kali. Belum pernah dirujuk.',
        esensial: false,
        variasi: {
          terpelajar: 'Sudah berkali-kali, Dok, saya sampai hafal polanya: diberi antibiotik minum, telinga kering sekitar satu-dua minggu, lalu berair lagi. Begitu terus sejak SD. Tidak pernah ada yang menyarankan saya ke dokter spesialis.',
          polos: 'Wis kerep, Dok. Saben mrene dikeki antibiotik ngombe, garing seminggu rong minggu, mengko kumat maneh. Ngono terus. Ora tau dikongkon nang dokter spesialis.',
        },
      }),
      {
        id: 'q_tetes_telinga',
        kategori: 'rpd',
        tanya: 'Pernah pakai obat tetes telinga? Yang mana?',
        jawab: 'Pernah beberapa kali beli sendiri di apotek, katanya tetes telinga antibiotik. Dipakai beberapa hari saja lalu berhenti.',
      },
      {
        id: 'q_distraktor_cotton_bud',
        kategori: 'sosial',
        tanya: 'Apakah sering membersihkan telinga dengan cotton bud atau korek kuping?',
        jawab: 'Sering, Dok, hampir tiap hari. Habis mandi pasti saya korek biar kering. Apa gara-gara itu ya?',
        distraktor: true,
      },
      {
        id: 'q_distraktor_alergi',
        kategori: 'rpd',
        tanya: 'Apakah punya alergi debu atau sering bersin-bersin di pagi hari?',
        jawab: 'Kalau pagi memang suka bersin-bersin, Dok, apalagi kalau nyapu. Sudah dari dulu begitu.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Liang telinga kiri berisi sekret kental kekuningan berbau sangat busuk. Setelah dibersihkan tampak lubang pada gendang telinga di bagian ATAS-PINGGIR (bukan di tengah), dengan jaringan granulasi rapuh di tepinya dan gumpalan putih seperti serpihan kulit di dalam rongga. Telinga kanan tenang, gendang telinga utuh.', relevan: true },
      { region: 'kepala_leher', temuan: 'Daerah belakang telinga kiri tidak bengkak, tidak merah, dan tidak nyeri ditekan; lekukan di belakang daun telinga masih terlihat jelas dan daun telinga tidak terdorong.', relevan: true },
      { region: 'neurologis', temuan: 'Saraf wajah kiri masih berfungsi penuh: dahi berkerut simetris, mata dapat menutup rapat, sudut bibir simetris. Tidak ada kaku kuduk. Kesadaran penuh, tidak ada kelumpuhan anggota gerak.', relevan: true },
      { region: 'umum', temuan: 'Tampak sehat, gizi cukup, tidak tampak sakit berat.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Hb 13,8 g/dL, leukosit 9.200/uL, trombosit 288.000/uL.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['H66.3', 'H60.3', 'H70.0'],
    tatalaksana: {
      obatBenar: ['asam_asetat_tetes_telinga_2'],
      obatSalahUmum: [
        { id: 'gentamisin_tetes_mata', alasan: 'Tetes aminoglikosida diteteskan ke telinga sebagai penggunaan di luar label karena tetes telinga khusus tidak tersedia. Pada gendang telinga yang BERLUBANG, obat masuk langsung ke rongga telinga tengah dan meresap ke telinga dalam: aminoglikosida bersifat racun bagi rumah siput dan organ keseimbangan, sehingga dapat menimbulkan tuli saraf menetap dan pusing berputar permanen yang tidak dapat diperbaiki oleh operasi apa pun. Pada telinga berlubang, gunakan tetes yang aman seperti asam asetat atau kuinolon topikal, bukan aminoglikosida.', bahaya: 'kontraindikasi' },
        { id: 'amoxicillin_500', alasan: 'Inilah kesalahan yang sudah diulang bertahun-tahun pada pasien ini: antibiotik minum membuat telinga kering satu-dua minggu sehingga terasa sembuh, lalu kambuh lagi. Kolesteatoma adalah kantong kulit yang tumbuh dan menggerogoti tulang — tidak ada antibiotik yang dapat melarutkannya. Setiap siklus antibiotik tanpa rujukan hanya membeli waktu bagi kantong itu untuk merusak lebih dalam.', bahaya: 'nonPrimer' },
        { id: 'karbogliserin_tetes', alasan: 'Diberikan karena tampak "ada kotoran menumpuk di liang telinga". Obat ini adalah pelunak kotoran telinga, bukan terapi infeksi, dan yang menumpuk di sini bukan serumen melainkan serpihan kolesteatoma. Selain salah sasaran, obat ini justru membasahi telinga yang seharusnya dijaga tetap kering.', bahaya: 'nonPrimer' },
      ],
      tindakanSalahUmum: [
        { id: 'ekstraksi_serumen', alasan: 'Membersihkan telinga dengan penyemprotan air (irigasi) adalah tindakan baku untuk kotoran telinga pada gendang yang UTUH. Di sini gendang telinga berlubang: air bertekanan masuk langsung ke telinga tengah, menyiram rongga yang sudah terinfeksi, memicu pusing berputar hebat karena telinga dalam terangsang dingin, dan berisiko mendorong kuman lebih dalam. Pada telinga berlubang, pembersihan dikerjakan kering (diusap/disedot), bukan disemprot.', bahaya: 'berbahaya' },
      ],
      edukasi: ['jaga_telinga_kering', 'tanda_bahaya', 'kontrol_rutin'],
      edukasiKritis: ['jaga_telinga_kering'],
    },
    clue: 'Telinga berair bertahun-tahun yang berbau sangat busuk, lubang gendang telinga di bagian atas-pinggir (bukan di tengah), jaringan granulasi, serpihan putih seperti kulit, ditambah penurunan pendengaran yang cepat, nyeri kepala, dan pusing berputar saat telinga tersentuh — ini OMSK tipe BAHAYA dengan dugaan kolesteatoma, dan pusing berputar itu menandakan kantongnya sudah mengikis tulang sampai membuka telinga dalam. Kolesteatoma adalah kantong kulit yang terus tumbuh dan melarutkan tulang di sekitarnya; ia tidak pernah sembuh dengan obat dan terapinya adalah pembedahan (mastoidektomi). Bedakan tegas dari OMSK tipe aman (lubang di tengah, sekret encer tak berbau, tanpa granulasi) yang boleh dikelola lebih lama di FKTP. Yang benar di FKTP: bersihkan secara kering, berikan asam asetat tetes yang aman bagi telinga berlubang, jaga telinga tetap kering, JANGAN diirigasi, JANGAN memberi tetes aminoglikosida, dan rujuk ke spesialis THT.',
    panduanResmi: `${PPK_FLOOR} OMSK adalah kompetensi SKDI 3A: dokter FKTP menegakkan diagnosis, memberi terapi awal, dan merujuk. PPK memisahkan OMSK tipe aman dari tipe bahaya, dan menetapkan rujukan ke spesialis THT untuk tipe bahaya, untuk tipe aman yang tidak membaik dengan terapi konservatif, serta segera bila muncul tanda komplikasi — pusing berputar, wajah mencong, nyeri kepala hebat, demam tinggi, atau penurunan kesadaran. Ketiga temuan pada pasien ini (lubang di bagian atas-pinggir, granulasi, dan pusing berputar) masing-masing sudah cukup menjadi alasan rujukan.`,
    catatanRealita: 'Permainan mengandaikan tetes asam asetat tersedia dan rujukan THT lancar. Kenyataannya banyak Puskesmas hanya memiliki tetes telinga berisi aminoglikosida di lemari obat — justru sediaan yang paling berbahaya pada gendang yang berlubang — sehingga tidak memberi tetes apa pun sambil menjaga telinga kering lebih baik daripada memberi yang ototoksik.',
    mutiaraEbm: 'OMSK tipe bahaya justru sering TIDAK nyeri dan tidak demam, dan telinganya hanya berair sedikit — sehingga terasa jauh lebih ringan daripada otitis media akut yang nyerinya menjerit-jerit tetapi jinak. Banyaknya cairan tidak menunjukkan bahayanya; letak lubang, ada tidaknya granulasi, dan bau busuk itulah yang menentukan. Perangkap kedua: telinga yang mengering setelah antibiotik terasa seperti perbaikan, padahal kolesteatoma tetap tumbuh diam-diam di balik telinga yang kering — jeda kering itulah yang selama bertahun-tahun menunda rujukan pasien ini. Perangkap ketiga: pusing berputar yang cuma beberapa detik saat telinga dikorek mudah dianggap keluhan sepele, padahal itu tanda tulang telinga dalam sudah bolong.',
    konsekuensi: {
      narasi: 'Pasien kembali diberi antibiotik minum satu siklus lagi tanpa rujukan. Telinga mengering sebentar, lalu kolesteatoma melanjutkan pekerjaannya mengikis tulang ke arah saraf wajah dan rongga otak.',
      kembaliHariMin: 30,
      kembaliHariMax: 60,
      kondisiKembali: 'Kembali dengan wajah kiri mencong, mata kiri tidak bisa menutup rapat, dan nyeri kepala hebat disertai demam tinggi serta kesadaran yang mulai menurun — kolesteatoma sudah melumpuhkan saraf wajah dan menembus ke dalam rongga tengkorak. Dirawat sebagai abses otak; pendengaran telinga kiri tidak dapat dikembalikan dan kelumpuhan wajah hanya pulih sebagian.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Otitis Media Supuratif Kronik, SKDI 3A); WHO Chronic Suppurative Otitis Media — Burden of Illness and Management Options',
    },
  }),

  buatKasusLab({
    id: 'lab_mastoiditis_akut',
    nama: 'Mastoiditis Akut pada Anak',
    icd10: 'H70.0',
    skdi: '3B',
    kategori: 'tht',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'tht',
    keluhanUtama: 'Anak saya demam tinggi terus, Dok, dan belakang telinga kirinya bengkak merah sampai kupingnya terdorong ke depan.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 3, usiaMax: 10 },
    vital: { td: '100/62', nadi: 128, rr: 26, suhu: 39.2, spo2: 98 },
    pembuka: {
      tanya: 'Boleh diceritakan sejak kapan bengkaknya muncul dan bagaimana awalnya?',
      jawab: 'Dua minggu lalu dia sakit telinga dan demam, sudah berobat, dikasih antibiotik minum. Baru diminum empat hari sudah kelihatan enakan jadi saya hentikan. Empat hari lalu demamnya balik lagi lebih tinggi, dan tiga hari ini belakang telinganya bengkak merah, makin lama makin menonjol.',
      oldcarts: ['onset', 'durasi', 'keparahan', 'penyerta'],
    },
    pertanyaan: [
      tanya({
        id: 'q_riwayat_oma',
        kategori: 'rpd',
        tanya: 'Antibiotik yang dua minggu lalu itu diminum berapa hari dari yang seharusnya?',
        jawab: 'Seharusnya sepuluh hari, Dok. Baru empat hari sudah tidak demam dan tidak mengeluh sakit telinga lagi, jadi saya simpan sisanya. Saya kira sudah sembuh.',
        esensial: true,
        variasi: {
          wali_anak: 'Kata bu bidan sepuluh hari, Dok. Tapi baru empat hari anaknya sudah lari-lari lagi, sudah tidak demam, tidak ngeluh kupingnya. Ya sudah saya stop, sisanya saya simpan di lemari. Salah ya, Dok? Saya tidak tahu.',
          cemas: 'Aduh, Dok, itu yang saya sesali! Harusnya sepuluh hari tapi baru empat hari saya stop karena kelihatan sudah sembuh. Ini gara-gara saya ya, Dok? Anak saya kenapa ini? Bahaya tidak?',
        },
      }),
      tanya({
        id: 'q_bengkak_sifat',
        kategori: 'rps',
        tanya: 'Bengkak di belakang telinganya nyeri kalau disentuh? Kupingnya sejak kapan terdorong ke depan?',
        jawab: 'Nyeri sekali, Dok. Disentuh sedikit saja dia menjerit dan menepis tangan saya. Kupingnya mulai terdorong dua hari ini, sekarang jelas sekali menonjol ke depan dan ke bawah dibanding yang kanan.',
        esensial: true,
        oldcarts: ['lokasi', 'karakter', 'keparahan'],
        variasi: {
          wali_anak: 'Nyeri sekali, Dok. Saya mau usap saja dia menjerit dan menepis tangan saya. Kupingnya mulai maju dua hari ini. Coba Dokter bandingkan dengan yang kanan, kelihatan sekali yang kiri lebih menonjol ke depan dan agak ke bawah.',
          cemas: 'Nyeri banget, Dok! Disentuh dikit saja dia menjerit sampai saya tidak berani pegang lagi! Dan kupingnya itu lho, makin hari makin maju ke depan, tidak seperti yang kanan. Itu kenapa, Dok? Kok bisa kupingnya bergeser? Ada apa di dalamnya?',
        },
      }),
      tanya({
        id: 'q_keluar_cairan',
        kategori: 'rps',
        tanya: 'Ada cairan atau nanah yang keluar dari lubang telinganya?',
        jawab: 'Ada, Dok, sejak seminggu lalu keluar cairan kental kekuningan. Anehnya begitu keluar cairannya, dia malah tidak mengeluh sakit telinga lagi, jadi saya makin yakin sudah sembuh.',
        esensial: true,
        variasi: {
          wali_anak: 'Ada, Dok, seminggu lalu keluar cairan kental kuning, bantalnya sampai basah. Tapi justru sejak cairannya keluar dia berhenti mengeluh sakit telinga. Saya pikir itu tandanya kotorannya sudah keluar dan sembuh, Dok. Ternyata malah begini.',
          polos: 'Ana, Dok, seminggu kepungkur metu banyu kentel kuning. Aneh e, bar metu banyune bocahe malah ora sambat lara kuping maneh. Tak kira wis mari.',
        },
      }),
      {
        id: 'q_kesadaran_kejang',
        kategori: 'rps',
        tanya: 'Ada kejang, muntah menyembur, leher kaku, atau anaknya jadi sangat mengantuk dan sulit dibangunkan?',
        jawab: 'Tidak ada kejang, tidak muntah menyembur. Lehernya biasa saja. Cuma dia jadi rewel terus dan tidak mau main, tapi masih menjawab kalau dipanggil.',
        esensial: true,
      },
      {
        id: 'q_wajah',
        kategori: 'rps',
        tanya: 'Wajahnya ada yang mencong, atau matanya sulit menutup saat tidur?',
        jawab: 'Tidak ada, Dok. Wajahnya masih simetris.',
        esensial: true,
      },
      {
        id: 'q_makan_minum',
        kategori: 'rps',
        tanya: 'Masih mau makan dan minum? Buang air kecilnya bagaimana?',
        jawab: 'Makannya turun banyak, tapi minum masih mau. Pipisnya masih seperti biasa, popoknya tetap basah.',
        esensial: true,
      },
      {
        id: 'q_telinga_kanan',
        kategori: 'rps',
        tanya: 'Telinga kanannya bagaimana, ada keluhan juga?',
        jawab: 'Yang kanan tidak apa-apa, Dok. Cuma yang kiri.',
      },
      {
        id: 'q_riwayat_berulang',
        kategori: 'rpd',
        tanya: 'Sebelumnya sering sakit telinga berulang, atau ini yang pertama?',
        jawab: 'Setahun ini sudah tiga kali sakit telinga, Dok. Tapi biasanya sembuh sendiri setelah minum obat.',
      },
      {
        id: 'q_distraktor_imunisasi',
        kategori: 'rpd',
        tanya: 'Imunisasinya lengkap?',
        jawab: 'Lengkap, Dok, sesuai buku KIA semua. Tidak pernah bolong.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_kolam',
        kategori: 'sosial',
        tanya: 'Apakah anaknya sering berenang atau main air?',
        jawab: 'Sesekali saja main air di ember, Dok. Berenang jarang, mungkin sebulan sekali.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'kepala_leher', temuan: 'Daerah belakang telinga kiri bengkak, merah, teraba hangat dan sangat nyeri ditekan, dengan bagian tengah yang terasa lunak berisi cairan. Lekukan di belakang daun telinga MENGHILANG. Daun telinga kiri jelas terdorong ke arah depan-bawah dibanding telinga kanan.', relevan: true },
      { region: 'tht_mulut', temuan: 'Liang telinga kiri sempit karena dinding belakang-atasnya menggantung turun; tampak sekret kental kekuningan. Gendang telinga kiri menggembung dengan lubang kecil yang mengalirkan nanah. Telinga kanan normal.', relevan: true },
      { region: 'umum', temuan: 'Anak rewel, tampak sakit sedang-berat, badan teraba panas; masih menjawab saat dipanggil dan masih mau minum. Mata tidak cekung, waktu pengisian kapiler kurang dari dua detik.', relevan: true },
      { region: 'neurologis', temuan: 'Kesadaran penuh. Tidak ada kaku kuduk, tidak ada wajah mencong, manik mata sama besar dan bereaksi terhadap cahaya, tidak ada kelumpuhan anggota gerak.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru, tidak ada tarikan dinding dada.', relevan: false },
      { region: 'abdomen', temuan: 'Perut lemas, tidak nyeri, hati dan limpa tidak teraba membesar.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Leukosit 19.800/uL dengan dominasi neutrofil; Hb 11,6 g/dL; trombosit 402.000/uL.', flag: 'tinggi', relevan: true },
    ],
    diagnosisBanding: ['H70.0', 'H66.0', 'L04.0'],
    tatalaksana: {
      obatBenar: ['ceftriaxone_1g_inj', 'paracetamol_sirup'],
      terapiKritis: ['ceftriaxone_1g_inj'],
      obatSalahUmum: [
        { id: 'amoxicillin_sirup', alasan: 'Melanjutkan atau mengulang antibiotik MINUM yang sudah terbukti gagal pada anak ini. Rongga mastoid yang sudah berisi nanah dan tulangnya mulai dimakan hampir tidak dapat dicapai kadar bakterisid lewat jalur minum; yang dibutuhkan adalah antibiotik suntik dosis pertama lalu rujukan, bukan resep pulang.', bahaya: 'nonPrimer' },
        { id: 'cefixime_100', alasan: 'Sefalosporin generasi ketiga dalam bentuk minum sering dipilih karena terdengar "lebih kuat", padahal penyerapannya terbatas dan kadar yang dicapai di tulang mastoid jauh di bawah yang diperlukan. Memberikannya melahirkan rasa aman palsu yang menunda rujukan pada penyakit berhitung jam.', bahaya: 'nonPrimer' },
        { id: 'dexamethasone_05', alasan: 'Steroid diberikan agar bengkak dan demamnya cepat turun. Bengkak memang mereda sementara dan anak tampak membaik, tetapi nanah di dalam mastoid tetap ada dan justru mendapat tekanan kekebalan yang menurun; yang paling berbahaya, tanda-tanda perburukan ke arah komplikasi dalam rongga tengkorak menjadi tersamar sehingga terlambat dikenali.', bahaya: 'kontraindikasi' },
      ],
      prosedur: ['pasang_infus', 'pemantauan_ketat_vital'],
      tindakanSalahUmum: [
        { id: 'insisi_abses', alasan: 'Bengkak yang teraba berisi cairan menggoda untuk diinsisi seperti bisul biasa. Ini keliru: sumber nanahnya ada di dalam rongga tulang mastoid, bukan di kulit, sehingga insisi di FKTP tidak mengosongkan mastoid sama sekali. Yang didapat justru risikonya — di bawah lapangan itu berjalan pembuluh balik besar otak (sinus sigmoid) dan saraf wajah, dan luka yang dibuat berpotensi menjadi lubang bernanah menahun. Pengeluaran nanah yang benar adalah mastoidektomi di kamar operasi.', bahaya: 'berbahaya' },
      ],
      edukasi: ['tanda_bahaya', 'persiapan_rujukan_operatif', 'kepatuhan_obat'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Otitis media akut yang antibiotiknya dihentikan di tengah jalan, lalu demam tinggi kembali disertai bengkak merah nyeri di belakang telinga, hilangnya lekukan retroaurikuler, dan daun telinga yang terdorong ke depan-bawah: ini mastoiditis akut. Rongga mastoid berhubungan langsung dengan telinga tengah, dan bila nanah terperangkap di sana ia akan mengikis sekat-sekat tulang lalu menembus ke luar (abses di bawah selaput tulang), ke dalam (abses otak, radang selaput otak), atau ke pembuluh balik besar otak (trombosis sinus lateral). Trias tanda khasnya: nyeri belakang telinga, hilangnya lekukan di belakang daun telinga, dan daun telinga yang terdorong. Yang benar di FKTP: kenali sebagai kegawatan, pasang jalur infus, berikan antibiotik suntik dosis pertama tanpa menunggu apa pun, turunkan demam dan nyerinya, pantau ketat, lalu rujuk SEGERA ke spesialis THT untuk pencitraan dan mastoidektomi. Dosis pertama antibiotik suntik di FKTP bukan formalitas: ia memulai jam terapi lebih awal sebelum anak sampai di rumah sakit.',
    panduanResmi: `${PPK_FLOOR} Mastoiditis akut adalah kompetensi SKDI 3B: dokter FKTP wajib menegakkan diagnosis, memberi penanganan awal kegawatdaruratan, dan merujuk. PPK menegaskan bahwa OMA yang tidak tuntas diobati dapat berlanjut menjadi mastoiditis, dan bahwa munculnya tanda di belakang telinga adalah alasan rujukan segera, bukan alasan menambah antibiotik minum. Perhatikan juga kriteria rujukan gawat darurat pada anak: demam tinggi menetap dengan sumber infeksi yang jelas dan tanda perluasan lokal.`,
    catatanRealita: 'Skenario mengandaikan ceftriaxone injeksi, jalur infus, dan ambulans siap. Di Puskesmas tanpa rawat inap, memasang infus pada anak tiga tahun yang menjerit dan menepis sering butuh dua orang dan beberapa percobaan; bila jalur vena gagal berulang, jangan menghabiskan waktu di situ — antibiotik suntik lewat otot dan berangkat lebih baik daripada infus sempurna yang terlambat satu jam.',
    mutiaraEbm: 'Justru keluarnya nanah dari telinga yang membuat anak ini berhenti mengeluh sakit — gendang telinga yang bocor melepaskan tekanan, nyeri hilang, dan orang tua serta dokter sama-sama membaca itu sebagai kesembuhan, padahal infeksinya sedang berpindah ke rongga mastoid. Perangkap kedua adalah mastoiditis yang tersamar: anak yang sudah sempat menerima antibiotik minum bisa datang tanpa demam tinggi, tanpa nyeri hebat, dan dengan gendang telinga yang tampak hampir normal, sementara mastoidnya sudah bernanah. Karena itu bengkak di belakang telinga dan daun telinga yang terdorong lebih dipercaya daripada gambaran gendang telinga atau tingginya demam.',
    konsekuensi: {
      narasi: 'Anak dipulangkan dengan antibiotik minum dan penurun panas karena "masih sadar dan masih mau minum". Nanah di dalam mastoid terus menekan dan mencari jalan keluar ke arah rongga tengkorak.',
      kembaliHariMin: 1,
      kembaliHariMax: 3,
      kondisiKembali: 'Dibawa kembali dalam keadaan sangat mengantuk dan sulit dibangunkan, demam 40 derajat, leher kaku, dan muntah menyembur; bengkak di belakang telinga sudah pecah mengalirkan nanah. Dirawat di PICU sebagai radang selaput otak dengan trombosis pembuluh balik otak. Anak selamat setelah mastoidektomi darurat, tetapi telinga kirinya tuli menetap.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Mastoiditis / Komplikasi Otitis Media Akut, SKDI 3B); WHO Pocket Book of Hospital Care for Children',
    },
  }),

  buatKasusLab({
    id: 'lab_benda_asing_esofagus',
    nama: 'Benda Asing Esofagus pada Anak — Baterai Kancing',
    icd10: 'T18.1',
    skdi: '3B',
    kategori: 'tht',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'tht',
    keluhanUtama: 'Anak saya tadi menelan sesuatu, Dok, sekarang tidak mau makan sama sekali, ngiler terus, dan katanya sakit kalau menelan.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 2, usiaMax: 8 },
    vital: { td: '100/64', nadi: 118, rr: 24, suhu: 36.9, spo2: 98 },
    pembuka: {
      tanya: 'Tolong ceritakan kejadiannya: apa yang ditelan, jam berapa, dan siapa yang melihat?',
      jawab: 'Sekitar tiga jam lalu, Dok. Dia main sendiri di ruang tamu dekat toples uang receh dan remote TV yang rusak. Kakaknya lihat dia tersedak lalu menangis. Kami pikir uang logam karena toplesnya terbuka dan isinya berhamburan.',
      oldcarts: ['onset', 'waktu', 'karakter'],
    },
    pertanyaan: [
      tanya({
        id: 'q_benda_apa',
        kategori: 'rps',
        tanya: 'Apakah ada yang benar-benar melihat benda itu masuk ke mulutnya? Remote TV yang rusak itu baterainya masih ada?',
        jawab: 'Tidak ada yang lihat persis, Dok. Kami cuma dengar dia tersedak. Soal remote... aduh, saya baru sadar. Tutup baterainya memang sudah lepas dari kemarin dan ada baterai bulat pipih di dalamnya. Saya belum cek masih ada atau tidak.',
        esensial: true,
        variasi: {
          cemas: 'Tidak ada yang lihat, Dok! Kami cuma dengar dia tersedak terus nangis kencang! Remote itu... ya Allah, tutupnya lepas dari kemarin, ada baterai bulat pipih di situ. Saya tidak cek! Bahaya ya, Dok? Bahaya ya?',
          wali_anak: 'Tidak ada yang lihat, Dok. Cuma dengar tersedak. Remote-nya memang rusak, tutup baterainya lepas. Baterainya yang bulat pipih itu. Saya belum periksa masih ada apa tidak.',
        },
      }),
      {
        id: 'q_ngiler_menelan',
        kategori: 'rps',
        tanya: 'Ngilernya seberapa banyak, dan apakah ludahnya bisa ditelan?',
        jawab: 'Ngiler terus, Dok, sampai bajunya basah semua. Ludahnya seperti tidak bisa ditelan, dikeluarkan terus. Diberi air minum dia mau, tapi langsung dimuntahkan lagi.',
        esensial: true,
        oldcarts: ['karakter', 'keparahan'],
      },
      {
        id: 'q_napas',
        kategori: 'rps',
        tanya: 'Napasnya bagaimana? Ada bunyi ngik, suara serak, batuk terus, atau kebiruan?',
        jawab: 'Napasnya biasa saja, Dok, itu yang bikin kami agak tenang. Tidak ada bunyi aneh, tidak biru, suaranya juga normal waktu menangis.',
        esensial: true,
      },
      tanya({
        id: 'q_tindakan_rumah',
        kategori: 'rps',
        tanya: 'Di rumah sudah diberi atau dilakukan apa saja untuk mengeluarkannya?',
        jawab: 'Nenek menyuruh telan pisang sepotong besar biar terdorong, tapi dimuntahkan lagi. Lalu disuruh makan nasi kepal, sama saja. Terus mau dikorek pakai jari tapi dia meronta jadi tidak jadi.',
        esensial: true,
        variasi: {
          wali_anak: 'Kata nenek suruh telan pisang biar terdorong ke bawah, Dok, sudah dicoba tapi dimuntahkan. Terus nasi kepal, sama saja. Ada yang bilang suruh minum air hangat banyak. Mana yang betul, Dok?',
          polos: 'Wis dikeki gedhang sak potong gedhe ben mudhun, Dok, ning dimutahke. Terus sega dikepel, podho wae. Arep dikorek nganggo jari, bocahe mbrontak.',
        },
      }),
      {
        id: 'q_nyeri_lokasi',
        kategori: 'rps',
        tanya: 'Kalau ditanya sakitnya di mana, dia menunjuk ke bagian mana?',
        jawab: 'Dia selalu menunjuk ke bawah leher, di cekungan dekat tulang selangka. Sambil menangis kalau disuruh menelan.',
        esensial: true,
        oldcarts: ['lokasi'],
      },
      {
        id: 'q_muntah_darah',
        kategori: 'rps',
        tanya: 'Ada muntah bercampur darah, atau ludah yang kemerahan?',
        jawab: 'Belum ada darah, Dok. Ludahnya bening saja, cuma banyak sekali.',
        esensial: true,
      },
      {
        id: 'q_demam',
        kategori: 'rps',
        tanya: 'Ada demam, atau nyeri di dada dan punggung?',
        jawab: 'Tidak demam. Dia tidak bilang sakit dada, cuma leher bawah itu tadi.',
      },
      {
        id: 'q_riwayat_telan',
        kategori: 'rpd',
        tanya: 'Sebelumnya pernah menelan benda lain, atau ada masalah menelan sejak bayi?',
        jawab: 'Belum pernah, Dok. Makannya selama ini lancar-lancar saja.',
      },
      {
        id: 'q_distraktor_alergi_makanan',
        kategori: 'rpd',
        tanya: 'Apakah anaknya punya alergi makanan tertentu?',
        jawab: 'Tidak ada, Dok. Dia makan apa saja tidak pernah bentol atau gatal.',
        distraktor: true,
      },
      {
        id: 'q_distraktor_cacing',
        kategori: 'sosial',
        tanya: 'Apakah anaknya sering main tanah tanpa alas kaki dan sudah minum obat cacing?',
        jawab: 'Main tanah sering, Dok. Obat cacing terakhir enam bulan lalu di Posyandu.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Anak rewel dan menangis, air liur menetes terus membasahi baju. Tidak biru, tidak tampak sesak, masih menolak dan meronta dengan tenaga penuh.', relevan: true },
      { region: 'tht_mulut', temuan: 'Rongga mulut dan bagian belakang tenggorok bersih: tidak tampak benda asing, tidak ada luka, amandel tidak membesar dan tidak merah. Air liur menggenang banyak di dasar mulut.', relevan: true },
      { region: 'kepala_leher', temuan: 'Leher tidak bengkak, tidak merah, dan tidak teraba gelembung udara di bawah kulit; tidak ada nyeri tekan di sisi leher. Anak menunjuk cekungan di atas tulang dada saat ditanya lokasi nyeri.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas terdengar sama dan bersih di kedua sisi, tanpa bunyi ngik dan tanpa suara napas berbunyi kasar saat menarik napas. Tidak ada tarikan dinding dada.', relevan: true },
      { region: 'abdomen', temuan: 'Perut lemas, tidak kembung, tidak nyeri ditekan, bising usus normal.', relevan: false },
      { region: 'jantung', temuan: 'Denyut cepat teratur sesuai usia dan tangisan, tidak ada bising.', relevan: false },
    ],
    lab: [
      { id: 'foto_toraks', hasil: 'Tampak bayangan cakram padat (opak) melintang setinggi pintu masuk rongga dada, sekitar setinggi tulang selangka. Pada gambar dari depan, cakram itu memperlihatkan GAMBARAN CINCIN GANDA (lingkaran di dalam lingkaran / tanda halo); pada gambar dari samping, tepinya TIDAK rata melainkan bertingkat seperti anak tangga. Tidak tampak udara bebas di leher maupun rongga dada. Kedua paru mengembang normal.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['T18.1', 'T17.9', 'J03.9'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'domperidon_10', alasan: 'Diberikan dengan harapan "mendorong benda itu turun ke lambung". Obat pelancar gerakan lambung tidak mendorong benda padat melewati penyempitan esofagus, dan yang lebih penting: pada baterai kancing, mendorongnya turun bukanlah tujuan — mengeluarkannya dalam hitungan jam-lah tujuannya. Setiap menit yang dipakai menunggu obat bekerja adalah menit tambahan bagi luka bakar di dinding esofagus.', bahaya: 'nonPrimer' },
        { id: 'ondansetron_4', alasan: 'Diberikan untuk menghentikan muntah dan ngilernya. Justru ngiler dan muntah itulah penanda klinis bahwa jalur menelan tersumbat; meredamnya menghapus tanda pemantauan tanpa menyentuh penyebabnya, dan membuat anak tampak lebih tenang daripada keadaan sebenarnya.', bahaya: 'nonPrimer' },
        { id: 'antasida_doen', alasan: 'Muncul dari penalaran keliru bahwa luka bakar baterai adalah luka bakar asam lambung yang bisa "dinetralkan". Kerusakan baterai kancing bukan kerusakan asam melainkan kerusakan basa akibat arus listrik yang memecah cairan tubuh di sekitarnya; antasida tidak menyentuh proses itu sedikit pun dan hanya menambah isi lambung menjelang tindakan pembiusan.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['pemantauan_ketat_vital'],
      tindakanSalahUmum: [
        { id: 'bilas_lambung', alasan: 'Memasukkan selang lalu menyiram dan menyedot isi lambung pada benda asing padat di esofagus adalah tindakan berbahaya: selang harus melewati benda itu lebih dulu — berisiko mendorongnya lebih dalam atau menusuk dinding yang sudah terbakar — sementara cairan yang disiramkan membanjiri jalur menelan yang tersumbat sehingga sangat mudah masuk ke paru. Bilas lambung tidak pernah menjadi cara mengeluarkan benda asing esofagus; jalannya adalah endoskopi.', bahaya: 'berbahaya' },
        { id: 'dekompresi_ngt', alasan: 'Memasang selang lambung terasa masuk akal untuk "mengosongkan lambung sebelum rujukan". Pada benda asing esofagus, selang itu harus menerobos melewati benda tersebut secara membuta: ia dapat mendorong baterai lebih dalam, mengubah letaknya sehingga menyulitkan endoskopi, atau menembus dinding esofagus yang jaringannya sudah dilunakkan oleh luka bakar. Pengosongan lambung bukan prioritas di sini; pengeluaran bendanya yang prioritas.', bahaya: 'berbahaya' },
      ],
      edukasi: ['puasa_sambil_rujuk', 'tanda_bahaya', 'cegah_benda_asing_hidung'],
      edukasiKritis: ['puasa_sambil_rujuk'],
    },
    clue: 'Anak yang tersedak lalu menolak makan, ngiler tanpa henti karena ludahnya tidak bisa ditelan, dan menunjuk cekungan di atas tulang dada: benda asing esofagus, tersangkut di penyempitan paling atas. Napas yang baik TIDAK menyingkirkannya — benda di esofagus memang tidak menyumbat jalan napas. Yang menentukan segalanya adalah jenis bendanya, dan di sinilah foto polos menjadi penentu: uang logam tampak sebagai cakram polos bertepi rata, sedangkan BATERAI KANCING memperlihatkan gambaran cincin ganda (tanda halo) dari depan dan tepi bertingkat seperti anak tangga dari samping. Foto anak ini menunjukkan cincin ganda: ini baterai kancing, bukan uang logam, dan keluarga memang tidak pernah benar-benar melihat apa yang tertelan. Baterai kancing adalah kegawatan BERHITUNG JAM, bukan hari: arus listrik yang mengalir di dinding esofagus yang lembap menghasilkan zat basa kuat, dan kerusakan jaringan sudah dimulai dalam 2 jam serta dapat menembus dinding esofagus dalam 6-8 jam — bahkan setelah baterainya dikeluarkan, kerusakan basa itu terus berlanjut. Yang benar di FKTP: kenali gambaran cincin gandanya, PUASAKAN total, jangan sekali-kali mendorong dengan pisang atau nasi, jangan menginduksi muntah (baterai naik-turun melukai dua kali dan berisiko masuk paru), jangan memasang selang secara membuta, pantau ketat, dan rujuk untuk endoskopi darurat pada kesempatan tercepat. Catatan EBM: pedoman NASPGHAN/National Capital Poison Center menganjurkan madu atau sukralfat 10 mL tiap 10 menit pada anak di atas 12 bulan dalam 12 jam pertama sebagai penyangga sementara selama transportasi — manfaatnya nyata tetapi kecil, dan ia TIDAK boleh menunda keberangkatan atau menggantikan endoskopi; bila ragu antara memberi madu atau berangkat lebih cepat, berangkatlah.',
    panduanResmi: `${PPK_FLOOR} Benda asing esofagus adalah kompetensi SKDI 3B: dokter FKTP mengenali, menstabilkan, dan merujuk; pengeluarannya lewat endoskopi bukan kewenangan FKTP. PPK menetapkan foto polos sebagai penunjang awal dan rujukan segera ke spesialis THT untuk pengeluaran. Yang perlu ditegaskan melampaui teks PPK: baterai kancing berada di kelas kegawatan tersendiri — targetnya pengeluaran dalam 2 jam sejak tertelan, sehingga tidak ada tempat untuk observasi menunggu, foto ulang berkala, ataupun percobaan terapi apa pun di FKTP.`,
    catatanRealita: 'Skenario mengandaikan foto polos tersedia saat itu juga. Banyak Puskesmas tidak punya rontgen, dan justru di situ letak keputusannya: bila ada dugaan menelan benda dan anak ngiler serta menolak makan, JANGAN menunggu foto — puasakan dan berangkatkan, karena foto dapat dikerjakan di rumah sakit rujukan tanpa kehilangan jam.',
    mutiaraEbm: 'Setiap hal yang menenangkan pada kasus ini adalah jebakan. Napas yang baik, tidak biru, tanpa bunyi ngik, dan anak yang masih meronta bertenaga membuat kasus ini terasa seperti keluhan tersedak biasa — padahal baterai kancing tidak membunuh lewat sumbatan napas melainkan lewat luka bakar listrik-basa yang senyap, dan anak bisa tampak baik-baik saja tepat pada jam-jam ketika esofagusnya sedang terbakar. Perangkap kedua adalah keyakinan keluarga: mereka menyebut uang logam dengan yakin, padahal tidak seorang pun melihat kejadiannya — dan uang logam serta baterai kancing sama-sama cakram padat yang mirip di foto, sehingga hanya tanda cincin ganda dan tepi bertingkat yang memisahkan barang yang boleh ditunggu semalam dari barang yang harus keluar dalam dua jam. Karena itu setiap cakram padat di esofagus anak diperlakukan sebagai baterai sampai foto membuktikan sebaliknya.',
    konsekuensi: {
      narasi: 'Anak dipulangkan dengan obat mual dan pesan "kalau belum keluar besok kontrol lagi", karena napasnya baik dan dia masih aktif. Arus listrik baterai terus bekerja di dinding esofagus sepanjang malam.',
      kembaliHariMin: 1,
      kembaliHariMax: 2,
      kondisiKembali: 'Dibawa kembali dengan demam tinggi, nyeri dada tembus ke punggung, leher yang teraba berkeretak karena udara bocor ke bawah kulit, dan air liur bercampur darah — dinding esofagus sudah berlubang. Dirawat di PICU dengan radang rongga dada; anak selamat setelah operasi berkepanjangan, tetapi esofagusnya menyempit karena jaringan parut sehingga harus dilebarkan berulang kali selama bertahun-tahun.',
      guideline: 'PPK Dokter FKTP KMK 1186/2022 (Benda Asing Esofagus, SKDI 3B); NASPGHAN Button Battery Ingestion Clinical Report; National Capital Poison Center Button Battery Ingestion Triage Guideline',
    },
  }),

  buatKasusLab({
    id: 'lab_tia_serangan_iskemik_sesaat',
    nama: 'TIA — Serangan Iskemik Sesaat yang Sudah Pulih',
    icd10: 'G45.9',
    skdi: '3B',
    kategori: 'saraf',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'saraf',
    keluhanUtama: 'Tadi pagi bicara saya tiba-tiba pelo dan tangan kanan lemas sekitar dua puluh menit, Dok, tapi sekarang sudah normal lagi — saya ke sini cuma karena dipaksa keluarga.',
    demografi: { usiaMin: 55, usiaMax: 75 },
    vital: { td: '168/96', nadi: 92, rr: 18, suhu: 36.6, spo2: 98 },
    pembuka: {
      tanya: 'Coba ceritakan persis apa yang terjadi tadi pagi, dari awal sampai pulih.',
      jawab: 'Sekitar jam tujuh pagi saya lagi minum kopi. Tiba-tiba bicara saya jadi pelo, istri saya tidak paham saya ngomong apa. Bersamaan itu tangan kanan saya lemas, cangkirnya sampai jatuh. Kira-kira dua puluh menit lalu hilang sendiri, pelan-pelan normal lagi. Sekarang sudah tidak ada apa-apa, lihat sendiri Dok, saya baik-baik saja.',
      oldcarts: ['onset', 'durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      tanya({
        id: 'q_durasi_pulih',
        kategori: 'rps',
        tanya: 'Pulihnya bertahap atau sekaligus? Sekarang benar-benar tidak ada sisa sedikit pun?',
        jawab: 'Pelan-pelan, Dok, mungkin lima menit terakhir. Sekarang tidak ada sisa apa-apa. Tangan saya kuat, bicara saya jelas. Makanya saya bilang tidak perlu ke sini.',
        esensial: true,
        oldcarts: ['durasi', 'keparahan'],
        variasi: {
          skeptis: 'Pelan-pelan hilangnya. Dan sekarang sudah tidak ada apa-apa sama sekali — coba Dokter lihat, saya bisa genggam kuat, bicara saya jelas. Jadi buat apa saya di sini? Cuma kecapekan itu. Kalau memang stroke ya saya sudah lumpuh sekarang, betul tidak?',
          cemas: 'Pelan-pelan, Dok, tapi saya takut sekali waktu itu! Sekarang memang sudah normal tapi kalau kambuh lagi bagaimana? Kalau pas saya sendirian? Ini kenapa, Dok? Saya mau stroke ya?',
        },
      }),
      {
        id: 'q_gejala_lain',
        kategori: 'rps',
        tanya: 'Waktu itu ada wajah yang mencong, satu mata mendadak gelap seperti ditutup tirai, atau kaki kanan ikut lemas?',
        jawab: 'Kata istri saya mulut saya agak turun sebelah kanan. Mata tidak ada yang gelap. Kaki tidak ikut lemas, saya masih bisa berdiri.',
        esensial: true,
      },
      tanya({
        id: 'q_pertama_kali',
        kategori: 'rpd',
        tanya: 'Ini pertama kali, atau sebelumnya pernah ada kejadian serupa walau lebih singkat?',
        jawab: 'Sebenarnya... tiga hari lalu pernah, Dok. Tangan kanan kesemutan dan lemas sekitar lima menit, terus hilang. Saya kira ketindihan waktu tidur, jadi tidak saya pikirkan.',
        esensial: true,
        oldcarts: ['waktu'],
        variasi: {
          skeptis: 'Kalau dihitung, ya tiga hari lalu pernah sebentar. Tangan kesemutan lemas lima menit terus hilang. Tapi itu jelas ketindihan waktu tidur, Dok, saya memang suka tidur miring. Tidak usah dibesar-besarkan.',
        },
      }),
      tanya({
        id: 'q_hipertensi',
        kategori: 'rpd',
        tanya: 'Punya darah tinggi? Obatnya diminum teratur?',
        jawab: 'Darah tinggi sudah delapan tahun, Dok. Obatnya... jujur saja tidak teratur. Saya minum kalau kepala pusing atau tengkuk pegal saja. Kalau enak badan ya tidak minum.',
        esensial: true,
        variasi: {
          skeptis: 'Ada, delapan tahun. Obatnya saya minum kalau perlu saja — kalau tengkuk pegal atau kepala nyut-nyutan. Buat apa minum obat tiap hari kalau badan enak? Malah rusak ginjal nanti.',
        },
      }),
      {
        id: 'q_jantung_berdebar',
        kategori: 'rps',
        tanya: 'Pernah merasa jantung berdebar tidak beraturan, seperti melompat-lompat atau kadang berhenti sesaat?',
        jawab: 'Sering, Dok, sudah setahunan. Kadang dadanya seperti bergetar sendiri, tidak teratur. Saya kira karena kopi. Belum pernah diperiksa jantungnya.',
        esensial: true,
      },
      {
        id: 'q_nyeri_kepala',
        kategori: 'rps',
        tanya: 'Waktu kejadian tadi ada sakit kepala hebat mendadak, muntah, atau kejang?',
        jawab: 'Tidak ada. Kepala tidak sakit sama sekali, tidak muntah, tidak kejang.',
        esensial: true,
      },
      {
        id: 'q_dm_kolesterol',
        kategori: 'rpd',
        tanya: 'Ada kencing manis atau kolesterol tinggi?',
        jawab: 'Kolesterol pernah dibilang tinggi dua tahun lalu, tapi saya tidak minum obat apa-apa. Kencing manis tidak ada.',
      },
      {
        id: 'q_merokok',
        kategori: 'sosial',
        tanya: 'Merokok? Berapa lama dan berapa banyak?',
        jawab: 'Masih, Dok. Sehari sebungkus, sudah dari umur dua puluh.',
      },
      {
        id: 'q_distraktor_kecapekan',
        kategori: 'sosial',
        tanya: 'Akhir-akhir ini apakah kurang tidur, banyak pikiran, atau kelelahan?',
        jawab: 'Nah itu dia, Dok! Seminggu ini saya memang kurang tidur, banyak urusan. Pasti gara-gara itu kan? Cuma kecapekan saja kan?',
        distraktor: true,
      },
      {
        id: 'q_distraktor_urut',
        kategori: 'sosial',
        tanya: 'Apakah sudah dibawa ke tukang urut atau minum jamu untuk keluhan ini?',
        jawab: 'Belum, tapi tetangga menyarankan diurut saja katanya angin duduk. Bagus tidak, Dok?',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'neurologis', temuan: 'SELURUHNYA NORMAL saat ini: kesadaran penuh, bicara jelas dan lancar, wajah simetris termasuk saat menyeringai, kekuatan keempat anggota gerak penuh dan simetris, rasa raba normal, tidak ada gangguan keseimbangan berjalan. Tidak ada kaku kuduk.', relevan: true },
      { region: 'jantung', temuan: 'Denyut jantung IREGULER-IREGULER, tidak ada pola sama sekali, laju sekitar 92 per menit; bunyi jantung satu dengan kuat yang berubah-ubah. Tidak ada bising, tidak ada bengkak tungkai.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak terdengar bunyi desiran pada kedua pembuluh leher; denyut nadi leher teraba sama kuat di kedua sisi.', relevan: true },
      { region: 'umum', temuan: 'Tampak sehat dan bugar, duduk santai, berulang kali menyatakan ingin segera pulang karena merasa tidak ada masalah.', relevan: true },
      { region: 'mata', temuan: 'Manik mata sama besar dan bereaksi terhadap cahaya; gerakan bola mata bebas ke segala arah.', relevan: false },
      { region: 'ekstremitas', temuan: 'Denyut nadi tangan dan kaki teraba; tidak ada luka maupun perubahan warna kulit.', relevan: false },
    ],
    lab: [
      { id: 'ekg', hasil: 'FIBRILASI ATRIUM dengan laju respons ventrikel sekitar 92 per menit: tidak tampak gelombang P, jarak antar-denyut sama sekali tidak teratur. Tidak ada elevasi segmen ST. Tampak tanda pembesaran otot bilik kiri.', flag: 'abnormal', relevan: true },
      { id: 'gds', hasil: '138 mg/dL.', flag: 'normal', relevan: true },
      { id: 'profil_lipid', hasil: 'Kolesterol total 268 mg/dL, LDL 186 mg/dL, HDL 38 mg/dL, trigliserida 192 mg/dL.', flag: 'tinggi', relevan: true },
      { id: 'darah_rutin', hasil: 'Hb 14,6 g/dL, leukosit 7.100/uL, trombosit 254.000/uL.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['G45.9', 'I63.9', 'E16.2'],
    tatalaksana: {
      obatBenar: ['simvastatin_20'],
      obatOpsional: ['amlodipine_5'],
      obatSalahUmum: [
        { id: 'nifedipin_10', alasan: 'Godaan klasik: tekanan darah 168/96 pada pasien yang "baru kena serangan otak" terasa harus segera diturunkan, dan nifedipin kerja cepat menurunkannya dalam menit. Justru inilah bahayanya. Pada fase akut gangguan pembuluh darah otak, tekanan darah yang agak tinggi adalah upaya tubuh mempertahankan aliran ke jaringan otak yang pasokannya rawan; menurunkannya mendadak dan tanpa kendali dapat mengubah serangan sesaat yang sudah pulih menjadi infark yang menetap. Pengendalian tekanan darah pada TIA adalah proyek jangka panjang, bukan tindakan menit ini.', bahaya: 'kontraindikasi' },
        { id: 'betahistin_6', alasan: 'Keluhan sesaat pada lansia sering dibaca sebagai "kurang darah ke otak" atau vertigo lalu diberi betahistin. Obat ini bekerja pada organ keseimbangan telinga dalam dan tidak menurunkan risiko stroke sama sekali. Kerugian sebenarnya bukan pada obatnya, melainkan pada cerita yang dibawa pulang pasien: ia merasa penyakitnya sudah bernama dan sudah diobati, tepat pada 48 jam ketika ia paling mungkin terkena stroke.', bahaya: 'nonPrimer' },
        { id: 'vitamin_b_kompleks', alasan: 'Diberikan sebagai "obat saraf" untuk keluhan pelo dan lemas. Tidak ada bukti bahwa vitamin B mencegah stroke pada pasien ini, dan resep ini menyempurnakan rasa aman palsu: pasien yang sejak awal sudah yakin dirinya tidak sakit kini pulang membawa bukti bahwa dokter pun sependapat.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['tanda_bahaya', 'kepatuhan_obat', 'kontrol_rutin', 'diet_rendah_garam', 'berhenti_merokok'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Gejala neurologis mendadak yang khas satu wilayah pembuluh darah otak (bicara pelo dan lengan kanan lemas), berlangsung dua puluh menit, lalu pulih total: ini serangan iskemik sesaat (TIA). Gula darah normal menyingkirkan peniru yang paling sering. EKG menemukan penyebabnya: fibrilasi atrium yang belum pernah terdiagnosis — sumber bekuan yang berulang. Inti kasus ini adalah waktu, bukan obat: risiko stroke setelah TIA paling tinggi justru pada 48 jam pertama dan sebagian besar stroke susulan terjadi dalam minggu pertama, sehingga TIA diperlakukan sebagai kegawatan yang dinilai spesialis pada hari yang sama, bukan dijadwalkan poliklinik minggu depan (bukti dari studi EXPRESS dan SOS-TIA: penilaian serta terapi segera menurunkan stroke dini sampai sekitar 80%). Serangan lima menit tiga hari lalu bukan hiburan melainkan pemberat: TIA berulang menaikkan risiko lebih jauh lagi. Yang benar dan aman di FKTP: kenali dan beri nama masalahnya, kerjakan EKG untuk mencari fibrilasi atrium, periksa gula untuk menyingkirkan peniru, potret faktor risikonya, mulai statin, JANGAN menurunkan tekanan darah secara mendadak, lalu rujuk ke spesialis saraf secepat mungkin hari itu juga. TIA adalah stroke yang beruntung — keberuntungan yang hanya berlaku sekali.',
    panduanResmi: `${PPK_FLOOR} TIA adalah kompetensi SKDI 3B: dokter FKTP mengenali, memberi penanganan awal, dan merujuk. PNPK Stroke KMK 304/2026 dan AHA 2023 Scientific Statement on TIA menegaskan evaluasi segera berbasis risiko serta pencarian etiologi; pulihnya gejala tidak meniadakan urgensi. Fibrilasi atrium mengubah pencegahan sekunder menuju antikoagulasi setelah penilaian perdarahan/pencitraan dan timing yang tepat, sehingga keputusan regimen tidak diimprovisasi di FKTP.`,
    catatanRealita: 'Dua celah jujur perlu disebut. Pertama, terapi antiplatelet (aspirin, dan pada TIA risiko tinggi kombinasi singkat dengan klopidogrel) adalah tulang punggung pencegahan stroke dini dalam pedoman internasional, tetapi tidak tersedia dalam formularium permainan ini sehingga tidak dapat diklik —',
    mutiaraEbm: 'Pemulihan sempurna adalah temuan paling menyesatkan dalam neurologi. Pemeriksaan yang seluruhnya normal di hadapan Anda terasa seperti bukti bahwa tidak ada yang perlu dicemaskan — padahal justru pemulihan itulah yang menamai penyakitnya, dan penyakit itu adalah peringatan bahwa stroke sedang bersiap. Perangkap kedua bersifat kelembagaan: bila pasien terlanjur dirujuk dan menjalani CT kepala, hasilnya kemungkinan besar normal — dan CT normal pada TIA adalah temuan yang DIHARAPKAN, bukan tanda aman; ia sama sekali tidak mengubah kegentingannya. Perangkap ketiga ada pada denyut nadi: fibrilasi atrium sering tidak bergejala dan tidak akan ketahuan bila nadi hanya dihitung sepuluh detik lalu dikalikan enam — ia harus diraba cukup lama untuk merasakan ketidakteraturannya, dan dipastikan dengan EKG.',
    konsekuensi: {
      narasi: 'Pasien pulang tanpa rujukan, membawa vitamin saraf dan pesan "kalau kambuh baru datang lagi", karena semua pemeriksaannya normal dan ia sendiri bersikeras sudah sehat. Fibrilasi atriumnya terus melontarkan bekuan.',
      kembaliHariMin: 1,
      kembaliHariMax: 3,
      kondisiKembali: 'Dibawa keluarga dalam keadaan tidak dapat bicara sama sekali dan lengan serta tungkai kanan lumpuh total sejak bangun tidur — sehingga waktu pasti mulainya serangan tidak diketahui dan jendela terapi penghancur bekuan sudah tertutup. Stroke iskemik luas di belahan otak kiri. Pasien bertahan hidup dengan kelumpuhan sisi kanan yang menetap dan kesulitan bicara, bergantung pada keluarga untuk kegiatan sehari-hari.',
      guideline: 'PPK FKTP KMK 1186/2022; PNPK Tata Laksana Stroke KMK 304/2026; AHA 2023 Scientific Statement on Diagnosis, Workup, Risk Reduction of TIA in the Emergency Department',
    },
  }),

  buatKasusLab({
    id: 'lab_meningitis_bakterial_suspek',
    nama: 'Suspek Meningitis Bakterial',
    icd10: 'G00.9',
    skdi: '3B',
    kategori: 'saraf',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'saraf',
    keluhanUtama: 'Kepala saya sakit hebat sekali sejak kemarin, Dok, demam tinggi, leher rasanya kaku, dan tadi muntah menyembur.',
    demografi: { usiaMin: 15, usiaMax: 30 },
    vital: { td: '108/64', nadi: 122, rr: 26, suhu: 39.6, spo2: 96 },
    pembuka: {
      tanya: 'Sejak kapan sakit kepalanya, dan seberapa berat dibanding sakit kepala yang pernah dirasakan?',
      jawab: 'Mulai kemarin siang, makin lama makin hebat. Ini sakit kepala paling parah seumur hidup saya, Dok. Rasanya kepala mau pecah dan tidak berkurang sama sekali walau sudah minum obat warung. Tadi pagi muntah sampai menyembur jauh, padahal perut saya tidak mual.',
      oldcarts: ['onset', 'durasi', 'keparahan', 'penyerta'],
    },
    pertanyaan: [
      {
        id: 'q_leher_kaku',
        kategori: 'rps',
        tanya: 'Lehernya kaku bagaimana? Bisa menunduk sampai dagu menyentuh dada?',
        jawab: 'Tidak bisa, Dok. Kalau saya coba menunduk rasanya tertahan dan sakit sekali sampai ke belakang kepala. Menoleh ke samping masih bisa, tapi menunduk tidak.',
        esensial: true,
        oldcarts: ['karakter'],
      },
      tanya({
        id: 'q_silau',
        kategori: 'rps',
        tanya: 'Apakah cahaya terasa menyakitkan? Suara ribut bagaimana?',
        jawab: 'Silau sekali, Dok. Dari tadi saya tutup mata terus, kalau tirai dibuka rasanya menusuk. Suara ribut juga bikin kepala tambah sakit. Tolong lampunya jangan dinyalakan.',
        esensial: true,
        variasi: {
          terpelajar: 'Sangat, Dok. Cahaya terasa seperti menusuk sampai ke dalam kepala, jadi sejak kemarin saya menutup mata terus dan minta tirai kamar ditutup. Suara ribut juga menambah sakitnya. Maaf, boleh lampunya jangan dinyalakan?',
          polos: 'Silau nemen, Dok... mripat tak tutup terus. Nek gordene dibukak rasane koyo ditusuk. Suoro rame yo nggarai sirah tambah mumet. Lampune ampun diurupke, Dok.',
        },
      }),
      {
        id: 'q_ruam',
        kategori: 'rps',
        tanya: 'Ada bintik atau bercak merah di kulit yang muncul belakangan ini?',
        jawab: 'Kata teman kos saya tadi ada bintik-bintik merah kecil di kaki saya, muncul sejak tadi pagi. Saya sendiri belum lihat, dari tadi saya tidak kuat bangun.',
        esensial: true,
      },
      tanya({
        id: 'q_kesadaran',
        kategori: 'rps',
        tanya: 'Apakah sempat bingung, mengigau, tidak mengenali orang, atau kejang?',
        jawab: 'Kejang tidak ada. Tapi kata teman saya, dari tadi siang saya susah dibangunkan dan ngomongnya kacau. Saya sendiri... jujur agak bingung sekarang, Dok, ini hari apa ya?',
        esensial: true,
        variasi: {
          cemas: 'Kejang tidak ada, Dok, tapi teman saya bilang saya ngomong ngelantur dan susah dibangunkan dari siang! Saya sendiri sekarang bingung, ini hari apa sih? Kenapa saya jadi begini, Dok? Saya takut, tolong saya...',
          terpelajar: 'Tidak ada kejang, Dok. Tapi teman sekamar saya bilang sejak siang saya sulit dibangunkan dan bicara saya melantur — dan terus terang saya sendiri tidak ingat sebagian siang tadi. Sekarang pun saya harus berpikir keras untuk menjawab. Ini hari apa ya, Dok?',
        },
      }),
      {
        id: 'q_demam',
        kategori: 'rps',
        tanya: 'Demamnya sejak kapan, dan ada menggigil sampai gemetar?',
        jawab: 'Sejak kemarin siang bersamaan dengan sakit kepalanya. Semalam menggigil hebat sampai gigi saya beradu, selimut dua lapis tetap dingin.',
        esensial: true,
        oldcarts: ['onset', 'durasi'],
      },
      {
        id: 'q_kontak_asrama',
        kategori: 'sosial',
        tanya: 'Tinggal di kos atau asrama? Ada teman sekamar yang sakit serupa?',
        jawab: 'Saya tinggal di kos-kosan padat, Dok, sekamar berdua dan satu kamar mandi dipakai bersama sepuluh orang. Belum ada yang sakit seperti saya setahu saya.',
        esensial: true,
      },
      {
        id: 'q_sumber_infeksi',
        kategori: 'rpd',
        tanya: 'Sebelum ini ada telinga berair, sakit gigi berat, atau sinus yang sering nyeri?',
        jawab: 'Tidak ada, Dok. Telinga saya baik, gigi tidak ada yang sakit.',
      },
      {
        id: 'q_daya_tahan',
        kategori: 'rpd',
        tanya: 'Ada penyakit yang menurunkan daya tahan tubuh, minum obat jangka panjang, atau limpa pernah diangkat?',
        jawab: 'Tidak ada. Saya selama ini sehat, tidak pernah dirawat, tidak minum obat apa pun rutin.',
      },
      tanya({
        id: 'q_distraktor_begadang',
        kategori: 'sosial',
        tanya: 'Apakah akhir-akhir ini sering begadang atau banyak pikiran karena ujian?',
        jawab: 'Iya, Dok, minggu ini memang saya begadang terus, ada ujian. Mungkin cuma kecapekan dan masuk angin ya?',
        distraktor: true,
        variasi: {
          terpelajar: 'Betul, Dok, minggu ini saya begadang hampir tiap malam karena ujian akhir. Apa mungkin ini cuma kelelahan berat? Teman-teman saya juga bilang begitu.',
          cemas: 'Iya, Dok, saya begadang terus minggu ini! Tolong bilang ini cuma kecapekan ya, Dok? Cuma masuk angin kan? Kan cuma kurang tidur?',
        },
      }),
      {
        id: 'q_distraktor_migren',
        kategori: 'rpd',
        tanya: 'Apakah dari dulu sering sakit kepala sebelah, misalnya kalau telat makan?',
        jawab: 'Kadang-kadang kalau telat makan kepala saya nyut-nyutan sebelah, Dok. Tapi yang sekarang ini beda jauh, tidak ada apa-apanya dibanding ini.',
        distraktor: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Tampak sakit berat, mengantuk berat tetapi masih dapat dibangunkan dan menjawab pertanyaan singkat dengan kacau; badan teraba sangat panas, kulit lembap. Berbaring meringkuk membelakangi jendela dan menutup mata dengan lengan.', relevan: true },
      { region: 'neurologis', temuan: 'Kaku kuduk JELAS: dagu tidak dapat didekatkan ke dada. Kernig dan Brudzinski positif. Manik mata sama besar dan bereaksi terhadap cahaya. Tidak ada kelumpuhan satu sisi, tidak ada wajah mencong. Kesadaran menurun ringan.', relevan: true },
      { region: 'kulit', temuan: 'Tampak bercak dan bintik merah keunguan kecil di kedua tungkai bawah dan badan, TIDAK MEMUCAT saat ditekan dengan gelas; beberapa mulai menyatu menjadi bercak yang lebih besar.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada nyeri tekan di daerah sinus; gendang telinga kedua sisi utuh dan tidak meradang; gigi-geligi tidak ada yang berlubang besar atau bernanah.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas bersih di kedua lapang paru, tidak ada ronki, napas cepat tanpa tarikan dinding dada.', relevan: false },
      { region: 'abdomen', temuan: 'Perut lemas, tidak nyeri ditekan, hati dan limpa tidak teraba membesar, bising usus normal.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Leukosit 21.400/uL dengan dominasi neutrofil dan pergeseran ke kiri; Hb 13,2 g/dL; TROMBOSIT 118.000/uL (menurun).', flag: 'tinggi', relevan: true },
      { id: 'gds', hasil: '112 mg/dL.', flag: 'normal', relevan: true },
    ],
    diagnosisBanding: ['G00.9', 'I61.9', 'A01.0'],
    tatalaksana: {
      obatBenar: ['ceftriaxone_1g_inj', 'paracetamol_500'],
      terapiKritis: ['ceftriaxone_1g_inj'],
      obatOpsional: ['ondansetron_4'],
      obatSalahUmum: [
        { id: 'diazepam_2', alasan: 'Diberikan untuk "menenangkan" pasien yang gelisah dan mengigau. Ini menutup satu-satunya alat pemantauan yang tersisa selama perjalanan rujukan: tingkat kesadaran. Setelah diazepam, tidak ada yang bisa membedakan pasien yang tenang karena obat dari pasien yang kesadarannya jatuh karena tekanan dalam kepala meninggi — dan benzodiazepin sendiri menekan pusat napas pada pasien yang kesadarannya sudah turun.', bahaya: 'kontraindikasi' },
        { id: 'natrium_diklofenak_50', alasan: 'Dipilih karena "lebih kuat" untuk sakit kepala hebat dan demam tinggi. Pada pasien ini keliru berlapis: demam dan nyeri kepala adalah penanda perburukan yang justru sedang dipantau; ginjal sedang menghadapi awal sepsis dengan tekanan darah yang sudah di batas bawah; dan trombosit yang turun ke 118.000 dengan bercak perdarahan di kulit menandakan pembekuan darah mulai kacau, keadaan ketika obat yang mengganggu fungsi keping darah adalah hal terakhir yang dibutuhkan. Untuk demam dan nyeri, parasetamol sudah memadai dan aman.', bahaya: 'kontraindikasi' },
        { id: 'amoxicillin_500', alasan: 'Antibiotik MINUM pada pasien yang muntah menyembur dan kesadarannya menurun: sebagian besar dosisnya tidak akan terserap, dan amoksisilin menembus selaput otak dengan buruk sehingga tidak pernah mencapai kadar yang membunuh kuman di cairan otak. Kerugian terbesarnya adalah waktu — resep ini melahirkan perasaan "antibiotik sudah diberikan" pada penyakit yang setiap jam penundaannya berbayar nyawa.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['pasang_infus', 'oksigen', 'pemantauan_ketat_vital'],
      edukasi: ['tanda_bahaya', 'obati_kontak_serumah', 'etika_batuk'],
      edukasiKritis: ['tanda_bahaya'],
    },
    stabilisasiWajib: ['pasang_infus'],
    clue: 'Demam tinggi, sakit kepala terhebat seumur hidup, kaku kuduk dengan Kernig-Brudzinski positif, silau, muntah menyembur, dan kesadaran yang mulai menurun: suspek meningitis bakterial. Bercak keunguan yang tidak memucat saat ditekan menaikkan taruhannya lagi — itu perdarahan kecil di kulit yang menandakan meningokokus dengan kuman beredar di darah, dan turunnya trombosit menunjukkan pembekuan darah sudah mulai kacau; keadaan ini dapat membunuh dalam hitungan jam. INILAH INTI PEDAGOGIS KASUS INI: antibiotik suntik dosis pertama diberikan SEKARANG, di Puskesmas, sebelum rujukan — bukan setelah sampai rumah sakit dan bukan setelah pungsi lumbal. Pungsi lumbal memang standar untuk memastikan diagnosis, tetapi ia tidak dapat dikerjakan di FKTP, dan menahan antibiotik demi menunggu pungsi lumbal di rumah sakit adalah kesalahan yang mematikan: pedoman menegaskan antibiotik tidak boleh ditunda oleh prosedur diagnostik apa pun, dan biakan cairan otak yang menjadi kurang tajam setelah antibiotik adalah harga yang jauh lebih murah daripada nyawa. Setiap jam penundaan antibiotik menaikkan kematian secara bermakna. Yang benar di FKTP: pasang jalur infus, berikan ceftriaxone dosis pertama segera, turunkan demam dengan parasetamol, oksigen bila perlu, pantau ketat kesadaran dan tanda vital selama perjalanan, rujuk sebagai kegawatan, dan jangan lupa kewajiban kesehatan masyarakatnya — laporkan serta atur obat pencegahan untuk kontak erat di kos.',
    panduanResmi: `${PPK_FLOOR} Meningitis adalah kompetensi SKDI 3B: dokter FKTP menegakkan dugaan, memberi antibiotik parenteral dosis awal tanpa menunggu pungsi lumbal, menstabilkan, lalu merujuk. WHO Guidelines on Meningitis 2025 menegaskan antimikroba empiris harus dimulai sedini mungkin dan pemeriksaan diagnostik tidak boleh menunda terapi. Ruam non-blanching/dugaan meningokokus juga memicu pelaporan, penelusuran kontak erat, dan kemoprofilaksis sesuai program.`,
    catatanRealita: 'Skenario mengandaikan ceftriaxone injeksi ada di lemari, infus terpasang, dan ambulans berangkat. Kenyataannya sebagian Puskesmas tidak menyimpan ceftriaxone injeksi, dan sebagian dokter ragu memberi antibiotik dosis pertama karena khawatir "merusak hasil pemeriksaan di rumah sakit" atau disalahkan bila diagnosisnya meleset —',
    mutiaraEbm: 'Trias klasik demam, kaku kuduk, dan penurunan kesadaran lengkap hanya pada sekitar separuh penderita meningitis bakterial — sehingga menunggu ketiganya muncul berarti melewatkan separuh pasien. Yang lebih menjebak: Kernig dan Brudzinski, dua tanda yang paling percaya diri diajarkan, ternyata sensitivitasnya rendah (sekitar 5% pada beberapa penelitian) sehingga hasil NEGATIF sama sekali tidak menyingkirkan meningitis; keduanya berguna bila positif dan tidak berarti apa-apa bila negatif. Pasien ini kebetulan menunjukkan tanda yang lengkap — pasien berikutnya mungkin hanya datang dengan demam, sakit kepala, dan terasa "tidak seperti biasanya", dan justru pasien itulah yang paling sering pulang membawa parasetamol. Perangkap ketiga khas Indonesia: demam tinggi dengan sakit kepala hebat pada dewasa muda hampir selalu dibaca sebagai tifus atau demam berdarah lebih dulu, dan sudut pandang itu bertahan bahkan setelah leher kaku ditemukan.',
    konsekuensi: {
      narasi: 'Antibiotik ditahan agar "tidak mengaburkan pemeriksaan cairan otak di rumah sakit", dan pasien diberangkatkan hanya dengan penurun panas. Perjalanan memakan tiga jam, dan kuman terus berkembang biak di dalam selaput otak tanpa perlawanan.',
      kembaliHariMin: 1,
      kembaliHariMax: 2,
      kondisiKembali: 'Tiba di rumah sakit dalam keadaan tidak sadar, tekanan darah jatuh, dan bercak perdarahan sudah menyatu memenuhi kedua tungkai. Dirawat di ICU sebagai syok berat dengan pembekuan darah yang kacau. Bertahan hidup setelah dua minggu perawatan, dengan tuli menetap pada kedua telinga dan ujung jari kaki yang harus diamputasi karena mati jaringan.',
      guideline: 'PPK FKTP KMK 1186/2022; WHO Guidelines on Meningitis 2025; ESCMID Guideline — Diagnosis and Treatment of Acute Bacterial Meningitis',
    },
  }),
]

export const LAB_BATCH_4_MTS_ARCHETYPE_SPECS: Record<string, LabArchetypeSpec> = {
  lab_katarak_matur: { conceptId: 'concept:mature_cataract', credits: ['clinical:lab_katarak_matur'] },
  lab_ablasio_retina: { conceptId: 'concept:retinal_detachment', credits: ['clinical:lab_ablasio_retina'] },
  lab_retinopati_diabetik_proliferatif: { conceptId: 'concept:proliferative_diabetic_retinopathy', credits: ['clinical:lab_retinopati_diabetik_proliferatif'] },
  lab_otitis_media_supuratif_kronik_komplikata: { conceptId: 'concept:csom_complicated', credits: ['clinical:lab_otitis_media_supuratif_kronik_komplikata'] },
  lab_mastoiditis_akut: { conceptId: 'concept:acute_mastoiditis', credits: ['clinical:lab_mastoiditis_akut'] },
  lab_benda_asing_esofagus: { conceptId: 'concept:esophageal_foreign_body', credits: ['clinical:lab_benda_asing_esofagus'] },
  lab_tia_serangan_iskemik_sesaat: { conceptId: 'concept:transient_ischemic_attack', credits: ['clinical:lab_tia_serangan_iskemik_sesaat'] },
  lab_meningitis_bakterial_suspek: { conceptId: 'concept:suspected_bacterial_meningitis', credits: ['clinical:lab_meningitis_bakterial_suspek'] },
}
