import type { KasusKlinis } from '../types'
import { buatKasusLab } from './labCaseFactory'

export interface LabArchetypeSpec {
  conceptId: string
  credits: string[]
}

const PPK_FLOOR = 'PPK Dokter FKTP KMK 1186/2022 menjadi floor; terapi disesuaikan dengan pedoman yang lebih baru bila relevan.'

export const LAB_BATCH_1_CASES: KasusKlinis[] = [
  buatKasusLab({
    id: 'lab_pneumonia_komunitas_dewasa',
    nama: 'Pneumonia Komunitas Dewasa - Rawat Jalan',
    icd10: 'J18.9',
    skdi: '4A',
    kategori: 'respirasi',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Saya batuk, demam, dan kalau tarik napas dada kanan terasa sakit, Dok.',
    demografi: { usiaMin: 20, usiaMax: 55 },
    vital: { td: '118/76', nadi: 98, rr: 24, suhu: 38.2, spo2: 96 },
    pembuka: {
      tanya: 'Boleh ceritakan batuk dan keluhan yang paling mengganggu?',
      jawab: 'Batuk berdahak kuning sejak tiga hari, demam, dan dada kanan sakit saat menarik napas.',
      oldcarts: ['onset', 'karakter', 'lokasi', 'penyerta'],
    },
    pertanyaan: [
      { id: 'q_sesak', kategori: 'rps', tanya: 'Apakah napas terasa sesak atau makin cepat?', jawab: 'Sedikit lebih pendek kalau berjalan, tetapi saya masih bisa bicara dan makan biasa.', esensial: true, oldcarts: ['keparahan', 'agravasi'] },
      { id: 'q_berat', kategori: 'rps', tanya: 'Ada bingung, pingsan, muntah terus, atau bibir kebiruan?', jawab: 'Tidak ada, Dok.', esensial: true, oldcarts: ['penyerta'] },
      { id: 'q_tb', kategori: 'rps', tanya: 'Batuk lebih dari dua minggu, berat badan turun, keringat malam, atau kontak TB?', jawab: 'Tidak. Baru tiga hari dan berat badan tetap.', esensial: true },
      { id: 'q_komorbid', kategori: 'rpd', tanya: 'Ada penyakit paru, jantung, ginjal, diabetes, atau antibiotik tiga bulan terakhir?', jawab: 'Tidak ada dan belum minum antibiotik.', esensial: true },
      { id: 'q_rokok', kategori: 'sosial', tanya: 'Apakah merokok?', jawab: 'Kadang satu dua batang saat berkumpul, tidak setiap hari.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Sadar penuh, tampak sakit sedang, masih dapat berbicara kalimat penuh.', relevan: true },
      { region: 'toraks_paru', temuan: 'Gerak dada simetris; ronki halus dan suara napas bronkial fokal basal kanan.', relevan: true },
      { region: 'jantung', temuan: 'S1/S2 reguler, perfusi perifer baik.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Leukosit 13.200/uL, neutrofil dominan.', flag: 'tinggi', relevan: true },
    ],
    diagnosisBanding: ['J18.9', 'J20.9', 'A15.0'],
    tatalaksana: {
      obatBenar: ['amoxicillin_500', 'paracetamol_500'],
      obatSalahUmum: [
        { id: 'ciprofloxacin_500', alasan: 'Bukan fluorokuinolon respirasi dan bukan terapi empiris rutin pneumonia komunitas rawat jalan.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['kepatuhan_obat', 'etika_batuk', 'tanda_bahaya'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Pneumonia komunitas rawat jalan: gejala akut plus temuan paru fokal, tanpa instabilitas atau komorbid. Permenkes 28/2021 memuat amoksisilin oral 500 mg tiap 8 jam selama 5-7 hari; nilai derajat berat dan evaluasi 48-72 jam.',
    panduanResmi: 'PNPK Pneumonia Dewasa KMK 2147/2023 mewajibkan penilaian derajat berat; PPK FKTP membolehkan rawat jalan bila klinis baik dan tidak ada indikasi rawat.',
    catatanRealita: 'Rontgen memperkuat diagnosis PNPK tetapi tidak diasumsikan tersedia di Puskesmas Sukamaju; vignette rawat jalan ini memakai sindrom klinis jelas dan memberi instruksi kembali bila memburuk.',
    konsekuensi: {
      narasi: 'Keterlambatan antibiotik yang tepat atau kegagalan mengenali perburukan dapat berakhir pada hipoksemia dan rawat inap.',
      kembaliHariMin: 2,
      kembaliHariMax: 3,
      kondisiKembali: 'Sesak memberat, demam menetap, dan saturasi turun.',
      guideline: 'KMK 2147/2023 PNPK Pneumonia Dewasa; Permenkes 28/2021 Penggunaan Antibiotik.',
    },
  }),

  buatKasusLab({
    id: 'lab_influenza_tanpa_komplikasi',
    nama: 'Influenza Tanpa Komplikasi',
    icd10: 'J11',
    skdi: '4A',
    kategori: 'respirasi',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'tinggi',
    keluhanUtama: 'Sejak kemarin badan mendadak pegal semua, demam, pilek, dan batuk kering.',
    demografi: { usiaMin: 18, usiaMax: 50 },
    vital: { td: '116/74', nadi: 94, rr: 18, suhu: 38.1, spo2: 98 },
    pembuka: {
      tanya: 'Keluhannya mulai bagaimana?',
      jawab: 'Mendadak sejak kemarin: demam, menggigil, kepala berat, badan pegal, pilek, dan batuk kering.',
      oldcarts: ['onset', 'karakter', 'penyerta'],
    },
    pertanyaan: [
      { id: 'q_napas', kategori: 'rps', tanya: 'Ada sesak, nyeri dada, atau bibir kebiruan?', jawab: 'Tidak ada, Dok.', esensial: true },
      { id: 'q_risiko', kategori: 'rpd', tanya: 'Punya penyakit kronis atau daya tahan tubuh lemah?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_hamil', kategori: 'rpd', tanya: 'Apakah sedang hamil?', jawab: 'Tidak.', hanyaUntuk: 'P' },
      { id: 'q_kontak', kategori: 'sosial', tanya: 'Ada orang sekitar dengan keluhan serupa?', jawab: 'Tiga rekan kerja juga mendadak demam dan batuk minggu ini.', esensial: true },
      { id: 'q_lama', kategori: 'rps', tanya: 'Demamnya sudah berapa lama dan apakah terus memburuk?', jawab: 'Baru satu hari dan masih bisa makan serta minum.', oldcarts: ['durasi', 'keparahan'] },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Tampak lelah tetapi tidak toksik dan hidrasi baik.', relevan: true },
      { region: 'tht_mulut', temuan: 'Mukosa hidung hiperemis, sekret jernih; faring hiperemis ringan.', relevan: true },
      { region: 'toraks_paru', temuan: 'Suara napas vesikuler, ronki dan wheezing tidak ada.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['J11', 'J00', 'J18.9'],
    tatalaksana: {
      obatBenar: ['paracetamol_500'],
      obatOpsional: ['ctm_4'],
      obatSalahUmum: [
        { id: 'amoxicillin_500', alasan: 'Influenza tanpa komplikasi adalah infeksi virus; antibiotik tidak mengobati penyebabnya.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['istirahat_cukup', 'etika_batuk', 'cuci_tangan', 'tanda_bahaya'],
    },
    clue: 'Onset mendadak demam, mialgia, sakit kepala, dan batuk kering lebih mendukung influenza daripada common cold. Kasus sehat tanpa red flag ditangani suportif; antibiotik tidak rutin.',
    panduanResmi: `${PPK_FLOOR} PPK menyebut influenza umumnya self-limited, dengan terapi simptomatik dan rujuk bila muncul tanda pneumonia.`,
  }),

  buatKasusLab({
    id: 'lab_pertusis_remaja',
    nama: 'Pertusis pada Remaja',
    icd10: 'A37',
    skdi: '4A',
    kategori: 'respirasi',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'rendah',
    keluhanUtama: 'Batuk saya sudah hampir dua minggu, sekali mulai susah berhenti sampai muntah.',
    demografi: { usiaMin: 12, usiaMax: 18 },
    vital: { td: '110/70', nadi: 88, rr: 20, suhu: 37.2, spo2: 98 },
    pembuka: {
      tanya: 'Batuknya seperti apa dan sudah berapa lama?',
      jawab: 'Sudah dua belas hari. Batuk datang bergerombol panjang sampai sulit menarik napas dan kadang muntah.',
      oldcarts: ['durasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      { id: 'q_whoop', kategori: 'rps', tanya: 'Setelah rentetan batuk, ada tarikan napas panjang berbunyi atau muntah?', jawab: 'Iya, habis batuk saya menarik napas bunyi tinggi lalu kadang muntah.', esensial: true },
      { id: 'q_demam', kategori: 'rps', tanya: 'Ada demam tinggi atau sesak menetap di antara serangan?', jawab: 'Tidak. Di antara serangan napas biasa.', esensial: true },
      { id: 'q_kontak', kategori: 'sosial', tanya: 'Ada kontak dengan bayi atau orang yang batuk lama?', jawab: 'Sepupu saya yang masih bayi sering saya gendong; kakak juga batuk lama.', esensial: true },
      { id: 'q_imunisasi', kategori: 'rpd', tanya: 'Imunisasi pertusis dan penguat saat sekolah lengkap?', jawab: 'Orang tua bilang imunisasi bayi lengkap, tetapi saya tidak ingat suntikan penguat.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Kondisi baik di antara paroksisme; saat diperiksa muncul rentetan batuk dengan inspiratory whoop.', relevan: true },
      { region: 'toraks_paru', temuan: 'Vesikuler bilateral, tanpa ronki fokal atau retraksi.', relevan: true },
      { region: 'kepala_leher', temuan: 'Petekie kecil periorbital setelah batuk kuat.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['A37', 'J20.9', 'J18.9'],
    tatalaksana: {
      obatBenar: ['azitromisin_500'],
      obatSalahUmum: [
        { id: 'amoxicillin_500', alasan: 'Amoksisilin bukan terapi eradikasi Bordetella pertussis; gunakan makrolida sesuai usia dan risiko.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['cegah_pertusis', 'etika_batuk', 'kepatuhan_obat', 'tanda_bahaya'],
      edukasiKritis: ['cegah_pertusis'],
    },
    clue: 'Paroksisme batuk, inspiratory whoop, dan muntah pascabatuk sangat khas pertusis. CDC 2025 merekomendasikan makrolida; terapi dini mengurangi keparahan dan terapi dalam tiga minggu pada usia >=1 tahun membatasi penularan.',
    catatanRealita: 'Koordinasikan surveilans dan profilaksis kontak berisiko tinggi melalui program setempat; jangan menyamakan resep pasien indeks dengan keputusan profilaksis semua kontak.',
  }),

  buatKasusLab({
    id: 'lab_laringitis_akut',
    nama: 'Laringitis Akut',
    icd10: 'J04.0',
    skdi: '4A',
    kategori: 'respirasi',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Suara saya mendadak serak setelah pilek, tenggorokan juga terasa kering.',
    demografi: { usiaMin: 18, usiaMax: 60 },
    vital: { td: '122/78', nadi: 80, rr: 18, suhu: 37.3, spo2: 99 },
    pembuka: {
      tanya: 'Apa perubahan suara dan keluhan tenggorokannya?',
      jawab: 'Suara serak sejak dua hari setelah pilek dan banyak berbicara; tenggorokan kering dan batuk ringan.',
      oldcarts: ['onset', 'durasi', 'karakter'],
    },
    pertanyaan: [
      { id: 'q_jalan_napas', kategori: 'rps', tanya: 'Ada sulit bernapas, bunyi napas kasar, atau sulit menelan ludah?', jawab: 'Tidak ada, Dok.', esensial: true },
      { id: 'q_lama', kategori: 'rps', tanya: 'Seraknya pernah menetap lebih dari dua minggu atau disertai batuk darah?', jawab: 'Tidak pernah dan tidak ada darah.', esensial: true },
      { id: 'q_suara', kategori: 'sosial', tanya: 'Apakah pekerjaan menuntut banyak bicara atau bernyanyi?', jawab: 'Saya mengajar dan kemarin berbicara keras seharian.', esensial: true },
      { id: 'q_rokok', kategori: 'sosial', tanya: 'Apakah merokok atau sering terpapar asap?', jawab: 'Tidak merokok, tetapi suami merokok di teras.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Suara serak, tidak stridor, tidak sesak, tidak toksik.', relevan: true },
      { region: 'tht_mulut', temuan: 'Faring hiperemis ringan; tidak ada edema epiglotis yang terlihat atau drooling.', relevan: true },
      { region: 'toraks_paru', temuan: 'Vesikuler, tanpa ronki atau wheezing.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['J04.0', 'J02.9', 'J38.7'],
    tatalaksana: {
      obatBenar: ['paracetamol_500'],
      obatSalahUmum: [
        { id: 'amoxicillin_500', alasan: 'Laringitis akut tanpa bukti infeksi bakteri atau pneumonia umumnya viral dan tidak memerlukan antibiotik.', bahaya: 'nonPrimer' },
        { id: 'dexamethasone_05', alasan: 'Kortikosteroid sistemik tidak rutin untuk laringitis ringan tanpa sumbatan jalan napas.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['istirahat_suara', 'berhenti_merokok', 'tanda_bahaya'],
    },
    clue: 'Serak akut setelah ISPA atau penggunaan suara berlebih tanpa stridor ditangani dengan istirahat suara, hidrasi, dan analgesik bila perlu. Antibiotik dan steroid tidak rutin pada penyakit ringan.',
    panduanResmi: `${PPK_FLOOR} Rujuk bila ada sumbatan jalan napas atas, toksisitas, sianosis, kelelahan, usia <3 tahun, atau kecurigaan tumor.`,
  }),

  buatKasusLab({
    id: 'lab_mabuk_perjalanan',
    nama: 'Mabuk Perjalanan',
    icd10: 'T75.3',
    skdi: '4A',
    kategori: 'tht',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Setiap naik bus berkelok saya pusing, mual, dan keringat dingin.',
    demografi: { usiaMin: 12, usiaMax: 55 },
    vital: { td: '114/72', nadi: 76, rr: 17, suhu: 36.6, spo2: 99 },
    pembuka: {
      tanya: 'Pusing dan mualnya muncul pada situasi apa?',
      jawab: 'Hanya saat kendaraan bergerak, terutama jalan berkelok; reda setelah turun dan duduk sebentar.',
      oldcarts: ['agravasi', 'waktu', 'durasi'],
    },
    pertanyaan: [
      { id: 'q_neuro', kategori: 'rps', tanya: 'Ada kelemahan satu sisi, bicara pelo, pingsan, atau sakit kepala hebat?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_telinga', kategori: 'rps', tanya: 'Ada telinga berdenging, pendengaran turun, atau pusing saat berbalik di tempat tidur?', jawab: 'Tidak. Kalau tidak naik kendaraan saya baik-baik saja.', esensial: true },
      { id: 'q_hamil', kategori: 'rpd', tanya: 'Apakah sedang hamil atau punya glaukoma dan gangguan berkemih?', jawab: 'Tidak ada.', hanyaUntuk: 'P' },
      { id: 'q_sopir', kategori: 'sosial', tanya: 'Apakah Anda akan mengemudi setelah minum obat?', jawab: 'Tidak, saya penumpang.', esensial: true },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Kondisi umum baik, berjalan stabil.', relevan: true },
      { region: 'neurologis', temuan: 'Saraf kranialis, kekuatan, koordinasi, dan gaya berjalan normal.', relevan: true },
      { region: 'tht_mulut', temuan: 'Otoskopi dalam batas normal.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['T75.3', 'H81.1', 'H81.2'],
    tatalaksana: {
      obatBenar: ['dimenhidrinat_50'],
      edukasi: ['cegah_mabuk_perjalanan', 'tanda_bahaya'],
    },
    clue: 'Hubungan ketat dengan gerak kendaraan dan resolusi setelah gerak berhenti mendukung mabuk perjalanan. Dimenhidrinat dapat diberikan sebelum perjalanan, tetapi sedasi membuat pasien tidak boleh mengemudi atau mengoperasikan mesin.',
    catatanRealita: 'Dimenhidrinat 50 mg tercantum dalam Fornas 1199/2025; pencantuman tidak membuktikan stok lokal pada hari kunjungan.',
  }),

  buatKasusLab({
    id: 'lab_furunkel_hidung',
    nama: 'Furunkel pada Hidung',
    icd10: 'J34.0',
    skdi: '4A',
    kategori: 'tht',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Lubang hidung kanan nyeri dan ada benjolan seperti bisul sejak tiga hari.',
    demografi: { usiaMin: 15, usiaMax: 55 },
    vital: { td: '120/78', nadi: 82, rr: 18, suhu: 37.3, spo2: 99 },
    pembuka: {
      tanya: 'Benjolannya mulai kapan dan bagaimana rasanya?',
      jawab: 'Tiga hari lalu mulai perih di dekat bulu hidung, lalu jadi benjolan kecil sangat nyeri.',
      oldcarts: ['onset', 'lokasi', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      { id: 'q_menyebar', kategori: 'rps', tanya: 'Bengkak menyebar ke pipi atau sekitar mata, demam tinggi, atau penglihatan terganggu?', jawab: 'Tidak. Hanya di tepi lubang hidung.', esensial: true },
      { id: 'q_manipulasi', kategori: 'rps', tanya: 'Pernah dipencet, ditusuk, atau dicabut bulu hidungnya?', jawab: 'Sering mencabut bulu hidung; benjolan ini belum saya pencet.', esensial: true },
      { id: 'q_dm', kategori: 'rpd', tanya: 'Ada diabetes, daya tahan tubuh lemah, atau bisul berulang?', jawab: 'Tidak ada.' },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Nodul pustular 5 mm pada vestibulum nasi kanan, eritema lokal, belum fluktuatif.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada selulitis wajah, edema periorbita, atau nyeri sinus.', relevan: true },
      { region: 'umum', temuan: 'Tidak toksik.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['J34.0', 'L01.0', 'J34.89'],
    tatalaksana: {
      obatBenar: ['mupirosin_krim'],
      obatOpsional: ['paracetamol_500'],
      tindakanSalahUmum: [
        { id: 'insisi_abses', alasan: 'Lesi kecil belum fluktuatif di segitiga wajah tidak boleh diinsisi atau dipencet secara serampangan.', bahaya: 'berbahaya' },
      ],
      edukasi: ['jangan_pencet_furunkel_hidung', 'kebersihan_kulit', 'tanda_bahaya'],
      edukasiKritis: ['jangan_pencet_furunkel_hidung'],
    },
    clue: 'Furunkel vestibulum nasi: nyeri fokal dan pustul di folikel. Kompres hangat dan terapi topikal pada lesi lokal; jangan dipencet karena risiko penyebaran infeksi pada segitiga wajah. Rujuk bila selulitis menyebar atau komplikasi orbita/neurologis.',
    panduanResmi: `${PPK_FLOOR} PPK melarang pasien memencet atau menginsisi sendiri dan memasukkan terapi antimikroba serta kompres hangat.`,
  }),

  buatKasusLab({
    id: 'lab_rinitis_vasomotor',
    nama: 'Rinitis Vasomotor',
    icd10: 'J30.0',
    skdi: '4A',
    kategori: 'tht',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Hidung saya sering mampet dan berair kalau kena asap atau udara dingin, tapi tidak gatal.',
    demografi: { usiaMin: 20, usiaMax: 65 },
    vital: { td: '126/80', nadi: 78, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: {
      tanya: 'Kapan hidung mampet atau berair dan apa pemicunya?',
      jawab: 'Muncul saat kena asap, parfum tajam, atau pindah ke ruangan dingin; cairannya bening dan saya tidak demam.',
      oldcarts: ['agravasi', 'karakter', 'waktu'],
    },
    pertanyaan: [
      { id: 'q_gatal', kategori: 'rps', tanya: 'Hidung atau mata terasa gatal dan bersin beruntun?', jawab: 'Tidak gatal. Bersin paling satu dua kali.', esensial: true },
      { id: 'q_infeksi', kategori: 'rps', tanya: 'Ada nyeri wajah, demam, atau ingus kental bernanah?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_obat', kategori: 'rpd', tanya: 'Sering memakai semprot pelega hidung lebih dari beberapa hari?', jawab: 'Tidak pernah.', esensial: true },
      { id: 'q_iritan', kategori: 'sosial', tanya: 'Paparan asap rokok atau bahan berbau tajam sering?', jawab: 'Saya bekerja dekat dapur dan asap sering masuk.' },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Mukosa hidung kemerahan ringan, konka membesar, sekret jernih; tidak pucat kebiruan.', relevan: true },
      { region: 'mata', temuan: 'Tidak ada konjungtivitis alergi.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada nyeri tekan sinus.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['J30.0', 'J30.4', 'J00'],
    tatalaksana: {
      obatBenar: ['flutikason_semprot_hidung'],
      obatSalahUmum: [
        { id: 'amoxicillin_500', alasan: 'Tidak ada tanda infeksi bakteri; antibiotik tidak menangani hiperreaktivitas nonalergik.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['hindari_iritan_hidung', 'bilas_salin_hidung', 'tanda_bahaya'],
    },
    clue: 'Rinorea jernih dan kongesti dipicu iritan atau perubahan suhu tanpa gatal dominan mendukung rinitis vasomotor. Hindari pemicu, bilas salin, dan kortikosteroid intranasal dapat dipakai untuk gejala menetap.',
    panduanResmi: `${PPK_FLOOR} PPK mencantumkan kortikosteroid intranasal dan penghindaran iritan; tindakan operatif menjadi alasan rujukan.`,
    catatanRealita: 'Flutikason intranasal dipakai sebagai EBM yang lebih praktis, tetapi tidak ditandai sebagai item Fornas FKTP pada katalog lab; bila tidak tersedia, jangan menggantinya dengan antibiotik atau dekongestan berkepanjangan.',
  }),

  buatKasusLab({
    id: 'lab_stomatitis_aftosa',
    nama: 'Stomatitis Aftosa Rekuren',
    icd10: 'K12',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'tinggi',
    keluhanUtama: 'Ada sariawan nyeri di bibir bagian dalam sejak empat hari.',
    demografi: { usiaMin: 14, usiaMax: 50 },
    vital: { td: '118/76', nadi: 76, rr: 17, suhu: 36.7, spo2: 99 },
    pembuka: {
      tanya: 'Lukanya di mana, berapa banyak, dan sejak kapan?',
      jawab: 'Satu luka bulat kecil di bibir bawah bagian dalam sejak empat hari, nyeri kalau kena makanan asam.',
      oldcarts: ['lokasi', 'durasi', 'karakter', 'agravasi'],
    },
    pertanyaan: [
      { id: 'q_sistemik', kategori: 'rps', tanya: 'Ada demam, berat badan turun, diare lama, luka genital, atau mata merah?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_lama', kategori: 'rps', tanya: 'Pernah ada luka yang tidak sembuh lebih dari dua minggu atau makin besar?', jawab: 'Biasanya sembuh sendiri dalam seminggu.', esensial: true },
      { id: 'q_trauma', kategori: 'rps', tanya: 'Ada tergigit, kawat gigi tajam, atau makanan keras sebelum luka muncul?', jawab: 'Sering tergigit di tempat yang sama saat makan.', esensial: true },
      { id: 'q_obat', kategori: 'rpd', tanya: 'Sedang minum obat baru atau punya penyakit daya tahan tubuh?', jawab: 'Tidak.' },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Ulkus tunggal bulat 4 mm, dasar putih-kekuningan dengan halo eritema pada mukosa labial nonkeratinisasi.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada limfadenopati atau pembesaran kelenjar.', relevan: true },
      { region: 'kulit', temuan: 'Tidak ada lesi kulit atau genital yang menyertai.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['K12', 'B00.2', 'C06.9'],
    tatalaksana: {
      obatBenar: ['triamcinolone_orabase'],
      obatOpsional: ['paracetamol_500'],
      edukasi: ['higiene_mulut', 'gizi_seimbang', 'tanda_bahaya'],
    },
    clue: 'Aftosa minor berupa ulkus nyeri dangkal pada mukosa nonkeratinisasi tanpa gejala sistemik. Kortikosteroid topikal oral dapat memperpendek gejala; evaluasi bila menetap >2 minggu, sangat berat, atau disertai tanda sistemik.',
    panduanResmi: `${PPK_FLOOR} PPK menyebut triamsinolon asetonid 0,1% orabase dan higiene mulut untuk aftosa.`,
    catatanRealita: 'Sediaan orabase tidak dianggap stok rutin Puskesmas Sukamaju. Bila tidak ada, gunakan perawatan suportif dan hilangkan trauma; jangan memberi antibiotik sistemik.',
  }),

  buatKasusLab({
    id: 'lab_kandidiasis_mulut',
    nama: 'Kandidiasis Mulut',
    icd10: 'B37.9',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Mulut terasa perih dan ada lapisan putih yang bisa terkelupas.',
    demografi: { usiaMin: 25, usiaMax: 70 },
    vital: { td: '124/78', nadi: 82, rr: 18, suhu: 36.8, spo2: 99 },
    pembuka: {
      tanya: 'Lapisan putihnya sejak kapan dan apakah bisa dibersihkan?',
      jawab: 'Sudah lima hari. Kalau diseka sebagian terangkat, tetapi bagian bawahnya merah dan perih.',
      oldcarts: ['onset', 'karakter', 'durasi'],
    },
    pertanyaan: [
      { id: 'q_pemicu', kategori: 'rpd', tanya: 'Baru minum antibiotik, memakai steroid inhalasi, atau memakai gigi palsu?', jawab: 'Baru selesai antibiotik seminggu dan sering lupa berkumur setelah inhaler.', esensial: true },
      { id: 'q_dm', kategori: 'rpd', tanya: 'Ada diabetes, penurunan berat badan, infeksi berulang, atau risiko gangguan imunitas?', jawab: 'Gula darah pernah tinggi tetapi belum kontrol lagi.', esensial: true },
      { id: 'q_telan', kategori: 'rps', tanya: 'Ada nyeri atau sulit menelan sampai dada?', jawab: 'Tidak, hanya mulut perih.', esensial: true },
      { id: 'q_higiene', kategori: 'sosial', tanya: 'Bagaimana kebersihan mulut dan perawatan gigi palsu?', jawab: 'Saya jarang membersihkan lidah dan gigi palsu dipakai saat tidur.' },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Plak putih krem pada lidah dan mukosa bukal dapat dikerok, meninggalkan dasar eritematosa.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada limfadenopati atau pembengkakan leher.', relevan: false },
      { region: 'umum', temuan: 'Tidak tampak wasting atau dehidrasi.', relevan: true },
    ],
    lab: [
      { id: 'gds', hasil: 'GDS 218 mg/dL; perlu evaluasi diabetes terpisah.', flag: 'tinggi', relevan: true },
      { id: 'mikroskopis_gram_koh', hasil: 'Budding yeast dan pseudohifa tampak.', flag: 'abnormal', relevan: false },
    ],
    diagnosisBanding: ['B37.9', 'K12', 'D37.0'],
    tatalaksana: {
      obatBenar: ['nistatin_suspensi'],
      edukasi: ['higiene_mulut', 'kontrol_rutin', 'tanda_bahaya'],
    },
    clue: 'Plak putih yang dapat dikerok dan meninggalkan dasar merah mendukung kandidiasis pseudomembran. Beri nistatin lokal, koreksi pencetus, dan cari diabetes atau imunosupresi bila berulang.',
    panduanResmi: `${PPK_FLOOR} PPK mencantumkan nistatin suspensi 100.000-200.000 IU/mL dan kontrol faktor predisposisi.`,
    catatanRealita: 'Nistatin suspensi tercantum di Fornas 1199/2025. Pencantuman tidak membuktikan stok; bila tidak tersedia, rujuk jejaring formularium tanpa improvisasi antijamur yang tidak sesuai.',
  }),

  buatKasusLab({
    id: 'lab_parotitis_mumps',
    nama: 'Parotitis Epidemika (Mumps)',
    icd10: 'B26',
    skdi: '4A',
    kategori: 'infeksi',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'rendah',
    keluhanUtama: 'Pipi dekat telinga kiri bengkak dan sakit saat mengunyah.',
    demografi: { usiaMin: 7, usiaMax: 30 },
    vital: { td: '108/68', nadi: 86, rr: 18, suhu: 37.8, spo2: 99 },
    pembuka: {
      tanya: 'Bengkaknya mulai dari mana dan apa yang membuatnya sakit?',
      jawab: 'Mulai dua hari lalu di depan telinga kiri, sakit saat mengunyah atau makan asam.',
      oldcarts: ['onset', 'lokasi', 'agravasi', 'durasi'],
    },
    pertanyaan: [
      { id: 'q_komplikasi', kategori: 'rps', tanya: 'Ada sakit kepala berat, kaku kuduk, atau nyeri perut hebat?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_orchitis', kategori: 'rps', tanya: 'Ada nyeri atau bengkak pada testis?', jawab: 'Tidak ada.', esensial: true, hanyaUntuk: 'L' },
      { id: 'q_nanah', kategori: 'rps', tanya: 'Ada rasa nanah di mulut atau demam tinggi menggigil?', jawab: 'Tidak.', esensial: true },
      { id: 'q_kontak', kategori: 'sosial', tanya: 'Ada teman atau keluarga dengan bengkak serupa?', jawab: 'Teman satu kelas tidak masuk karena pipinya juga bengkak.', esensial: true },
      { id: 'q_imunisasi', kategori: 'rpd', tanya: 'Apakah pernah mendapat imunisasi MMR?', jawab: 'Orang tua tidak yakin pernah mendapat MMR.' },
    ],
    pemeriksaanFisik: [
      { region: 'kepala_leher', temuan: 'Pembengkakan parotis kiri, sudut mandibula menghilang; kulit tidak merah menyala.', relevan: true },
      { region: 'tht_mulut', temuan: 'Muara duktus Stensen edema tanpa pus.', relevan: true },
      { region: 'neurologis', temuan: 'Tidak ada kaku kuduk atau defisit neurologis.', relevan: false },
    ],
    lab: [],
    diagnosisBanding: ['B26', 'K11.2', 'L04.0'],
    tatalaksana: {
      obatBenar: ['paracetamol_sirup'],
      obatSalahUmum: [
        { id: 'amoxicillin_500', alasan: 'Tidak ada tanda parotitis bakterial; mumps adalah infeksi virus.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['cuci_tangan', 'istirahat_cukup', 'tanda_bahaya'],
    },
    clue: 'Parotitis dengan pajanan klaster, muara Stensen tanpa pus, dan tanpa toksisitas mendukung mumps. Tata laksana suportif; batasi kontak dekat selama periode menular dan cek status imunisasi kontak.',
    panduanResmi: `${PPK_FLOOR} PPK menempatkan parotitis mumps sebagai terapi suportif dan merujuk bila ada komplikasi atau penyakit sistemik.`,
  }),

  buatKasusLab({
    id: 'lab_intoleransi_makanan_laktosa',
    nama: 'Intoleransi Makanan - Dugaan Laktosa',
    icd10: 'K90.4',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Perut selalu kembung dan mulas setelah minum susu, tapi tidak pernah sesak atau biduran.',
    demografi: { usiaMin: 12, usiaMax: 55 },
    vital: { td: '116/74', nadi: 76, rr: 17, suhu: 36.6, spo2: 99 },
    pembuka: {
      tanya: 'Apa hubungan keluhan perut dengan makanan tertentu?',
      jawab: 'Sekitar satu jam setelah minum susu saya kembung, banyak kentut, mulas, lalu BAB encer; tanpa susu saya baik.',
      oldcarts: ['waktu', 'agravasi', 'karakter'],
    },
    pertanyaan: [
      { id: 'q_alergi', kategori: 'rps', tanya: 'Pernah muncul biduran, bibir bengkak, mengi, pingsan, atau muntah mendadak?', jawab: 'Tidak pernah.', esensial: true },
      { id: 'q_redflag', kategori: 'rps', tanya: 'Ada darah di tinja, berat badan turun, demam, atau diare malam hari?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_produk', kategori: 'rps', tanya: 'Bagaimana bila makan yoghurt atau susu bebas laktosa?', jawab: 'Yoghurt sedikit masih aman; susu bebas laktosa tidak membuat mulas.', esensial: true },
      { id: 'q_keluarga', kategori: 'rpk', tanya: 'Ada keluarga dengan keluhan serupa?', jawab: 'Ayah juga tidak tahan susu biasa.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Status gizi baik, tidak pucat, tidak dehidrasi.', relevan: true },
      { region: 'abdomen', temuan: 'Abdomen lunak, bising usus normal, tanpa nyeri tekan atau massa.', relevan: true },
      { region: 'kulit', temuan: 'Tidak ada urtikaria atau angioedema.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['K90.4', 'L27.2', 'K58.0'],
    tatalaksana: {
      obatBenar: [],
      edukasi: ['eliminasi_makanan_terarah', 'gizi_seimbang', 'tanda_bahaya'],
    },
    clue: 'Gejala gastrointestinal yang konsisten setelah laktosa tanpa manifestasi imunologis mendukung intoleransi, bukan alergi. Lakukan eliminasi terbatas lalu reintroduksi terarah; pertahankan kecukupan kalsium dan nutrisi.',
    panduanResmi: `${PPK_FLOOR} PPK menyarankan pembatasan nutrisi terarah, suplementasi bila perlu, dan reintroduksi setelah gejala hilang untuk menguji hubungan kausal.`,
  }),

  buatKasusLab({
    id: 'lab_alergi_makanan_ringan',
    nama: 'Alergi Makanan Tanpa Anafilaksis',
    icd10: 'L27.2',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Setiap makan udang, kulit saya bentol gatal dalam beberapa menit.',
    demografi: { usiaMin: 15, usiaMax: 55 },
    vital: { td: '120/78', nadi: 82, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: {
      tanya: 'Apa yang terjadi setelah makan dan seberapa cepat munculnya?',
      jawab: 'Sekitar lima belas menit setelah makan udang muncul bentol gatal di lengan dan badan.',
      oldcarts: ['onset', 'agravasi', 'karakter'],
    },
    pertanyaan: [
      { id: 'q_anafilaksis', kategori: 'rps', tanya: 'Ada suara serak, sesak, mengi, bibir atau lidah bengkak, pusing, atau pingsan?', jawab: 'Tidak ada. Hanya bentol dan gatal.', esensial: true },
      { id: 'q_repro', kategori: 'rps', tanya: 'Apakah selalu berulang setelah makanan yang sama?', jawab: 'Sudah tiga kali setelah udang; makanan lain aman.', esensial: true },
      { id: 'q_obat', kategori: 'rpd', tanya: 'Pernah mengalami reaksi berat atau punya asma tidak terkontrol?', jawab: 'Tidak pernah reaksi berat dan tidak punya asma.', esensial: true },
      { id: 'q_label', kategori: 'sosial', tanya: 'Apakah terbiasa membaca label atau menanyakan bahan makanan?', jawab: 'Belum, saya sering tidak tahu ada campuran udang.' },
    ],
    pemeriksaanFisik: [
      { region: 'kulit', temuan: 'Beberapa wheal eritematosa yang memucat saat ditekan, tanpa angioedema.', relevan: true },
      { region: 'toraks_paru', temuan: 'Tidak ada wheezing atau stridor.', relevan: true },
      { region: 'umum', temuan: 'Perfusi baik, sadar penuh, tidak ada tanda syok.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['L27.2', 'L50.0', 'T78.2'],
    tatalaksana: {
      obatBenar: ['cetirizine_10'],
      edukasi: ['eliminasi_makanan_terarah', 'tanda_bahaya'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Reaksi kulit cepat dan berulang setelah makanan yang sama mendukung alergi makanan. Antihistamin cukup untuk urtikaria ringan, tetapi gejala jalan napas, sirkulasi, atau multisistem berarti anafilaksis dan memerlukan adrenalin serta penanganan gawat darurat.',
    panduanResmi: `${PPK_FLOOR} PPK menekankan penghindaran pemicu, label makanan, dan larangan uji provokasi sembarangan pada riwayat reaksi berat.`,
  }),

  buatKasusLab({
    id: 'lab_keracunan_makanan_ringan',
    nama: 'Keracunan Makanan Ringan',
    icd10: 'T62',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Sejak tadi malam muntah dan diare setelah makan nasi kotak bersama teman-teman.',
    demografi: { usiaMin: 16, usiaMax: 60 },
    vital: { td: '112/72', nadi: 92, rr: 18, suhu: 37.3, spo2: 99 },
    pembuka: {
      tanya: 'Apa yang dimakan dan kapan keluhan mulai?',
      jawab: 'Enam jam setelah nasi kotak saya mual, muntah dua kali, dan BAB cair empat kali; tiga teman juga sama.',
      oldcarts: ['onset', 'agravasi', 'durasi', 'penyerta'],
    },
    pertanyaan: [
      { id: 'q_dehidrasi', kategori: 'rps', tanya: 'Masih bisa minum dan berkemih? Ada sangat haus, lemas, atau pusing saat berdiri?', jawab: 'Masih bisa minum sedikit dan tadi pagi masih kencing.', esensial: true },
      { id: 'q_invasif', kategori: 'rps', tanya: 'Ada darah atau lendir pada tinja, demam tinggi, atau nyeri perut menetap?', jawab: 'Tidak ada darah, hanya mulas sebelum BAB.', esensial: true },
      { id: 'q_risiko', kategori: 'rpd', tanya: 'Punya gangguan ginjal atau daya tahan tubuh lemah?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_hamil', kategori: 'rpd', tanya: 'Apakah sedang hamil?', jawab: 'Tidak.', hanyaUntuk: 'P' },
      { id: 'q_makanan', kategori: 'sosial', tanya: 'Makanan disimpan lama pada suhu ruang?', jawab: 'Katanya nasi kotak sudah dibuat sejak pagi dan baru dimakan sore.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Sadar, mukosa sedikit kering, turgor masih baik.', relevan: true },
      { region: 'abdomen', temuan: 'Abdomen lunak, bising usus meningkat, tanpa defans atau nyeri tekan fokal.', relevan: true },
      { region: 'jantung', temuan: 'Nadi sedikit cepat, perfusi perifer baik.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['T62', 'A09', 'A03'],
    tatalaksana: {
      obatBenar: ['oralit'],
      obatOpsional: ['ondansetron_4'],
      obatSalahUmum: [
        { id: 'ciprofloxacin_500', alasan: 'Kasus ringan non-invasif pada orang sehat terutama memerlukan rehidrasi; antibiotik rutin tidak dianjurkan.', bahaya: 'nonPrimer' },
        { id: 'loperamid_2', alasan: 'Tidak menjadi terapi utama dan harus dihindari bila kemudian muncul demam tinggi atau tinja berdarah.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['cairan_oralit', 'cuci_tangan_makanan', 'tanda_bahaya'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Klaster gejala gastrointestinal beberapa jam setelah makanan yang sama mendukung penyakit bawaan makanan. Pada kasus ringan tanpa demam tinggi atau darah, fokus pada oralit dan pemantauan; antibiotik tidak rutin.',
    panduanResmi: `${PPK_FLOOR} PPK menempatkan rehidrasi sebagai tujuan utama dan merujuk bila memburuk atau tidak berhenti setelah tiga hari.`,
  }),

  buatKasusLab({
    id: 'lab_cacing_tambang',
    nama: 'Infeksi Cacing Tambang',
    icd10: 'B76.0',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'rendah',
    keluhanUtama: 'Saya cepat lelah dan pucat, perut kadang tidak enak sejak beberapa bulan.',
    demografi: { usiaMin: 12, usiaMax: 55 },
    vital: { td: '104/68', nadi: 94, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: {
      tanya: 'Keluhan lelahnya sejak kapan dan disertai apa?',
      jawab: 'Sekitar tiga bulan cepat capek, kadang pusing, dan perut mulas ringan.',
      oldcarts: ['durasi', 'karakter', 'penyerta'],
    },
    pertanyaan: [
      { id: 'q_tanah', kategori: 'sosial', tanya: 'Sering bekerja atau berjalan tanpa alas kaki di tanah lembap?', jawab: 'Saya bekerja di kebun dan sering tanpa alas kaki.', esensial: true },
      { id: 'q_perdarahan', kategori: 'rps', tanya: 'Ada muntah darah, BAB hitam pekat, atau perdarahan lain?', jawab: 'Tidak ada perdarahan yang terlihat.', esensial: true },
      { id: 'q_gizi', kategori: 'sosial', tanya: 'Bagaimana pola makan dan penggunaan jamban di rumah?', jawab: 'Makan seadanya dan jamban keluarga masih dekat kebun.', esensial: true },
      { id: 'q_reproduksi', kategori: 'rpd', tanya: 'Apakah sedang hamil atau haid sangat banyak?', jawab: 'Tidak.', hanyaUntuk: 'P' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Konjungtiva pucat, tidak ikterik, status gizi cukup.', relevan: true },
      { region: 'abdomen', temuan: 'Lunak, nyeri tekan ringan difus, tanpa organomegali.', relevan: true },
      { region: 'kulit', temuan: 'Bekas papul gatal pada telapak kaki, tanpa infeksi aktif.', relevan: true },
    ],
    lab: [
      { id: 'hb', hasil: 'Hb 9,8 g/dL, gambaran mikrositik hipokrom.', flag: 'rendah', relevan: true },
      { id: 'feses_rutin', hasil: 'Telur cacing tambang ditemukan.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['B76.0', 'D50.9', 'B77.9'],
    tatalaksana: {
      obatBenar: ['albendazol_400'],
      edukasi: ['cegah_cacing_tanah', 'gizi_seimbang', 'tanda_bahaya'],
    },
    konfirmasiWajib: 'feses_rutin',
    clue: 'Paparan tanah tanpa alas kaki, anemia mikrositik, dan telur cacing pada feses mendukung cacing tambang. WHO merekomendasikan albendazol 400 mg; evaluasi dan koreksi anemia sesuai derajat.',
    catatanRealita: 'Albendazol tercantum dalam Fornas dan juga digunakan program deworming; kasus individual tetap memerlukan penilaian kehamilan, anemia, dan diagnosis banding perdarahan.',
  }),

  buatKasusLab({
    id: 'lab_strongiloidiasis',
    nama: 'Strongiloidiasis Kronik',
    icd10: 'B78.9',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'rendah',
    keluhanUtama: 'Perut saya sering mulas dan kadang ada garis merah gatal yang cepat berpindah di kulit.',
    demografi: { usiaMin: 18, usiaMax: 65 },
    vital: { td: '118/76', nadi: 78, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: {
      tanya: 'Keluhan perut dan kulitnya berlangsung bagaimana?',
      jawab: 'Mulas dan diare datang-pergi berbulan-bulan; sesekali ada garis merah gatal di bokong yang bergeser cepat.',
      oldcarts: ['durasi', 'karakter', 'lokasi', 'waktu'],
    },
    pertanyaan: [
      { id: 'q_tanah', kategori: 'sosial', tanya: 'Pernah lama bekerja tanpa alas kaki di tanah lembap atau tinggal di daerah tropis pedesaan?', jawab: 'Sejak kecil saya berkebun tanpa alas kaki.', esensial: true },
      { id: 'q_steroid', kategori: 'rpd', tanya: 'Sedang atau akan mendapat steroid dosis tinggi atau obat penekan daya tahan tubuh?', jawab: 'Dokter lain berencana memberi steroid untuk penyakit sendi minggu depan.', esensial: true },
      { id: 'q_berat', kategori: 'rps', tanya: 'Ada sesak berat, batuk darah, demam, lemah sekali, atau nyeri perut hebat?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_hamil', kategori: 'rpd', tanya: 'Apakah sedang hamil atau menyusui?', jawab: 'Tidak.', hanyaUntuk: 'P', esensial: true },
    ],
    pemeriksaanFisik: [
      { region: 'kulit', temuan: 'Jejak urtikarial linear cepat memanjang pada bokong, sesuai larva currens.', relevan: true },
      { region: 'abdomen', temuan: 'Lunak, nyeri tekan ringan epigastrium, tanpa tanda peritonitis.', relevan: true },
      { region: 'toraks_paru', temuan: 'Vesikuler, tanpa ronki.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Eosinofil 12%; leukosit lain normal.', flag: 'tinggi', relevan: true },
      { id: 'feses_rutin', hasil: 'Larva Strongyloides ditemukan pada pemeriksaan serial.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['B78.9', 'B76.0', 'K58.0'],
    tatalaksana: {
      obatBenar: ['ivermektin_3'],
      obatSalahUmum: [
        { id: 'dexamethasone_05', alasan: 'Steroid sebelum strongiloidiasis dikenali dapat memicu hiperinfeksi yang fatal.', bahaya: 'kontraindikasi' },
      ],
      edukasi: ['cegah_cacing_tanah', 'kepatuhan_obat', 'tanda_bahaya'],
      edukasiKritis: ['tanda_bahaya'],
    },
    konfirmasiWajib: 'feses_rutin',
    clue: 'Larva currens, eosinofilia, pajanan tanah, dan larva feses mendukung strongiloidiasis. CDC merekomendasikan ivermektin 200 mcg/kg oral 1-2 hari; skrining sangat penting sebelum imunosupresi karena hiperinfeksi dapat fatal.',
    catatanRealita: 'Fornas 1199/2025 mencantumkan ivermektin, tetapi akses dapat melalui program atau jejaring. Resep item 3 mg di game mewakili obat, bukan jumlah tablet; dosis tetap berbasis berat badan.',
  }),

  buatKasusLab({
    id: 'lab_skistosomiasis_sulteng',
    nama: 'Skistosomiasis dari Fokus Endemis Sulawesi Tengah',
    icd10: 'B65.9',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'rendah',
    keluhanUtama: 'Sejak pulang dari kebun di Lembah Napu, perut sering sakit dan BAB kadang bercampur darah.',
    demografi: { usiaMin: 18, usiaMax: 55 },
    vital: { td: '116/74', nadi: 84, rr: 18, suhu: 37.1, spo2: 99 },
    pembuka: {
      tanya: 'Keluhan BAB dan perutnya mulai kapan?',
      jawab: 'Sekitar dua bulan setelah pulang dari Lembah Napu, perut mulas dan beberapa kali ada garis darah pada tinja.',
      oldcarts: ['onset', 'durasi', 'karakter'],
    },
    pertanyaan: [
      { id: 'q_air', kategori: 'sosial', tanya: 'Apakah sering masuk sawah, sungai, atau air tawar di daerah endemis?', jawab: 'Setiap hari saya melewati parit dan sawah tanpa sepatu bot.', esensial: true },
      { id: 'q_portal', kategori: 'rps', tanya: 'Perut makin besar, muntah darah, BAB hitam, kaki bengkak, atau sangat lemas?', jawab: 'Tidak ada.', esensial: true },
      { id: 'q_infeksi', kategori: 'rps', tanya: 'Ada demam tinggi atau diare akut pada orang serumah?', jawab: 'Tidak.', esensial: true },
      { id: 'q_hamil', kategori: 'rpd', tanya: 'Apakah sedang hamil?', jawab: 'Tidak.', hanyaUntuk: 'P' },
    ],
    pemeriksaanFisik: [
      { region: 'abdomen', temuan: 'Nyeri tekan ringan kuadran kanan atas; hati teraba 1 cm, tanpa asites atau splenomegali.', relevan: true },
      { region: 'umum', temuan: 'Tidak pucat berat, status gizi cukup.', relevan: true },
      { region: 'kulit', temuan: 'Tidak ada ruam aktif.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Eosinofil 10%, Hb 11,5 g/dL.', flag: 'tinggi', relevan: true },
      { id: 'feses_rutin', hasil: 'Telur Schistosoma japonicum ditemukan.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['B65.9', 'A06.0', 'A03'],
    tatalaksana: {
      obatBenar: ['prazikuantel_600'],
      edukasi: ['hindari_air_tawar_endemis', 'cuci_tangan_makanan', 'tanda_bahaya'],
    },
    konfirmasiWajib: 'feses_rutin',
    clue: 'Paparan air tawar pada fokus endemis Sulawesi Tengah, eosinofilia, dan telur S. japonicum menegakkan skistosomiasis. WHO merekomendasikan prazikuantel; evaluasi komplikasi hepatosplenis dan tindak lanjut program.',
    catatanRealita: 'Fornas 1199/2025 membatasi prazikuantel antisistosoma untuk Sulawesi Tengah; vignette sengaja menyebut fokus endemis. Obat dan tindak lanjut dikoordinasikan dengan program, bukan diasumsikan selalu ada di rak Sukamaju.',
  }),

  buatKasusLab({
    id: 'lab_taeniasis_intestinal',
    nama: 'Taeniasis Intestinal Tanpa Gejala Neurologis',
    icd10: 'B68.9',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'rendah',
    keluhanUtama: 'Saya melihat potongan putih pipih bergerak di tinja beberapa kali.',
    demografi: { usiaMin: 18, usiaMax: 65 },
    vital: { td: '120/76', nadi: 78, rr: 18, suhu: 36.7, spo2: 99 },
    pembuka: {
      tanya: 'Benda putih di tinja itu seperti apa dan sejak kapan terlihat?',
      jawab: 'Seperti potongan pita kecil pipih, kadang bergerak, terlihat tiga kali dalam dua minggu.',
      oldcarts: ['karakter', 'durasi', 'waktu'],
    },
    pertanyaan: [
      { id: 'q_daging', kategori: 'sosial', tanya: 'Sering makan daging babi atau sapi yang kurang matang?', jawab: 'Sebulan lalu beberapa kali makan olahan babi yang bagian tengahnya masih merah.', esensial: true },
      { id: 'q_neuro', kategori: 'rps', tanya: 'Pernah kejang, sakit kepala baru yang berat, penglihatan terganggu, atau lemah satu sisi?', jawab: 'Tidak pernah.', esensial: true },
      { id: 'q_gi', kategori: 'rps', tanya: 'Ada nyeri perut berat, muntah terus, atau berat badan turun banyak?', jawab: 'Hanya perut kadang tidak nyaman, berat badan tetap.', esensial: true },
      { id: 'q_sanitasi', kategori: 'sosial', tanya: 'Apakah rumah memakai jamban dan air bersih?', jawab: 'Ada jamban, tetapi saat bekerja di kebun kadang memakai jamban darurat.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Kondisi umum baik, status gizi cukup.', relevan: true },
      { region: 'abdomen', temuan: 'Lunak, tanpa massa, organomegali, atau nyeri tekan bermakna.', relevan: true },
      { region: 'neurologis', temuan: 'Pemeriksaan neurologis normal.', relevan: true },
    ],
    lab: [
      { id: 'feses_rutin', hasil: 'Proglotid dan telur Taenia ditemukan; spesies perlu identifikasi lanjutan bila tersedia.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['B68.9', 'B77.9', 'B76.0'],
    tatalaksana: {
      obatBenar: ['prazikuantel_600'],
      edukasi: ['masak_daging_matang', 'cuci_tangan_makanan', 'tanda_bahaya'],
      edukasiKritis: ['tanda_bahaya'],
    },
    konfirmasiWajib: 'feses_rutin',
    clue: 'Keluarnya proglotid dan pajanan daging kurang matang mendukung taeniasis. WHO mencantumkan prazikuantel 10 mg/kg dosis tunggal; gejala neurologis harus memicu evaluasi sistiserkosis sebelum terapi sederhana.',
    catatanRealita: 'Prazikuantel tercantum dalam Fornas. Item 600 mg mewakili sediaan, sedangkan jumlah tablet harus dihitung menurut berat badan dan protokol program.',
  }),

  buatKasusLab({
    id: 'lab_hepatitis_a_akut',
    nama: 'Hepatitis A Akut Tanpa Gagal Hati',
    icd10: 'B15',
    skdi: '4A',
    kategori: 'infeksi',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'rendah',
    keluhanUtama: 'Mata saya kuning, urine gelap, dan sejak seminggu lalu mual serta tidak nafsu makan.',
    demografi: { usiaMin: 15, usiaMax: 55 },
    vital: { td: '116/74', nadi: 82, rr: 18, suhu: 37.2, spo2: 99 },
    pembuka: {
      tanya: 'Keluhan kuningnya didahului apa dan mulai kapan?',
      jawab: 'Seminggu lalu demam ringan, mual, dan lemas; tiga hari ini mata kuning serta urine seperti teh.',
      oldcarts: ['onset', 'durasi', 'karakter', 'penyerta'],
    },
    pertanyaan: [
      { id: 'q_gagal_hati', kategori: 'rps', tanya: 'Ada mengantuk atau bingung, mudah berdarah, muntah terus, atau perut membesar?', jawab: 'Tidak ada. Saya masih sadar dan bisa minum.', esensial: true },
      { id: 'q_pajanan', kategori: 'sosial', tanya: 'Ada orang sekitar sakit kuning atau riwayat makanan dan air yang diragukan?', jawab: 'Dua rekan kos juga sakit setelah makan dari warung yang sama.', esensial: true },
      { id: 'q_obat', kategori: 'rpd', tanya: 'Minum jamu, suplemen, parasetamol dosis tinggi, alkohol, atau obat baru?', jawab: 'Tidak minum alkohol atau obat dosis tinggi.', esensial: true },
      { id: 'q_hepatitis', kategori: 'rpd', tanya: 'Pernah hepatitis, transfusi, tato tidak steril, atau perilaku berisiko?', jawab: 'Tidak pernah.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Ikterus sklera, sadar penuh, tidak ada asteriksis.', relevan: true },
      { region: 'abdomen', temuan: 'Hati teraba 2 cm dan nyeri ringan; tanpa asites atau splenomegali.', relevan: true },
      { region: 'kulit', temuan: 'Tidak ada petekie atau perdarahan spontan.', relevan: true },
    ],
    lab: [
      { id: 'sgot_sgpt', hasil: 'AST 620 U/L, ALT 910 U/L.', flag: 'tinggi', relevan: true },
      { id: 'anti_hav_igm', hasil: 'Reaktif.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['B15', 'B16.9', 'K71.6'],
    tatalaksana: {
      obatBenar: [],
      obatOpsional: ['ondansetron_4'],
      obatSalahUmum: [
        { id: 'paracetamol_500', alasan: 'WHO 2026 menganjurkan menghindari obat yang tidak perlu dan dapat membebani hati, termasuk parasetamol, pada hepatitis A.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['cegah_hepatitis_a', 'istirahat_cukup', 'tanda_bahaya'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Prodromal demam-mual diikuti ikterus, urine gelap, ALT/AST tinggi, dan IgM anti-HAV reaktif menegakkan hepatitis A akut. WHO 2026: tidak ada antivirus spesifik; fokus hidrasi, nutrisi, dan hindari obat tidak perlu yang membebani hati.',
    panduanResmi: `${PPK_FLOOR} PPK menekankan terapi suportif dan rujuk bila ikterus menetap, muncul keluhan lain, atau ada penurunan kesadaran.`,
  }),

  buatKasusLab({
    id: 'lab_bronkiolitis_berat',
    nama: 'Bronkiolitis Bayi dengan Hipoksemia',
    icd10: 'J21.9',
    skdi: '3B',
    kategori: 'respirasi',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'anak',
    keluhanUtama: 'Bayi saya pilek lalu sejak tadi malam napasnya cepat dan susunya jauh berkurang.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 0, usiaMax: 0, usiaBulanMin: 3, usiaBulanMax: 8 },
    vital: { nadi: 156, rr: 58, suhu: 37.7, spo2: 89 },
    pembuka: {
      tanya: 'Apa perubahan napas dan minum bayi sejak pilek?',
      jawab: 'Dua hari pilek, lalu napas cepat berbunyi dan sejak tadi malam hanya minum kurang dari setengah biasanya.',
      oldcarts: ['onset', 'durasi', 'keparahan', 'penyerta'],
    },
    pertanyaan: [
      { id: 'q_apnea', kategori: 'rps', tanya: 'Pernah berhenti napas, kebiruan, sangat mengantuk, atau sulit dibangunkan?', jawab: 'Tadi sempat tampak kebiruan sebentar saat menyusu, tidak berhenti napas.', esensial: true },
      { id: 'q_hidrasi', kategori: 'rps', tanya: 'Berapa kali buang air kecil dan apakah muntah semua minuman?', jawab: 'Popok basah hanya dua kali sejak pagi; tidak muntah semua.', esensial: true },
      { id: 'q_risiko', kategori: 'rpd', tanya: 'Lahir prematur atau punya kelainan jantung, paru, dan daya tahan tubuh?', jawab: 'Lahir cukup bulan dan sebelumnya sehat.', esensial: true },
      { id: 'q_kontak', kategori: 'sosial', tanya: 'Ada anggota rumah yang sedang pilek atau merokok dekat bayi?', jawab: 'Kakaknya pilek dan ayah kadang merokok di teras.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Bayi rewel lalu cepat lelah; retraksi subkostal dan napas cuping hidung.', relevan: true },
      { region: 'toraks_paru', temuan: 'Wheezing dan ronki halus difus bilateral; tidak ada temuan konsolidasi fokal.', relevan: true },
      { region: 'jantung', temuan: 'Takikardia, perfusi perifer sedikit memanjang.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['J21.9', 'J18.9', 'J45.9'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'salbutamol_2', alasan: 'Bronkodilator tidak diberikan rutin pada bronkiolitis bayi tanpa respons teruji dan indikasi khusus.', bahaya: 'nonPrimer' },
        { id: 'amoxicillin_sirup', alasan: 'Gambaran viral difus tanpa bukti infeksi bakteri; antibiotik tidak rutin.', bahaya: 'nonPrimer' },
        { id: 'dexamethasone_05', alasan: 'Kortikosteroid sistemik tidak rutin pada bronkiolitis.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['oksigen'],
      edukasi: ['tanda_bahaya', 'asi_eksklusif'],
      edukasiKritis: ['tanda_bahaya'],
    },
    stabilisasiWajib: ['oksigen'],
    clue: 'Bayi dengan prodrom pilek, wheezing/ronki difus, retraksi, asupan <50%, dan SpO2 89% mengalami bronkiolitis berat. WHO 2026 menekankan diagnosis klinis, terapi suportif, oksigen untuk hipoksemia, dan rujuk; jangan rutin memberi antibiotik, bronkodilator, atau steroid.',
    catatanRealita: 'Skenario menyatakan oksigen dan transport siap. Bila alat atau transport tidak siap, koordinasikan jejaring sambil melakukan stabilisasi yang tersedia; jangan menunda rujukan demi pemeriksaan tambahan.',
  }),

  buatKasusLab({
    id: 'lab_efusi_pleura',
    nama: 'Efusi Pleura Simptomatik',
    icd10: 'J90',
    skdi: '3A',
    kategori: 'respirasi',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'paru',
    keluhanUtama: 'Napas makin pendek dan dada kiri terasa berat sejak satu minggu.',
    demografi: { usiaMin: 30, usiaMax: 75 },
    vital: { td: '118/74', nadi: 104, rr: 28, suhu: 37.8, spo2: 91 },
    pembuka: {
      tanya: 'Sesaknya berkembang bagaimana dan di bagian mana dada terasa berat?',
      jawab: 'Makin berat selama seminggu, terutama saat berbaring; dada kiri bawah terasa penuh dan sakit saat tarik napas dalam.',
      oldcarts: ['durasi', 'lokasi', 'agravasi', 'karakter'],
    },
    pertanyaan: [
      { id: 'q_tb', kategori: 'rps', tanya: 'Ada batuk lama, berat badan turun, demam sore, atau keringat malam?', jawab: 'Batuk kering tiga minggu dan berat badan turun sekitar tiga kilo.', esensial: true },
      { id: 'q_jantung', kategori: 'rpd', tanya: 'Ada gagal jantung, bengkak kedua kaki, atau sesak saat tidur sebelumnya?', jawab: 'Tidak pernah.', esensial: true },
      { id: 'q_kanker', kategori: 'rpd', tanya: 'Ada riwayat kanker, operasi, atau bekuan darah?', jawab: 'Tidak ada.' },
      { id: 'q_gawat', kategori: 'rps', tanya: 'Ada pingsan, batuk darah banyak, atau sesak mendadak sangat berat?', jawab: 'Tidak, sesaknya bertambah perlahan.', esensial: true },
    ],
    pemeriksaanFisik: [
      { region: 'toraks_paru', temuan: 'Hemitoraks kiri tertinggal; fremitus menurun, perkusi redup, dan suara napas melemah pada basal kiri.', relevan: true },
      { region: 'umum', temuan: 'Tampak sesak sedang, masih sadar penuh dan dapat bicara.', relevan: true },
      { region: 'jantung', temuan: 'S1/S2 reguler, tidak ada edema perifer.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Hb 11,2 g/dL, leukosit 10.800/uL.', flag: 'abnormal', relevan: false },
    ],
    diagnosisBanding: ['J90', 'J18.9', 'A15.0'],
    tatalaksana: {
      obatBenar: [],
      prosedur: ['oksigen'],
      edukasi: ['tanda_bahaya', 'etika_batuk'],
    },
    stabilisasiWajib: ['oksigen'],
    clue: 'Redup pada perkusi, fremitus turun, dan suara napas melemah di satu basal mendukung efusi pleura. Hipoksemia perlu oksigen dan pasien dirujuk untuk pencitraan, torakosentesis diagnostik, serta penentuan etiologi seperti TB, infeksi, gagal jantung, atau keganasan.',
    catatanRealita: 'Puskesmas Sukamaju tidak diasumsikan memiliki rontgen atau kemampuan torakosentesis. Jawaban benar adalah mengenali sindrom, memberi oksigen, dan merujuk tanpa prosedur buta.',
  }),

  buatKasusLab({
    id: 'lab_edema_paru_akut_hipertensif',
    nama: 'Edema Paru Akut Hipertensif',
    icd10: 'J81',
    skdi: '3B',
    kategori: 'kardiovaskular',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'penyakit_dalam',
    keluhanUtama: 'Saya mendadak sangat sesak saat tidur dan batuk berbusa merah muda.',
    demografi: { usiaMin: 45, usiaMax: 80 },
    vital: { td: '194/112', nadi: 124, rr: 34, suhu: 36.8, spo2: 84 },
    pembuka: {
      tanya: 'Sesaknya mulai kapan dan apa yang terjadi saat itu?',
      jawab: 'Mendadak satu jam lalu saat berbaring; saya terbangun megap-megap dan batuk berbusa merah muda.',
      oldcarts: ['onset', 'waktu', 'karakter', 'keparahan'],
    },
    pertanyaan: [
      { id: 'q_jantung', kategori: 'rpd', tanya: 'Ada riwayat gagal jantung, serangan jantung, atau tekanan darah sangat tinggi?', jawab: 'Saya punya darah tinggi dan sering lupa obat; pernah dirawat karena jantung lemah.', esensial: true },
      { id: 'q_iskemia', kategori: 'rps', tanya: 'Ada nyeri dada menekan yang menjalar atau keringat dingin?', jawab: 'Dada terasa berat tetapi tidak menjalar.', esensial: true },
      { id: 'q_obat', kategori: 'rpd', tanya: 'Sudah minum obat apa malam ini, termasuk obat kuat pria?', jawab: 'Belum minum obat apa pun dan tidak memakai obat kuat.', esensial: true },
      { id: 'q_cairan', kategori: 'sosial', tanya: 'Ada konsumsi garam atau cairan berlebih beberapa hari ini?', jawab: 'Dua hari ini banyak makan asin saat hajatan.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Gelisah, ortopnea, bicara terputus, kulit dingin berkeringat.', relevan: true },
      { region: 'toraks_paru', temuan: 'Ronki basah halus difus bilateral hingga lapang tengah.', relevan: true },
      { region: 'jantung', temuan: 'Takikardia reguler, gallop S3, vena jugularis meningkat.', relevan: true },
    ],
    lab: [
      { id: 'ekg', hasil: 'Takikardia sinus, hipertrofi ventrikel kiri, tanpa elevasi ST.', flag: 'abnormal', relevan: true },
    ],
    diagnosisBanding: ['J81', 'I50.9', 'J18.9'],
    tatalaksana: {
      obatBenar: ['isosorbid_dinitrat_5'],
      prosedur: ['posisi_semifowler', 'oksigen'],
      tindakanSalahUmum: [
        { id: 'akses_iv_resusitasi', alasan: 'Bolus cairan resusitasi pada edema paru kongestif dapat memperburuk banjir alveolus; akses IV tidak berarti cairan bebas.', bahaya: 'berbahaya' },
      ],
      edukasi: ['tanda_bahaya', 'diet_rendah_garam'],
    },
    stabilisasiWajib: ['posisi_semifowler', 'oksigen'],
    clue: 'Ortopnea mendadak, sputum berbusa, ronki difus, hipertensi berat, dan hipoksemia mendukung edema paru akut. Dudukkan, beri oksigen, pertimbangkan nitrat bila tekanan darah memadai dan tanpa kontraindikasi, monitor, lalu rujuk segera.',
    catatanRealita: 'Furosemid injeksi tidak diasumsikan ready di Puskesmas Sukamaju dan tidak dijadikan klik wajib. Stabilkan jalan napas/oksigenasi, gunakan nitrat secara selektif, dan jangan menunda transfer.',
  }),

  buatKasusLab({
    id: 'lab_pneumotoraks_spontan',
    nama: 'Pneumotoraks Spontan',
    icd10: 'J93.9',
    skdi: '3A',
    kategori: 'respirasi',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'paru',
    keluhanUtama: 'Dada kanan mendadak sakit tajam dan napas pendek saat sedang duduk.',
    demografi: { usiaMin: 18, usiaMax: 45 },
    vital: { td: '118/76', nadi: 108, rr: 28, suhu: 36.7, spo2: 90 },
    pembuka: {
      tanya: 'Nyeri dada dan sesaknya mulai bagaimana?',
      jawab: 'Mendadak dua jam lalu, nyeri tajam di kanan makin terasa saat tarik napas dan saya jadi sesak.',
      oldcarts: ['onset', 'lokasi', 'karakter', 'agravasi'],
    },
    pertanyaan: [
      { id: 'q_tension', kategori: 'rps', tanya: 'Ada pingsan, sesak cepat memburuk, atau rasa sangat lemah?', jawab: 'Tidak pingsan dan kondisinya tidak memburuk cepat.', esensial: true },
      { id: 'q_trauma', kategori: 'rps', tanya: 'Baru mengalami benturan dada, tindakan medis, atau menyelam?', jawab: 'Tidak ada trauma atau tindakan.', esensial: true },
      { id: 'q_paru', kategori: 'rpd', tanya: 'Ada asma, PPOK, TB, atau kejadian serupa sebelumnya?', jawab: 'Tidak ada.' },
      { id: 'q_rokok', kategori: 'sosial', tanya: 'Apakah merokok?', jawab: 'Iya, sekitar setengah bungkus per hari.', esensial: true },
    ],
    pemeriksaanFisik: [
      { region: 'toraks_paru', temuan: 'Gerak hemitoraks kanan berkurang, perkusi hipersonor, dan suara napas kanan menurun.', relevan: true },
      { region: 'umum', temuan: 'Tampak sesak sedang, sadar penuh, trakea tetap di tengah.', relevan: true },
      { region: 'jantung', temuan: 'Takikardia; tekanan darah dan perfusi masih terjaga.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['J93.9', 'I26.9', 'J18.9'],
    tatalaksana: {
      obatBenar: [],
      prosedur: ['oksigen'],
      edukasi: ['tanda_bahaya', 'berhenti_merokok'],
    },
    stabilisasiWajib: ['oksigen'],
    clue: 'Nyeri pleuritik mendadak, hipersonor, dan suara napas unilateral turun mendukung pneumotoraks. Pasien ini belum menunjukkan tension physiology; beri oksigen, monitor, dan rujuk segera. Dekompresi jarum hanya untuk kecurigaan pneumotoraks tensi yang tidak boleh menunggu pencitraan.',
    panduanResmi: `${PPK_FLOOR} PPK pneumotoraks memerintahkan oksigen, akses IV bila ada gagal sirkulasi, dan rujuk segera setelah penanggulangan awal.`,
  }),

  buatKasusLab({
    id: 'lab_abses_peritonsil',
    nama: 'Abses Peritonsil',
    icd10: 'J36',
    skdi: '3A',
    kategori: 'tht',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'tht',
    keluhanUtama: 'Tenggorokan kiri sangat sakit, suara berubah, dan mulut sulit dibuka.',
    demografi: { usiaMin: 15, usiaMax: 50 },
    vital: { td: '116/74', nadi: 106, rr: 20, suhu: 38.5, spo2: 97 },
    pembuka: {
      tanya: 'Nyeri tenggoroknya mulai bagaimana dan apakah masih bisa menelan?',
      jawab: 'Tiga hari makin berat di sisi kiri; saya masih bisa menelan sedikit tetapi ludah sering terkumpul.',
      oldcarts: ['onset', 'lokasi', 'keparahan', 'durasi'],
    },
    pertanyaan: [
      { id: 'q_airway', kategori: 'rps', tanya: 'Ada sesak, bunyi napas kasar, sulit menelan ludah sama sekali, atau leher membengkak cepat?', jawab: 'Tidak sesak dan masih bisa menelan sedikit.', esensial: true },
      { id: 'q_suara', kategori: 'rps', tanya: 'Suara menjadi bindeng seperti ada makanan panas di mulut dan mulut sulit dibuka?', jawab: 'Iya, suara berubah dan rahang sulit dibuka.', esensial: true },
      { id: 'q_antibiotik', kategori: 'rpd', tanya: 'Sudah minum antibiotik atau ada alergi obat?', jawab: 'Belum minum antibiotik dan tidak tahu ada alergi.' },
      { id: 'q_imun', kategori: 'rpd', tanya: 'Ada diabetes atau daya tahan tubuh lemah?', jawab: 'Tidak ada.' },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Trismus, pembengkakan peritonsil kiri, arkus anterior menonjol, uvula terdorong ke kanan.', relevan: true },
      { region: 'kepala_leher', temuan: 'KGB servikal kiri nyeri, tanpa pembengkakan leher difus.', relevan: true },
      { region: 'umum', temuan: 'Suara hot-potato, tidak stridor, perfusi baik.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['J36', 'J03.9', 'J39.0'],
    tatalaksana: {
      obatBenar: ['amoxiclav_625', 'paracetamol_500'],
      tindakanSalahUmum: [
        { id: 'insisi_abses', alasan: 'Drainase peritonsil tidak dilakukan buta tanpa kompetensi, visualisasi, perlindungan jalan napas, dan kesiapan menangani perdarahan.', bahaya: 'berbahaya' },
      ],
      edukasi: ['tanda_bahaya', 'kepatuhan_obat'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Nyeri unilateral, trismus, suara hot-potato, pembengkakan peritonsil, dan deviasi uvula mendukung abses peritonsil. Nilai jalan napas, beri analgesia dan antibiotik, lalu rujuk THT untuk drainase terkontrol.',
    catatanRealita: 'Kasus masih dapat menelan dan tidak stridor, sehingga antibiotik oral pra-rujuk dimodelkan. Bila jalan napas terancam atau pasien tidak dapat menelan, jangan memaksa obat oral; prioritaskan stabilisasi dan transfer.',
  }),

  buatKasusLab({
    id: 'lab_perdarahan_gi_atas',
    nama: 'Perdarahan Saluran Cerna Atas dengan Syok Terkompensasi',
    icd10: 'K92.2',
    skdi: '3B',
    kategori: 'pencernaan',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'penyakit_dalam',
    keluhanUtama: 'Saya muntah darah hitam dan sejak kemarin BAB hitam pekat.',
    demografi: { usiaMin: 30, usiaMax: 75 },
    vital: { td: '92/60', nadi: 118, rr: 24, suhu: 36.5, spo2: 92 },
    pembuka: {
      tanya: 'Berapa banyak muntah darah dan bagaimana warna BAB?',
      jawab: 'Muntah seperti ampas kopi satu gelas dan BAB hitam lengket dua kali sejak kemarin.',
      oldcarts: ['karakter', 'onset', 'keparahan', 'durasi'],
    },
    pertanyaan: [
      { id: 'q_syok', kategori: 'rps', tanya: 'Ada pingsan, sangat lemas, nyeri dada, atau sesak?', jawab: 'Saya hampir pingsan saat berdiri dan terasa sangat lemas.', esensial: true },
      { id: 'q_obat', kategori: 'rpd', tanya: 'Sering minum obat nyeri seperti ibuprofen, aspirin, atau pengencer darah?', jawab: 'Saya minum ibuprofen hampir tiap hari untuk nyeri lutut.', esensial: true },
      { id: 'q_hati', kategori: 'rpd', tanya: 'Ada penyakit hati, perut membesar, muntah darah sebelumnya, atau konsumsi alkohol berat?', jawab: 'Tidak ada penyakit hati dan tidak minum alkohol.', esensial: true },
      { id: 'q_nyeri', kategori: 'rps', tanya: 'Ada nyeri ulu hati atau muntah berulang sebelum darah keluar?', jawab: 'Ulu hati sering perih beberapa minggu ini.' },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Pucat, dingin, berkeringat, sadar penuh tetapi pusing saat duduk.', relevan: true },
      { region: 'abdomen', temuan: 'Nyeri tekan epigastrium ringan, tanpa defans, asites, atau hepatosplenomegali.', relevan: true },
      { region: 'jantung', temuan: 'Takikardia, pengisian kapiler 3 detik.', relevan: true },
    ],
    lab: [
      { id: 'hb', hasil: 'Hb 8,4 g/dL.', flag: 'rendah', relevan: true },
      { id: 'golongan_darah', hasil: 'O rhesus positif.', flag: 'normal', relevan: true },
    ],
    diagnosisBanding: ['K92.2', 'K25.4', 'I85.0'],
    tatalaksana: {
      obatBenar: [],
      prosedur: ['akses_iv_resusitasi', 'oksigen'],
      obatSalahUmum: [
        { id: 'ibuprofen_400', alasan: 'NSAID dapat memperburuk perdarahan saluran cerna dan harus dihentikan.', bahaya: 'kontraindikasi' },
      ],
      edukasi: ['tanda_bahaya'],
      edukasiKritis: ['tanda_bahaya'],
    },
    stabilisasiWajib: ['akses_iv_resusitasi', 'oksigen'],
    clue: 'Hematemesis coffee-ground, melena, hipotensi, dan takikardia adalah perdarahan GI atas dengan gangguan sirkulasi. Stabilkan ABC, dua akses IV/cairan terukur, oksigen karena hipoksemia, hentikan NSAID, dan transfer untuk endoskopi setelah resusitasi.',
    panduanResmi: 'PPK 1186/2022 memuat stabilisasi hemodinamik dan rujukan; NICE CG141 menempatkan endoskopi segera setelah resusitasi pada pasien tidak stabil.',
    catatanRealita: 'PPI pra-endoskopi tidak dijadikan jawaban wajib karena pedoman berbeda dan sediaan injeksi tidak diasumsikan ready. Jangan menunda transfer demi terapi oral atau bilas lambung rutin.',
  }),

  buatKasusLab({
    id: 'lab_ileus_obstruktif',
    nama: 'Ileus Obstruktif',
    icd10: 'K56.6',
    skdi: '3B',
    kategori: 'pencernaan',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'bedah',
    keluhanUtama: 'Perut makin kembung, muntah, dan saya tidak bisa BAB atau buang angin sejak kemarin.',
    demografi: { usiaMin: 25, usiaMax: 75 },
    vital: { td: '102/68', nadi: 110, rr: 22, suhu: 37.5, spo2: 97 },
    pembuka: {
      tanya: 'Kembung, muntah, dan BAB-nya berkembang bagaimana?',
      jawab: 'Nyeri perut datang bergelombang, perut membesar, muntah hijau tiga kali, dan 24 jam tidak BAB atau kentut.',
      oldcarts: ['onset', 'karakter', 'waktu', 'keparahan'],
    },
    pertanyaan: [
      { id: 'q_operasi', kategori: 'rpd', tanya: 'Pernah operasi perut, punya hernia, atau tumor?', jawab: 'Pernah operasi usus buntu sepuluh tahun lalu.', esensial: true },
      { id: 'q_strangulasi', kategori: 'rps', tanya: 'Nyeri menjadi terus-menerus hebat, ada darah pada BAB, demam tinggi, atau pingsan?', jawab: 'Nyeri masih hilang timbul dan belum ada darah.', esensial: true },
      { id: 'q_hidrasi', kategori: 'rps', tanya: 'Masih bisa minum dan kapan terakhir berkemih?', jawab: 'Minum langsung muntah; terakhir kencing sedikit pagi tadi.', esensial: true },
      { id: 'q_obat', kategori: 'rpd', tanya: 'Sudah minum obat pencahar atau obat lain?', jawab: 'Belum minum apa pun.' },
    ],
    pemeriksaanFisik: [
      { region: 'abdomen', temuan: 'Distensi, timpani, bising usus tinggi bernada metalik, nyeri tekan difus tanpa defans.', relevan: true },
      { region: 'umum', temuan: 'Mukosa kering, tampak kesakitan saat kolik, sadar penuh.', relevan: true },
      { region: 'jantung', temuan: 'Takikardia, pengisian kapiler 2-3 detik.', relevan: true },
    ],
    lab: [
      { id: 'elektrolit_serum', hasil: 'Natrium 132 mmol/L, kalium 3,2 mmol/L.', flag: 'rendah', relevan: true },
      { id: 'fungsi_ginjal', hasil: 'Kreatinin 1,4 mg/dL, meningkat ringan karena dehidrasi.', flag: 'tinggi', relevan: true },
    ],
    diagnosisBanding: ['K56.6', 'K56.7', 'K52.9'],
    tatalaksana: {
      obatBenar: [],
      prosedur: ['akses_iv_resusitasi', 'dekompresi_ngt'],
      obatSalahUmum: [
        { id: 'bisakodil_5', alasan: 'Laksatif pada obstruksi mekanik dapat meningkatkan distensi dan risiko perforasi.', bahaya: 'kontraindikasi' },
        { id: 'loperamid_2', alasan: 'Antimotilitas tidak boleh digunakan pada dugaan obstruksi usus.', bahaya: 'kontraindikasi' },
      ],
      edukasi: ['puasa_sambil_rujuk', 'tanda_bahaya'],
      edukasiKritis: ['puasa_sambil_rujuk'],
    },
    stabilisasiWajib: ['akses_iv_resusitasi', 'dekompresi_ngt'],
    clue: 'Nyeri kolik, muntah bilious, obstipasi, distensi, timpani, dan bising metalik mendukung ileus obstruktif. Puasakan, koreksi cairan/elektrolit secara terukur, dekompresi NGT, dan rujuk bedah; jangan beri laksatif atau obat antimotilitas.',
    catatanRealita: 'Skenario menyatakan NGT, cairan, operator, dan transport siap. Bila NGT tidak dapat dipasang aman, jangan menunda transfer atau melakukan probing berulang.',
  }),
]

export const LAB_BATCH_1_ARCHETYPE_SPECS: Record<string, LabArchetypeSpec> = {
  lab_pneumonia_komunitas_dewasa: { conceptId: 'concept:pneumonia', credits: ['fktp144:pneumonia_bacterial'] },
  lab_influenza_tanpa_komplikasi: { conceptId: 'concept:influenza', credits: ['fktp144:influenza'] },
  lab_pertusis_remaja: { conceptId: 'concept:pertussis', credits: ['fktp144:pertussis'] },
  lab_laringitis_akut: { conceptId: 'concept:laryngitis_acute', credits: ['fktp144:laryngitis_acute'] },
  lab_mabuk_perjalanan: { conceptId: 'concept:motion_sickness', credits: ['fktp144:motion_sickness'] },
  lab_furunkel_hidung: { conceptId: 'concept:furunkel_nose', credits: ['fktp144:furunkel_nose'] },
  lab_rinitis_vasomotor: { conceptId: 'concept:rhinitis_vasomotor', credits: ['fktp144:rhinitis_vasomotor'] },
  lab_stomatitis_aftosa: { conceptId: 'concept:aphthous_ulcer', credits: ['fktp144:stomatitis_aftosa'] },
  lab_kandidiasis_mulut: { conceptId: 'concept:oral_candidiasis', credits: ['fktp144:oral_candidiasis'] },
  lab_parotitis_mumps: { conceptId: 'concept:parotitis_mumps', credits: ['fktp144:parotitis_mumps'] },
  lab_intoleransi_makanan_laktosa: { conceptId: 'concept:food_intolerance', credits: ['fktp144:food_intolerance'] },
  lab_alergi_makanan_ringan: { conceptId: 'concept:food_allergy', credits: ['fktp144:food_allergy'] },
  lab_keracunan_makanan_ringan: { conceptId: 'concept:food_poisoning', credits: ['fktp144:food_poisoning'] },
  lab_cacing_tambang: { conceptId: 'concept:hookworm', credits: ['fktp144:hookworm'] },
  lab_strongiloidiasis: { conceptId: 'concept:strongyloidiasis', credits: ['fktp144:strongyloidiasis'] },
  lab_skistosomiasis_sulteng: { conceptId: 'concept:schistosomiasis', credits: ['fktp144:schistosomiasis'] },
  lab_taeniasis_intestinal: { conceptId: 'concept:taeniasis', credits: ['fktp144:taeniasis'] },
  lab_hepatitis_a_akut: { conceptId: 'concept:hepatitis_a', credits: ['fktp144:hepatitis_a'] },
  lab_bronkiolitis_berat: { conceptId: 'concept:bronchiolitis', credits: ['clinical:lab_bronkiolitis_berat'] },
  lab_efusi_pleura: { conceptId: 'concept:pleural_effusion', credits: ['clinical:lab_efusi_pleura'] },
  lab_edema_paru_akut_hipertensif: { conceptId: 'concept:acute_pulmonary_edema', credits: ['clinical:lab_edema_paru_akut_hipertensif'] },
  lab_pneumotoraks_spontan: { conceptId: 'concept:pneumothorax', credits: ['clinical:lab_pneumotoraks_spontan'] },
  lab_abses_peritonsil: { conceptId: 'concept:peritonsillar_abscess', credits: ['clinical:lab_abses_peritonsil'] },
  lab_perdarahan_gi_atas: { conceptId: 'concept:upper_gi_bleeding', credits: ['clinical:lab_perdarahan_gi_atas'] },
  lab_ileus_obstruktif: { conceptId: 'concept:bowel_obstruction', credits: ['clinical:lab_ileus_obstruktif'] },
}
