import type { KasusKlinis } from '../types'
import type { FktpLabSpec } from './labCaseFactory'
import { buatKasusFktpLab } from './labCaseFactory'

interface LabDefinition {
  catalogId: string
  conceptId?: string
  spec: FktpLabSpec
}

const PPK = 'PPK Dokter FKTP KMK 1186/2022 menjadi floor keputusan; sumber yang lebih baru dipakai bila mengubah keselamatan atau efektivitas.'
const NORMAL = { td: '120/78', nadi: 78, rr: 18, suhu: 36.7, spo2: 99 } as const

const DEFINITIONS: LabDefinition[] = [
  {
    catalogId: 'leg_ulcer',
    spec: {
      id: 'lab_ulkus_tungkai_vena', nama: 'Ulkus Tungkai Kronis - Dominan Vena', icd10: 'L97', kategori: 'muskuloskeletal', prevalensi: 'sedang',
      keluhanUtama: 'Luka di atas mata kaki saya sudah lama tidak menutup.', usia: [45, 75], vital: NORMAL,
      pembuka: ['Bagaimana luka ini bermula dan berubah?', 'Tiga bulan lalu kecil, lalu melebar; tungkai juga bengkak sore hari dan membaik saat diangkat.'],
      pertanyaan: [
        ['q_infeksi', 'rps', 'Ada demam, nanah, bau memburuk, atau kemerahan yang meluas?', 'Tidak demam dan tidak bernanah.', true],
        ['q_arteri', 'rps', 'Kaki nyeri saat berjalan atau saat istirahat, dingin, atau menghitam?', 'Tidak; kaki tetap hangat.', true],
        ['q_risiko', 'rpd', 'Ada diabetes, varises, bekuan darah, atau kebiasaan merokok?', 'Ada varises lama, gula darah terakhir normal.', true],
      ],
      fisik: [['ekstremitas', 'Ulkus dangkal tidak beraturan di gaiter area medial, edema pitting, hiperpigmentasi; kaki hangat dan nadi dorsalis pedis teraba.'], ['kulit', 'Tidak ada pus, selulitis, nekrosis, atau jaringan terpapar.']],
      lab: [['gds', '112 mg/dL.', 'normal']],
      diagnosisBanding: ['L97', 'I83.0', 'E11.5'],
      tatalaksana: { obatBenar: [], obatOpsional: ['paracetamol_500'], prosedur: ['perawatan_luka'], edukasi: ['perawatan_ulkus_tungkai', 'tanda_bahaya'] },
      clue: 'Lokasi gaiter, edema memburuk saat berdiri, varises, dan nadi teraba mendukung ulkus vena. Bersihkan dan balut, elevasi, nilai penyakit arteri sebelum kompresi, serta koreksi faktor risiko; jangan memberi antibiotik tanpa infeksi klinis.',
      panduanResmi: PPK,
      catatanRealita: 'Doppler/ABI tidak diasumsikan selalu ready. Kompresi kuat tidak dijadikan jawaban wajib sebelum perfusi arteri dinilai aman melalui jejaring.',
    },
  },
  {
    catalogId: 'lipoma',
    spec: {
      id: 'lab_lipoma_lengan', nama: 'Lipoma Subkutan', icd10: 'D17', kategori: 'muskuloskeletal', prevalensi: 'sedang',
      keluhanUtama: 'Ada benjolan lunak di lengan yang perlahan membesar.', usia: [25, 65], vital: NORMAL,
      pembuka: ['Sejak kapan benjolan ada dan bagaimana pertumbuhannya?', 'Sudah dua tahun, membesar sangat pelan, tidak sakit.'],
      pertanyaan: [
        ['q_redflag', 'rps', 'Apakah cepat membesar, keras, nyeri malam, melekat, atau mengganggu gerak?', 'Tidak, benjolan mudah digerakkan dan tidak mengganggu.', true],
        ['q_sistemik', 'rps', 'Ada demam, berat badan turun, atau benjolan lain?', 'Tidak ada.', true],
        ['q_riwayat', 'rpd', 'Pernah trauma atau keganasan?', 'Tidak pernah.', false],
      ],
      fisik: [['ekstremitas', 'Massa subkutan 3 cm, lunak, lobulated, mobile, tidak nyeri, kulit di atas normal.'], ['umum', 'Tidak ada limfadenopati atau tanda sistemik.', false]],
      diagnosisBanding: ['D17', 'L72.9', 'C49.9'],
      tatalaksana: { obatBenar: [], edukasi: ['kontrol_rutin', 'tanda_bahaya'] },
      clue: 'Massa subkutan lunak, mobile, lambat tumbuh, dan tanpa red flag khas lipoma. Beri reassurance dan observasi; eksisi elektif bila nyeri, mengganggu fungsi/kosmetik, diagnosis meragukan, atau pertumbuhan berubah.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'molluscum',
    spec: {
      id: 'lab_moluskum_kontagiosum_anak', nama: 'Moluskum Kontagiosum Anak', icd10: 'B08.1', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Anak saya punya bintil kecil mengilap di lengan dan badan.', keluhanUtamaOlehPendamping: true, usia: [2, 10], vital: { ...NORMAL, td: '100/64' },
      pembuka: ['Bintilnya mulai kapan dan apakah mengganggu?', 'Dua bulan, bertambah perlahan, tidak demam dan hanya sedikit gatal.'],
      pertanyaan: [
        ['q_sebar', 'rps', 'Ada bintil di mata atau kemaluan, bernanah, atau sangat meradang?', 'Tidak, hanya di lipatan siku dan badan.', true],
        ['q_kontak', 'sosial', 'Ada teman serumah dengan keluhan serupa atau berbagi handuk?', 'Sepupunya punya bintil mirip dan mereka sering bermain bersama.', true],
        ['q_imun', 'rpd', 'Anak sering infeksi berat atau memakai obat penekan imun?', 'Tidak.', false],
      ],
      fisik: [['kulit', 'Papul mutiara 2-5 mm multipel dengan umbilikasi sentral, tanpa selulitis.'], ['umum', 'Anak aktif dan status gizi baik.', false]],
      diagnosisBanding: ['B08.1', 'B07', 'L73.9'],
      tatalaksana: { obatBenar: [], prosedur: [], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Papul mutiara berlekuk di tengah khas moluskum dan sering swasirna. Hindari memencet/berbagi handuk; observasi adalah pilihan utama. Kuretase atau krioterapi hanya tindakan terpilih setelah diskusi nyeri, bekas, lokasi, dan kompetensi.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'herpes_simplex',
    spec: {
      id: 'lab_herpes_simpleks_labialis', nama: 'Herpes Simpleks Labialis Rekuren', icd10: 'B00.9', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Bibir saya kesemutan lalu muncul lenting bergerombol.', usia: [18, 55], vital: NORMAL,
      pembuka: ['Bagaimana keluhan ini dimulai dan sudah berapa lama?', 'Kesemutan kemarin, lalu lenting perih muncul di tepi bibir; pernah kambuh saat kurang tidur.'],
      pertanyaan: [
        ['q_mata', 'rps', 'Ada mata merah, nyeri, atau penglihatan kabur?', 'Tidak ada.', true],
        ['q_imun', 'rpd', 'Ada gangguan imun atau lesi sangat luas?', 'Tidak.', true],
        ['q_hamil', 'rpd', 'Apakah sedang hamil atau mungkin hamil?', 'Tidak.', false, 'P'],
        ['q_kontak', 'sosial', 'Ada kontak dekat dengan bayi atau orang imunitasnya lemah?', 'Ada bayi di rumah, tetapi belum saya cium sejak lenting muncul.', true],
      ],
      fisik: [['kulit', 'Vesikel berkelompok di dasar eritem pada vermilion bibir, tanpa pus.'], ['mata', 'Kornea jernih dan tidak ada lesi periokular.', true]],
      diagnosisBanding: ['B00.9', 'B02.9', 'K12.0'],
      tatalaksana: { obatBenar: ['asiklovir_400'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Prodrom kesemutan dan vesikel berkelompok rekuren mendukung HSV labialis. Antivirus dini paling bermanfaat; jaga kebersihan tangan, hindari kontak lesi dengan mata dan kontak dekat saat aktif.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'ektima',
    spec: {
      id: 'lab_ektima_tungkai', nama: 'Impetigo Ulseratif (Ektima)', icd10: 'L08.0', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Koreng tebal di tungkai menjadi luka cekung dan nyeri.', usia: [8, 12], vital: { ...NORMAL, td: '104/66', suhu: 37.4 },
      pembuka: ['Luka bermula seperti apa dan apakah menyebar?', 'Awalnya lecet gatal, lalu bernanah dan membentuk kerak tebal selama seminggu.'],
      pertanyaan: [
        ['q_sistemik', 'rps', 'Ada demam tinggi, kemerahan cepat meluas, atau sangat lemas?', 'Tidak.', true],
        ['q_risiko', 'rpd', 'Ada diabetes, gangguan imun, atau luka serupa berulang?', 'Tidak ada.', true],
        ['q_higiene', 'sosial', 'Bagaimana perawatan luka dan kebersihan di rumah?', 'Hanya ditutup kain dan sering tergaruk.', false],
      ],
      fisik: [['kulit', 'Ulkus dangkal punched-out multipel dengan krusta tebal melekat di tungkai; eritem lokal tanpa selulitis luas.'], ['umum', 'Perfusi baik, tidak toksik.', true]],
      diagnosisBanding: ['L08.0', 'L01.0', 'L97'],
      tatalaksana: { obatBenar: ['cefadroxil_sirup_125'], obatOpsional: ['mupirosin_krim'], prosedur: ['perawatan_luka'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Ulkus berkrusta tebal yang lebih dalam daripada impetigo mendukung ektima. Bersihkan krusta secara lembut dan beri antibiotik antistafilokokus/streptokokus; evaluasi selulitis, diabetes, dan respons.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'folliculitis',
    spec: {
      id: 'lab_folikulitis_superfisialis', nama: 'Folikulitis Superfisialis', icd10: 'L73.9', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Ada bintil bernanah kecil di sekitar rambut paha setelah mencukur.', usia: [18, 55], vital: NORMAL,
      pembuka: ['Kapan bintil muncul dan adakah pemicunya?', 'Dua hari setelah mencukur, bintil kecil sedikit perih tetapi tidak membesar.'],
      pertanyaan: [
        ['q_berat', 'rps', 'Ada benjolan besar, demam, kemerahan meluas, atau nyeri berat?', 'Tidak.', true],
        ['q_kambuh', 'rpd', 'Sering berulang, diabetes, atau memakai bak air panas bersama?', 'Tidak.', false],
        ['q_alat', 'sosial', 'Pisau cukur dipakai bersama atau sudah lama?', 'Pisau lama tetapi tidak dipakai orang lain.', true],
      ],
      fisik: [['kulit', 'Pustul 2-3 mm terpusat pada folikel rambut, jumlah terbatas, tanpa fluktuasi atau selulitis.'], ['umum', 'Afebris dan tampak baik.', false]],
      diagnosisBanding: ['L73.9', 'L02', 'L70.0'],
      tatalaksana: { obatBenar: ['mupirosin_krim'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Pustul kecil folikulosentrik tanpa abses atau gejala sistemik adalah folikulitis superfisial. Hentikan pencukuran sementara, kompres/higiene, terapi topikal terbatas; antibiotik oral tidak rutin.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'furuncle',
    spec: {
      id: 'lab_furunkel_fluktuatif', nama: 'Furunkel Fluktuatif Lokal', icd10: 'L02', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Benjolan di paha terasa berdenyut dan sekarang lunak di tengah.', usia: [18, 60], vital: NORMAL,
      pembuka: ['Bagaimana benjolan berkembang?', 'Mulai seperti bintil empat hari lalu, membesar dan nyeri; tidak demam.'],
      pertanyaan: [
        ['q_redflag', 'rps', 'Ada demam, garis merah, kemerahan luas, atau lokasi di wajah?', 'Tidak, hanya satu di paha.', true],
        ['q_risiko', 'rpd', 'Ada diabetes, gangguan imun, atau abses berulang?', 'Tidak.', true],
        ['q_manipulasi', 'sosial', 'Sudah dipencet atau ditusuk sendiri?', 'Belum.', false],
      ],
      fisik: [['kulit', 'Nodul 2 cm eritematosa dengan fluktuasi sentral; selulitis sekitar minimal.'], ['umum', 'Afebris, hemodinamik stabil.', false]],
      diagnosisBanding: ['L02', 'L73.9', 'L03.9'],
      tatalaksana: { obatBenar: [], prosedur: ['insisi_abses'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Furunkel berfluktuasi memerlukan insisi-drainase aseptik. Antibiotik sistemik bukan pengganti drainase dan tidak rutin pada abses kecil tanpa selulitis luas, gejala sistemik, lokasi berisiko, atau imunokompromais.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'erythrasma',
    spec: {
      id: 'lab_eritrasma_lipat_paha', nama: 'Eritrasma Lipat Paha', icd10: 'L08.1', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Lipat paha saya bercak cokelat tipis dan sedikit gatal.', usia: [25, 70], vital: NORMAL,
      pembuka: ['Sejak kapan bercak ada dan bagaimana rasanya?', 'Sebulan, tidak terlalu gatal, tidak melebar seperti cincin.'],
      pertanyaan: [
        ['q_risiko', 'rpd', 'Ada diabetes, berat badan berlebih, atau mudah berkeringat?', 'Saya mudah berkeringat dan berat badan berlebih.', true],
        ['q_obat', 'rpd', 'Sudah memakai antijamur atau steroid?', 'Antijamur seminggu tidak banyak berubah.', true],
        ['q_lokasi', 'rps', 'Ada juga di sela jari atau ketiak?', 'Sedikit di ketiak.', false],
      ],
      fisik: [['kulit', 'Plak cokelat-merah berbatas tegas dengan skuama halus di lipat paha, tanpa active border atau satelit.'], ['umum', 'Tidak ada tanda infeksi sistemik.', false]],
      lab: [['mikroskopis_gram_koh', 'KOH negatif; gambaran mendukung infeksi Corynebacterium.', 'abnormal']],
      diagnosisBanding: ['L08.1', 'B35.6', 'B37.2'],
      tatalaksana: { obatBenar: ['mupirosin_krim'], edukasi: ['kebersihan_kulit', 'kontrol_rutin'] },
      clue: 'Plak cokelat halus di lipatan tanpa tepi aktif, KOH negatif, dan respons buruk terhadap antijamur mendukung eritrasma. Jaga area kering dan gunakan antibiotik topikal; periksa diabetes bila berulang.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'erysipelas',
    spec: {
      id: 'lab_erisipelas_tungkai_ringan', nama: 'Erisipelas Tungkai Tanpa Sepsis', icd10: 'A46', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Tungkai bawah merah, hangat, dan nyeri sejak kemarin.', usia: [30, 70], vital: { td: '122/78', nadi: 92, rr: 18, suhu: 38.0, spo2: 99 },
      pembuka: ['Bagaimana kemerahan mulai dan menyebar?', 'Muncul mendadak dari lecet sela jari, batasnya jelas dan agak meluas.'],
      pertanyaan: [
        ['q_sepsis', 'rps', 'Ada menggigil hebat, bingung, pingsan, atau kencing berkurang?', 'Tidak.', true],
        ['q_risiko', 'rpd', 'Ada diabetes, gangguan imun, atau erisipelas berulang?', 'Tidak.', true],
        ['q_alergi', 'rpd', 'Pernah alergi berat terhadap penisilin?', 'Tidak.', true],
      ],
      fisik: [['kulit', 'Plak merah terang, hangat, nyeri, berbatas tegas dan sedikit meninggi di tungkai; tidak ada nekrosis atau krepitasi.'], ['umum', 'Sadar baik, perfusi normal, tidak toksik.', true]],
      diagnosisBanding: ['A46', 'L03.9', 'I80.2'],
      tatalaksana: { obatBenar: ['amoxicillin_500'], obatOpsional: ['paracetamol_500'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Plak eritem hangat, nyeri, berbatas tegas dan meninggi mendukung erisipelas streptokokus. Terapi beta-laktam, elevasi, tandai tepi, rawat pintu masuk, dan evaluasi ulang 24-48 jam; rujuk bila sepsis, progresi cepat, nekrosis, atau komorbid tidak stabil.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'scrofuloderma',
    spec: {
      id: 'lab_skrofuloderma_suspek', nama: 'Suspek Skrofuloderma - Konfirmasi Program', icd10: 'A18.4', kategori: 'kulit', prevalensi: 'rendah', harusDirujuk: true, spesialisRujukan: 'penyakit_dalam',
      keluhanUtama: 'Benjolan leher pecah menjadi luka berair yang tidak sembuh.', usia: [15, 55], vital: { ...NORMAL, suhu: 37.2 },
      pembuka: ['Benjolan dan lukanya berkembang bagaimana?', 'Dua bulan benjolan tidak nyeri, kemudian melunak dan pecah; berat badan turun.'],
      pertanyaan: [
        ['q_tb', 'rps', 'Ada batuk lama, keringat malam, demam lama, atau kontak TB?', 'Sering berkeringat malam dan paman serumah sedang berobat TB.', true],
        ['q_hiv', 'rpd', 'Pernah tes HIV atau punya gangguan imun?', 'Belum pernah tes HIV.', true],
        ['q_obat', 'rpd', 'Sudah minum antibiotik atau OAT?', 'Antibiotik biasa tidak memperbaiki, belum pernah OAT.', true],
      ],
      fisik: [['kepala_leher', 'Nodus servikal matted, sebagian fluktuatif, dengan sinus dan tepi undermined.'], ['toraks_paru', 'Suara napas vesikuler; tidak menyingkirkan TB ekstra paru.', true]],
      lab: [['tcm_spesimen_lesi', 'MTB terdeteksi; resistensi rifampisin tidak terdeteksi.', 'abnormal']],
      diagnosisBanding: ['A18.4', 'L04.0', 'C77.0'],
      tatalaksana: { obatBenar: [], edukasi: ['kepatuhan_obat', 'tanda_bahaya'] },
      konfirmasiWajib: 'tcm_spesimen_lesi',
      clue: 'Nodus dingin matted yang membentuk sinus kronis, gejala konstitusional, dan kontak TB mendukung skrofuloderma. Ambil spesimen lesi untuk pemeriksaan molekuler/histopatologi melalui jejaring dan tata laksana program TB; jangan mengarang regimen OAT atau memberi monoterapi empiris.',
      panduanResmi: PPK,
      catatanRealita: 'TCM lesi dan histopatologi tidak diasumsikan onsite; rujukan terkoordinasi adalah bagian jawaban, bukan kegagalan FKTP.',
    },
  },
  {
    catalogId: 'leprosy',
    spec: {
      id: 'lab_kusta_pausibasiler', nama: 'Kusta Pausibasiler Tanpa Reaksi', icd10: 'A30', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Ada dua bercak pucat yang mati rasa di lengan.', usia: [15, 65], vital: NORMAL,
      pembuka: ['Sejak kapan bercak ada dan apa yang berubah?', 'Enam bulan, tidak gatal, tetapi sentuhan dan panas kurang terasa.'],
      pertanyaan: [
        ['q_saraf', 'rps', 'Ada tangan atau kaki lemah, luka tak terasa, mata sulit menutup, atau nyeri saraf?', 'Tidak.', true],
        ['q_reaksi', 'rps', 'Bercak mendadak merah-bengkak, demam, atau saraf nyeri?', 'Tidak.', true],
        ['q_kontak', 'rpk', 'Ada kontak serumah dengan kusta?', 'Kakek dulu pernah berobat kusta sampai selesai.', true],
      ],
      fisik: [['kulit', 'Dua plak hipopigmentasi kering dengan hipoestesia jelas, distribusi asimetris.'], ['neurologis', 'Saraf perifer tidak menebal; kekuatan dan fungsi mata utuh.', true]],
      lab: [['slit_skin_smear', 'BTA negatif pada sediaan slit-skin smear.', 'normal']],
      diagnosisBanding: ['A30', 'B36.0', 'L30.0'],
      tatalaksana: { obatBenar: ['mdt_kusta_pb'], edukasi: ['kepatuhan_program_kusta', 'tanda_bahaya'], edukasiKritis: ['kepatuhan_program_kusta'] },
      clue: 'Kehilangan sensasi yang pasti pada lesi kulit adalah tanda kardinal kusta. Dua lesi, BTA negatif, tanpa keterlibatan saraf atau reaksi mendukung PB; registrasi program, MDT sesuai klasifikasi aktif, pemeriksaan fungsi saraf serial, perawatan diri, dan skrining kontak.',
      panduanResmi: PPK,
      catatanRealita: 'MDT adalah obat program, bukan stok formularium bebas. Kasus menyatakan diagnosis diregistrasi dan blister tersedia melalui program kusta kabupaten.',
    },
  },
  {
    catalogId: 'syphilis_12',
    spec: {
      id: 'lab_sifilis_primer', nama: 'Sifilis Primer', icd10: 'A51', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Ada luka di alat kelamin yang tidak sakit.', usia: [18, 55], vital: NORMAL,
      pembuka: ['Kapan luka muncul dan apakah ada keluhan lain?', 'Sepuluh hari lalu, satu luka bersih tidak nyeri; tiga minggu sebelumnya ada hubungan tanpa kondom.'],
      pertanyaan: [
        ['q_neuro', 'rps', 'Ada sakit kepala berat, gangguan penglihatan/pendengaran, kelemahan, atau kebingungan?', 'Tidak.', true],
        ['q_hamil', 'rpd', 'Apakah sedang hamil atau mungkin hamil?', 'Tidak.', false, 'P'],
        ['q_alergi', 'rpd', 'Pernah anafilaksis terhadap penisilin?', 'Tidak pernah.', true],
        ['q_pasangan', 'sosial', 'Apakah pasangan dapat dihubungi untuk pemeriksaan dan terapi?', 'Bisa.', true],
      ],
      fisik: [['kulit', 'Ulkus genital tunggal, dasar bersih, tepi tegas, tidak nyeri; limfadenopati inguinal tidak nyeri.'], ['neurologis', 'Tidak ada defisit atau tanda neurosifilis.', true]],
      lab: [['tes_sifilis', 'Tes treponemal reaktif dan RPR reaktif 1:32.', 'abnormal'], ['tes_hiv_serial', 'Tes HIV serial nonreaktif.', 'normal']],
      diagnosisBanding: ['A51', 'A60.0', 'A57'],
      tatalaksana: { obatBenar: ['benzatin_penisilin_24juta'], edukasi: ['cegah_ims_pasangan', 'tanda_bahaya'], edukasiKritis: ['cegah_ims_pasangan'] },
      konfirmasiWajib: 'tes_sifilis',
      clue: 'Chancre tunggal tidak nyeri dan serologi reaktif mendukung sifilis primer. Benzathine penicillin G 2,4 juta unit IM dosis tunggal, skrining HIV/IMS, penelusuran pasangan, dan tindak lanjut titer; gejala neurologis/okular atau kehamilan dengan alergi penisilin memerlukan jalur khusus.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'tinea_capitis',
    spec: {
      id: 'lab_tinea_kapitis_anak', nama: 'Tinea Kapitis Noninflamasi', icd10: 'B35.0', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Rambut anak saya patah-patah dan kulit kepala bersisik membentuk lingkaran.', keluhanUtamaOlehPendamping: true, usia: [4, 12], vital: { ...NORMAL, td: '100/64' },
      pembuka: ['Bagaimana kelainan kulit kepala bermula?', 'Tiga minggu bercak bersisik melebar dan rambut rontok pendek-pendek.'],
      pertanyaan: [
        ['q_kerion', 'rps', 'Ada bengkak lunak bernanah, nyeri berat, atau demam?', 'Tidak.', true],
        ['q_kontak', 'sosial', 'Ada kontak dengan hewan atau berbagi sisir/topi?', 'Sering bermain dengan anak kucing dan berbagi sisir dengan adiknya.', true],
        ['q_hati', 'rpd', 'Ada penyakit hati atau obat rutin?', 'Tidak.', false],
      ],
      fisik: [['kulit', 'Plak alopesia berskuama dengan black dots dan rambut patah; tidak ada kerion.'], ['kepala_leher', 'Limfonodi oksipital kecil, tidak nyeri.', false]],
      lab: [['mikroskopis_gram_koh', 'KOH rambut menunjukkan hifa/arthroconidia.', 'abnormal']],
      diagnosisBanding: ['B35.0', 'L21', 'L63.9'],
      tatalaksana: { obatBenar: ['griseofulvin_125'], edukasi: ['higiene_jamur_kulit', 'tanda_bahaya'] },
      konfirmasiWajib: 'mikroskopis_gram_koh',
      clue: 'Alopesia berskuama dengan rambut patah/black dots adalah tinea kapitis. Infeksi folikel memerlukan antijamur sistemik berbasis berat badan; terapi topikal saja tidak cukup. Periksa kontak, hewan, dan respons; rujuk bila kerion berat atau diagnosis meragukan.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'tinea_barbae',
    spec: {
      id: 'lab_tinea_barbae', nama: 'Tinea Barbae Noninflamasi', icd10: 'B35.0', kategori: 'kulit', prevalensi: 'rendah', jenisKelamin: 'L',
      keluhanUtama: 'Daerah jenggot bersisik, gatal, dan rambut mudah tercabut.', usia: [20, 60], vital: NORMAL,
      pembuka: ['Kelainan di jenggot berkembang bagaimana?', 'Dua minggu membentuk lingkaran dan rambut patah setelah memakai alat cukur bersama.'],
      pertanyaan: [
        ['q_berat', 'rps', 'Ada bengkak bernanah, demam, atau nyeri hebat?', 'Tidak.', true],
        ['q_hewan', 'sosial', 'Kontak hewan ternak atau alat cukur bersama?', 'Saya bekerja dengan sapi dan alat cukur sempat dipakai bersama.', true],
        ['q_hati', 'rpd', 'Ada penyakit hati atau obat rutin?', 'Tidak.', false],
      ],
      fisik: [['kulit', 'Plak annular berskuama di area jenggot dengan rambut patah, tanpa pustul dalam atau kerion.'], ['kepala_leher', 'Tidak ada limfadenopati bermakna.', false]],
      lab: [['mikroskopis_gram_koh', 'KOH rambut positif hifa dermatofita.', 'abnormal']],
      diagnosisBanding: ['B35.0', 'L73.9', 'L21'],
      tatalaksana: { obatBenar: ['griseofulvin_500'], edukasi: ['higiene_jamur_kulit', 'tanda_bahaya'] },
      konfirmasiWajib: 'mikroskopis_gram_koh',
      clue: 'Keterlibatan rambut jenggot dengan hifa memerlukan antijamur sistemik, bukan krim saja. Hentikan berbagi alat cukur dan evaluasi sumber hewan; inflamasi berat, abses, atau respons buruk perlu rujuk.',
      panduanResmi: PPK,
    },
  },
  ...([
    ['tinea_facialis', 'lab_tinea_fasialis', 'Tinea Fasialis', 'B35.8', 'pipi', 'Plak annular berskuama dengan tepi aktif di pipi, bagian tengah lebih tenang.', ['B35.8', 'L24', 'L93.0']],
    ['tinea_manus', 'lab_tinea_manus', 'Tinea Manus', 'B35.2', 'telapak tangan', 'Skuama difus satu telapak dengan tepi aktif; kuku belum terlibat.', ['B35.2', 'L24', 'L30.0']],
    ['tinea_cruris', 'lab_tinea_kruris', 'Tinea Kruris', 'B35.6', 'lipat paha', 'Plak annular berskuama dari lipat paha dengan central clearing; skrotum relatif bebas.', ['B35.6', 'B37.2', 'L08.1']],
    ['tinea_pedis', 'lab_tinea_pedis', 'Tinea Pedis Interdigital', 'B35.3', 'sela jari kaki', 'Maserasi dan skuama interdigital dengan tepi aktif, tanpa selulitis.', ['B35.3', 'L30.4', 'L08.1']],
  ] as const).map(([catalogId, id, nama, icd10, lokasi, temuan, diagnosisBanding]) => ({
    catalogId,
    spec: {
      id, nama, icd10, kategori: 'kulit' as const, prevalensi: 'sedang' as const,
      keluhanUtama: `Kulit ${lokasi} gatal dan membentuk bercak bersisik yang melebar.`, usia: [15, 65] as const, vital: NORMAL,
      pembuka: ['Bercaknya berkembang bagaimana?', 'Mulai kecil dua minggu lalu, tepinya makin melebar dan gatal saat berkeringat.'] as const,
      pertanyaan: [
        ['q_steroid', 'rpd', 'Sudah memakai krim steroid atau obat campuran?', 'Pernah memakai krim campur, sempat memudar lalu melebar.', true],
        ['q_kontak', 'sosial', 'Sering lembap atau berbagi handuk/pakaian?', 'Area sering lembap dan kadang berbagi handuk.', true],
        ['q_redflag', 'rps', 'Ada nanah, demam, nyeri berat, atau diabetes tidak terkontrol?', 'Tidak.', true],
      ] as const,
      fisik: [['kulit', temuan] as const, ['umum', 'Tidak ada tanda infeksi sistemik.', false] as const],
      lab: [['mikroskopis_gram_koh', 'KOH kerokan kulit menunjukkan hifa bersepta.', 'abnormal' as const] as const],
      diagnosisBanding: [...diagnosisBanding],
      tatalaksana: { obatBenar: ['mikonazol_krim'], obatSalahUmum: [{ id: 'betametason_krim', alasan: 'Steroid tunggal menyamarkan dan dapat memperluas dermatofitosis.', bahaya: 'kontraindikasi' as const }], edukasi: ['higiene_jamur_kulit', 'jaga_area_kering'] },
      konfirmasiWajib: 'mikroskopis_gram_koh',
      clue: `Tepi aktif berskuama, central clearing, dan KOH berhifa mendukung ${nama.toLowerCase()}. Gunakan antijamur topikal cukup lama dan lanjutkan setelah lesi membaik; hindari steroid tunggal.`,
      panduanResmi: PPK,
    },
  })),
  {
    catalogId: 'tinea_unguium',
    spec: {
      id: 'lab_tinea_unguium_terkonfirmasi', nama: 'Tinea Unguium Terbatas', icd10: 'B35.1', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Kuku jempol kaki menebal, rapuh, dan berubah kuning.', usia: [25, 70], vital: NORMAL,
      pembuka: ['Sejak kapan kuku berubah dan berapa kuku yang terkena?', 'Enam bulan, dua kuku kaki, perlahan menebal tanpa nyeri.'],
      pertanyaan: [
        ['q_risiko', 'rpd', 'Ada diabetes, gangguan imun, penyakit hati, atau obat rutin?', 'Tidak ada.', true],
        ['q_kulit', 'rps', 'Ada jamur sela jari atau telapak kaki?', 'Sela jari sering bersisik dan gatal.', true],
        ['q_trauma', 'rps', 'Ada trauma berulang atau cat kuku?', 'Tidak.', false],
      ],
      fisik: [['kulit', 'Dua kuku kaki distal-lateral menebal kuning dengan debris subungual; matriks proksimal tidak terlibat.'], ['ekstremitas', 'Perfusi kaki baik; tinea pedis interdigital ringan.', true]],
      lab: [['mikroskopis_gram_koh', 'KOH clipping kuku menunjukkan hifa dermatofita.', 'abnormal'], ['sgot_sgpt', 'SGOT/SGPT normal.', 'normal']],
      diagnosisBanding: ['B35.1', 'L60.3', 'L40.9'],
      tatalaksana: { obatBenar: ['griseofulvin_500'], edukasi: ['higiene_jamur_kulit', 'kontrol_rutin'] },
      konfirmasiWajib: 'mikroskopis_gram_koh',
      clue: 'Onikomikosis perlu konfirmasi mikologi sebelum terapi sistemik yang panjang. Nilai hati dan interaksi obat, gunakan griseofulvin FKTP dengan dosis serta durasi sesuai lokasi/berat badan, terapi tinea pedis bersamaan, lalu monitor respons; perubahan kuku tanpa konfirmasi tidak boleh otomatis diberi antijamur oral.',
      panduanResmi: PPK,
      catatanRealita: 'KOH dapat dilakukan bila mikroskop/operator ready; SGOT/SGPT dijadwalkan melalui jejaring bila tidak onsite.',
    },
  },
  {
    catalogId: 'pityriasis_versicolor',
    spec: {
      id: 'lab_pitiriasis_versikolor', nama: 'Pitiriasis Versikolor', icd10: 'B36.0', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Punggung saya belang terang dengan sisik sangat halus.', usia: [15, 50], vital: NORMAL,
      pembuka: ['Kapan bercak muncul dan kapan lebih jelas?', 'Sudah dua bulan, makin terlihat setelah kulit sekitar menggelap dan sedikit gatal saat berkeringat.'],
      pertanyaan: [
        ['q_sensasi', 'rps', 'Apakah bercak mati rasa atau rambut di sana berubah?', 'Tidak, rasa tetap normal.', true],
        ['q_kambuh', 'rpd', 'Pernah berulang atau mudah berkeringat?', 'Pernah dan saya bekerja di tempat panas.', true],
        ['q_obat', 'rpd', 'Sudah memakai steroid?', 'Tidak.', false],
      ],
      fisik: [['kulit', 'Makula hipopigmentasi multipel dengan fine scale di dada dan punggung; sensasi utuh.'], ['neurologis', 'Tidak ada penebalan saraf atau gangguan sensorik.', true]],
      lab: [['mikroskopis_gram_koh', 'KOH menunjukkan hifa pendek dan spora berkelompok.', 'abnormal']],
      diagnosisBanding: ['B36.0', 'L80', 'A30'],
      tatalaksana: { obatBenar: ['ketokonazol_krim'], edukasi: ['higiene_jamur_kulit', 'kontrol_rutin'] },
      clue: 'Makula ber-skuama halus di trunkus dengan sensasi normal dan KOH khas Malassezia mendukung pitiriasis versikolor. Jelaskan warna kulit pulih lebih lambat daripada eradikasi jamur dan kekambuhan umum.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'cutaneous_larva_migrans',
    spec: {
      id: 'lab_cutaneous_larva_migrans', nama: 'Cutaneous Larva Migrans', icd10: 'B76.9', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Ada garis merah berkelok di kaki yang maju setiap hari dan sangat gatal.', usia: [8, 60], vital: NORMAL,
      pembuka: ['Bagaimana garis ini mulai dan bergerak?', 'Muncul setelah berjalan tanpa alas di pantai; ujungnya maju beberapa sentimeter sehari.'],
      pertanyaan: [
        ['q_sistemik', 'rps', 'Ada sesak, demam, batuk, atau lesi sangat luas?', 'Tidak.', true],
        ['q_hamil', 'rpd', 'Sedang hamil atau menyusui?', 'Tidak.', true, 'P'],
        ['q_infeksi', 'rps', 'Ada nanah atau kemerahan meluas karena garukan?', 'Tidak.', false],
      ],
      fisik: [['kulit', 'Traktus serpiginosa eritematosa sedikit meninggi di plantar kaki, tanpa selulitis.'], ['umum', 'Afebris dan tampak baik.', false]],
      diagnosisBanding: ['B76.9', 'B86', 'L23.7'],
      tatalaksana: { obatBenar: ['ivermektin_3'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Erupsi serpiginosa yang bermigrasi setelah kontak tanah/pasir khas CLM. Beri antihelmintik sesuai berat badan dan status pasien, rawat ekskoriasi, serta anjurkan alas kaki; lesi luas atau keterlibatan sistemik perlu evaluasi lanjut.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'filariasis',
    spec: {
      id: 'lab_filariasis_terkonfirmasi', nama: 'Filariasis Limfatik Terkonfirmasi', icd10: 'B74', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Tungkai saya beberapa kali bengkak dan demam setelah tinggal di daerah endemis.', usia: [18, 65], vital: { ...NORMAL, suhu: 37.3 },
      pembuka: ['Bagaimana pola bengkak dan demamnya?', 'Berulang beberapa bulan; selangkangan nyeri saat demam lalu tungkai membengkak.'],
      pertanyaan: [
        ['q_daerah', 'sosial', 'Pernah tinggal lama di daerah endemis dan sering digigit nyamuk malam?', 'Tiga tahun bekerja di daerah endemis dan sering digigit nyamuk.', true],
        ['q_akut', 'rps', 'Sekarang ada kemerahan cepat, luka, atau demam tinggi?', 'Tidak, saat ini hanya bengkak ringan.', true],
        ['q_obat', 'rpd', 'Pernah mengikuti pengobatan filariasis atau punya penyakit berat?', 'Belum pernah.', true],
      ],
      fisik: [['ekstremitas', 'Edema unilateral ringan dengan penebalan kulit awal, tanpa selulitis akut.'], ['kulit', 'Tidak ada ulkus atau infeksi interdigital aktif.', true]],
      lab: [['apusan_darah_mikrofilaria', 'Mikrofilaria terdeteksi pada apusan darah malam.', 'abnormal']],
      diagnosisBanding: ['B74', 'I89.0', 'I82.4'],
      tatalaksana: { obatBenar: ['dietilkarbamazin_100', 'albendazol_400'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      konfirmasiWajib: 'apusan_darah_mikrofilaria',
      clue: 'Paparan endemis, episode adenolimfangitis, edema limfatik, dan mikrofilaria malam mendukung filariasis. Terapi harus mengikuti program/dosis berbasis berat badan dan epidemiologi setempat, disertai perawatan tungkai serta pencegahan gigitan; jangan terapi massal improvisasi pada diagnosis belum pasti.',
      panduanResmi: PPK,
      catatanRealita: 'Pemeriksaan malam dan obat program dijadwalkan melalui jejaring kabupaten; keduanya tidak diasumsikan selalu tersedia spontan di meja poli.',
    },
  },
  {
    catalogId: 'pediculosis_pubis',
    spec: {
      id: 'lab_pedikulosis_pubis', nama: 'Pedikulosis Pubis', icd10: 'B85.3', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Daerah kemaluan sangat gatal dan saya melihat kutu kecil.', usia: [18, 60], vital: NORMAL,
      pembuka: ['Kapan gatal mulai dan apa yang terlihat?', 'Dua minggu, terutama malam; ada telur menempel pada rambut.'],
      pertanyaan: [
        ['q_mata', 'rps', 'Ada kutu pada bulu mata atau iritasi mata?', 'Tidak.', true],
        ['q_kontak', 'sosial', 'Ada pasangan dengan gatal serupa dan kapan kontak seksual terakhir?', 'Pasangan juga gatal.', true],
        ['q_alergi', 'rpd', 'Pernah alergi berat terhadap obat kulit?', 'Tidak.', false],
        ['q_hamil', 'rpd', 'Sedang hamil atau menyusui?', 'Tidak.', false, 'P'],
      ],
      fisik: [['kulit', 'Kutu dan nits melekat pada rambut pubis dengan ekskoriasi, tanpa infeksi sekunder.'], ['mata', 'Tidak ada infestasi bulu mata.', true]],
      diagnosisBanding: ['B85.3', 'B86', 'L24'],
      tatalaksana: { obatBenar: ['permetrin_losion_1'], edukasi: ['cegah_ims_pasangan', 'cuci_seprai_panas'] },
      clue: 'Identifikasi kutu/nits pada rambut pubis menegakkan pedikulosis pubis. Terapi pedikulisida sesuai petunjuk, obati pasangan/kontak, cuci pakaian dan seprai, skrining IMS, dan evaluasi ulang bila masih ada kutu hidup.',
      panduanResmi: PPK,
      catatanRealita: 'Permetrin 1% adalah pilihan EBM tetapi Fornas 1199/2025 hanya mencantumkan krim 5%. Skenario menyatakan losio 1% tersedia melalui pengadaan lokal; jangan menukar konsentrasi diam-diam.',
    },
  },
  {
    catalogId: 'insect_bite',
    spec: {
      id: 'lab_reaksi_gigitan_serangga', nama: 'Reaksi Lokal Gigitan Serangga', icd10: 'T63.4', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Lengan saya bentol gatal setelah berkebun.', usia: [12, 70], vital: NORMAL,
      pembuka: ['Apa yang terjadi sebelum bentol muncul?', 'Terasa digigit serangga kemarin, lalu muncul tiga bentol gatal di area terbuka.'],
      pertanyaan: [
        ['q_anafilaksis', 'rps', 'Ada sesak, suara serak, bibir bengkak, muntah, atau hampir pingsan?', 'Tidak.', true],
        ['q_infeksi', 'rps', 'Ada demam, nanah, atau merah cepat meluas?', 'Tidak.', true],
        ['q_riwayat', 'rpd', 'Pernah reaksi berat karena sengatan?', 'Tidak.', false],
      ],
      fisik: [['kulit', 'Tiga papul urtikarial dengan punctum sentral, edema lokal kecil, tanpa selulitis.'], ['toraks_paru', 'Tidak ada wheezing atau stridor.', true]],
      diagnosisBanding: ['T63.4', 'L50.0', 'L03.9'],
      tatalaksana: { obatBenar: [], obatOpsional: ['cetirizine_10', 'hidrokortison_krim'], edukasi: ['kebersihan_kulit', 'rencana_anafilaksis'] },
      clue: 'Papul gatal lokal dengan punctum tanpa gejala sistemik adalah reaksi gigitan lokal. Kompres dingin, antihistamin/topikal ringan, hindari garuk, dan ajarkan tanda anafilaksis atau infeksi sekunder.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'dermatitis_kontak',
    spec: {
      id: 'lab_dermatitis_kontak_iritan_tangan', nama: 'Dermatitis Kontak Iritan Tangan', icd10: 'L24', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Kedua tangan merah, kering, dan perih setelah sering memakai deterjen.', usia: [18, 65], vital: NORMAL,
      pembuka: ['Kapan ruam muncul dan apa hubungannya dengan pekerjaan?', 'Memburuk setiap selesai mencuci tanpa sarung tangan dan membaik saat libur.'],
      pertanyaan: [
        ['q_alergi', 'rps', 'Apakah ruam meluas ke area yang tidak terkena atau muncul cepat setelah sedikit paparan?', 'Tidak, terbatas di tangan yang terkena deterjen.', true],
        ['q_infeksi', 'rps', 'Ada nanah, demam, atau nyeri berdenyut?', 'Tidak.', true],
        ['q_obat', 'rpd', 'Sudah memakai krim apa?', 'Hanya pelembap sesekali.', false],
      ],
      fisik: [['kulit', 'Eritema, xerosis, fisura halus pada dorsum dan sela jari kedua tangan sesuai area paparan; tanpa pus.'], ['umum', 'Tidak ada tanda sistemik.', false]],
      diagnosisBanding: ['L24', 'L23', 'B35.2'],
      tatalaksana: { obatBenar: ['hidrokortison_krim', 'emolien_petrolatum'], edukasi: ['jaga_kelembapan_kulit', 'kebersihan_kulit'] },
      clue: 'Hubungan dosis-paparan, batas sesuai area kontak, dan perbaikan saat bebas kerja mendukung dermatitis iritan. Hentikan/kurangi iritan, gunakan sarung tangan yang tepat, emolien sering, dan steroid topikal potensi ringan singkat pada inflamasi.',
      panduanResmi: PPK,
      catatanRealita: 'Petrolatum diperlakukan sebagai bahan perawatan kulit hasil pengadaan lokal, bukan klaim item obat Fornas. Bila tidak ada, pilih emolien sederhana tanpa pewangi yang tersedia.',
    },
  },
  {
    catalogId: 'atopic_dermatitis',
    spec: {
      id: 'lab_dermatitis_atopik_ringan', nama: 'Dermatitis Atopik Ringan', icd10: 'L20', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Lipatan siku dan lutut gatal berulang sejak kecil.', usia: [5, 35], vital: NORMAL,
      pembuka: ['Bagaimana pola kambuh dan lokasi gatalnya?', 'Kambuh saat udara kering, terutama malam, di kedua lipatan.'],
      pertanyaan: [
        ['q_atopi', 'rpk', 'Ada asma, rinitis alergi, atau keluarga dengan keluhan serupa?', 'Saya punya rinitis alergi dan ibu punya asma.', true],
        ['q_infeksi', 'rps', 'Ada cairan kuning, nyeri, demam, atau vesikel menyebar?', 'Tidak.', true],
        ['q_perawatan', 'rpd', 'Sabun dan pelembap apa yang digunakan?', 'Sering mandi air panas dan jarang memakai pelembap.', true],
      ],
      fisik: [['kulit', 'Plak eksematosa simetris di fossa kubiti/poplitea dengan xerosis dan ekskoriasi, tanpa infeksi.'], ['toraks_paru', 'Tidak ada wheezing saat ini.', false]],
      diagnosisBanding: ['L20', 'L24', 'B86'],
      tatalaksana: { obatBenar: ['hidrokortison_krim', 'emolien_petrolatum'], edukasi: ['jaga_kelembapan_kulit', 'tanda_bahaya'] },
      clue: 'Pruritus kronik berulang, distribusi fleksural, xerosis, dan riwayat atopi mendukung dermatitis atopik. Emolien adalah fondasi; steroid topikal ringan digunakan singkat pada flare, dengan pencetus dan infeksi sekunder dievaluasi.',
      panduanResmi: PPK,
      catatanRealita: 'Petrolatum adalah baseline pengadaan lokal untuk pemulihan sawar kulit dan tidak diklaim sebagai item Fornas. Produk harus sederhana, tanpa pewangi, dan dapat diganti emolien lokal yang setara.',
    },
  },
  {
    catalogId: 'nummular_dermatitis',
    spec: {
      id: 'lab_dermatitis_numularis', nama: 'Dermatitis Numularis', icd10: 'L30.0', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Ada bercak bulat seperti koin yang sangat gatal di tungkai.', usia: [25, 70], vital: NORMAL,
      pembuka: ['Bercaknya berubah bagaimana?', 'Muncul beberapa bercak bulat setelah kulit sangat kering; tidak melebar dengan tepi cincin.'],
      pertanyaan: [
        ['q_jamur', 'rps', 'Apakah tepi lebih aktif dan bagian tengah sembuh?', 'Tidak, seluruh bercak sama-sama merah dan bersisik.', true],
        ['q_infeksi', 'rps', 'Ada nanah, kerak madu, demam, atau nyeri?', 'Tidak.', true],
        ['q_pencetus', 'sosial', 'Sering mandi panas atau memakai sabun keras?', 'Iya, mandi air panas dua kali sehari.', false],
      ],
      fisik: [['kulit', 'Plak eksematosa berbentuk koin, batas tegas, berskuama merata tanpa central clearing.'], ['umum', 'Kulit umum xerotik.', true]],
      lab: [['mikroskopis_gram_koh', 'KOH negatif.', 'normal']],
      diagnosisBanding: ['L30.0', 'B35.4', 'L20'],
      tatalaksana: { obatBenar: ['hidrokortison_krim', 'emolien_petrolatum'], edukasi: ['jaga_kelembapan_kulit', 'kontrol_rutin'] },
      clue: 'Plak eksematosa berbentuk koin tanpa central clearing dan KOH negatif mendukung dermatitis numularis. Pulihkan sawar kulit dan gunakan steroid topikal singkat; jangan memberi antijamur hanya karena bentuknya bulat.',
      panduanResmi: PPK,
      catatanRealita: 'Petrolatum adalah emolien pengadaan lokal, bukan item Fornas. Skenario tidak bergantung pada merek tertentu dan menerima emolien sederhana tanpa pewangi yang setara.',
    },
  },
  {
    catalogId: 'napkin_eczema',
    spec: {
      id: 'lab_dermatitis_popok_iritan', nama: 'Dermatitis Popok Iritan', icd10: 'L22', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Kulit bayi merah di area popok sejak diare ringan.', keluhanUtamaOlehPendamping: true, usia: [0, 0], usiaBulan: [3, 11], vital: { nadi: 118, rr: 28, suhu: 36.8, spo2: 99 },
      pembuka: ['Kapan ruam muncul dan bagian mana yang terkena?', 'Tiga hari setelah lebih sering BAB; bagian menonjol merah tetapi lipatan relatif bersih.'],
      pertanyaan: [
        ['q_kandida', 'rps', 'Apakah lipatan ikut merah dengan bintil-bintil satelit?', 'Tidak.', true],
        ['q_sistemik', 'rps', 'Ada demam, lepuh, luka bernanah, atau bayi sulit minum?', 'Tidak.', true],
        ['q_perawatan', 'sosial', 'Seberapa sering popok diganti dan produk apa yang dipakai?', 'Kadang terlambat diganti dan memakai tisu berpewangi.', true],
      ],
      fisik: [['kulit', 'Eritema konfluens pada area cembung tertutup popok, lipatan relatif spared, tanpa pustul satelit.'], ['umum', 'Bayi aktif dan hidrasi baik.', false]],
      diagnosisBanding: ['L22', 'B37.2', 'L21'],
      tatalaksana: { obatBenar: ['zinc_oxide_krim'], edukasi: ['higiene_genital_lembut', 'tanda_bahaya'] },
      clue: 'Ruam pada permukaan cembung dengan lipatan relatif bebas mendukung dermatitis popok iritan. Ganti popok sering, bilas lembut, beri waktu bebas popok dan barrier zinc oxide; candidiasis melibatkan lipatan dan pustul satelit.',
      panduanResmi: PPK,
      catatanRealita: 'Zinc oxide adalah barrier hasil pengadaan lokal/OTC dan tidak diklaim sebagai item Fornas. Bila tidak ada, petrolatum sederhana dapat dipakai sebagai barrier pengganti.',
    },
  },
  {
    catalogId: 'seborrheic_dermatitis',
    spec: {
      id: 'lab_dermatitis_seboroik_dewasa', nama: 'Dermatitis Seboroik Dewasa', icd10: 'L21', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Kulit kepala dan sisi hidung bersisik berminyak dan gatal.', usia: [18, 65], vital: NORMAL,
      pembuka: ['Di mana sisik muncul dan bagaimana pola kambuhnya?', 'Berulang di kulit kepala, alis, dan samping hidung; memburuk saat stres.'],
      pertanyaan: [
        ['q_berat', 'rps', 'Ada rambut rontok bercak, pus, atau nyeri?', 'Tidak.', true],
        ['q_imun', 'rpd', 'Keluhan mendadak sangat berat atau ada gangguan imun/neurologis?', 'Tidak.', false],
        ['q_produk', 'sosial', 'Produk rambut apa yang digunakan?', 'Sampo biasa dan gel rambut.', false],
      ],
      fisik: [['kulit', 'Skuama kekuningan berminyak di scalp, alis, dan lipatan nasolabial dengan eritem ringan.'], ['kepala_leher', 'Tidak ada alopesia sikatriks atau limfadenopati.', true]],
      diagnosisBanding: ['L21', 'L40.9', 'B35.0'],
      tatalaksana: { obatBenar: ['ketokonazol_krim'], obatOpsional: ['hidrokortison_krim'], edukasi: ['jaga_kelembapan_kulit', 'kontrol_rutin'] },
      clue: 'Skuama berminyak pada area seboroik khas dermatitis seboroik. Antijamur topikal adalah inti; steroid ringan hanya singkat pada inflamasi, bukan pemakaian kontinu di wajah.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'pityriasis_rosea',
    spec: {
      id: 'lab_pitiriasis_rosea', nama: 'Pitiriasis Rosea', icd10: 'L42', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Bermula satu bercak besar, lalu muncul banyak bercak kecil di badan.', usia: [10, 40], vital: NORMAL,
      pembuka: ['Bagaimana urutan ruam muncul?', 'Satu bercak oval muncul seminggu lalu, kemudian bercak lebih kecil mengikuti garis kulit di punggung.'],
      pertanyaan: [
        ['q_obat', 'rpd', 'Ada obat baru sebelum ruam?', 'Tidak.', true],
        ['q_sifilis', 'sosial', 'Ada risiko seksual, luka genital, atau ruam di telapak tangan/kaki?', 'Tidak.', true],
        ['q_hamil', 'rpd', 'Sedang hamil atau mungkin hamil?', 'Tidak.', false, 'P'],
      ],
      fisik: [['kulit', 'Herald patch oval dengan collarette scale dan lesi lebih kecil pola Christmas-tree di trunkus; telapak bebas.'], ['umum', 'Tidak demam dan tidak ada limfadenopati.', false]],
      diagnosisBanding: ['L42', 'B36.0', 'A53.9'],
      tatalaksana: { obatBenar: [], obatOpsional: ['cetirizine_10'], edukasi: ['kontrol_rutin', 'tanda_bahaya'] },
      clue: 'Herald patch diikuti erupsi oval sejajar garis kulit mendukung pitiriasis rosea yang umumnya swasirna 6-8 minggu. Beri reassurance dan terapi gatal; telusuri obat, sifilis, serta kehamilan bila pola tidak khas.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'acne_vulgaris',
    spec: {
      id: 'lab_akne_vulgaris_ringan', nama: 'Akne Vulgaris Ringan', icd10: 'L70.0', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Wajah saya banyak komedo dan beberapa jerawat kecil.', usia: [12, 30], vital: NORMAL,
      pembuka: ['Jerawatnya seperti apa dan apakah meninggalkan bekas?', 'Enam bulan, terutama komedo dan bintil merah kecil, belum ada benjolan dalam atau bekas cekung.'],
      pertanyaan: [
        ['q_obat', 'rpd', 'Ada obat atau kosmetik berminyak, steroid, atau suplemen tertentu?', 'Memakai pomade berminyak.', true],
        ['q_hormonal', 'rps', 'Apakah siklus menstruasi sangat tidak teratur atau tumbuh rambut berlebih?', 'Siklus teratur dan tidak ada rambut berlebih.', false, 'P'],
        ['q_psikososial', 'sosial', 'Seberapa mengganggu perasaan dan aktivitas?', 'Agak minder tetapi tetap sekolah.', true],
      ],
      fisik: [['kulit', 'Komedo terbuka/tertutup dan beberapa papul-pustul kecil, tanpa nodul, kista, atau scar.'], ['umum', 'Tidak ada tanda hiperandrogenisme.', false]],
      diagnosisBanding: ['L70.0', 'L73.9', 'L71.0'],
      tatalaksana: { obatBenar: ['benzoyl_peroksida_25'], edukasi: ['kebersihan_kulit', 'kontrol_rutin'] },
      clue: 'Komedo membedakan akne dari folikulitis/perioral dermatitis. Akne ringan mulai dengan benzoyl peroxide tipis dan bertahap, perawatan nonkomedogenik, serta evaluasi 6-8 minggu; antibiotik topikal tidak digunakan tunggal.',
      panduanResmi: PPK,
      catatanRealita: 'Benzoil peroksida tidak diklaim sebagai item Fornas; skenario menyatakan stok pengadaan lokal/OTC tersedia. Mulai tipis dan bertahap untuk mengurangi iritasi.',
    },
  },
  {
    catalogId: 'hidradenitis',
    spec: {
      id: 'lab_hidradenitis_supuratif_hurley1', nama: 'Hidradenitis Supuratif Hurley I', icd10: 'L73.2', kategori: 'kulit', prevalensi: 'rendah',
      keluhanUtama: 'Benjolan nyeri berulang di ketiak, kadang pecah sendiri.', usia: [18, 50], vital: NORMAL,
      pembuka: ['Seberapa sering benjolan muncul dan apakah ada terowongan atau bekas?', 'Tiga kali dalam enam bulan, satu-dua benjolan, belum ada terowongan atau jaringan parut lebar.'],
      pertanyaan: [
        ['q_lokasi', 'rps', 'Ada juga di lipat paha, bawah payudara, atau bokong?', 'Kadang satu di lipat paha.', true],
        ['q_risiko', 'sosial', 'Merokok atau ada berat badan berlebih?', 'Saya merokok dan berat badan berlebih.', true],
        ['q_sistemik', 'rps', 'Ada demam atau kemerahan cepat meluas?', 'Tidak.', true],
      ],
      fisik: [['kulit', 'Dua nodul inflamasi dalam di aksila, tanpa sinus tract, bridging scar, atau selulitis luas.'], ['umum', 'Afebris dan tidak toksik.', false]],
      diagnosisBanding: ['L73.2', 'L02', 'L73.9'],
      tatalaksana: { obatBenar: ['klindamisin_topikal_1'], edukasi: ['kebersihan_kulit', 'kontrol_rutin'] },
      clue: 'Nodul nyeri rekuren pada area intertriginosa mendukung hidradenitis; Hurley I belum memiliki sinus/scar luas. Kurangi rokok, friksi, dan berat badan; terapi topikal dapat dipakai pada penyakit ringan, sedangkan flare sering, terowongan, atau dampak besar perlu rujuk.',
      panduanResmi: PPK,
      catatanRealita: 'Klindamisin topikal tidak diklaim sebagai item Fornas dan tersedia di skenario melalui pengadaan lokal. Bila tidak tersedia, jangan mengganti dengan kombinasi antibiotik sistemik tanpa penilaian ulang.',
    },
  },
  {
    catalogId: 'perioral_dermatitis',
    spec: {
      id: 'lab_dermatitis_perioral', nama: 'Dermatitis Perioral', icd10: 'L71.0', kategori: 'kulit', prevalensi: 'sedang', jenisKelamin: 'P',
      keluhanUtama: 'Sekitar mulut saya muncul bintil merah setelah sering memakai krim steroid.', usia: [18, 50], vital: NORMAL,
      pembuka: ['Bagaimana ruam bermula dan krim apa yang dipakai?', 'Awalnya sedikit merah lalu saya pakai steroid wajah; sesaat membaik tetapi bintil makin banyak.'],
      pertanyaan: [
        ['q_gejala', 'rps', 'Ada komedo, lepuh, kerak madu, atau nyeri mata?', 'Tidak ada komedo atau keluhan mata.', true],
        ['q_produk', 'sosial', 'Menggunakan kosmetik oklusif atau semprot steroid hidung?', 'Memakai kosmetik tebal.', false],
        ['q_hamil', 'rpd', 'Sedang hamil atau menyusui?', 'Tidak.', true],
      ],
      fisik: [['kulit', 'Papul eritem kecil perioral dengan vermilion border spared, tanpa komedo.'], ['mata', 'Tidak ada keterlibatan okular.', false]],
      diagnosisBanding: ['L71.0', 'L70.0', 'L21'],
      tatalaksana: { obatBenar: [], obatOpsional: ['metronidazol_topikal_075'], obatSalahUmum: [{ id: 'betametason_krim', alasan: 'Steroid wajah mempertahankan rebound dan memperburuk dermatitis perioral.', bahaya: 'kontraindikasi' }], edukasi: ['kebersihan_kulit', 'kontrol_rutin'] },
      clue: 'Papul perioral tanpa komedo dengan sparing vermilion dan paparan steroid mendukung dermatitis perioral. Hentikan steroid wajah dengan konseling kemungkinan rebound, sederhanakan produk, dan gunakan terapi topikal; kasus berat/refrakter dirujuk.',
      panduanResmi: PPK,
      catatanRealita: 'Menghentikan steroid dan kosmetik oklusif adalah inti. Metronidazol topikal hanya opsi pengadaan lokal/non-Fornas; ketiadaannya tidak boleh memicu antibiotik oral otomatis.',
    },
  },
  {
    catalogId: 'miliaria',
    spec: {
      id: 'lab_miliaria_rubra', nama: 'Miliaria Rubra', icd10: 'L74.3', kategori: 'kulit', prevalensi: 'tinggi',
      keluhanUtama: 'Leher dan punggung muncul bintil merah pedih saat cuaca panas.', usia: [5, 65], vital: NORMAL,
      pembuka: ['Kapan bintil muncul dan apa pemicunya?', 'Muncul setelah beberapa hari sangat panas dan berkeringat, terutama di area tertutup pakaian.'],
      pertanyaan: [
        ['q_infeksi', 'rps', 'Ada demam, nanah, atau nyeri berat?', 'Tidak.', true],
        ['q_obat', 'rpd', 'Ada obat baru atau alergi berat?', 'Tidak.', false],
        ['q_oklusi', 'sosial', 'Pakaian tebal/ketat atau banyak krim berminyak?', 'Sering memakai pakaian kerja tebal.', true],
      ],
      fisik: [['kulit', 'Papul-vesikel eritem kecil nonfolikular di leher dan punggung atas pada area oklusi, tanpa pustul.'], ['umum', 'Afebris dan tampak baik.', false]],
      diagnosisBanding: ['L74.3', 'L73.9', 'L27.0'],
      tatalaksana: { obatBenar: ['kalamin_losion'], edukasi: ['kebersihan_kulit', 'tanda_bahaya'] },
      clue: 'Papul kecil pada area panas/oklusi tanpa gejala sistemik mendukung miliaria rubra. Pendinginan lingkungan, pakaian longgar, menjaga kulit kering, dan losio penenang cukup; antibiotik atau steroid kuat tidak rutin.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'drug_eruption',
    conceptId: 'concept:exanthematous_drug_eruption',
    spec: {
      id: 'lab_erupsi_obat_morbiliformis', nama: 'Erupsi Obat Morbiliformis Tanpa SCAR', icd10: 'L27.0', kategori: 'kulit', prevalensi: 'sedang',
      keluhanUtama: 'Badan saya ruam merah gatal setelah mulai antibiotik baru.', usia: [18, 70], vital: NORMAL,
      pembuka: ['Obat apa yang baru dimulai dan kapan ruam muncul?', 'Amoksisilin mulai lima hari lalu; ruam simetris muncul kemarin dari badan.'],
      pertanyaan: [
        ['q_scar', 'rps', 'Ada luka di mulut/mata/kemaluan, lepuh, kulit nyeri, wajah bengkak, sesak, atau demam tinggi?', 'Tidak ada.', true],
        ['q_sistem', 'rps', 'Ada kuning, kencing gelap, pembesaran kelenjar, atau sangat lemas?', 'Tidak.', true],
        ['q_obat_lain', 'rpd', 'Sebutkan semua obat, jamu, dan suplemen 8 minggu terakhir.', 'Hanya amoksisilin baru; vitamin sudah lama.', true],
      ],
      fisik: [['kulit', 'Eksantema makulopapular simetris, blanching, dominan trunkus; Nikolsky negatif, tanpa bula atau purpura.'], ['tht_mulut', 'Mukosa utuh; tidak ada erosio.', true]],
      diagnosisBanding: ['L27.0', 'B09', 'L51.1'],
      tatalaksana: { obatBenar: [], obatOpsional: ['cetirizine_10'], edukasi: ['hentikan_obat_pencetus', 'tanda_bahaya'], edukasiKritis: ['hentikan_obat_pencetus'] },
      clue: 'Hubungan waktu obat baru dan eksantema simetris tanpa mukosa/organ mendukung erupsi morbiliformis sederhana. Hentikan obat tersangka bila aman, dokumentasikan alergi, terapi gejala, dan beri safety-net ketat; ruam nyeri, mukosa, bula, purpura, edema wajah, demam, atau keterlibatan organ memerlukan transfer emergensi.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'vulnus_laseratum',
    conceptId: 'concept:laceration',
    spec: {
      id: 'lab_vulnus_laseratum_lengan', nama: 'Vulnus Laseratum Sederhana', icd10: 'T14.1', kategori: 'gawat', prevalensi: 'tinggi',
      keluhanUtama: 'Lengan saya tersayat seng satu jam lalu.', usia: [12, 70], vital: NORMAL,
      pembuka: ['Bagaimana luka terjadi dan apa yang dilakukan setelahnya?', 'Tersayat tepi seng bersih, langsung ditekan kain; darah sudah berhenti.'],
      pertanyaan: [
        ['q_neurovaskular', 'rps', 'Ada kebas, lemah, jari pucat/dingin, atau perdarahan menyemprot?', 'Tidak.', true],
        ['q_kontaminasi', 'rps', 'Ada tanah, gigitan, benda tertinggal, atau luka tusuk dalam?', 'Tidak.', true],
        ['q_tetanus', 'rpd', 'Kapan vaksin tetanus terakhir?', 'Lebih dari sepuluh tahun lalu.', true],
      ],
      fisik: [['ekstremitas', 'Laserasi linear 3 cm di lengan bawah, subkutis dangkal, bersih; tendon, saraf, dan pembuluh utuh.'], ['umum', 'Hemodinamik stabil.', false]],
      diagnosisBanding: ['T14.1', 'S51.8', 'S56.9'],
      tatalaksana: { obatBenar: [], obatOpsional: ['paracetamol_500'], prosedur: ['perawatan_luka', 'hecting_luka', 'profilaksis_tetanus'], edukasi: ['rawat_luka_tetanus', 'tanda_bahaya'] },
      clue: 'Nilai neurovaskular, tendon, kontaminasi, benda asing, dan tetanus sebelum menutup luka. Luka sederhana yang telah diirigasi dapat dianestesi dan dijahit; antibiotik profilaksis tidak rutin pada laserasi bersih berisiko rendah.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'burn_grade12',
    spec: {
      id: 'lab_luka_bakar_derajat2_dangkal', nama: 'Luka Bakar Derajat II Dangkal Terbatas', icd10: 'T30', kategori: 'gawat', prevalensi: 'sedang',
      keluhanUtama: 'Lengan terkena air panas dua puluh menit lalu.', usia: [18, 65], vital: NORMAL,
      pembuka: ['Apa sumber panas, kapan, dan bagian mana yang terkena?', 'Air panas mengenai lengan bawah; langsung saya jauhkan tetapi belum dialiri air.'],
      pertanyaan: [
        ['q_khusus', 'rps', 'Ada wajah, tangan, kemaluan, sendi besar, luka melingkar, listrik, kimia, atau asap?', 'Tidak.', true],
        ['q_luas', 'rps', 'Apakah luasnya lebih besar dari beberapa telapak tangan?', 'Sekitar dua telapak tangan pasien.', true],
        ['q_tetanus', 'rpd', 'Kapan vaksin tetanus terakhir?', 'Lima tahun lalu.', false],
      ],
      fisik: [['kulit', 'Luka bakar merah, lembap, sangat nyeri, blister utuh, blanching baik, sekitar 2% TBSA lengan bawah; tidak sirkumferensial.'], ['umum', 'Jalan napas normal, hemodinamik stabil.', true]],
      diagnosisBanding: ['T30', 'T31.0', 'T14.1'],
      tatalaksana: { obatBenar: ['paracetamol_500'], prosedur: ['pendinginan_luka_bakar', 'balut_luka_bakar'], edukasi: ['pertolongan_luka_bakar', 'tanda_bahaya'], edukasiKritis: ['pertolongan_luka_bakar'] },
      clue: 'Luka merah-lembap, blister, nyeri dan blanching adalah partial-thickness dangkal. Aliri air mengalir sejuk hingga total 20 menit secepatnya, lepas perhiasan, tutup nonadheren, analgesia, dan evaluasi tetanus; jangan gunakan es/pasta/minyak atau memecahkan blister rutin.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'blunt_trauma',
    spec: {
      id: 'lab_trauma_tumpul_kepala_ringan', nama: 'Trauma Tumpul Kepala Risiko Rendah', icd10: 'S00-S09', kategori: 'gawat', prevalensi: 'sedang',
      keluhanUtama: 'Kepala terbentur lemari, tetapi saya tidak pingsan.', usia: [15, 65], vital: NORMAL,
      pembuka: ['Bagaimana benturan terjadi dan apa yang dirasakan sesudahnya?', 'Terbentur dari posisi berdiri dua jam lalu, sakit ringan, tetap ingat semua kejadian.'],
      pertanyaan: [
        ['q_redflag', 'rps', 'Ada pingsan, muntah berulang, kejang, amnesia, sakit kepala memburuk, lemah, atau cairan dari hidung/telinga?', 'Tidak.', true],
        ['q_obat', 'rpd', 'Minum antikoagulan, punya gangguan perdarahan, atau mabuk saat kejadian?', 'Tidak.', true],
        ['q_leher', 'rps', 'Ada nyeri leher atau kesemutan anggota gerak?', 'Tidak.', true],
      ],
      fisik: [['neurologis', 'GCS 15, pupil isokor-reaktif, tanpa defisit, gait normal.'], ['kepala_leher', 'Hematoma scalp kecil; tidak ada tanda fraktur basis kranii atau nyeri servikal.']],
      diagnosisBanding: ['S00-S09', 'S06.0', 'S06.5'],
      tatalaksana: { obatBenar: ['paracetamol_500'], prosedur: ['observasi_neurologis'], edukasi: ['tanda_bahaya', 'kontrol_rutin'], edukasiKritis: ['tanda_bahaya'] },
      clue: 'Trauma kepala ringan GCS 15 tanpa red flag dapat diobservasi serial dan dipulangkan dengan pendamping serta instruksi kembali yang jelas. Antikoagulan, penurunan kesadaran, defisit, kejang, muntah berulang, tanda fraktur, atau perburukan mengubah ambang rujuk/imaging.',
      panduanResmi: PPK,
    },
  },
  {
    catalogId: 'sharp_trauma',
    spec: {
      id: 'lab_trauma_tajam_kulit_kepala', nama: 'Trauma Tajam Kulit Kepala Sederhana', icd10: 'S00-S09', kategori: 'gawat', prevalensi: 'sedang',
      keluhanUtama: 'Kulit kepala tersayat tepi seng satu jam lalu.', usia: [15, 70], vital: NORMAL,
      pembuka: ['Bagaimana luka terjadi dan apa yang dirasakan sesudahnya?', 'Tepi seng menyayat dangkal saat saya membungkuk; tidak pingsan dan tetap ingat semua kejadian.'],
      pertanyaan: [
        ['q_neurologis', 'rps', 'Ada pingsan, muntah, amnesia, kejang, sakit kepala memburuk, atau lemah anggota gerak?', 'Tidak.', true],
        ['q_benda', 'rps', 'Ada benturan kuat, benda tertinggal, kontaminasi tanah, atau luka menembus tulang?', 'Tidak.', true],
        ['q_tetanus', 'rpd', 'Kapan vaksin tetanus terakhir?', 'Tidak ingat.', true],
      ],
      fisik: [['kepala_leher', 'Laserasi linear 2 cm pada kulit kepala, galea utuh, hemostasis tercapai; tidak ada step-off atau tanda fraktur basis kranii.'], ['neurologis', 'GCS 15, pupil isokor-reaktif, tanpa defisit.', true]],
      diagnosisBanding: ['S00-S09', 'T14.1', 'S06.0'],
      tatalaksana: { obatBenar: [], obatOpsional: ['paracetamol_500'], prosedur: ['perawatan_luka', 'hecting_luka', 'profilaksis_tetanus'], edukasi: ['rawat_luka_tetanus', 'tanda_bahaya'] },
      clue: 'Pada luka tajam kepala, nilai GCS, gejala neurologis, fraktur, kedalaman, kontaminasi, dan benda asing sebelum anestesi/penutupan. Irigasi dan jahit hanya luka kulit kepala sederhana; penurunan kesadaran, defisit, fraktur, penetrasi, perdarahan tak terkendali, atau benda asing perlu rujuk.',
      panduanResmi: PPK,
    },
  },
]

export const LAB_BATCH_3_CASES: KasusKlinis[] = DEFINITIONS.map(({ spec }) => buatKasusFktpLab(spec))

export const LAB_BATCH_3_ARCHETYPE_SPECS: Record<string, { conceptId: string; credits: string[] }> =
  Object.fromEntries(DEFINITIONS.map(({ catalogId, conceptId, spec }) => [
    spec.id,
    { conceptId: conceptId ?? `concept:${catalogId}`, credits: [`fktp144:${catalogId}`] },
  ]))
