import type { ItemLab, Obat, Tindakan, TopikEdukasi } from '../types'

export const OBAT_LAB: Record<string, Obat> = {
  dimenhidrinat_50: {
    id: 'dimenhidrinat_50',
    nama: 'Dimenhidrinat 50 mg',
    kelas: 'antiemetik-antivertigo',
    sediaan: 'tablet',
    hargaBeli: 300,
    hargaJual: 700,
    fornas: true,
  },
  flutikason_semprot_hidung: {
    id: 'flutikason_semprot_hidung',
    nama: 'Flutikason Semprot Hidung 50 mcg/dosis',
    kelas: 'kortikosteroid intranasal',
    sediaan: 'semprot hidung',
    hargaBeli: 45000,
    hargaJual: 65000,
    fornas: false,
  },
  triamcinolone_orabase: {
    id: 'triamcinolone_orabase',
    nama: 'Triamsinolon Asetonid 0,1% Orabase',
    kelas: 'kortikosteroid topikal oral',
    sediaan: 'pasta oral',
    hargaBeli: 15000,
    hargaJual: 25000,
    fornas: false,
  },
  nistatin_suspensi: {
    id: 'nistatin_suspensi',
    nama: 'Nistatin Suspensi 100.000 IU/mL',
    kelas: 'antijamur orofaringeal',
    sediaan: 'suspensi oral',
    hargaBeli: 12000,
    hargaJual: 22000,
    fornas: true,
  },
  ivermektin_3: {
    id: 'ivermektin_3',
    nama: 'Ivermektin 3 mg',
    kelas: 'antihelmintik',
    sediaan: 'tablet',
    hargaBeli: 2500,
    hargaJual: 5000,
    fornas: true,
  },
  prazikuantel_600: {
    id: 'prazikuantel_600',
    nama: 'Prazikuantel 600 mg',
    kelas: 'antihelmintik',
    sediaan: 'tablet',
    hargaBeli: 2500,
    hargaJual: 5000,
    fornas: true,
  },
}
export const LAB_LAB: Record<string, ItemLab> = {
  anti_hav_igm: {
    id: 'anti_hav_igm',
    nama: 'IgM Anti-HAV',
    biaya: 160000,
    nilaiNormal: 'Nonreaktif',
    hasilBesok: true,
  },
}

export const EDUKASI_LAB: Record<string, TopikEdukasi> = {
  istirahat_suara: {
    id: 'istirahat_suara',
    nama: '[THT] Istirahat suara, cukup minum, dan hindari asap',
    kategori: 'tindakan',
    sinonim: ['laringitis', 'serak', 'vocal rest'],
  },
  cegah_mabuk_perjalanan: {
    id: 'cegah_mabuk_perjalanan',
    nama: '[Perjalanan] Duduk stabil, lihat horizon, dan waspadai kantuk obat',
    kategori: 'tindakan',
    sinonim: ['mabuk kendaraan', 'dimenhidrinat', 'motion sickness'],
  },
  jangan_pencet_furunkel_hidung: {
    id: 'jangan_pencet_furunkel_hidung',
    nama: '[Hidung] Jangan pencet atau insisi sendiri furunkel hidung',
    kategori: 'higiene',
    sinonim: ['bisul hidung', 'furunkel', 'segitiga wajah'],
  },
  hindari_iritan_hidung: {
    id: 'hindari_iritan_hidung',
    nama: '[Hidung] Hindari asap, parfum tajam, dan perubahan suhu pemicu',
    kategori: 'gaya_hidup',
    sinonim: ['rinitis vasomotor', 'iritan', 'asap'],
  },
  higiene_mulut: {
    id: 'higiene_mulut',
    nama: '[Mulut] Jaga higiene mulut dan hindari trauma mukosa',
    kategori: 'higiene',
    sinonim: ['aftosa', 'sariawan', 'kandidiasis oral'],
  },
  eliminasi_makanan_terarah: {
    id: 'eliminasi_makanan_terarah',
    nama: '[Makanan] Catat pemicu, baca label, dan eliminasi terarah',
    kategori: 'diet',
    sinonim: ['alergi makanan', 'intoleransi', 'food diary'],
  },
  cegah_cacing_tanah: {
    id: 'cegah_cacing_tanah',
    nama: '[Cacing tanah] Pakai alas kaki, gunakan jamban, dan hentikan pencemaran tanah oleh tinja',
    kategori: 'higiene',
    sinonim: ['cacing tambang', 'strongiloidiasis', 'tanah', 'WASH', 'sanitasi'],
  },
  rencana_cacing_tambang_anemia: {
    id: 'rencana_cacing_tambang_anemia',
    nama: '[Cacing tambang] Tuntaskan obat cacing dan besi; kontrol gejala serta Hb',
    kategori: 'tindakan',
    sinonim: ['hookworm', 'anemia', 'albendazol', 'tablet Fe'],
  },
  beda_popm_cacingan: {
    id: 'beda_popm_cacingan',
    nama: '[Program cacingan] Rawat pasien; POPM ditentukan dari kelompok risiko dan data wilayah',
    kategori: 'tindakan',
    sinonim: ['deworming', 'POPM', 'sekolah', 'prevalensi'],
  },
  rencana_strongiloides_steroid: {
    id: 'rencana_strongiloides_steroid',
    nama: '[Strongyloides] Koordinasikan sebelum steroid atau imunosupresi untuk mencegah hiperinfeksi',
    kategori: 'tindakan',
    sinonim: ['kortikosteroid', 'imunosupresi', 'hiperinfeksi', 'sepsis'],
  },
  kontrol_strongiloides: {
    id: 'kontrol_strongiloides',
    nama: '[Strongyloides] Hitung ivermektin menurut berat badan dan tutup hasil kontrol bila gejala menetap',
    kategori: 'kepatuhan',
    sinonim: ['ivermektin', '200 mcg/kg', 'feses ulang', '2-4 minggu'],
  },
  hindari_air_tawar_endemis: {
    id: 'hindari_air_tawar_endemis',
    nama: '[Skistosomiasis] Ikuti peta fokus; gunakan jalur dan pelindung aman saat melintasi air',
    kategori: 'gaya_hidup',
    sinonim: ['schistosoma', 'Sulawesi Tengah', 'Napu', 'Lindu', 'Bada', 'air tawar'],
  },
  alur_program_skistosomiasis: {
    id: 'alur_program_skistosomiasis',
    nama: '[Skistosomiasis] Hubungkan hasil feses, terapi berbasis berat, kontrol, dan surveilans desa endemis',
    kategori: 'tindakan',
    sinonim: ['praziquantel', 'program', 'POPM', 'feses', 'kontrol'],
  },
  one_health_skistosomiasis: {
    id: 'one_health_skistosomiasis',
    nama: '[Skistosomiasis] Padukan WASH, pemetaan keong-air, hewan reservoir, dan pengelolaan lingkungan',
    kategori: 'higiene',
    sinonim: ['One Health', 'keong', 'ternak', 'moluskisida', 'lingkungan'],
  },
  masak_daging_matang: {
    id: 'masak_daging_matang',
    nama: '[Taeniasis] Masak dan periksa daging, gunakan jamban, dan jauhkan babi dari tinja manusia',
    kategori: 'higiene',
    sinonim: ['cacing pita', 'babi', 'sapi', 'One Health', 'inspeksi daging'],
  },
  rencana_taeniasis: {
    id: 'rencana_taeniasis',
    nama: '[Taeniasis] Hitung obat menurut berat, identifikasi spesies bila mungkin, dan pastikan proglotid berhenti',
    kategori: 'kepatuhan',
    sinonim: ['praziquantel', 'proglotid', 'Taenia solium', 'kontrol'],
  },
  tanda_bahaya_sistiserkosis: {
    id: 'tanda_bahaya_sistiserkosis',
    nama: '[Taenia solium] Rujuk sebelum terapi sederhana bila ada kejang, sakit kepala berat baru, gangguan mata, atau defisit saraf',
    kategori: 'tindakan',
    sinonim: ['neurosistiserkosis', 'kejang', 'sakit kepala', 'penglihatan'],
  },
  cegah_hepatitis_a: {
    id: 'cegah_hepatitis_a',
    nama: '[Hepatitis A] Cuci tangan, gunakan air-pangan aman, dan laporkan pajanan bersama',
    kategori: 'higiene',
    sinonim: ['HAV', 'jaundice', 'ikterus', 'warung', 'klaster', 'sanitasi'],
  },
  perawatan_hepatitis_a_rumah: {
    id: 'perawatan_hepatitis_a_rumah',
    nama: '[Hepatitis A] Cukup cairan dan nutrisi; hindari alkohol serta obat yang tidak perlu',
    kategori: 'tindakan',
    sinonim: ['hidrasi', 'nutrisi', 'hepatotoksik', 'alkohol'],
  },
  tanda_bahaya_hepatitis_akut: {
    id: 'tanda_bahaya_hepatitis_akut',
    nama: '[Hepatitis akut] Kembali segera bila mengantuk, bingung, berdarah, muntah terus, atau sulit minum',
    kategori: 'tindakan',
    sinonim: ['gagal hati', 'ensefalopati', 'perdarahan', 'rujuk'],
  },
  cegah_pertusis: {
    id: 'cegah_pertusis',
    nama: '[Pertusis] Hindari kontak rentan sampai 5 hari terapi; etika batuk dan cek imunisasi',
    kategori: 'higiene',
    sinonim: ['batuk rejan', 'droplet', 'whooping cough'],
  },
  puasa_sambil_rujuk: {
    id: 'puasa_sambil_rujuk',
    nama: '[Rujukan akut] Jangan makan/minum sampai evaluasi lanjutan',
    kategori: 'tindakan',
    sinonim: ['NPO', 'puasa', 'ileus', 'operasi', 'endoskopi', 'transfer'],
  },
  hentikan_nsaid_perdarahan_gi: {
    id: 'hentikan_nsaid_perdarahan_gi',
    nama: '[Perdarahan cerna] Hentikan ibuprofen/NSAID non-aspirin; laporkan semua antiplatelet dan antikoagulan',
    kategori: 'kepatuhan',
    sinonim: ['muntah darah', 'melena', 'ibuprofen', 'OAINS', 'aspirin', 'pengencer darah'],
  },
  aktivitas_setelah_pneumotoraks: {
    id: 'aktivitas_setelah_pneumotoraks',
    nama: '[Pneumotoraks] Tidak terbang sampai 7 hari setelah pulih radiologis; scuba hanya setelah pencegahan definitif',
    kategori: 'tindakan',
    sinonim: ['pesawat', 'penerbangan', 'menyelam', 'diving', 'kambuh', 'pleura'],
  },
}

export const TINDAKAN_LAB: Record<string, Tindakan> = {
  akses_iv_resusitasi: {
    id: 'akses_iv_resusitasi',
    nama: 'Akses IV dan cairan resusitasi terukur',
    icd9: '38.93',
    biaya: 50000,
  },
  dekompresi_ngt: {
    id: 'dekompresi_ngt',
    nama: 'Pasang NGT untuk dekompresi',
    icd9: '96.07',
    biaya: 45000,
  },
  posisi_semifowler: {
    id: 'posisi_semifowler',
    nama: 'Posisikan duduk atau semi-Fowler',
    icd9: '93.59',
    biaya: 0,
  },
}
