import type { ItemLab, Obat, Tindakan, TopikEdukasi } from '../types'

export const OBAT_LAB_EXPANSION: Record<string, Obat> = {
  arv_tld: {
    id: 'arv_tld',
    nama: 'ARV TDF 300 mg + 3TC 300 mg + DTG 50 mg',
    kelas: 'antiretroviral kombinasi program',
    sediaan: 'tablet kombinasi dosis tetap',
    hargaBeli: 0,
    hargaJual: 0,
    fornas: true,
  },
  ceftriaxone_1g_inj: {
    id: 'ceftriaxone_1g_inj',
    nama: 'Seftriakson 1 g Injeksi',
    kelas: 'antibiotik sefalosporin generasi 3',
    golonganAlergi: 'sefalosporin',
    sediaan: 'vial injeksi 1 g',
    hargaBeli: 9000,
    hargaJual: 18000,
    fornas: true,
    antibiotik: true,
  },
  klotrimazol_vaginal_100: {
    id: 'klotrimazol_vaginal_100',
    nama: 'Klotrimazol Vaginal 100 mg',
    kelas: 'antijamur azol intravaginal',
    sediaan: 'tablet vaginal',
    hargaBeli: 2500,
    hargaJual: 5000,
    fornas: true,
  },
  betametason_krim_005: {
    id: 'betametason_krim_005',
    nama: 'Betametason Valerat Krim 0,05%',
    kelas: 'kortikosteroid topikal',
    sediaan: 'krim',
    hargaBeli: 3500,
    hargaJual: 7000,
    fornas: true,
  },
  insulin_nph: {
    id: 'insulin_nph',
    nama: 'Insulin NPH 100 IU/mL',
    kelas: 'insulin basal kerja menengah',
    sediaan: 'vial atau penfill',
    hargaBeli: 65000,
    hargaJual: 85000,
    fornas: true,
  },
  insulin_regular: {
    id: 'insulin_regular',
    nama: 'Insulin Regular 100 IU/mL',
    kelas: 'insulin prandial kerja pendek',
    sediaan: 'vial atau penfill',
    hargaBeli: 65000,
    hargaJual: 85000,
    fornas: true,
  },
  benzatin_penisilin_24juta: {
    id: 'benzatin_penisilin_24juta',
    nama: 'Benzatin Benzilpenisilin 2,4 Juta IU',
    kelas: 'antibiotik penisilin kerja panjang',
    golonganAlergi: 'penisilin',
    sediaan: 'vial injeksi intramuskular',
    hargaBeli: 18000,
    hargaJual: 30000,
    fornas: true,
    antibiotik: true,
  },
  dietilkarbamazin_100: {
    id: 'dietilkarbamazin_100',
    nama: 'Dietilkarbamazin 100 mg',
    kelas: 'antifilaria program',
    sediaan: 'tablet',
    hargaBeli: 0,
    hargaJual: 0,
    fornas: true,
  },
  mdt_kusta_pb: {
    id: 'mdt_kusta_pb',
    nama: 'MDT Kusta Pausibasiler Dewasa',
    kelas: 'antimikobakteri kombinasi program',
    sediaan: 'blister bulanan program',
    hargaBeli: 0,
    hargaJual: 0,
    fornas: false,
  },
  permetrin_losion_1: {
    id: 'permetrin_losion_1',
    nama: 'Permetrin Losion 1%',
    kelas: 'pedikulisida topikal',
    sediaan: 'losion',
    hargaBeli: 7000,
    hargaJual: 13000,
    fornas: false,
  },
  emolien_petrolatum: {
    id: 'emolien_petrolatum',
    nama: 'Emolien Petrolatum',
    kelas: 'pelembap dan pelindung sawar kulit',
    sediaan: 'salep',
    hargaBeli: 6000,
    hargaJual: 11000,
    fornas: false,
  },
  zinc_oxide_krim: {
    id: 'zinc_oxide_krim',
    nama: 'Zinc Oxide Krim 10%',
    kelas: 'pelindung sawar kulit',
    sediaan: 'krim',
    hargaBeli: 5000,
    hargaJual: 9000,
    fornas: false,
  },
  benzoyl_peroksida_25: {
    id: 'benzoyl_peroksida_25',
    nama: 'Benzoil Peroksida 2,5%',
    kelas: 'antiakne topikal',
    sediaan: 'gel',
    hargaBeli: 12000,
    hargaJual: 22000,
    fornas: false,
  },
  klindamisin_topikal_1: {
    id: 'klindamisin_topikal_1',
    nama: 'Klindamisin Topikal 1%',
    kelas: 'antibiotik topikal linkosamida',
    golonganAlergi: 'linkosamida',
    sediaan: 'gel atau losion',
    hargaBeli: 14000,
    hargaJual: 25000,
    fornas: false,
    antibiotik: true,
  },
  metronidazol_topikal_075: {
    id: 'metronidazol_topikal_075',
    nama: 'Metronidazol Topikal 0,75%',
    kelas: 'antimikroba-antiinflamasi topikal',
    sediaan: 'gel',
    hargaBeli: 18000,
    hargaJual: 30000,
    fornas: false,
  },
  griseofulvin_125: {
    id: 'griseofulvin_125',
    nama: 'Griseofulvin 125 mg',
    kelas: 'antijamur sistemik',
    sediaan: 'tablet',
    hargaBeli: 350,
    hargaJual: 800,
    fornas: true,
  },
  cefadroxil_sirup_125: {
    id: 'cefadroxil_sirup_125',
    nama: 'Sefadroksil Sirup Kering 125 mg/5 mL',
    kelas: 'antibiotik sefalosporin generasi 1',
    golonganAlergi: 'sefalosporin',
    sediaan: 'sirup kering',
    hargaBeli: 6500,
    hargaJual: 12000,
    fornas: true,
    antibiotik: true,
  },
}

export const LAB_LAB_EXPANSION: Record<string, ItemLab> = {
  tes_hiv_serial: {
    id: 'tes_hiv_serial',
    nama: 'Tes Cepat HIV Serial Sesuai Algoritma Nasional',
    biaya: 0,
    nilaiNormal: 'Nonreaktif',
  },
  tcm_spesimen_lesi: {
    id: 'tcm_spesimen_lesi',
    nama: 'TCM MTB/RIF Spesimen Lesi',
    biaya: 0,
    nilaiNormal: 'MTB tidak terdeteksi',
    hasilBesok: true,
    bolehTundaTerapi: true,
  },
  tes_sifilis: {
    id: 'tes_sifilis',
    nama: 'Tes Cepat Sifilis/RPR-TP',
    biaya: 0,
    nilaiNormal: 'Nonreaktif',
  },
  apusan_darah_mikrofilaria: {
    id: 'apusan_darah_mikrofilaria',
    nama: 'Apusan Darah Malam Mikrofilaria',
    biaya: 0,
    nilaiNormal: 'Mikrofilaria tidak ditemukan',
    hasilBesok: true,
    bolehTundaTerapi: true,
  },
  slit_skin_smear: {
    id: 'slit_skin_smear',
    nama: 'Slit-Skin Smear BTA M. leprae',
    biaya: 0,
    nilaiNormal: 'BTA tidak ditemukan',
    hasilBesok: true,
  },
  ferritin_serum: {
    id: 'ferritin_serum',
    nama: 'Ferritin Serum',
    biaya: 120000,
    nilaiNormal: 'Perempuan 15-150; laki-laki 30-400 ng/mL',
    hasilBesok: true,
  },
}

export const EDUKASI_LAB_EXPANSION: Record<string, TopikEdukasi> = {
  pertolongan_kejang: { id: 'pertolongan_kejang', nama: '[Kejang] Miringkan, lindungi kepala, catat durasi, jangan memasukkan benda ke mulut', kategori: 'tindakan', sinonim: ['kejang demam', 'first aid seizure'] },
  kepatuhan_arv: { id: 'kepatuhan_arv', nama: '[HIV] Minum ARV konsisten, kontrol viral load, dan pahami U=U', kategori: 'kepatuhan', sinonim: ['ARV', 'HIV', 'undetectable'] },
  perawatan_terjadwal_somatik: { id: 'perawatan_terjadwal_somatik', nama: '[Keluhan fungsional] Validasi gejala dan gunakan kontrol terjadwal', kategori: 'kepatuhan', sinonim: ['somatoform', 'functional symptoms'] },
  higiene_kelopak_mata: { id: 'higiene_kelopak_mata', nama: '[Mata] Kompres hangat dan bersihkan tepi kelopak dengan lembut', kategori: 'higiene', sinonim: ['blefaritis', 'lid hygiene'] },
  perlindungan_mata: { id: 'perlindungan_mata', nama: '[Mata] Hindari mengucek dan gunakan pelindung saat bekerja', kategori: 'tindakan', sinonim: ['benda asing mata', 'eye protection'] },
  adaptasi_kacamata: { id: 'adaptasi_kacamata', nama: '[Refraksi] Gunakan koreksi optik sesuai hasil refraksi dan kontrol bila berubah', kategori: 'tindakan', sinonim: ['kacamata', 'miopia', 'presbiopia'] },
  perawatan_tali_pusat_kering: { id: 'perawatan_tali_pusat_kering', nama: '[Neonatus] Jaga tali pusat bersih-kering dan kenali kemerahan yang meluas', kategori: 'kia', sinonim: ['umbilikus', 'omfalitis'] },
  cegah_ims_pasangan: { id: 'cegah_ims_pasangan', nama: '[IMS] Obati pasangan, gunakan kondom, dan tunda hubungan sampai terapi selesai', kategori: 'higiene', sinonim: ['gonore', 'sifilis', 'partner treatment'] },
  higiene_genital_lembut: { id: 'higiene_genital_lembut', nama: '[Genital] Hindari douching, sabun pewangi, dan pakaian lembap', kategori: 'higiene', sinonim: ['vulvitis', 'vaginitis'] },
  perawatan_perineum: { id: 'perawatan_perineum', nama: '[Nifas] Jaga luka perineum bersih-kering dan kenali infeksi/perdarahan', kategori: 'kia', sinonim: ['ruptur perineum', 'jahitan nifas'] },
  dukungan_laktasi: { id: 'dukungan_laktasi', nama: '[Laktasi] Koreksi posisi-perlekatan dan tetap kosongkan payudara', kategori: 'kia', sinonim: ['mastitis', 'puting lecet', 'inverted nipple'] },
  keamanan_insulin: { id: 'keamanan_insulin', nama: '[DM tipe 1] Cocokkan insulin-makan, rotasi suntikan, dan siapkan penanganan hipoglikemia', kategori: 'kepatuhan', sinonim: ['insulin', 'DM1'] },
  rehabilitasi_gizi: { id: 'rehabilitasi_gizi', nama: '[Gizi] Tingkatkan energi-protein bertahap dan pantau berat badan', kategori: 'diet', sinonim: ['malnutrisi', 'PEM'] },
  diet_zat_besi: { id: 'diet_zat_besi', nama: '[Anemia] Konsumsi sumber zat besi dan pisahkan tablet Fe dari teh/kopi', kategori: 'diet', sinonim: ['ferritin', 'anemia defisiensi besi'] },
  cegah_leptospirosis: { id: 'cegah_leptospirosis', nama: '[Leptospirosis] Lindungi kulit dari air banjir dan kendalikan tikus', kategori: 'higiene', sinonim: ['banjir', 'leptospira'] },
  rencana_anafilaksis: { id: 'rencana_anafilaksis', nama: '[Anafilaksis] Hindari pemicu dan cari pertolongan segera bila gejala berulang', kategori: 'tindakan', sinonim: ['alergi berat', 'adrenalin'] },
  higiene_jamur_kulit: { id: 'higiene_jamur_kulit', nama: '[Jamur kulit] Jaga area kering dan jangan berbagi handuk atau alat cukur', kategori: 'higiene', sinonim: ['tinea', 'dermatofitosis'] },
  kepatuhan_program_kusta: { id: 'kepatuhan_program_kusta', nama: '[Kusta] Tuntaskan MDT, periksa saraf, dan cegah stigma', kategori: 'kepatuhan', sinonim: ['lepra', 'MDT'] },
  rawat_luka_tetanus: { id: 'rawat_luka_tetanus', nama: '[Luka] Jaga luka bersih dan lengkapi profilaksis tetanus sesuai status imunisasi', kategori: 'tindakan', sinonim: ['vulnus', 'tetanus toxoid'] },
  pertolongan_luka_bakar: { id: 'pertolongan_luka_bakar', nama: '[Luka bakar] Aliri air 20 menit; jangan gunakan es, pasta gigi, atau minyak', kategori: 'tindakan', sinonim: ['burn', 'pendinginan'] },
  perawatan_ulkus_tungkai: { id: 'perawatan_ulkus_tungkai', nama: '[Ulkus tungkai] Rawat luka, elevasi, dan kontrol penyakit vaskular/metabolik', kategori: 'tindakan', sinonim: ['venous ulcer', 'leg ulcer'] },
  hentikan_obat_pencetus: { id: 'hentikan_obat_pencetus', nama: '[Erupsi obat] Hentikan obat tersangka dan jangan mencoba ulang sendiri', kategori: 'kepatuhan', sinonim: ['drug eruption', 'fixed drug eruption'] },
}

export const TINDAKAN_LAB_EXPANSION: Record<string, Tindakan> = {
  ekstraksi_benda_asing_konjungtiva: { id: 'ekstraksi_benda_asing_konjungtiva', nama: 'Irigasi dan ekstraksi superfisial benda asing konjungtiva', icd9: '98.21', biaya: 35000 },
  epilasi_trikiasis: { id: 'epilasi_trikiasis', nama: 'Epilasi bulu mata penyebab trikiasis', icd9: '08.91', biaya: 25000 },
  uji_visus_refraksi: { id: 'uji_visus_refraksi', nama: 'Uji visus, pinhole, dan refraksi sederhana', icd9: '95.09', biaya: 20000 },
  perawatan_tali_pusat: { id: 'perawatan_tali_pusat', nama: 'Perawatan tali pusat bersih dan kering', icd9: '99.84', biaya: 15000 },
  reduksi_parafimosis: { id: 'reduksi_parafimosis', nama: 'Kompresi edema dan reduksi manual parafimosis', icd9: '64.0', biaya: 50000 },
  jahit_perineum: { id: 'jahit_perineum', nama: 'Anestesi lokal dan jahit ruptur perineum derajat 1-2', icd9: '75.69', biaya: 90000 },
  konseling_laktasi: { id: 'konseling_laktasi', nama: 'Observasi dan koreksi posisi-perlekatan menyusui', icd9: 'V65.4', biaya: 0 },
  adrenalin_im_anafilaksis: { id: 'adrenalin_im_anafilaksis', nama: 'Epinefrin 1 mg/mL intramuskular paha sesuai berat badan', icd9: '99.29', biaya: 25000 },
  perawatan_luka: { id: 'perawatan_luka', nama: 'Irigasi, debridemen selektif, dan balut luka', icd9: '86.28', biaya: 50000 },
  profilaksis_tetanus: { id: 'profilaksis_tetanus', nama: 'Profilaksis tetanus sesuai jenis luka dan riwayat imunisasi', icd9: '99.38', biaya: 25000 },
  pendinginan_luka_bakar: { id: 'pendinginan_luka_bakar', nama: 'Aliri luka bakar dengan air mengalir selama 20 menit', icd9: '93.57', biaya: 0 },
  balut_luka_bakar: { id: 'balut_luka_bakar', nama: 'Tutup luka bakar dengan balutan bersih nonadheren', icd9: '93.57', biaya: 30000 },
  observasi_neurologis: { id: 'observasi_neurologis', nama: 'Observasi serial GCS, pupil, dan defisit neurologis', icd9: '89.14', biaya: 15000 },
  minim_stimulus_tetanus: { id: 'minim_stimulus_tetanus', nama: 'Tempatkan pasien tetanus di ruang tenang dengan stimulus minimal', icd9: '93.59', biaya: 0 },
  antibiotik_parenteral_neonatus_protokol: { id: 'antibiotik_parenteral_neonatus_protokol', nama: 'Antibiotik parenteral awal neonatus sesuai protokol jejaring', icd9: '99.21', biaya: 30000 },
}
