import type { ItemLab, Obat, Tindakan, TopikEdukasi } from '../types'

export const OBAT_LAB_EXPANSION: Record<string, Obat> = {
  tetanus_imunoglobulin_500: {
    id: 'tetanus_imunoglobulin_500',
    nama: 'Human Tetanus Immunoglobulin 500 IU',
    kelas: 'imunoglobulin antitoksin',
    sediaan: 'injeksi intramuskular 500 IU',
    hargaBeli: 225000,
    hargaJual: 250000,
    fornas: true,
  },
  arv_tld: {
    id: 'arv_tld',
    nama: 'ARV TDF 300 mg + 3TC 300 mg + DTG 50 mg',
    kelas: 'antiretroviral kombinasi program',
    sediaan: 'tablet kombinasi dosis tetap',
    hargaBeli: 0,
    hargaJual: 0,
    fornas: true,
  },
  ceftriaxone_1g_inj: {
    id: 'ceftriaxone_1g_inj',
    nama: 'Seftriakson 1 g Injeksi',
    kelas: 'antibiotik sefalosporin generasi 3',
    golonganAlergi: 'sefalosporin',
    sediaan: 'vial injeksi 1 g',
    hargaBeli: 9000,
    hargaJual: 18000,
    fornas: true,
    antibiotik: true,
  },
  klotrimazol_vaginal_100: {
    id: 'klotrimazol_vaginal_100',
    nama: 'Klotrimazol Vaginal 100 mg',
    kelas: 'antijamur azol intravaginal',
    sediaan: 'tablet vaginal',
    hargaBeli: 2500,
    hargaJual: 5000,
    fornas: true,
  },
  betametason_krim_005: {
    id: 'betametason_krim_005',
    nama: 'Betametason Valerat Krim 0,05%',
    kelas: 'kortikosteroid topikal',
    sediaan: 'krim',
    hargaBeli: 3500,
    hargaJual: 7000,
    fornas: true,
  },
  insulin_nph: {
    id: 'insulin_nph',
    nama: 'Insulin NPH 100 IU/mL',
    kelas: 'insulin basal kerja menengah',
    sediaan: 'vial atau penfill',
    hargaBeli: 65000,
    hargaJual: 85000,
    fornas: true,
  },
  insulin_regular: {
    id: 'insulin_regular',
    nama: 'Insulin Regular 100 IU/mL',
    kelas: 'insulin prandial kerja pendek',
    sediaan: 'vial atau penfill',
    hargaBeli: 65000,
    hargaJual: 85000,
    fornas: true,
  },
  benzatin_penisilin_24juta: {
    id: 'benzatin_penisilin_24juta',
    nama: 'Benzatin Benzilpenisilin 2,4 Juta IU',
    kelas: 'antibiotik penisilin kerja panjang',
    golonganAlergi: 'penisilin',
    sediaan: 'vial injeksi intramuskular',
    hargaBeli: 18000,
    hargaJual: 30000,
    fornas: true,
    antibiotik: true,
  },
  dietilkarbamazin_100: {
    id: 'dietilkarbamazin_100',
    nama: 'Dietilkarbamazin 100 mg',
    kelas: 'antifilaria program',
    sediaan: 'tablet',
    hargaBeli: 0,
    hargaJual: 0,
    fornas: true,
  },
  mdt_kusta_pb: {
    id: 'mdt_kusta_pb',
    nama: 'MDT Kusta PB Dewasa: Rifampisin + Dapson + Klofazimin (6 Bulan)',
    kelas: 'antimikobakteri kombinasi program',
    sediaan: 'blister bulanan program',
    hargaBeli: 0,
    hargaJual: 0,
    fornas: false,
  },
  permetrin_losion_1: {
    id: 'permetrin_losion_1',
    nama: 'Permetrin Losion 1%',
    kelas: 'pedikulisida topikal',
    sediaan: 'losion',
    hargaBeli: 7000,
    hargaJual: 13000,
    fornas: false,
  },
  emolien_petrolatum: {
    id: 'emolien_petrolatum',
    nama: 'Emolien Petrolatum',
    kelas: 'pelembap dan pelindung sawar kulit',
    sediaan: 'salep',
    hargaBeli: 6000,
    hargaJual: 11000,
    fornas: false,
  },
  zinc_oxide_krim: {
    id: 'zinc_oxide_krim',
    nama: 'Zinc Oxide Krim 10%',
    kelas: 'pelindung sawar kulit',
    sediaan: 'krim',
    hargaBeli: 5000,
    hargaJual: 9000,
    fornas: false,
  },
  benzoyl_peroksida_25: {
    id: 'benzoyl_peroksida_25',
    nama: 'Benzoil Peroksida 2,5%',
    kelas: 'antiakne topikal',
    sediaan: 'gel',
    hargaBeli: 12000,
    hargaJual: 22000,
    fornas: false,
  },
  klindamisin_topikal_1: {
    id: 'klindamisin_topikal_1',
    nama: 'Klindamisin Topikal 1%',
    kelas: 'antibiotik topikal linkosamida',
    golonganAlergi: 'linkosamida',
    sediaan: 'gel atau losion',
    hargaBeli: 14000,
    hargaJual: 25000,
    fornas: false,
    antibiotik: true,
  },
  metronidazol_topikal_075: {
    id: 'metronidazol_topikal_075',
    nama: 'Metronidazol Topikal 0,75%',
    kelas: 'antimikroba-antiinflamasi topikal',
    sediaan: 'gel',
    hargaBeli: 18000,
    hargaJual: 30000,
    fornas: false,
  },
  griseofulvin_125: {
    id: 'griseofulvin_125',
    nama: 'Griseofulvin 125 mg',
    kelas: 'antijamur sistemik',
    sediaan: 'tablet',
    hargaBeli: 350,
    hargaJual: 800,
    fornas: true,
  },
  cefadroxil_sirup_125: {
    id: 'cefadroxil_sirup_125',
    nama: 'Sefadroksil Sirup Kering 125 mg/5 mL',
    kelas: 'antibiotik sefalosporin generasi 1',
    golonganAlergi: 'sefalosporin',
    sediaan: 'sirup kering',
    hargaBeli: 6500,
    hargaJual: 12000,
    fornas: true,
    antibiotik: true,
  },
}

export const LAB_LAB_EXPANSION: Record<string, ItemLab> = {
  tes_hiv_serial: {
    id: 'tes_hiv_serial',
    nama: 'Tes Cepat HIV Serial Sesuai Algoritma Nasional',
    biaya: 0,
    nilaiNormal: 'Nonreaktif',
  },
  panel_awal_hiv_jejaring: {
    id: 'panel_awal_hiv_jejaring',
    nama: 'Panel Awal HIV Jejaring (CD4, eGFR/Kreatinin, HBsAg)',
    biaya: 0,
    nilaiNormal: 'CD4 >=200 sel/mm3; eGFR >=60 mL/menit/1,73 m2; HBsAg nonreaktif',
  },
  tcm_spesimen_lesi: {
    id: 'tcm_spesimen_lesi',
    nama: 'TCM MTB/RIF Spesimen Lesi',
    biaya: 0,
    nilaiNormal: 'MTB tidak terdeteksi',
    hasilBesok: true,
    bolehTundaTerapi: true,
  },
  tes_sifilis: {
    id: 'tes_sifilis',
    nama: 'Tes Cepat Sifilis/RPR-TP',
    biaya: 0,
    nilaiNormal: 'Nonreaktif',
  },
  apusan_darah_mikrofilaria: {
    id: 'apusan_darah_mikrofilaria',
    nama: 'Apusan Darah Malam Mikrofilaria',
    biaya: 0,
    nilaiNormal: 'Mikrofilaria tidak ditemukan',
    hasilBesok: true,
    bolehTundaTerapi: true,
  },
  ferritin_serum: {
    id: 'ferritin_serum',
    nama: 'Ferritin Serum',
    biaya: 120000,
    nilaiNormal: 'Perempuan 15-150; laki-laki 30-400 ng/mL',
    hasilBesok: true,
  },
}

export const EDUKASI_LAB_EXPANSION: Record<string, TopikEdukasi> = {
  pertolongan_kejang: { id: 'pertolongan_kejang', nama: '[Kejang] Miringkan, lindungi kepala, catat durasi, jangan memasukkan benda ke mulut', kategori: 'tindakan', sinonim: ['kejang demam', 'first aid seizure'] },
  kepatuhan_arv: { id: 'kepatuhan_arv', nama: '[HIV] Minum ARV konsisten; U=U berlaku setelah supresi viral terverifikasi dan dipertahankan', kategori: 'kepatuhan', sinonim: ['ARV', 'HIV', 'undetectable', 'U=U'] },
  retensi_hiv_viral_load: { id: 'retensi_hiv_viral_load', nama: '[HIV] Jadwalkan viral load dan tawarkan re-engagement rahasia bila kunjungan terlewat', kategori: 'kepatuhan', sinonim: ['viral load', 'retensi', 'lost to follow-up', 're-engagement'] },
  pencegahan_hiv_berpusat_pasien: { id: 'pencegahan_hiv_berpusat_pasien', nama: '[HIV] Pilih pencegahan, dukungan pasangan, dan layanan reproduksi tanpa membuka status secara paksa', kategori: 'higiene', sinonim: ['kondom', 'pasangan', 'kerahasiaan', 'reproduksi'] },
  tpt_hiv_setelah_skrining_tb: { id: 'tpt_hiv_setelah_skrining_tb', nama: '[HIV-TB] Setelah TB aktif disingkirkan, nilai kelayakan TPT sesuai program', kategori: 'tindakan', sinonim: ['TPT', 'terapi pencegahan tuberkulosis', 'HIV TB', '3HP', 'isoniazid'] },
  validasi_penjelasan_somatik: { id: 'validasi_penjelasan_somatik', nama: '[Keluhan fisik persisten] Validasi gejala dan bangun penjelasan tubuh-emosi bersama pasien', kategori: 'tindakan', sinonim: ['somatoform', 'bodily distress', 'validasi gejala', 'penjelasan kolaboratif'] },
  perawatan_terjadwal_somatik: { id: 'perawatan_terjadwal_somatik', nama: '[Keluhan fisik persisten] Satu klinisi, kontrol terjadwal, dan sasaran fungsi', kategori: 'kepatuhan', sinonim: ['somatoform', 'continuity', 'scheduled follow-up', 'fungsi'] },
  aktivitas_redflag_somatik: { id: 'aktivitas_redflag_somatik', nama: '[Keluhan fisik persisten] Kembali bertahap beraktivitas; evaluasi ulang bila pola berubah', kategori: 'tindakan', sinonim: ['graded activity', 'safety net', 'red flag', 'keluhan baru'] },
  higiene_kelopak_mata: { id: 'higiene_kelopak_mata', nama: '[Mata] Kompres hangat dan bersihkan tepi kelopak dengan lembut', kategori: 'higiene', sinonim: ['blefaritis', 'lid hygiene'] },
  perlindungan_mata: { id: 'perlindungan_mata', nama: '[Mata] Hindari mengucek dan gunakan pelindung saat bekerja', kategori: 'tindakan', sinonim: ['benda asing mata', 'eye protection'] },
  perawatan_pasca_benda_asing_mata: { id: 'perawatan_pasca_benda_asing_mata', nama: '[Cedera mata] Jangan membawa pulang anestetik tetes; kontrol 24-48 jam setelah benda organik diangkat', kategori: 'kepatuhan', sinonim: ['benda asing mata', 'topical anaesthetic', 'kontrol mata', 'sekam'] },
  adaptasi_kacamata: { id: 'adaptasi_kacamata', nama: '[Refraksi] Gunakan koreksi optik sesuai hasil refraksi dan kontrol bila berubah', kategori: 'tindakan', sinonim: ['kacamata', 'miopia', 'presbiopia'] },
  perawatan_tali_pusat_kering: { id: 'perawatan_tali_pusat_kering', nama: '[Neonatus] Jaga tali pusat bersih-kering dan kenali kemerahan yang meluas', kategori: 'kia', sinonim: ['umbilikus', 'omfalitis'] },
  cegah_ims_pasangan: { id: 'cegah_ims_pasangan', nama: '[IMS] Obati pasangan, gunakan kondom, dan tunda hubungan sampai terapi selesai', kategori: 'higiene', sinonim: ['gonore', 'sifilis', 'partner treatment'] },
  tindak_lanjut_sifilis: { id: 'tindak_lanjut_sifilis', nama: '[Sifilis] Catat titer RPR awal, ulang sesuai jadwal program, dan nilai penurunan titer', kategori: 'kepatuhan', sinonim: ['RPR', 'titer', 'serologi', 'follow-up'] },
  layanan_pasangan_sifilis: { id: 'layanan_pasangan_sifilis', nama: '[Sifilis] Tawarkan layanan pasangan secara rahasia, sukarela, dan aman sesuai waktu pajanan', kategori: 'higiene', sinonim: ['partner services', 'contact', 'pasangan', 'IMS'] },
  reaksi_jarisch_herxheimer: { id: 'reaksi_jarisch_herxheimer', nama: '[Sifilis] Kenali demam-nyeri sementara pascaterapi; kehamilan memerlukan evaluasi segera', kategori: 'tindakan', sinonim: ['Jarisch-Herxheimer', 'demam setelah penisilin', 'kehamilan'] },
  tindak_lanjut_gonore: { id: 'tindak_lanjut_gonore', nama: '[Gonore] Tuntaskan cakupan klamidia, hindari hubungan sesuai interval aman, dan retest sekitar 3 bulan', kategori: 'kepatuhan', sinonim: ['gonorrhea', 'doxycycline', 'retest', 'reinfection'] },
  tindak_lanjut_servisitis: { id: 'tindak_lanjut_servisitis', nama: '[Servisitis] Tuntaskan terapi, pastikan gejala pulih, dan kembali segera bila timbul nyeri pelvis', kategori: 'kepatuhan', sinonim: ['cervicitis', 'follow-up', 'PID', 'contact bleeding'] },
  tindak_lanjut_pid: { id: 'tindak_lanjut_pid', nama: '[PID] Tuntaskan 14 hari terapi dan evaluasi ulang bila belum membaik dalam 72 jam', kategori: 'kepatuhan', sinonim: ['pelvic inflammatory disease', 'radang panggul', '72 jam', '14 hari'] },
  layanan_pasangan_ims: { id: 'layanan_pasangan_ims', nama: '[IMS] Hubungkan pasangan ke tes-terapi secara sukarela, rahasia, dan aman dari kekerasan', kategori: 'higiene', sinonim: ['partner services', 'contact tracing', 'pasangan', 'confidential'] },
  pencegahan_ims_terintegrasi: { id: 'pencegahan_ims_terintegrasi', nama: '[IMS] Tawarkan tes HIV-sifilis, kondom, vaksinasi, dan PrEP sesuai risiko serta preferensi', kategori: 'higiene', sinonim: ['HIV', 'sifilis', 'kondom', 'PrEP', 'vaksin'] },
  higiene_genital_lembut: { id: 'higiene_genital_lembut', nama: '[Genital] Hindari douching, sabun pewangi, dan pakaian lembap', kategori: 'higiene', sinonim: ['vulvitis', 'vaginitis'] },
  // Audit CODEX 2026-08-04 (temuan 7): topik di atas ber-tag [Genital] dan
  // menyebut douching — istilah higiene vulvovaginal perempuan (sinonimnya
  // eksplisit vulvitis/vaginitis) — dulu juga dipakai pada fimosis (anak
  // laki-laki 5-11 th) dan parafimosis. Douching tak berlaku sama sekali di
  // sana, sementara poin ajar sesungguhnya (tertulis di clue kedua kasus)
  // tak terwakili topik mana pun. Kelas yang SAMA dengan sapuan 2026-08-04
  // pada dermatitis popok; batch2.ts lolos dari sapuan itu.
  // Kalimat kedua topik di bawah ditranskrip dari clue kasusnya sendiri,
  // bukan anjuran klinis baru.
  jangan_tarik_paksa_kulup: { id: 'jangan_tarik_paksa_kulup', nama: '[Kulup] Jangan tarik paksa; retraksi lembut bertahap sesuai anjuran', kategori: 'higiene', sinonim: ['fimosis', 'preputium', 'kulup', 'retraksi'] },
  pascareduksi_parafimosis: { id: 'pascareduksi_parafimosis', nama: '[Kulup] Sesudah reduksi: jangan biarkan kulup tertarik ke belakang, kembali bila bengkak/nyeri memberat', kategori: 'tindakan', sinonim: ['parafimosis', 'pascareduksi', 'edema glans'] },
  // Audit tag-vs-penyakit 2026-08-04: topik di atas ber-tag [Genital] &
  // menyebut douching — istilah higiene vulvovaginal dewasa/remaja, dulu
  // dipakai lagi utk dermatitis popok BAYI (3-11 bulan). Topik baru berikut
  // spesifik utk perawatan kulit area popok.
  perawatan_area_popok: { id: 'perawatan_area_popok', nama: '[Popok] Ganti sering, bilas lembut, beri waktu bebas popok, pakai zinc oxide', kategori: 'higiene', sinonim: ['dermatitis popok', 'ruam popok', 'napkin eczema', 'zinc oxide'] },
  perawatan_perineum: { id: 'perawatan_perineum', nama: '[Nifas] Jaga luka perineum bersih-kering dan kenali infeksi/perdarahan', kategori: 'kia', sinonim: ['ruptur perineum', 'jahitan nifas'] },
  dukungan_laktasi: { id: 'dukungan_laktasi', nama: '[Laktasi] Koreksi posisi-perlekatan dan tetap kosongkan payudara', kategori: 'kia', sinonim: ['mastitis', 'puting lecet', 'inverted nipple'] },
  sick_day_dm1: { id: 'sick_day_dm1', nama: '[DM tipe 1] Jangan hentikan insulin basal saat sakit; pantau gula-keton dan cairan lebih sering', kategori: 'kepatuhan', sinonim: ['sick day', 'keton', 'DKA', 'insulin basal'] },
  hipoglikemia_dm1: { id: 'hipoglikemia_dm1', nama: '[DM tipe 1] Tangani gula rendah segera, cek ulang 10-15 menit, dan ajarkan penolong keluarga', kategori: 'tindakan', sinonim: ['hipoglikemia', 'rule of 15', 'glukosa', 'DM1'] },
  rencana_prb_dm1: { id: 'rencana_prb_dm1', nama: '[DM tipe 1] Bawa log dan resume; cocokkan dosis, target, stok, dan jadwal spesialis saat rujuk balik', kategori: 'kepatuhan', sinonim: ['PRB', 'rujuk balik', 'log gula', 'resume rumah sakit'] },
  rehabilitasi_gizi: { id: 'rehabilitasi_gizi', nama: '[Gizi] Tingkatkan energi-protein bertahap dan pantau berat badan', kategori: 'diet', sinonim: ['malnutrisi', 'PEM'] },
  rujuk_gizi_buruk_komplikasi: { id: 'rujuk_gizi_buruk_komplikasi', nama: '[Gizi buruk berkomplikasi] Jelaskan stabilisasi, rujukan rawat inap, dan larangan cairan cepat', kategori: 'tindakan', sinonim: ['gizi buruk', 'hipoglikemia', 'ReSoMal', 'rujuk TFC'] },
  rujuk_mastoiditis_anak: { id: 'rujuk_mastoiditis_anak', nama: '[Mastoiditis anak] Rujuk sekarang; bawa dokumen dan obat, ikuti arahan puasa jejaring', kategori: 'tindakan', sinonim: ['mastoiditis', 'bengkak belakang telinga', 'rujuk THT', 'puasa'] },
  rujuk_bronkiolitis_bayi: { id: 'rujuk_bronkiolitis_bayi', nama: '[Bronkiolitis berat] Rujuk sekarang dengan oksigen; jangan paksa minum saat sesak berat', kategori: 'tindakan', sinonim: ['bronkiolitis', 'bayi sesak', 'oksigen', 'rujuk anak'] },
  minum_aman_bronkiolitis_bayi: { id: 'minum_aman_bronkiolitis_bayi', nama: '[Bronkiolitis] Lanjutkan minum sesuai usia dan toleransi setelah napas aman', kategori: 'kia', sinonim: ['ASI', 'MPASI', 'hidrasi', 'minum bayi'] },
  bebas_asap_bayi: { id: 'bebas_asap_bayi', nama: '[Bayi] Jauhkan asap rokok dari rumah, kendaraan, dan pengasuh', kategori: 'higiene', sinonim: ['rokok', 'asap', 'bayi', 'secondhand smoke'] },
  alur_pmt_lokal_2025: { id: 'alur_pmt_lokal_2025', nama: '[Gizi kurang] Jalankan PMT lokal 56 hari sebagai tambahan, bukan pengganti makanan utama', kategori: 'diet', sinonim: ['PMT lokal', '56 hari', 'gizi kurang', 'Posyandu'] },
  makan_balita_padat_gizi: { id: 'makan_balita_padat_gizi', nama: '[Gizi kurang] Susun makan padat energi-protein dengan lauk hewani yang terjangkau keluarga', kategori: 'diet', sinonim: ['protein hewani', 'telur', 'ikan', 'wasting'] },
  pantau_tumbuh_mingguan: { id: 'pantau_tumbuh_mingguan', nama: '[Gizi kurang] Catat konsumsi dan pertumbuhan mingguan; evaluasi ulang bila dua minggu tanpa perbaikan', kategori: 'kepatuhan', sinonim: ['berat badan', 'Buku KIA', 'kader', 'follow-up'] },
  diet_zat_besi: { id: 'diet_zat_besi', nama: '[Anemia] Konsumsi sumber zat besi dan pisahkan tablet Fe dari teh/kopi', kategori: 'diet', sinonim: ['ferritin', 'anemia defisiensi besi'] },
  terapi_besi_terukur: { id: 'terapi_besi_terukur', nama: '[Anemia besi] Minum sekitar 60 mg besi elemental sekali sehari; selang sehari bila tidak toleran', kategori: 'kepatuhan', sinonim: ['fero sulfat', 'tablet Fe', 'mual', 'konstipasi'] },
  telusuri_sumber_anemia: { id: 'telusuri_sumber_anemia', nama: '[Anemia besi] Cari dan tangani sumber perdarahan; tablet Fe bukan penutup diagnosis', kategori: 'tindakan', sinonim: ['haid banyak', 'perdarahan', 'HMB', 'gastrointestinal'] },
  kontrol_hb_anemia: { id: 'kontrol_hb_anemia', nama: '[Anemia besi] Ulang Hb dalam 2-4 minggu dan lanjutkan besi sekitar 3 bulan setelah Hb normal', kategori: 'kepatuhan', sinonim: ['kontrol Hb', 'respons besi', 'cadangan besi', 'follow-up'] },
  cegah_leptospirosis: { id: 'cegah_leptospirosis', nama: '[Leptospirosis] Gunakan pelindung saat banjir dan petakan sumber air, rodensia, serta hewan bersama', kategori: 'higiene', sinonim: ['banjir', 'leptospira', 'tikus', 'One Health', 'klaster'] },
  rencana_leptospirosis_jejaring: { id: 'rencana_leptospirosis_jejaring', nama: '[Leptospirosis] Mulai terapi dini; atur spesimen dan fungsi ginjal-hati tanpa menunda pengobatan', kategori: 'tindakan', sinonim: ['PCR', 'IgM', 'jejaring laboratorium', 'fungsi ginjal'] },
  tanda_bahaya_leptospirosis: { id: 'tanda_bahaya_leptospirosis', nama: '[Leptospirosis] Rujuk bila kuning, urine berkurang, sesak, batuk darah, perdarahan, hipotensi, atau bingung', kategori: 'tindakan', sinonim: ['Weil', 'gagal ginjal', 'perdarahan paru', 'rujuk'] },
  alur_program_filariasis: { id: 'alur_program_filariasis', nama: '[Filariasis] Daftarkan kasus, telusuri fokus bersama program, dan jangan memulai POPM dari satu resep', kategori: 'tindakan', sinonim: ['MDA', 'POPM', 'surveilans', 'program filariasis'] },
  perawatan_limfedema_filariasis: { id: 'perawatan_limfedema_filariasis', nama: '[Filariasis] Cuci-keringkan tungkai, rawat sela jari, latihan, dan elevasi untuk mencegah serangan akut', kategori: 'tindakan', sinonim: ['MMDP', 'limfedema', 'adenolimfangitis', 'perawatan kulit'] },
  cegah_gigitan_filariasis: { id: 'cegah_gigitan_filariasis', nama: '[Filariasis] Kurangi gigitan nyamuk dan ikuti penilaian program wilayah', kategori: 'higiene', sinonim: ['kelambu', 'vektor', 'nyamuk', 'endemis'] },
  rencana_anafilaksis: { id: 'rencana_anafilaksis', nama: '[Anafilaksis] Hindari pemicu dan cari pertolongan segera bila gejala berulang', kategori: 'tindakan', sinonim: ['alergi berat', 'adrenalin'] },
  higiene_jamur_kulit: { id: 'higiene_jamur_kulit', nama: '[Jamur kulit] Jaga area kering dan jangan berbagi handuk atau alat cukur', kategori: 'higiene', sinonim: ['tinea', 'dermatofitosis'] },
  kepatuhan_program_kusta: { id: 'kepatuhan_program_kusta', nama: '[Kusta] Tuntaskan MDT tiga obat selama enam bulan dan jangan berhenti saat reaksi', kategori: 'kepatuhan', sinonim: ['lepra', 'MDT', 'rifampisin', 'dapson', 'klofazimin'] },
  perawatan_saraf_kusta: { id: 'perawatan_saraf_kusta', nama: '[Kusta] Periksa saraf-mata-tangan-kaki serial dan lindungi area mati rasa dari cedera', kategori: 'tindakan', sinonim: ['saraf', 'disabilitas', 'self-care', 'mati rasa'] },
  skrining_kontak_kusta: { id: 'skrining_kontak_kusta', nama: '[Kusta] Skrining kontak dan nilai SDR-PEP lewat program setelah consent serta cek kelayakan', kategori: 'higiene', sinonim: ['kontak serumah', 'SDR-PEP', 'rifampisin dosis tunggal', 'consent'] },
  rawat_luka_tetanus: { id: 'rawat_luka_tetanus', nama: '[Luka] Jaga luka bersih dan lengkapi profilaksis tetanus sesuai status imunisasi', kategori: 'tindakan', sinonim: ['vulnus', 'tetanus toxoid'] },
  imunitas_setelah_tetanus: { id: 'imunitas_setelah_tetanus', nama: '[Tetanus] Sakit tidak membuat kebal; lanjutkan vaksin setelah stabil dan pahami bahwa tetanus tidak menular antarmanusia', kategori: 'kepatuhan', sinonim: ['TIG', 'Td', 'toksoid', 'imunisasi', 'tidak menular'] },
  tanda_bahaya_cedera_kepala: { id: 'tanda_bahaya_cedera_kepala', nama: '[Cedera kepala] Ke IGD segera bila makin mengantuk, bingung, kejang, muntah, nyeri memburuk, lemah, atau perilaku berubah', kategori: 'tindakan', sinonim: ['cedera kepala', 'konkusi', 'red flag', 'muntah', 'kejang'] },
  pengawasan_24_jam_cedera_kepala: { id: 'pengawasan_24_jam_cedera_kepala', nama: '[Cedera kepala] Pulang hanya dengan pendamping dewasa yang mengawasi 24 jam dan mengetahui jalur kembali', kategori: 'kepatuhan', sinonim: ['pendamping', '24 jam', 'observasi rumah', 'safety net'] },
  pemulihan_bertahap_cedera_kepala: { id: 'pemulihan_bertahap_cedera_kepala', nama: '[Cedera kepala] Hindari aktivitas berisiko hari ini; bila gejala konkusi muncul, istirahat relatif 1-2 hari lalu kembali bertahap', kategori: 'tindakan', sinonim: ['return to activity', 'mengemudi', 'olahraga', 'pemulihan konkusi'] },
  pertolongan_luka_bakar: { id: 'pertolongan_luka_bakar', nama: '[Luka bakar] Aliri air 20 menit; jangan gunakan es, pasta gigi, atau minyak', kategori: 'tindakan', sinonim: ['burn', 'pendinginan'] },
  perawatan_balutan_luka_bakar: { id: 'perawatan_balutan_luka_bakar', nama: '[Luka bakar] Jaga balutan bersih; jangan pecahkan blister kecil atau membalut lengan terlalu ketat', kategori: 'tindakan', sinonim: ['burn', 'blister', 'balutan', 'nonadheren'] },
  kontrol_luka_bakar: { id: 'kontrol_luka_bakar', nama: '[Luka bakar] Kontrol 24-72 jam; kembali segera bila nyeri/kemerahan memburuk, demam, baal, jari dingin, atau balutan kotor-tembus', kategori: 'kepatuhan', sinonim: ['burn', 'kontrol', 'red flag', 'infeksi', 'neurovaskular'] },
  perawatan_ulkus_tungkai: { id: 'perawatan_ulkus_tungkai', nama: '[Ulkus tungkai] Rawat luka, elevasi, dan kontrol penyakit vaskular/metabolik', kategori: 'tindakan', sinonim: ['venous ulcer', 'leg ulcer'] },
  hentikan_obat_pencetus: { id: 'hentikan_obat_pencetus', nama: '[Erupsi obat] Hentikan obat tersangka dan jangan mencoba ulang sendiri', kategori: 'kepatuhan', sinonim: ['drug eruption', 'fixed drug eruption'] },
  // Audit tag-vs-penyakit 2026-08-04 (dossier serupa §47): hentikan_obat_pencetus
  // di atas ber-tag [Erupsi obat] (khusus ruam kulit) dulu dipakai lagi utk
  // peritonitis & retensio urin akut — penyakit yg sama sekali bukan reaksi
  // kulit. Dua topik baru berikut menggantikannya, masing2 spesifik penyebab.
  hentikan_nsaid_pencetus_ulkus: { id: 'hentikan_nsaid_pencetus_ulkus', nama: '[Lambung] Hentikan NSAID/obat warung pencetus tukak & perforasi', kategori: 'kepatuhan', sinonim: ['NSAID', 'ulkus peptikum', 'perforasi', 'obat pereda nyeri warung'] },
  hindari_antikolinergik_retensi_urin: { id: 'hindari_antikolinergik_retensi_urin', nama: '[Prostat] Hindari obat flu/antihistamin antikolinergik pencetus retensi urin', kategori: 'kepatuhan', sinonim: ['BPH', 'retensi urin akut', 'antikolinergik', 'CTM', 'obat flu warung'] },
}

export const TINDAKAN_LAB_EXPANSION: Record<string, Tindakan> = {
  ekstraksi_benda_asing_konjungtiva: { id: 'ekstraksi_benda_asing_konjungtiva', nama: 'Irigasi atau ekstraksi lembut benda asing konjungtiva yang tampak superfisial', icd9: '98.21', biaya: 35000 },
  epilasi_trikiasis: { id: 'epilasi_trikiasis', nama: 'Epilasi bulu mata penyebab trikiasis', icd9: '08.91', biaya: 25000 },
  uji_visus_refraksi: { id: 'uji_visus_refraksi', nama: 'Uji visus, pinhole, dan refraksi sederhana', icd9: '95.09', biaya: 20000 },
  perawatan_tali_pusat: { id: 'perawatan_tali_pusat', nama: 'Perawatan tali pusat bersih dan kering', icd9: '99.84', biaya: 15000 },
  reduksi_parafimosis: { id: 'reduksi_parafimosis', nama: 'Kompresi edema dan reduksi manual parafimosis', icd9: '64.0', biaya: 50000 },
  jahit_perineum: { id: 'jahit_perineum', nama: 'Anestesi lokal dan jahit ruptur perineum derajat 1-2', icd9: '75.69', biaya: 90000 },
  konseling_laktasi: { id: 'konseling_laktasi', nama: 'Observasi dan koreksi posisi-perlekatan menyusui', icd9: 'V65.4', biaya: 0 },
  adrenalin_im_anafilaksis: { id: 'adrenalin_im_anafilaksis', nama: 'Epinefrin 1 mg/mL intramuskular paha sesuai berat badan', icd9: '99.29', biaya: 25000 },
  perawatan_luka: { id: 'perawatan_luka', nama: 'Irigasi, debridemen selektif, dan balut luka', icd9: '86.28', biaya: 50000 },
  profilaksis_tetanus: { id: 'profilaksis_tetanus', nama: 'Profilaksis tetanus sesuai jenis luka dan riwayat imunisasi', icd9: '99.38', biaya: 25000 },
  pendinginan_luka_bakar: { id: 'pendinginan_luka_bakar', nama: 'Lanjutkan air mengalir sejuk hingga total 20 menit; jaga bagian tubuh lain tetap hangat', icd9: '93.57', biaya: 0 },
  balut_luka_bakar: { id: 'balut_luka_bakar', nama: 'Bersihkan lembut lalu tutup dengan balutan non/low-adherent tanpa melingkar ketat', icd9: '93.57', biaya: 30000 },
  observasi_neurologis: { id: 'observasi_neurologis', nama: 'Observasi serial komponen GCS (E/V/M), pupil, gejala, dan defisit neurologis', icd9: '89.14', biaya: 15000 },
  minim_stimulus_tetanus: { id: 'minim_stimulus_tetanus', nama: 'Tempatkan pasien tetanus di ruang tenang dengan stimulus minimal', icd9: '93.59', biaya: 0 },
  kesiapan_airway_rujuk: { id: 'kesiapan_airway_rujuk', nama: 'Siapkan suction, BVM, oksigen, dan pendamping terlatih selama transfer', icd9: '93.90', biaya: 20000 },
  antibiotik_parenteral_neonatus_protokol: { id: 'antibiotik_parenteral_neonatus_protokol', nama: 'Antibiotik parenteral awal neonatus sesuai protokol jejaring', icd9: '99.21', biaya: 30000 },
  suction_hidung_bronkiolitis_selektif: { id: 'suction_hidung_bronkiolitis_selektif', nama: 'Suction Hidung Lembut bila Sekret Mengganggu Napas/Minum', icd9: '93.99', biaya: 10000 },
}
