import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../');
const INTELLIGENCE_PATH = path.join(ROOT, 'PRIMERA_INTELLIGENCE.md');
const DIAG_DIR = path.join(ROOT, 'diagnostics');
const WATCHDOG_ESLINT = path.join(ROOT, 'megalog/outputs/eslint.json');

async function main() {
    console.log("🛰️ PRIMERA Sentinel: Scanning Structural Integrity...");

    // 1. Run Sub-Diagnostics
    try {
        execSync(`node scripts/primera/pldb_analyzer.mjs`, { cwd: ROOT });
        execSync(`node scripts/primera/store_dumper.mjs`, { cwd: ROOT });
    } catch (e) {
        console.warn("⚠️ Some sub-diagnostics failed, but continuing Sentinel scan...");
    }

    // 2. Generate Tree Data
    let treeMD = "";
    try {
        // Simple internal tree generator for MD
        const getTree = (dir, depth = 0) => {
            if (depth > 2) return "";
            let str = "";
            const files = fs.readdirSync(dir, { withFileTypes: true });
            files.forEach(file => {
                if (['node_modules', '.git', 'dist', '_backups'].includes(file.name)) return;
                const indent = "  ".repeat(depth);
                str += `${indent}- ${file.isDirectory() ? '📁' : '📄'} ${file.name}\n`;
                if (file.isDirectory()) {
                    str += getTree(path.join(dir, file.name), depth + 1);
                }
            });
            return str;
        };
        treeMD = getTree(path.join(ROOT, 'src'));
    } catch (e) {
        console.error("Tree generation error:", e);
        treeMD = "Error generating tree: " + e.message;
    }

    // 3. Risk Assessment Logic — reads FRESH data from watchdog ESLint output
    let riskLevel = "UNKNOWN";
    let riskColor = "gray";
    let riskReason = "Scan incomplete.";

    let undefCount = 0;
    let purityCount = 0;

    // Primary: Read live ESLint JSON from watchdog pipeline
    if (fs.existsSync(WATCHDOG_ESLINT)) {
        try {
            const eslintData = JSON.parse(fs.readFileSync(WATCHDOG_ESLINT, 'utf8'));
            for (const file of eslintData) {
                for (const msg of (file.messages || [])) {
                    if (msg.severity === 2) {
                        if (msg.ruleId === 'no-undef') undefCount++;
                        if (msg.ruleId === 'react-hooks/purity') purityCount++;
                    }
                }
            }
        } catch { /* fallback below */ }
    }
    // Fallback: Read from diagnostics summary if watchdog output is missing
    else {
        const summaryPath = path.join(DIAG_DIR, 'lint-rules-summary.json');
        if (fs.existsSync(summaryPath)) {
            try {
                const summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
                undefCount = summary['no-undef'] || 0;
                purityCount = summary['react-hooks/purity'] || 0;
            } catch { /* ignore */ }
        }
    }

    if (undefCount > 5) {
        riskLevel = "CRITICAL (FATAL)";
        riskColor = "red";
        riskReason = `${undefCount} orphan variables (no-undef) detected. Core features are likely broken.`;
    } else if (undefCount > 0 || purityCount > 5) {
        riskLevel = "HIGH (STABILITY AT RISK)";
        riskColor = "orange";
        riskReason = "Undefined symbols or React purity violations detected. High regression probability.";
    } else {
        riskLevel = "STABLE";
        riskColor = "green";
        riskReason = "Structural wiring is secure. No critical lint violations.";
    }

    // 4. Generate PRIMERA_INTELLIGENCE.md
    const timestamp = new Date().toLocaleString();
    let intelligenceMD = `# 🧠 PRIMERA Intelligence Hub\n\n`;
    intelligenceMD += `> **Sentinel Status**: Active\n`;
    intelligenceMD += `> **Last Scan**: ${timestamp}\n\n`;

    intelligenceMD += `## 🛡️ Structural Risk Assessment\n\n`;
    intelligenceMD += `| Metric | Value |\n`;
    intelligenceMD += `| :--- | :--- |\n`;
    intelligenceMD += `| **Risk Level** | **${riskLevel}** |\n`;
    intelligenceMD += `| **Reason** | ${riskReason} |\n\n`;

    intelligenceMD += `## 🌳 Project Topology (src/)\n\n\`\`\`text\n${treeMD}\n\`\`\`\n\n`;

    intelligenceMD += `## 🧊 State Contract (Zustand)\n\n`;
    const storeSchemaPath = path.join(DIAG_DIR, 'store-schema.md');
    if (fs.existsSync(storeSchemaPath)) {
        intelligenceMD += fs.readFileSync(storeSchemaPath, 'utf8').split('\n').slice(3).join('\n');
    } else {
        intelligenceMD += "*Store schema not available.*\n";
    }

    intelligenceMD += `\n---
Generated by PRIMERA Sentinel v1.0
`;

    fs.writeFileSync(INTELLIGENCE_PATH, intelligenceMD);
    console.log(`✅ Intelligence Hub Updated: ${INTELLIGENCE_PATH}`);
}

main();
