/**
 * @reflection
 * [IDENTITY]: sentinel
 * [PURPOSE]: Generate PRIMERA_INTELLIGENCE.md from canonical health.json and lightweight topology diagnostics.
 * [STATE]: Active
 * [ANCHOR]: main
 * [DEPENDS_ON]: artifact_manifest
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { readStampedJson, stampMarkdown } from './artifact_manifest.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../');
const OUTDIR = path.join(ROOT, 'megalog/outputs');
const INTELLIGENCE_PATH = path.join(ROOT, 'PRIMERA_INTELLIGENCE.md');
const HEALTH_PATH = path.join(OUTDIR, 'health.json');
const DIAG_DIR = path.join(ROOT, 'diagnostics');

function buildTree(dir, depth = 0) {
    if (depth > 2) return '';
    let output = '';
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        if (['node_modules', '.git', 'dist', '_backups'].includes(entry.name)) continue;
        const indent = '  '.repeat(depth);
        output += `${indent}- ${entry.isDirectory() ? '[DIR]' : '[FILE]'} ${entry.name}\n`;
        if (entry.isDirectory()) {
            output += buildTree(path.join(dir, entry.name), depth + 1);
        }
    }
    return output;
}

function deriveRisk(health) {
    if (!health) {
        return {
            level: 'UNKNOWN',
            reason: 'health.json is missing. Run megalog_v5 first.'
        };
    }

    if ((health.staleInputs || []).length > 0) {
        return {
            level: 'HIGH',
            reason: `Canonical health is carrying stale inputs: ${(health.staleInputs || []).join(', ')}.`
        };
    }

    if (health.total < 50) {
        return {
            level: 'CRITICAL',
            reason: health.capReason || 'Unified health is below 50.'
        };
    }

    if (health.total < 80) {
        return {
            level: 'HARDENING',
            reason: health.capReason || 'Unified health is below the trusted threshold.'
        };
    }

    return {
        level: 'STABLE',
        reason: 'Canonical health.json indicates trusted runtime and structural posture.'
    };
}

async function main() {
    console.log('PRIMERA Sentinel: reading canonical health...');

    try {
        execSync('node scripts/primera/pldb_analyzer.mjs', { cwd: ROOT, stdio: 'ignore' });
        execSync('node scripts/primera/store_dumper.mjs', { cwd: ROOT, stdio: 'ignore' });
    } catch {
        // Lightweight diagnostics are best-effort only.
    }

    const health = readStampedJson(HEALTH_PATH);
    const risk = deriveRisk(health);
    const tree = buildTree(path.join(ROOT, 'src'));
    const storeSchemaPath = path.join(DIAG_DIR, 'store-schema.md');
    const storeSchema = fs.existsSync(storeSchemaPath)
        ? fs.readFileSync(storeSchemaPath, 'utf8').split('\n').slice(3).join('\n')
        : '*Store schema not available.*\n';

    const markdown = `# PRIMERA Intelligence Hub

> Sentinel Status: Active
> Last Scan: ${new Date().toLocaleString('id-ID')}

## Structural Risk Assessment

| Metric | Value |
| :--- | :--- |
| **Risk Level** | **${risk.level}** |
| **Reason** | ${risk.reason} |
| **Health Score** | **${health?.total ?? 'missing'}/100** |
| **Cap Reason** | ${health?.capReason || '-'} |
| **Dirty Worktree** | ${health?.dirty ?? 'unknown'} |
| **Health Git SHA** | ${health?.gitSha || 'unknown'} |

## Breakdown

\`\`\`json
${JSON.stringify(health?.breakdown || {}, null, 2)}
\`\`\`

## Project Topology (src/)

\`\`\`text
${tree}
\`\`\`

## State Contract (Zustand)

${storeSchema}

---
Generated by PRIMERA Sentinel vNext
`;

    fs.writeFileSync(
        INTELLIGENCE_PATH,
        stampMarkdown(markdown, 'sentinel', ['health.json', 'store-schema.md'])
    );
    console.log(`Intelligence Hub updated: ${INTELLIGENCE_PATH}`);
}

main().catch((error) => {
    console.error('Sentinel failed:', error);
    process.exit(1);
});
