import type { KasusKlinis } from '../../types'

export const M13_1A_CLINIC_DRAFTS: KasusKlinis[] = [
  {
    id: 'diare_akut_bayi_dehidrasi_berat',
    nama: 'Diare Akut Bayi dengan Dehidrasi Berat',
    icd10: 'A09',
    skdi: '4A',
    kategori: 'pencernaan',
    fktp144: true,
    harusDirujuk: true,
    prevalensi: 'tinggi',
    spesialisRujukan: 'anak',
    keluhanUtama: 'Bayi saya mencret dan muntah sejak kemarin, sekarang lemas sekali, Dok.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 0, usiaMax: 0 },
    vital: { td: '70/40', nadi: 172, rr: 42, suhu: 37.8, spo2: 97, gds: 72 },
    anamnesis: [
      {
        id: 'nb_keluhan',
        kategori: 'keluhan_utama',
        tanya: 'Apa yang terjadi pada bayinya, Bu?',
        jawab: 'Sejak kemarin muntah dan BAB cair berkali-kali. Sejak subuh badannya lemas.',
        variasi: {
          wali_anak: 'Bayi saya mencret dan muntah sejak kemarin, Dok. Pagi ini lemas dan lebih banyak memejamkan mata.',
        },
        esensial: true,
        oldcarts: ['onset', 'karakter', 'keparahan'],
      },
      {
        id: 'nb_frekuensi',
        kategori: 'rps',
        tanya: 'Sejak mulai sakit, sudah berapa kali BAB dan muntah?',
        jawab: 'BAB cair sekitar delapan kali dan muntah empat kali sejak kemarin sore.',
        variasi: { wali_anak: 'Saya hitung delapan kali BAB cair dan empat kali muntah sejak kemarin sore.' },
        esensial: true,
        bukaSetelah: ['nb_keluhan'],
        oldcarts: ['durasi', 'waktu', 'keparahan'],
      },
      {
        id: 'nb_darah',
        kategori: 'rps',
        tanya: 'BAB-nya cair saja atau ada darah dan lendir?',
        jawab: 'Cair kekuningan, tidak ada darah atau lendir.',
        variasi: { wali_anak: 'Cair kekuningan saja, Dok. Saya tidak melihat darah atau lendir.' },
        esensial: true,
        bukaSetelah: ['nb_keluhan'],
        oldcarts: ['karakter'],
      },
      {
        id: 'nb_minum',
        kategori: 'rps',
        tanya: 'Masih mau menyusu atau minum? Bagaimana hisapannya?',
        jawab: 'Sejak pagi hanya mengisap sebentar lalu melepas, sekarang hampir tidak mau menyusu.',
        variasi: { wali_anak: 'Biasanya menyusu kuat. Sejak pagi hanya mengisap sebentar lalu lepas dan sekarang hampir tidak mau.' },
        esensial: true,
        bukaSetelah: ['nb_keluhan'],
        oldcarts: ['penyerta', 'keparahan'],
      },
      {
        id: 'nb_kencing',
        kategori: 'rps',
        tanya: 'Kapan popok terakhir basah oleh kencing?',
        jawab: 'Popok terakhir basah tadi malam. Sejak subuh masih kering.',
        variasi: { wali_anak: 'Terakhir basah tadi malam, Dok. Popok yang saya pasang sejak subuh masih kering.' },
        esensial: true,
        bukaSetelah: ['nb_keluhan'],
        oldcarts: ['penyerta', 'waktu', 'keparahan'],
      },
      {
        id: 'nb_kesadaran',
        kategori: 'rps',
        tanya: 'Apakah bayi sulit dibangunkan, kejang, atau tidak merespons seperti biasa?',
        jawab: 'Tidak kejang, tapi sejak pagi sangat mengantuk dan sulit diajak menatap.',
        variasi: { wali_anak: 'Tidak kejang, Dok, tapi bayi saya sulit diajak menatap dan terus memejamkan mata.' },
        esensial: true,
        bukaSetelah: ['nb_keluhan'],
        oldcarts: ['penyerta', 'keparahan'],
      },
      {
        id: 'nb_demam',
        kategori: 'rps',
        tanya: 'Ada demam tinggi, perut kembung, atau muntah berwarna hijau?',
        jawab: 'Badannya hangat saja. Perut tidak kembung dan muntahnya putih kekuningan, bukan hijau.',
        variasi: { wali_anak: 'Hangat saja, Dok. Perutnya tidak kembung dan muntahnya bukan hijau.' },
        esensial: true,
        bukaSetelah: ['nb_keluhan'],
        oldcarts: ['penyerta'],
      },
      {
        id: 'nb_asupan',
        kategori: 'rps',
        tanya: 'Sebelum sakit, selain ASI ada makanan atau minuman lain yang diberikan?',
        jawab: 'Kemarin diberi pisang kerok oleh neneknya. Biasanya masih ASI.',
        variasi: { wali_anak: 'Kemarin Mbah memberi pisang kerok. Biasanya bayi saya masih menyusu.' },
        esensial: true,
        bukaSetelah: ['nb_keluhan'],
        oldcarts: ['penyerta'],
      },
      {
        id: 'nb_kontak',
        kategori: 'rpk',
        tanya: 'Ada orang serumah yang sedang muntah atau diare?',
        jawab: 'Tidak ada yang sedang muntah atau diare.',
        variasi: { wali_anak: 'Tidak ada, Dok. Hanya bayi saya yang sakit.' },
      },
      {
        id: 'nb_riwayat',
        kategori: 'rpd',
        tanya: 'Lahir cukup bulan? Ada penyakit bawaan atau pernah dirawat sebelumnya?',
        jawab: 'Lahir cukup bulan, berat lahir normal, dan belum pernah dirawat.',
        variasi: { wali_anak: 'Lahir cukup bulan dan sehat. Belum pernah dirawat sejak lahir.' },
        esensial: true,
      },
      {
        id: 'nb_obat',
        kategori: 'rpd',
        tanya: 'Sudah diberi obat, oralit, atau ramuan apa sebelum ke sini?',
        jawab: 'Baru diberi ASI sedikit-sedikit. Belum diberi obat atau ramuan.',
        variasi: { wali_anak: 'Saya hanya mencoba menyusui sedikit-sedikit. Belum memberi obat atau ramuan.' },
      },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Berat badan 5,6 kg. Bayi letargis, respons terhadap rangsang lambat, tangisan lemah tanpa air mata.', relevan: true },
      { region: 'kepala_leher', temuan: 'Mata sangat cekung; fontanel anterior cekung; mukosa mulut sangat kering.', relevan: true },
      { region: 'kulit', temuan: 'Cubitan kulit abdomen kembali sangat lambat (>2 detik), akral dingin, CRT 3 detik.', relevan: true },
      { region: 'abdomen', temuan: 'Abdomen tidak distensi, bising usus meningkat, tanpa tanda peritonitis.', relevan: true },
      { region: 'toraks_paru', temuan: 'Napas spontan, suara napas vesikuler bilateral, tidak ada retraksi.', relevan: false },
    ],
    lab: [
      { id: 'gds', hasil: '72 mg/dL; tidak hipoglikemia, tetapi tetap dipantau selama resusitasi.', flag: 'normal', relevan: true },
      { id: 'elektrolit_serum', hasil: 'Belum tersedia; pengambilan sampel tidak boleh menunda rehidrasi dan rujukan.', flag: 'normal', relevan: false },
      { id: 'feses_rutin', hasil: 'Tidak dikerjakan pada fase stabilisasi awal karena tidak mengubah Plan C.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['A09', 'A08.0', 'A03'],
    tatalaksana: {
      obatBenar: [],
      obatOpsional: ['oralit', 'zinc_20'],
      obatSalahUmum: [
        { id: 'loperamid_2', alasan: 'Antimotilitas tidak diberikan pada bayi dan tidak mengatasi kegawatan dehidrasi.', bahaya: 'kontraindikasi' },
        { id: 'amoxicillin_sirup', alasan: 'Diare cair tanpa darah tidak memerlukan antibiotik empiris rutin.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['rehidrasi_plan_c_bayi'],
      edukasi: ['tanda_bahaya', 'cairan_oralit', 'asi_eksklusif', 'cuci_tangan'],
      edukasiKritis: ['tanda_bahaya'],
    },
    clue: 'Bayi 3 bulan ini memenuhi dehidrasi berat: letargis, mata cekung, hampir tidak mau minum, dan cubitan kulit kembali sangat lambat. Mulai Plan C segera: Ringer laktat/NaCl 0,9% total 100 mL/kg (usia <12 bulan: 30 mL/kg dalam 1 jam lalu 70 mL/kg dalam 5 jam), nilai ulang 1-2 jam, dan beri ORS sekitar 5 mL/kg/jam segera setelah mampu minum. Setelah fase akut aman, berikan zinc 10 mg/hari selama 14 hari (setengah tablet dispersibel 20 mg), bukan 20 mg penuh. Stabilkan sambil mengatur rujukan anak; jangan menunda cairan untuk pemeriksaan feses atau antibiotik empiris.',
    mutiaraEbm: 'Pada bayi yang letargis dan hampir tidak mau minum, ORS oral bukan pengganti cairan IV awal. ORS dan zinc 10 mg/hari masuk setelah jalan napas-sirkulasi aman dan kemampuan minum dinilai ulang.',
    panduanResmi: 'MTBS/ILP menempatkan klasifikasi merah sebagai tindakan awal segera dan rujukan. WHO IMCI Plan C memberi pembagian cairan khusus bayi <12 bulan dan mewajibkan penilaian ulang serial.',
    catatanRealita: 'Kemampuan memasang akses IV bayi, ketersediaan Ringer laktat, dan waktu tempuh RS anak berbeda antar-Puskesmas. Bila akses IV tidak dapat segera diperoleh, ikuti jalur Plan C untuk rujuk segera dengan ORS sedikit-sedikit/NG bila aman dan petugas terlatih.',
    konsekuensi: {
      narasi: 'Menunda rehidrasi atau memaksa cairan oral pada bayi letargis dapat memperberat hipoperfusi dan aspirasi selama perjalanan.',
      kembaliHariMin: 0,
      kembaliHariMax: 1,
      kondisiKembali: 'Bayi kembali dengan nadi sangat lemah, ekstremitas dingin, dan penurunan kesadaran akibat syok hipovolemik.',
      guideline: 'WHO IMCI Chart Booklet - Plan C; Kemenkes ILP/MTBS.',
    },
    stabilisasiWajib: 'rehidrasi_plan_c_bayi',
  },
  {
    id: 'asma_eksaserbasi_berat_anak',
    nama: 'Eksaserbasi Asma Berat pada Anak',
    icd10: 'J46',
    skdi: '3B',
    kategori: 'respirasi',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'sedang',
    spesialisRujukan: 'anak',
    keluhanUtama: 'Anak saya sesak sejak semalam dan obat uap di rumah tidak banyak membantu, Dok.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 6, usiaMax: 11 },
    vital: { td: '92/58', nadi: 136, rr: 38, suhu: 37.1, spo2: 87 },
    anamnesis: [
      {
        id: 'da_keluhan',
        kategori: 'keluhan_utama',
        tanya: 'Sejak kapan sesaknya memburuk, Bu?',
        jawab: 'Mulai semalam dan makin berat menjelang subuh. Sekarang bicara hanya beberapa kata.',
        variasi: { wali_anak: 'Anak saya mulai sesak semalam, Dok, lalu makin berat menjelang subuh. Sekarang bicara cuma beberapa kata.' },
        esensial: true,
        oldcarts: ['onset', 'waktu', 'keparahan'],
      },
      {
        id: 'da_gejala',
        kategori: 'rps',
        tanya: 'Selain sesak, ada mengi, batuk, atau dada terasa berat?',
        jawab: 'Mengi keras dan batuk kering. Ia bilang dadanya berat.',
        variasi: { wali_anak: 'Ada bunyi ngik-ngik keras, batuk kering, dan ia bilang dadanya berat.' },
        esensial: true,
        bukaSetelah: ['da_keluhan'],
        oldcarts: ['karakter', 'penyerta'],
      },
      {
        id: 'da_bicara',
        kategori: 'rps',
        tanya: 'Masih bisa berjalan dan bicara satu kalimat penuh?',
        jawab: 'Tidak. Berjalan beberapa langkah saja makin sesak dan bicara terputus-putus.',
        variasi: { wali_anak: 'Tidak bisa, Dok. Beberapa langkah saja tambah sesak dan bicaranya putus-putus.' },
        esensial: true,
        bukaSetelah: ['da_keluhan'],
        oldcarts: ['keparahan', 'agravasi'],
      },
      {
        id: 'da_terapi_rumah',
        kategori: 'rps',
        tanya: 'Apa yang sudah diberikan di rumah dan bagaimana responsnya?',
        jawab: 'Sudah dinebul dua kali dengan obat pelega, sempat ringan sebentar lalu sesak lagi.',
        variasi: { wali_anak: 'Saya nebul dua kali dengan obat peleganya. Hanya ringan sebentar, lalu sesak lagi.' },
        esensial: true,
        bukaSetelah: ['da_keluhan'],
        oldcarts: ['agravasi', 'waktu'],
      },
      {
        id: 'da_bahaya',
        kategori: 'rps',
        tanya: 'Pernah bibir membiru, mengantuk tidak wajar, atau napasnya tiba-tiba tidak berbunyi?',
        jawab: 'Bibirnya sempat tampak kebiruan. Ia masih sadar dan mengi masih terdengar.',
        variasi: { wali_anak: 'Bibirnya tadi kebiruan samar, Dok. Masih sadar dan bunyi ngik-ngiknya masih ada.' },
        esensial: true,
        bukaSetelah: ['da_keluhan'],
        oldcarts: ['penyerta', 'keparahan'],
      },
      {
        id: 'da_serangan_lalu',
        kategori: 'rpd',
        tanya: 'Pernah dirawat, masuk ICU, atau dipasang selang napas karena asma?',
        jawab: 'Pernah dirawat sekali dua tahun lalu, belum pernah ICU atau dipasang selang napas.',
        variasi: { wali_anak: 'Pernah dirawat sekali dua tahun lalu, tapi belum pernah ICU atau dipasang selang napas.' },
        esensial: true,
      },
      {
        id: 'da_kontrol',
        kategori: 'rpd',
        tanya: 'Seberapa sering asma kambuh dan apakah memakai obat pengendali setiap hari?',
        jawab: 'Dua bulan ini sesak hampir tiap minggu. Inhaler pengendali sering terlewat kalau sedang merasa sehat.',
        variasi: { wali_anak: 'Dua bulan ini hampir tiap minggu kambuh. Inhaler pengendalinya sering terlewat saat anak saya merasa sehat.' },
        esensial: true,
      },
      {
        id: 'da_pencetus',
        kategori: 'rps',
        tanya: 'Sebelum serangan ini ada paparan asap, debu, udara dingin, atau aktivitas berat?',
        jawab: 'Ayahnya pulang dengan jaket berbau asap rokok lalu memeluknya. Sesak mulai beberapa jam kemudian.',
        variasi: { wali_anak: 'Ayahnya baru pulang kerja, jaketnya sangat bau asap rokok. Beberapa jam setelah dipeluk, anak saya mulai sesak.' },
        esensial: true,
        oldcarts: ['agravasi'],
      },
      {
        id: 'da_infeksi',
        kategori: 'rps',
        tanya: 'Ada demam tinggi, dahak bernanah, atau nyeri dada menetap?',
        jawab: 'Tidak demam tinggi dan tidak ada dahak bernanah. Hanya pilek ringan dua hari.',
        variasi: { wali_anak: 'Tidak demam tinggi dan tidak ada dahak, Dok. Hanya pilek ringan dua hari.' },
      },
      {
        id: 'da_alergi',
        kategori: 'rpd',
        tanya: 'Ada alergi obat atau reaksi berat terhadap obat sebelumnya?',
        jawab: 'Tidak ada alergi obat yang diketahui.',
        variasi: { wali_anak: 'Sejauh yang saya tahu tidak ada alergi obat.' },
        esensial: true,
      },
      {
        id: 'da_keluarga',
        kategori: 'rpk',
        tanya: 'Ada riwayat asma atau alergi pada keluarga?',
        jawab: 'Ibunya punya rinitis alergi dan pamannya asma.',
        variasi: { wali_anak: 'Saya sering alergi debu dan pamannya juga asma.' },
      },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Berat badan 24 kg. Anak gelisah, duduk bertumpu, bicara kata demi kata, sianosis perioral samar.', relevan: true },
      { region: 'toraks_paru', temuan: 'Retraksi interkostal dan suprasternal, ekspirasi memanjang, mengi bilateral dengan aliran udara menurun.', relevan: true },
      { region: 'jantung', temuan: 'Takikardi reguler, perfusi perifer masih teraba, tanpa gallop.', relevan: true },
      { region: 'tht_mulut', temuan: 'Pilek ringan, tidak ada stridor atau benda asing yang tampak.', relevan: false },
      { region: 'kulit', temuan: 'Tidak ada urtikaria atau edema wajah.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Tidak dikerjakan pada stabilisasi awal; tidak ada tanda infeksi bakteri fokal.', flag: 'normal', relevan: false },
      { id: 'gds', hasil: '104 mg/dL.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['J46', 'J45.9', 'J18.9', 'T17.9'],
    tatalaksana: {
      obatBenar: ['ipratropium_salbutamol_neb', 'prednison_5'],
      obatSalahUmum: [
        { id: 'amoxicillin_sirup', alasan: 'Tidak ada bukti infeksi bakteri; antibiotik menunda bronkodilatasi dan steroid.', bahaya: 'nonPrimer' },
        { id: 'salbutamol_2', alasan: 'Salbutamol oral bekerja lebih lambat dan menambah efek sistemik; serangan berat memerlukan terapi inhalasi berulang.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['oksigen', 'nebulisasi'],
      edukasi: ['tanda_bahaya', 'teknik_inhaler', 'hindari_pencetus_asma', 'kontrol_rutin'],
      edukasiKritis: ['tanda_bahaya', 'teknik_inhaler'],
    },
    clue: 'SpO2 87%, bicara kata demi kata, retraksi, dan respons singkat setelah dua nebulisasi rumah menandai eksaserbasi asma berat. Beri oksigen dengan target SpO2 94-98%, nebulisasi SABA + ipratropium setiap 20 menit sampai 3 kali pada jam pertama, dan kortikosteroid sistemik sedini mungkin sambil memantau respons. Pedoman Asma FKTP memberi prednison/prednisolon 1-2 mg/kgBB/hari (maksimum 40 mg) selama 3-5 hari; kekuatan tablet 5 mg di formularium bukan dosis total pasien. Karena tetap berat/hipoksemik, rujuk segera ke layanan anak dengan terapi berjalan; jangan menunggu mengi menghilang karena silent chest dapat berarti aliran udara makin buruk.',
    mutiaraEbm: 'Mengi yang mendadak lebih pelan pada anak yang makin lelah bukan selalu perbaikan; silent chest, mengantuk, atau bradikardi adalah tanda gagal napas mengancam.',
    panduanResmi: 'Pedoman Asma FKTP Kemenkes memuat oksigen bila hipoksemia, SABA inhalasi berulang, steroid sistemik, dan rujuk bila berat/tidak respons. WHO 2026 menambahkan ipratropium nebulisasi pada eksaserbasi pediatrik berat.',
    catatanRealita: 'Fornas 1199/2025 mencantumkan kombinasi ipratropium 0,5 mg + salbutamol 2,5 mg untuk serangan asma akut/UGD. Stok, sumber oksigen, spacer, dan kemampuan transport harus diperiksa tanpa menunda terapi pertama.',
    konsekuensi: {
      narasi: 'Menunda oksigen, bronkodilator berulang, steroid, atau rujukan dapat mengubah obstruksi berat menjadi kelelahan napas dan henti napas.',
      kembaliHariMin: 0,
      kembaliHariMax: 1,
      kondisiKembali: 'Anak menjadi mengantuk dengan gerakan dada minimal dan suara napas sangat lemah.',
      guideline: 'Kemenkes Pedoman Asma FKTP 2015; WHO childhood asthma guideline 2026.',
    },
    stabilisasiWajib: 'oksigen',
  },
  {
    id: 'hipoglikemia_ringan_dewasa',
    nama: 'Hipoglikemia Ringan pada Dewasa dengan DM',
    icd10: 'E16.2',
    skdi: '4A',
    kategori: 'metabolik',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Sejak siang saya gemetar, berkeringat dingin, dan sangat lapar, Dok.',
    demografi: { usiaMin: 35, usiaMax: 64 },
    vital: { td: '118/74', nadi: 102, rr: 18, suhu: 36.5, spo2: 98, gds: 58 },
    anamnesis: [
      { id: 'hg_keluhan', kategori: 'keluhan_utama', tanya: 'Apa yang paling mengganggu sekarang?', jawab: 'Tangan gemetar, keringat dingin, jantung berdebar, dan sangat lapar.', esensial: true, oldcarts: ['karakter', 'penyerta'] },
      { id: 'hg_onset', kategori: 'rps', tanya: 'Kapan mulai dan apakah muncul mendadak?', jawab: 'Mulai mendadak sekitar satu jam lalu saat masih bekerja.', esensial: true, bukaSetelah: ['hg_keluhan'], oldcarts: ['onset', 'durasi'] },
      { id: 'hg_neuro', kategori: 'rps', tanya: 'Ada bingung, pingsan, kejang, bicara pelo, atau lemah satu sisi?', jawab: 'Tidak pingsan atau kejang. Saya masih sadar penuh dan tidak ada lemah satu sisi.', esensial: true, bukaSetelah: ['hg_keluhan'], oldcarts: ['penyerta', 'keparahan'] },
      { id: 'hg_makan', kategori: 'rps', tanya: 'Kapan terakhir makan dan apakah ada waktu makan yang terlewat?', jawab: 'Sarapan jam enam. Siang tadi rapat panjang jadi belum makan.', esensial: true, oldcarts: ['waktu', 'agravasi'] },
      { id: 'hg_obat', kategori: 'rpd', tanya: 'Obat diabetes apa dan kapan dosis terakhir diminum?', jawab: 'Glimepirid 2 mg diminum setelah sarapan seperti biasa.', esensial: true },
      { id: 'hg_dosis', kategori: 'rpd', tanya: 'Ada kemungkinan minum dosis ganda atau perubahan dosis baru-baru ini?', jawab: 'Tidak ada dosis ganda dan dosisnya tidak berubah.', esensial: true },
      { id: 'hg_ulang', kategori: 'rpd', tanya: 'Pernah mengalami keluhan serupa sebelumnya?', jawab: 'Pernah sekali saat telat makan, membaik setelah minum teh manis.', esensial: true },
      { id: 'hg_ginjal', kategori: 'rpd', tanya: 'Ada penyakit ginjal, hati, muntah berkepanjangan, atau berat badan turun?', jawab: 'Tidak ada penyakit ginjal atau hati dan tidak sedang muntah.', esensial: true },
      { id: 'hg_alkohol', kategori: 'sosial', tanya: 'Ada konsumsi alkohol, puasa, atau olahraga berat hari ini?', jawab: 'Tidak minum alkohol. Hanya belum sempat makan siang.', esensial: true },
      { id: 'hg_pendamping', kategori: 'sosial', tanya: 'Ada orang yang bisa menemani dan memastikan makan serta memantau setelah ini?', jawab: 'Rekan kerja saya menunggu di luar dan bisa menemani.', oldcarts: ['penyerta'] },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Sadar penuh, kooperatif, tampak berkeringat dan tremor halus.', relevan: true },
      { region: 'neurologis', temuan: 'GCS 15, pupil isokor, bicara jelas, kekuatan motorik simetris.', relevan: true },
      { region: 'jantung', temuan: 'Takikardi reguler, tidak ada murmur.', relevan: true },
      { region: 'abdomen', temuan: 'Lunak, tidak nyeri tekan.', relevan: false },
    ],
    lab: [
      { id: 'gds', hasil: '58 mg/dL saat gejala berlangsung.', flag: 'rendah', relevan: true },
      { id: 'fungsi_ginjal', hasil: 'Ureum/kreatinin dalam batas normal.', flag: 'normal', relevan: true },
    ],
    diagnosisBanding: ['E16.2', 'F41.0', 'I95.9', 'G45.9'],
    tatalaksana: {
      obatBenar: ['glukosa_oral_15g'],
      obatSalahUmum: [
        { id: 'metformin_500', alasan: 'Menambah obat antidiabetes saat glukosa rendah tidak mengoreksi keadaan akut.', bahaya: 'nonPrimer' },
        { id: 'glibenclamide_5', alasan: 'Sulfonilurea tambahan dapat memperpanjang dan memperberat hipoglikemia.', bahaya: 'kontraindikasi' },
      ],
      edukasi: ['kenali_hipoglikemia', 'diet_dm', 'tinjau_obat_hipoglikemia', 'kontrol_rutin'],
      edukasiKritis: ['kenali_hipoglikemia', 'tinjau_obat_hipoglikemia'],
    },
    clue: 'Pasien sadar dengan gejala adrenergik dan GDS 58 mg/dL: beri 15-20 g glukosa oral, periksa ulang 15 menit, dan ulangi bila masih <70 mg/dL/gejala menetap. Setelah pulih, beri makan utama/camilan, evaluasi pemicu, lalu hentikan sementara atau kurangi sulfonilurea sesuai penilaian dan selaraskan regimen dengan pola makan; jangan menyuruh melanjutkan dosis berikut tanpa review. Rujuk bila tidak membaik, berulang, kesadaran turun, atau tidak aman dipantau.',
    panduanResmi: 'PNPK DM2 Dewasa 2026 memakai ambang <70 mg/dL, glukosa 15-20 g untuk pasien sadar, pemeriksaan ulang 15 menit, dan makanan setelah kadar normal.',
    catatanRealita: 'Glukosa 15 g dapat diberikan sebagai gula terukur yang dilarutkan dalam air bila sediaan gel/tablet tidak ada; jangan memakai makanan berlemak sebagai koreksi pertama karena absorpsi lebih lambat.',
    konsekuensi: {
      narasi: 'Tanpa koreksi dan evaluasi pencetus, hipoglikemia dapat berulang dan berkembang menjadi neuroglikopenia.',
      kembaliHariMin: 0,
      kembaliHariMax: 1,
      kondisiKembali: 'Pasien kembali bingung dan sulit menelan setelah tetap bekerja tanpa makan.',
      guideline: 'PNPK DM Tipe 2 Dewasa 302/2026.',
    },
  },
  {
    id: 'benda_asing_hidung_anak',
    nama: 'Benda Asing Hidung pada Anak',
    icd10: 'T17.1',
    skdi: '4A',
    kategori: 'tht',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Anak saya memasukkan manik-manik ke hidung kirinya sekitar dua jam lalu, Dok.',
    keluhanUtamaOlehPendamping: true,
    demografi: { usiaMin: 3, usiaMax: 5 },
    vital: { nadi: 104, rr: 22, suhu: 36.7, spo2: 99 },
    anamnesis: [
      {
        id: 'bah_keluhan',
        kategori: 'keluhan_utama',
        tanya: 'Apa yang terjadi dan siapa yang melihatnya, Bu?',
        jawab: 'Ibunya melihat anak memasukkan manik-manik ke hidung kiri sekitar dua jam lalu.',
        variasi: { wali_anak: 'Saya melihat anak saya memasukkan manik-manik biru ke hidung kirinya sekitar dua jam lalu, Dok.' },
        esensial: true,
        oldcarts: ['onset', 'lokasi', 'durasi'],
      },
      {
        id: 'bah_jenis',
        kategori: 'rps',
        tanya: 'Bendanya apa, berapa banyak, dan apakah mungkin baterai, magnet, benda tajam, atau bahan yang mengembang?',
        jawab: 'Satu manik-manik plastik bulat. Mainannya tidak memakai baterai atau magnet.',
        variasi: { wali_anak: 'Satu manik-manik plastik bulat, Dok. Bukan baterai, magnet, kacang, atau benda tajam.' },
        esensial: true,
        bukaSetelah: ['bah_keluhan'],
        oldcarts: ['karakter', 'keparahan'],
      },
      {
        id: 'bah_napas',
        kategori: 'rps',
        tanya: 'Setelah benda masuk, anak sempat tersedak, batuk hebat, sesak, membiru, atau suaranya berubah?',
        jawab: 'Tidak tersedak atau sesak dan tidak membiru.',
        variasi: { wali_anak: 'Tidak, Dok. Anak saya tidak tersedak, batuk hebat, sesak, atau membiru.' },
        esensial: true,
        bukaSetelah: ['bah_keluhan'],
        oldcarts: ['penyerta', 'keparahan'],
      },
      {
        id: 'bah_gejala_lokal',
        kategori: 'rps',
        tanya: 'Ada darah, nyeri hebat, bau busuk, atau cairan dari satu sisi hidung?',
        jawab: 'Hanya sedikit tidak nyaman. Tidak ada darah, bau busuk, atau cairan.',
        variasi: { wali_anak: 'Katanya agak mengganjal saja. Tidak ada darah, bau, atau ingus bernanah.' },
        esensial: true,
        oldcarts: ['penyerta'],
      },
      {
        id: 'bah_upaya',
        kategori: 'rps',
        tanya: 'Apa yang sudah dicoba di rumah? Apakah bendanya sempat dikorek atau didorong?',
        jawab: 'Ibunya hanya menyuruh meniup hidung sekali dan tidak memasukkan alat apa pun.',
        variasi: { wali_anak: 'Saya hanya menyuruhnya meniup sekali, Dok. Saya tidak berani mengorek atau memasukkan pinset.' },
        esensial: true,
        oldcarts: ['agravasi'],
      },
      {
        id: 'bah_lokasi_lain',
        kategori: 'rps',
        tanya: 'Ada kemungkinan benda lain masuk ke lubang hidung sebelah, telinga, atau tertelan?',
        jawab: 'Tidak. Sisa manik-manik sudah dihitung dan hanya satu yang hilang.',
        variasi: { wali_anak: 'Tidak, Dok. Saya hitung sisa manik-maniknya; hanya satu yang hilang dan saya melihat masuk ke hidung kiri.' },
        esensial: true,
      },
      {
        id: 'bah_riwayat',
        kategori: 'rpd',
        tanya: 'Pernah kejadian serupa, operasi hidung, gangguan perdarahan, atau penyakit berat?',
        jawab: 'Belum pernah dan tidak ada penyakit berat atau gangguan perdarahan.',
        variasi: { wali_anak: 'Belum pernah, Dok. Tidak ada operasi hidung, mudah berdarah, atau penyakit berat.' },
      },
      {
        id: 'bah_kooperatif',
        kategori: 'sosial',
        tanya: 'Apakah anak bisa duduk dipangku dan mengikuti instruksi singkat saat diperiksa?',
        jawab: 'Anak takut tetapi dapat tenang saat dipangku ibunya.',
        variasi: { wali_anak: 'Bisa, Dok. Anak saya takut, tapi kalau saya pangku dan jelaskan dulu biasanya mau diam sebentar.' },
        esensial: true,
      },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Anak sadar, bernapas nyaman, dan dapat ditenangkan di pangkuan ibu.', relevan: true },
      { region: 'tht_mulut', temuan: 'Rinoskopi anterior: satu manik-manik plastik biru bulat tampak jelas di kavum nasi kiri bagian anterior; mukosa hanya edema ringan, tanpa perdarahan.', relevan: true },
      { region: 'tht_mulut', temuan: 'Kavum nasi kanan dan faring posterior bersih; tidak tampak benda asing lain atau sekret purulen.', relevan: true },
      { region: 'toraks_paru', temuan: 'Tidak ada stridor; suara napas vesikuler bilateral tanpa mengi.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['T17.1', 'J34.89', 'J31.0'],
    tatalaksana: {
      obatBenar: [],
      obatSalahUmum: [
        { id: 'amoxicillin_sirup', alasan: 'Benda baru dua jam, tanpa infeksi sekunder; antibiotik tidak mengeluarkan benda asing.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['ekstraksi_benda_asing_hidung'],
      edukasi: ['cegah_benda_asing_hidung', 'tanda_bahaya'],
      edukasiKritis: ['cegah_benda_asing_hidung'],
    },
    clue: 'Manik-manik bulat tampak jelas di anterior, anak stabil dan kooperatif: lakukan ekstraksi sekali secara terencana dengan alat sesuai bentuk, misalnya pengait tumpul yang dilewatkan ke belakang benda, kateter balon, atau suction. Jangan menjepit benda bulat dari depan atau mengorek secara buta karena dapat mendorongnya ke posterior dan mengancam jalan napas. Rujuk bila baterai kancing, benda sulit dilihat/menempel, upaya pertama gagal, terjadi komplikasi, alat tidak memadai, atau anak tidak dapat diposisikan aman.',
    mutiaraEbm: 'Baterai kancing di hidung adalah emergensi kimia karena dapat merusak mukosa dan septum dalam beberapa jam; jangan menunggu gejala atau mencoba ekstraksi berulang tanpa kesiapan.',
    panduanResmi: 'PPK 1186/2022 menetapkan benda asing hidung dan keterampilan pengambilannya sebagai 4A. Instrumen dipilih menurut bentuk; benda bulat tidak dijepit dari depan, dan kegagalan, posisi sulit, atau pasien tidak kooperatif menjadi kriteria rujukan.',
    catatanRealita: 'Batas aman FKTP bergantung pada pencahayaan, spekulum, suction/pengait, petugas yang dapat memegang kepala dengan aman, serta kerja sama anak. Satu upaya terencana lebih aman daripada percobaan berulang.',
    konsekuensi: {
      narasi: 'Mengorek tanpa visualisasi atau menjepit manik-manik bulat dari depan dapat mendorongnya ke nasofaring dan saluran napas bawah.',
      kembaliHariMin: 0,
      kembaliHariMax: 1,
      kondisiKembali: 'Anak kembali batuk mendadak dan sesak setelah benda terdorong posterior saat dicoba diambil berulang kali.',
      guideline: 'PPK FKTP 1186/2022 - Benda Asing di Hidung dan Pengambilan Benda Asing pada Hidung.',
    },
    justifikasiRujukValid: ['komplikasi', 'keterbatasan_fasilitas'],
  },
  {
    id: 'otitis_eksterna_akut_ringan',
    nama: 'Otitis Eksterna Akut Ringan',
    icd10: 'H60.9',
    skdi: '4A',
    kategori: 'tht',
    fktp144: true,
    harusDirujuk: false,
    prevalensi: 'sedang',
    keluhanUtama: 'Telinga kanan saya nyeri sejak dua hari setelah berenang, Dok.',
    demografi: { usiaMin: 15, usiaMax: 45 },
    vital: { td: '118/76', nadi: 82, rr: 18, suhu: 36.8, spo2: 99 },
    anamnesis: [
      { id: 'oe_keluhan', kategori: 'keluhan_utama', tanya: 'Telinga mana yang sakit dan sejak kapan?', jawab: 'Telinga kanan sejak dua hari lalu.', esensial: true, oldcarts: ['lokasi', 'onset', 'durasi'] },
      { id: 'oe_nyeri', kategori: 'rps', tanya: 'Apakah makin sakit saat daun telinga disentuh atau saat mengunyah?', jawab: 'Ya, paling sakit saat bagian depan telinga ditekan dan saat mengunyah.', esensial: true, bukaSetelah: ['oe_keluhan'], oldcarts: ['karakter', 'agravasi'] },
      { id: 'oe_cairan', kategori: 'rps', tanya: 'Ada cairan, telinga penuh, atau pendengaran berkurang?', jawab: 'Terasa penuh dan ada cairan sedikit. Pendengaran agak teredam.', esensial: true, oldcarts: ['penyerta'] },
      { id: 'oe_paparan', kategori: 'rps', tanya: 'Baru berenang atau membersihkan telinga dengan cotton bud?', jawab: 'Berenang tiga hari lalu lalu membersihkan telinga dengan cotton bud.', esensial: true, oldcarts: ['agravasi'] },
      { id: 'oe_bahaya', kategori: 'rps', tanya: 'Ada demam tinggi, nyeri sampai belakang telinga, pusing berat, atau wajah mencong?', jawab: 'Tidak ada demam tinggi, pusing, atau wajah mencong.', esensial: true, oldcarts: ['penyerta', 'keparahan'] },
      { id: 'oe_risiko', kategori: 'rpd', tanya: 'Ada diabetes, daya tahan tubuh lemah, operasi telinga, atau gendang telinga pernah berlubang?', jawab: 'Tidak ada diabetes atau gangguan daya tahan tubuh dan belum pernah operasi telinga.', esensial: true },
    ],
    pemeriksaanFisik: [
      { region: 'tht_mulut', temuan: 'Nyeri tekan tragus dan tarik aurikula kanan; liang telinga hiperemis-edem ringan dengan sekret minimal; membran timpani tampak utuh.', relevan: true },
      { region: 'kepala_leher', temuan: 'Tidak ada mastoid tenderness atau limfadenopati bermakna.', relevan: true },
      { region: 'neurologis', temuan: 'Fungsi nervus fasialis normal.', relevan: false },
      { region: 'umum', temuan: 'Keadaan umum baik, afebris.', relevan: true },
    ],
    lab: [],
    diagnosisBanding: ['H60.9', 'H66.0', 'H61.2', 'B36.9'],
    tatalaksana: {
      obatBenar: ['asam_asetat_tetes_telinga_2'],
      obatOpsional: ['paracetamol_500'],
      obatSalahUmum: [
        { id: 'amoxicillin_500', alasan: 'Otitis eksterna ringan tanpa penyebaran ditangani topikal; antibiotik sistemik rutin tidak diperlukan.', bahaya: 'nonPrimer' },
        { id: 'karbogliserin_tetes', alasan: 'Karbogliserin adalah serumenolitik, bukan terapi inflamasi/infeksi liang telinga.', bahaya: 'nonPrimer' },
      ],
      edukasi: ['jaga_telinga_kering', 'tanda_bahaya'],
    },
    clue: 'Nyeri tragus/aurikula setelah berenang dengan edema liang telinga dan membran timpani utuh mendukung otitis eksterna akut ringan. Bersihkan liang telinga secara hati-hati bila perlu. Draf ini memakai asam asetat otik 2% sebanyak 5 tetes 3-4 kali sehari; ajarkan teknik tetes, jaga telinga kering, dan nilai respons dalam 48-72 jam. Antibiotik sistemik bukan terapi rutin. Rujuk bila ada penyebaran/komplikasi, kecurigaan otitis eksterna maligna, faktor host berisiko dengan gejala berat, atau gagal membaik.',
    mutiaraEbm: 'Pastikan status membran timpani sebelum memilih tetes otik; beberapa larutan bersifat iritatif/ototoksik bila masuk telinga tengah.',
    panduanResmi: 'PPK 1186/2022 menempatkan otitis eksterna sebagai 4A dan merekomendasikan pembersihan hati-hati serta terapi topikal. AAO-HNSF menganjurkan terapi topikal untuk penyakit akut difus tanpa komplikasi dan penilaian ulang bila tidak membaik dalam 48-72 jam. Fornas 1199/2025 mencantumkan asam asetat tetes telinga 2%.',
    catatanRealita: 'PPK menyebut povidon iodin atau tampon kombinasi antibiotik-steroid, bukan asam asetat secara spesifik. Pilihan asam asetat dalam draf berasal dari ketersediaan Fornas dan didukung label produk pembanding, sehingga pilihan agen, tolerabilitas, dan durasi lokal tetap memerlukan keputusan dokter sebelum aktivasi.',
  },
  {
    id: 'fraktur_terbuka_tibia_stabil',
    nama: 'Fraktur Terbuka Tibia - Stabilisasi Pra-Rujuk',
    icd10: 'S82.2',
    skdi: '3B',
    kategori: 'muskuloskeletal',
    fktp144: false,
    harusDirujuk: true,
    prevalensi: 'rendah',
    spesialisRujukan: 'bedah',
    keluhanUtama: 'Kaki kanan saya terluka dan tulangnya kelihatan setelah jatuh dari motor, Dok.',
    demografi: { usiaMin: 18, usiaMax: 50 },
    vital: { td: '108/70', nadi: 108, rr: 22, suhu: 36.6, spo2: 98 },
    anamnesis: [
      { id: 'ft_keluhan', kategori: 'keluhan_utama', tanya: 'Bagaimana kecelakaannya dan bagian mana yang paling sakit?', jawab: 'Motor tergelincir sekitar satu jam lalu. Kaki kanan bawah terbentur aspal dan ada luka terbuka.', esensial: true, oldcarts: ['onset', 'lokasi', 'karakter'] },
      { id: 'ft_mekanisme', kategori: 'rps', tanya: 'Seberapa cepat benturannya dan apakah tubuh terpental?', jawab: 'Kecepatan sedang, saya jatuh ke sisi kanan dan tidak terlindas.', esensial: true, bukaSetelah: ['ft_keluhan'], oldcarts: ['keparahan'] },
      { id: 'ft_abc', kategori: 'rps', tanya: 'Sempat pingsan, muntah, sesak, atau nyeri leher/dada/perut?', jawab: 'Tidak pingsan, muntah, atau sesak. Leher, dada, dan perut tidak sakit.', esensial: true, bukaSetelah: ['ft_keluhan'], oldcarts: ['penyerta'] },
      { id: 'ft_darah', kategori: 'rps', tanya: 'Darah sempat menyembur atau membasahi banyak kain?', jawab: 'Tidak menyembur. Darah merembes dan berkurang setelah dibalut kain bersih.', esensial: true, oldcarts: ['karakter', 'keparahan'] },
      { id: 'ft_neurovaskular', kategori: 'rps', tanya: 'Jari kaki kebas, dingin, pucat, atau sulit digerakkan?', jawab: 'Jari masih terasa dan bisa digerakkan pelan, tetapi tungkai sangat sakit.', esensial: true, oldcarts: ['penyerta'] },
      { id: 'ft_kontaminasi', kategori: 'rps', tanya: 'Lukanya terkena tanah, air selokan, atau bahan kimia?', jawab: 'Terkena debu dan pasir aspal, tidak masuk selokan.', esensial: true },
      { id: 'ft_tetanus', kategori: 'rpd', tanya: 'Kapan terakhir vaksin tetanus? Ada catatan imunisasi?', jawab: 'Tidak ingat dan tidak membawa catatan vaksin.', esensial: true },
      { id: 'ft_obat', kategori: 'rpd', tanya: 'Ada alergi antibiotik, minum pengencer darah, atau penyakit berat?', jawab: 'Tidak ada alergi yang diketahui dan tidak minum pengencer darah.', esensial: true },
    ],
    pemeriksaanFisik: [
      { region: 'umum', temuan: 'Sadar penuh; airway-breathing stabil; tidak ada tanda syok dekompensata.', relevan: true },
      { region: 'ekstremitas', temuan: 'Luka 4 cm anteromedial tungkai kanan dengan fragmen tulang tampak, kontaminasi sedang, deformitas; perdarahan merembes.', relevan: true },
      { region: 'ekstremitas', temuan: 'Nadi dorsalis pedis teraba, CRT jari <2 detik, sensibilitas dan gerak jari masih ada.', relevan: true },
      { region: 'neurologis', temuan: 'GCS 15 tanpa defisit fokal.', relevan: false },
      { region: 'abdomen', temuan: 'Abdomen lunak tanpa nyeri tekan.', relevan: false },
    ],
    lab: [
      { id: 'darah_rutin', hasil: 'Hb 12,8 g/dL; leukosit 11.200/uL; trombosit normal. Tidak menunda rujukan.', flag: 'normal', relevan: true },
      { id: 'golongan_darah', hasil: 'O Rh positif; dicatat untuk jejaring rujukan.', flag: 'normal', relevan: false },
    ],
    diagnosisBanding: ['S82.2', 'S80.1', 'S83.9'],
    tatalaksana: {
      obatBenar: ['sefazolin_inj_1g', 'vaksin_td', 'tetanus_imunoglobulin_250'],
      obatSalahUmum: [
        { id: 'cefadroxil_500', alasan: 'Antibiotik oral bukan pengganti profilaksis antibiotik parenteral dini pada fraktur terbuka.', bahaya: 'nonPrimer' },
      ],
      prosedur: ['irigasi_luka_fraktur_terbuka', 'balut_luka_steril', 'imobilisasi_bidai', 'pasang_infus'],
      edukasi: ['keselamatan_fraktur_rujuk', 'tanda_bahaya'],
      edukasiKritis: ['keselamatan_fraktur_rujuk'],
    },
    clue: 'Fraktur terbuka adalah emergensi 3B: lakukan primary survey, kontrol perdarahan dengan tekanan lembut, irigasi singkat dengan NaCl untuk membuang kontaminan lepas tanpa debridement atau manipulasi fragmen, tutup luka steril, nilai neurovaskular sebelum-sesudah bidai, beri antibiotik parenteral sedini mungkin dan profilaksis tetanus sesuai riwayat, lalu rujuk segera untuk debridement/fiksasi. Analgesia harus diberikan sesuai kondisi dan protokol, tetapi pilihan regimen masih menunggu review dokter. Pemeriksaan radiologi di FKTP tidak boleh menunda transfer.',
    mutiaraEbm: 'Jangan berulang kali membuka balutan atau memanipulasi fragmen untuk "melihat" luka; dokumentasikan status neurovaskular dan mekanisme sebelum transfer.',
    panduanResmi: 'PPK 1186/2022 menetapkan fraktur terbuka sebagai 3B dan meminta tata laksana emergensi, irigasi/pembersihan awal yang aman, imobilisasi, cairan, antibiotik IV, pencegahan tetanus, lalu rujuk setelah stabil. PNPK Trauma menempatkan peran utama Puskesmas pada stabilisasi dan transfer aman.',
    catatanRealita: 'Sefazolin tercantum di Fornas dengan restriksi profilaksis bedah; entri itu tidak sendirinya membuktikan regimen fraktur terbuka atau stok rutin FPKTP. Pilihan/dosis antibiotik, analgesia, kebutuhan cakupan tambahan, profilaksis tetanus, dan jangan-menunda-transfer harus mengikuti protokol trauma jejaring setempat; semuanya menunggu review dokter sebelum aktivasi.',
    konsekuensi: {
      narasi: 'Menutup luka tanpa antibiotik/tetanus, mendorong fragmen kembali, atau mengirim tanpa bidai meningkatkan perdarahan, kontaminasi, nyeri, dan kerusakan neurovaskular.',
      kembaliHariMin: 0,
      kembaliHariMax: 1,
      kondisiKembali: 'Pasien tiba kembali dengan perdarahan bertambah dan kaki pucat setelah tungkai dipindahkan tanpa imobilisasi.',
      guideline: 'PPK FKTP 1186/2022; PNPK Trauma 132/2017.',
    },
    stabilisasiWajib: 'imobilisasi_bidai',
  },
]
