import type { EvidenceBinding } from '../types'

const PENDING = 'pending' as const

export const M13_1A_EVIDENCE_BINDINGS: EvidenceBinding[] = [
  {
    id: 'm13-1a:item-status-asmatikus-skdi',
    subject: { kind: 'curriculum_item', id: 'clinical:status_asmatikus_anak' },
    facet: 'skdi',
    source: 'skdi:kki-2012',
    locator: 'Daftar Penyakit Sistem Respirasi no. 248: Status asmatikus (asma akut berat), level 3B',
    population: 'Anak dan dewasa dengan asma akut berat; draf encounter dibatasi usia 6-11 tahun',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:item-fraktur-terbuka-skdi',
    subject: { kind: 'curriculum_item', id: 'clinical:fraktur_terbuka' },
    facet: 'skdi',
    source: 'skdi:kki-2012',
    locator: 'Daftar Penyakit Sistem Muskuloskeletal no. 608: Fraktur terbuka/tertutup, level 3B',
    population: 'Pasien dewasa dengan fraktur terbuka ekstremitas',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:item-infark-skdi',
    subject: { kind: 'curriculum_item', id: 'clinical:infark_miokard_akut' },
    facet: 'skdi',
    source: 'skdi:kki-2012',
    locator: 'Daftar Penyakit Sistem Kardiovaskular no. 280: Infark miokard, level 3B',
    population: 'Dewasa dengan dugaan infark miokard akut',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:nayla-assessment',
    subject: { kind: 'encounter_archetype', id: 'clinic:diare_akut_bayi_dehidrasi_berat' },
    facet: 'assessment',
    source: 'who:imci-chart-booklet-2014',
    locator: 'Chart booklet pp. 3 and 20: four signs and classification of severe dehydration; Plan C',
    population: 'Bayi 3 bulan dengan diare akut dan tanda dehidrasi berat',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:nayla-anamnesis',
    subject: { kind: 'encounter_archetype', id: 'clinic:diare_akut_bayi_dehidrasi_berat' },
    facet: 'anamnesis',
    source: 'who:imci-chart-booklet-2014',
    locator: 'Assess and classify diarrhoea: duration, blood, general condition, eyes, drinking, skin pinch',
    population: 'Bayi 3 bulan; jawaban diberikan oleh wali anak',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:nayla-regimen-dose',
    subject: { kind: 'encounter_archetype', id: 'clinic:diare_akut_bayi_dehidrasi_berat' },
    facet: 'dose',
    source: 'who:imci-chart-booklet-2014',
    locator: 'Plan C: 100 mL/kg; infant <12 months 30 mL/kg in 1 h then 70 mL/kg in 5 h; reassess 1-2 hourly',
    population: 'Bayi usia kurang dari 12 bulan dengan dehidrasi berat',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:nayla-disposition',
    subject: { kind: 'encounter_archetype', id: 'clinic:diare_akut_bayi_dehidrasi_berat' },
    facet: 'disposition',
    source: 'who:imci-chart-booklet-2014',
    locator: 'Plan C referral branches when IV treatment cannot be delivered immediately/nearby; ORS during transfer when safe',
    population: 'Bayi 3 bulan letargis dengan akses dan kapasitas FKTP yang harus dinilai segera',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:dimas-assessment',
    subject: { kind: 'encounter_archetype', id: 'clinic:asma_eksaserbasi_berat_anak' },
    facet: 'assessment',
    source: 'kemenkes:asma-fktp-2015',
    locator: 'Bagian eksaserbasi akut anak: bicara kata, retraksi, SpO2 <90%, PEF <=50% sebagai kriteria berat',
    population: 'Anak 7 tahun dengan asma dan hipoksemia setelah terapi pelega di rumah',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:dimas-red-flags',
    subject: { kind: 'encounter_archetype', id: 'clinic:asma_eksaserbasi_berat_anak' },
    facet: 'anamnesis',
    source: 'who:childhood-asthma-2026',
    locator: 'Management of asthma in children: severity assessment, inability to complete sentences, SpO2 <90%, impending collapse',
    population: 'Anak 6-11 tahun dengan eksaserbasi asma akut',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:dimas-regimen',
    subject: { kind: 'encounter_archetype', id: 'clinic:asma_eksaserbasi_berat_anak' },
    facet: 'regimen',
    source: 'who:childhood-asthma-2026',
    locator: 'Recommendation 1a: nebulized ipratropium added to inhaled SABA and systemic corticosteroid in severe paediatric exacerbation',
    population: 'Anak 7 tahun dengan eksaserbasi berat di fasilitas kesehatan',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:dimas-dose-local',
    subject: { kind: 'encounter_archetype', id: 'clinic:asma_eksaserbasi_berat_anak' },
    facet: 'dose',
    source: 'kemenkes:asma-fktp-2015',
    locator: 'Tata laksana serangan akut anak: SABA inhalasi dapat diulang sampai 3 kali tiap 20 menit; prednison/prednisolon 1-2 mg/kg/hari (maks 40 mg)',
    population: 'Anak 7 tahun; dosis individual wajib dihitung dari berat badan sebelum aktivasi',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:dimas-formulary',
    subject: { kind: 'encounter_archetype', id: 'clinic:asma_eksaserbasi_berat_anak' },
    facet: 'formulary',
    source: 'fornas:kmk-1199-2025',
    locator: 'PDF pp. 198-200: ipratropium 0,5 mg + salbutamol 2,5 mg for acute asthma/UGD; prednison and salbutamol entries',
    population: 'Anak dengan serangan asma akut; ikuti restriksi sediaan dan fasilitas',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:dimas-disposition',
    subject: { kind: 'encounter_archetype', id: 'clinic:asma_eksaserbasi_berat_anak' },
    facet: 'disposition',
    source: 'kemenkes:asma-fktp-2015',
    locator: 'Kriteria serangan mengancam nyawa/tidak respons: lanjutkan stabilisasi dan rujuk',
    population: 'Anak dengan hipoksemia dan respons tidak memadai setelah terapi awal',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:hypo-diagnosis',
    subject: { kind: 'encounter_archetype', id: 'clinic:hipoglikemia_ringan_dewasa' },
    facet: 'diagnosis',
    source: 'pnpk:dm-tipe2-dewasa-302-2026',
    locator: 'PDF p. 72 and pp. 143-144: hypoglycaemia <70 mg/dL, autonomic/neuroglycopenic symptoms',
    population: 'Dewasa sadar dengan DM2, gejala adrenergik, dan GDS 58 mg/dL',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:hypo-regimen',
    subject: { kind: 'encounter_archetype', id: 'clinic:hipoglikemia_ringan_dewasa' },
    facet: 'regimen',
    source: 'pnpk:dm-tipe2-dewasa-302-2026',
    locator: 'PDF pp. 143-144: oral glucose 15-20 g in conscious patient; repeat check after 15 minutes; meal after recovery',
    population: 'Dewasa sadar dan mampu menelan dengan hipoglikemia ringan',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:hypo-disposition',
    subject: { kind: 'encounter_archetype', id: 'clinic:hipoglikemia_ringan_dewasa' },
    facet: 'disposition',
    source: 'pnpk:dm-tipe2-dewasa-302-2026',
    locator: 'PDF pp. 150-151: unresolved hypoglycaemia is a referral indication; resolved hypoglycaemia can return to primary care',
    population: 'Dewasa sadar yang segera membaik, dapat diobservasi dengan aman, dan memiliki pencetus makan terlewat yang jelas',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:hypo-follow-up',
    subject: { kind: 'encounter_archetype', id: 'clinic:hipoglikemia_ringan_dewasa' },
    facet: 'follow-up',
    source: 'pnpk:dm-tipe2-dewasa-302-2026',
    locator: 'PDF pp. 144-145: evaluate trigger; stop/reduce causative medicine and align sulfonylurea regimen with food and activity',
    population: 'Dewasa pengguna sulfonilurea tanpa gagal ginjal/hati pada vignette',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:nasal-foreign-body-anamnesis',
    subject: { kind: 'encounter_archetype', id: 'clinic:benda_asing_hidung_anak' },
    facet: 'anamnesis',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF pp. 500-501: onset unilateral, jenis benda, gejala lokal, dan laporan orang tua',
    population: 'Anak usia 3-5 tahun dengan benda asing hidung yang disaksikan wali',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:nasal-foreign-body-assessment',
    subject: { kind: 'encounter_archetype', id: 'clinic:benda_asing_hidung_anak' },
    facet: 'assessment',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF pp. 501-502: rinoskopi anterior, risiko aspirasi, dan kerusakan cepat oleh baterai',
    population: 'Anak stabil dengan manik-manik plastik anterior yang tampak jelas, bukan baterai atau benda tajam',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:nasal-foreign-body-regimen',
    subject: { kind: 'encounter_archetype', id: 'clinic:benda_asing_hidung_anak' },
    facet: 'regimen',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF pp. 978-980: pemilihan pengait, kateter balon, atau suction menurut bentuk; hindari forceps pada benda bulat',
    population: 'Anak kooperatif dengan benda bulat yang terlihat dan alat ekstraksi yang sesuai tersedia',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:nasal-foreign-body-disposition',
    subject: { kind: 'encounter_archetype', id: 'clinic:benda_asing_hidung_anak' },
    facet: 'disposition',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF p. 502: rujuk bila perlekatan/posisi sulit dilihat, ekstraksi gagal, atau pasien tidak kooperatif',
    population: 'Anak dengan benda asing hidung; vignette aktif hanya dapat ditangani di FKTP bila visualisasi dan posisi aman',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:otitis-diagnosis',
    subject: { kind: 'encounter_archetype', id: 'clinic:otitis_eksterna_akut_ringan' },
    facet: 'diagnosis',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF pp. 253-254: otalgia worsened by touching auricle, tragal tenderness, canal oedema/hyperaemia',
    population: 'Remaja atau dewasa imunokompeten dengan otitis eksterna akut difus unilateral ringan',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:otitis-regimen',
    subject: { kind: 'encounter_archetype', id: 'clinic:otitis_eksterna_akut_ringan' },
    facet: 'regimen',
    source: 'aao-hns:acute-otitis-externa-2014',
    locator: 'Key action statements 2 and 5-8: topical initial therapy, no routine systemic antimicrobial, delivery support, and reassessment in 48-72 h',
    population: 'Penyakit ringan dengan membran timpani utuh tanpa diabetes atau imunosupresi',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:otitis-dose-label',
    subject: { kind: 'encounter_archetype', id: 'clinic:otitis_eksterna_akut_ringan' },
    facet: 'dose',
    source: 'dailymed:acetic-acid-otic-2-2025',
    locator: 'Dosage and Administration: after canal cleaning, 5 drops three or four times daily; perforated tympanic membrane listed as contraindication',
    population: 'Remaja atau dewasa dengan membran timpani tampak utuh dan edema ringan tanpa sumbatan bermakna',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:otitis-formulary',
    subject: { kind: 'encounter_archetype', id: 'clinic:otitis_eksterna_akut_ringan' },
    facet: 'formulary',
    source: 'fornas:kmk-1199-2025',
    locator: 'PDF p. 213: acetic acid 2% ear drops listed for FPKTP/FPKTL',
    population: 'Pasien dengan membran timpani utuh; hindari bila dicurigai perforasi',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:otitis-disposition',
    subject: { kind: 'encounter_archetype', id: 'clinic:otitis_eksterna_akut_ringan' },
    facet: 'disposition',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF p. 255: refer otitis externa with complications or malignant otitis externa',
    population: 'Otitis eksterna ringan tanpa komplikasi atau tanda keganasan',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:fracture-assessment',
    subject: { kind: 'encounter_archetype', id: 'clinic:fraktur_terbuka_tibia_stabil' },
    facet: 'assessment',
    source: 'pnpk:trauma-132-2017',
    locator: 'Primary survey, haemorrhage control, repeated neurovascular assessment, and safe transfer sections',
    population: 'Dewasa dengan hemodinamik terkompensasi dan fraktur terbuka tibia terisolasi setelah kecelakaan lalu lintas',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:fracture-regimen',
    subject: { kind: 'encounter_archetype', id: 'clinic:fraktur_terbuka_tibia_stabil' },
    facet: 'regimen',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF pp. 295-297: emergency management, wound care, immobilisation, IV antibiotic, tetanus prevention, and immediate referral',
    population: 'Dewasa dengan fraktur terbuka tibia terkontaminasi menyerupai derajat II dan perfusi distal utuh',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:fracture-formulary',
    subject: { kind: 'encounter_archetype', id: 'clinic:fraktur_terbuka_tibia_stabil' },
    facet: 'formulary',
    source: 'fornas:kmk-1199-2025',
    locator: 'Cefazolin injection is listed with surgical-prophylaxis restriction; human tetanus immunoglobulin and Td entries require indication/facility review',
    population: 'Dewasa dengan luka terbuka terkontaminasi dan riwayat vaksinasi tetanus tidak diketahui',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:fracture-disposition',
    subject: { kind: 'encounter_archetype', id: 'clinic:fraktur_terbuka_tibia_stabil' },
    facet: 'disposition',
    source: 'ppk:kmk-1186-2022',
    locator: 'PDF p. 297: refer immediately after stabilisation while monitoring vital signs',
    population: 'Semua pasien fraktur terbuka setelah stabilisasi awal',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:stemi-diagnosis',
    subject: { kind: 'encounter_archetype', id: 'igd:igd_stemi_anterior_hipoksemik' },
    facet: 'diagnosis',
    source: 'pnpk:ska-675-2019',
    locator: 'PDF pp. 13-15: typical acute angina plus persistent ST elevation in contiguous leads',
    population: 'Laki-laki dewasa dengan nyeri dada menekan 35 menit dan elevasi ST anterior',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:stemi-assessment',
    subject: { kind: 'encounter_archetype', id: 'igd:igd_stemi_anterior_hipoksemik' },
    facet: 'assessment',
    source: 'pnpk:ska-675-2019',
    locator: 'PDF pp. 14 and 20: 12-lead ECG immediately/within 10 minutes; do not await biomarkers for diagnostic STEMI ECG',
    population: 'Kontak medis pertama di ruang tindakan gawat darurat FKTP',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:stemi-regimen',
    subject: { kind: 'encounter_archetype', id: 'igd:igd_stemi_anterior_hipoksemik' },
    facet: 'regimen',
    source: 'pnpk:ska-675-2019',
    locator: 'PDF pp. 18-19: aspirin 160-320 mg immediately if tolerated; oxygen for hypoxaemia/distress; nitrate contraindications',
    population: 'Dewasa dengan SpO2 88%, tanpa alergi aspirin, dan tanpa perdarahan aktif',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:stemi-disposition',
    subject: { kind: 'encounter_archetype', id: 'igd:igd_stemi_anterior_hipoksemik' },
    facet: 'disposition',
    source: 'pnpk:ska-675-2019',
    locator: 'Regional STEMI network and reperfusion-delay sections: minimise first-medical-contact-to-reperfusion time',
    population: 'STEMI di FKTP tanpa PCI dengan akses ambulans terpantau',
    reviewStatus: PENDING,
  },

  {
    id: 'm13-1a:gunawan-objective',
    subject: { kind: 'ukm_scenario', id: 'ukm:keluarga_gunawan:gunawan_k2' },
    facet: 'ukm-objective',
    source: 'kemenkes:pis-pk-monitoring-2017',
    locator: 'Twelve PIS-PK indicators: no family member smokes',
    population: 'Keluarga dengan ayah perokok dan anak dengan asma',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:gunawan-dependence-assessment',
    subject: { kind: 'ukm_scenario', id: 'ukm:keluarga_gunawan:gunawan_k2' },
    facet: 'assessment',
    source: 'who:tobacco-cessation-2024',
    locator: 'Assessment and treatment planning should consider dependence, withdrawal, prior quit attempts, behavioural support, and pharmacotherapy eligibility',
    population: 'Perokok dewasa sekitar dua bungkus per hari yang sempat berhenti tiga hari lalu relaps pada situasi kerja',
    reviewStatus: PENDING,
  },
  {
    id: 'm13-1a:gunawan-intervention',
    subject: { kind: 'ukm_scenario', id: 'ukm:keluarga_gunawan:gunawan_k2' },
    facet: 'follow-up',
    source: 'who:tobacco-cessation-2024',
    locator: 'Behavioural interventions and follow-up support for adults attempting tobacco cessation',
    population: 'Perokok dewasa dengan pencetus kerja atau mengemudi malam dan upaya berhenti baru-baru ini',
    reviewStatus: PENDING,
  },
]
