export type EvidenceRelation = 'direct' | 'related'

export interface PpkCrosswalkEntry {
  entryIndex: number
  relation: EvidenceRelation
  rationale?: string
}

export interface PnpkCrosswalkEntry {
  slug: string
  relation: EvidenceRelation
  rationale?: string
}

/**
 * Crosswalk editorial konservatif terhadap 167 bab KMK 1186/2022.
 * `related` tidak boleh ditampilkan sebagai pedoman diagnosis yang identik.
 * Kasus yang sengaja tidak tercantum berarti tidak ditemukan bab langsung/terkait.
 */
export const PPK_CROSSWALK: Record<string, PpkCrosswalkEntry> = {
  lab_pneumonia_komunitas_dewasa: { entryIndex: 97, relation: 'direct' },
  lab_influenza_tanpa_komplikasi: { entryIndex: 90, relation: 'direct' },
  lab_laringitis_akut: { entryIndex: 92, relation: 'direct' },
  lab_furunkel_hidung: { entryIndex: 101, relation: 'direct' },
  lab_rinitis_vasomotor: { entryIndex: 103, relation: 'direct' },
  lab_stomatitis_aftosa: { entryIndex: 19, relation: 'direct' },
  lab_kandidiasis_mulut: { entryIndex: 8, relation: 'direct' },
  lab_parotitis_mumps: { entryIndex: 34, relation: 'direct' },
  lab_intoleransi_makanan_laktosa: { entryIndex: 22, relation: 'direct' },
  lab_alergi_makanan_ringan: { entryIndex: 11, relation: 'direct' },
  lab_keracunan_makanan_ringan: { entryIndex: 10, relation: 'direct' },
  lab_hepatitis_a_akut: { entryIndex: 29, relation: 'direct' },
  lab_edema_paru_akut_hipertensif: {
    entryIndex: 63,
    relation: 'related',
    rationale: 'Bab gagal jantung, bukan bab edema paru hipertensif yang identik.',
  },
  lab_pneumotoraks_spontan: { entryIndex: 98, relation: 'direct' },
  lab_abses_peritonsil: {
    entryIndex: 93,
    relation: 'related',
    rationale: 'Bab tonsilitis akut memberi konteks, bukan tata laksana abses peritonsil definitif.',
  },
  lab_perdarahan_gi_atas: { entryIndex: 27, relation: 'direct' },
  lab_ileus_obstruktif: {
    entryIndex: 33,
    relation: 'related',
    rationale: 'Bab peritonitis hanya terkait kegawatan abdomen; diagnosis ileus tidak punya bab sendiri.',
  },
  lab_kejang_demam_sederhana: { entryIndex: 83, relation: 'direct' },
  lab_tetanus_generalisata_awal: { entryIndex: 76, relation: 'direct' },
  lab_hiv_tanpa_komplikasi: { entryIndex: 16, relation: 'direct' },
  lab_gangguan_somatoform: { entryIndex: 85, relation: 'direct' },
  lab_benda_asing_konjungtiva: { entryIndex: 41, relation: 'direct' },
  lab_perdarahan_subkonjungtiva: { entryIndex: 40, relation: 'direct' },
  lab_mata_kering: { entryIndex: 35, relation: 'direct' },
  lab_blefaritis_anterior: { entryIndex: 39, relation: 'direct' },
  lab_trikiasis: { entryIndex: 49, relation: 'direct' },
  lab_episkleritis_ringan: { entryIndex: 50, relation: 'direct' },
  lab_hipermetropia: { entryIndex: 43, relation: 'direct' },
  lab_miopia_ringan: { entryIndex: 44, relation: 'direct' },
  lab_astigmatisme_ringan: { entryIndex: 42, relation: 'direct' },
  lab_presbiopia: { entryIndex: 45, relation: 'direct' },
  lab_buta_senja_defisiensi_vitamin_a: { entryIndex: 36, relation: 'direct' },
  lab_infeksi_umbilikus_neonatus: { entryIndex: 7, relation: 'direct' },
  lab_gonore_uretritis_pria: { entryIndex: 164, relation: 'direct' },
  lab_pielonefritis_tanpa_komplikasi: { entryIndex: 147, relation: 'direct' },
  lab_fimosis_patologis_ringan: { entryIndex: 148, relation: 'direct' },
  lab_parafimosis_reduksibel: { entryIndex: 149, relation: 'direct' },
  lab_sindrom_duh_genital_servisitis: {
    entryIndex: 162,
    relation: 'related',
    rationale: 'Bab fluor albus/vaginal discharge, bukan servisitis terkonfirmasi.',
  },
  lab_vulvitis_iritan: { entryIndex: 166, relation: 'direct' },
  lab_vaginitis_kandida: { entryIndex: 165, relation: 'direct' },
  lab_vaginosis_bakterialis: {
    entryIndex: 165,
    relation: 'related',
    rationale: 'Bab vaginitis terkait, tetapi etiologi bakterial perlu sumber regimen yang lebih spesifik.',
  },
  lab_abortus_spontan_komplit: { entryIndex: 155, relation: 'direct' },
  lab_ruptur_perineum_derajat_1: { entryIndex: 158, relation: 'direct' },
  lab_abses_folikel_rambut: {
    entryIndex: 117,
    relation: 'related',
    rationale: 'Bab pioderma terkait infeksi kulit, bukan padanan abses yang identik.',
  },
  lab_mastitis_laktasi: { entryIndex: 159, relation: 'direct' },
  lab_puting_lecet: { entryIndex: 161, relation: 'direct' },
  lab_puting_tenggelam_laktasi: { entryIndex: 160, relation: 'direct' },
  lab_anemia_defisiensi_besi_nonhamil: {
    entryIndex: 15,
    relation: 'related',
    rationale: 'Bab anemia defisiensi besi relevan; kode sumber memakai klasifikasi lama 280.',
  },
  lab_limfadenitis_servikal_akut: { entryIndex: 18, relation: 'direct' },
  lab_leptospirosis_tanpa_komplikasi: { entryIndex: 5, relation: 'direct' },
  lab_anafilaksis_makanan: { entryIndex: 13, relation: 'direct' },
  lab_ulkus_tungkai_vena: { entryIndex: 137, relation: 'direct' },
  lab_lipoma_lengan: { entryIndex: 72, relation: 'direct' },
  lab_moluskum_kontagiosum_anak: { entryIndex: 110, relation: 'direct' },
  lab_herpes_simpleks_labialis: { entryIndex: 109, relation: 'direct' },
  lab_ektima_tungkai: {
    entryIndex: 117,
    relation: 'related',
    rationale: 'Bab pioderma/impetigo terkait; ektima lebih dalam dan tidak identik.',
  },
  lab_folikulitis_superfisialis: {
    entryIndex: 117,
    relation: 'related',
    rationale: 'Bab pioderma terkait, bukan padanan folikulitis langsung.',
  },
  lab_furunkel_fluktuatif: {
    entryIndex: 117,
    relation: 'related',
    rationale: 'Bab pioderma terkait, bukan padanan furunkel langsung.',
  },
  lab_eritrasma_lipat_paha: { entryIndex: 128, relation: 'direct' },
  lab_erisipelas_tungkai_ringan: { entryIndex: 118, relation: 'direct' },
  lab_skrofuloderma_suspek: { entryIndex: 129, relation: 'direct' },
  lab_kusta_pausibasiler: { entryIndex: 9, relation: 'direct' },
  lab_sifilis_primer: { entryIndex: 163, relation: 'direct' },
  lab_tinea_kapitis_anak: { entryIndex: 115, relation: 'direct' },
  lab_tinea_barbae: { entryIndex: 115, relation: 'direct' },
  lab_tinea_fasialis: { entryIndex: 115, relation: 'direct' },
  lab_tinea_manus: { entryIndex: 115, relation: 'direct' },
  lab_tinea_kruris: { entryIndex: 115, relation: 'direct' },
  lab_tinea_pedis: { entryIndex: 115, relation: 'direct' },
  lab_tinea_unguium_terkonfirmasi: { entryIndex: 115, relation: 'direct' },
  lab_pitiriasis_versikolor: { entryIndex: 116, relation: 'direct' },
  lab_cutaneous_larva_migrans: { entryIndex: 135, relation: 'direct' },
  lab_filariasis_terkonfirmasi: { entryIndex: 6, relation: 'direct' },
  lab_pedikulosis_pubis: { entryIndex: 114, relation: 'direct' },
  lab_reaksi_gigitan_serangga: { entryIndex: 111, relation: 'direct' },
  lab_dermatitis_kontak_iritan_tangan: { entryIndex: 124, relation: 'direct' },
  lab_dermatitis_atopik_ringan: { entryIndex: 120, relation: 'direct' },
  lab_dermatitis_numularis: { entryIndex: 121, relation: 'direct' },
  lab_dermatitis_popok_iritan: { entryIndex: 125, relation: 'direct' },
  lab_dermatitis_seboroik_dewasa: { entryIndex: 119, relation: 'direct' },
  lab_pitiriasis_rosea: { entryIndex: 127, relation: 'direct' },
  lab_akne_vulgaris_ringan: { entryIndex: 131, relation: 'direct' },
  lab_hidradenitis_supuratif_hurley1: { entryIndex: 130, relation: 'direct' },
  lab_dermatitis_perioral: { entryIndex: 126, relation: 'direct' },
  lab_miliaria_rubra: { entryIndex: 106, relation: 'direct' },
  lab_erupsi_obat_morbiliformis: { entryIndex: 133, relation: 'direct' },
  lab_vulnus_laseratum_lengan: { entryIndex: 71, relation: 'direct' },
  lab_luka_bakar_derajat2_dangkal: { entryIndex: 136, relation: 'direct' },
  lab_kolesistitis_akut: { entryIndex: 31, relation: 'direct' },
  lab_apendisitis_akut_anak: { entryIndex: 32, relation: 'direct' },
  lab_peritonitis_generalisata: { entryIndex: 33, relation: 'direct' },
  lab_hemoroid_interna_derajat4: {
    entryIndex: 28,
    relation: 'related',
    rationale: 'PPK membahas grade 1-2; kasus grade IV memakai bab ini hanya untuk batas rujuk.',
  },
  lab_katarak_matur: { entryIndex: 46, relation: 'direct' },
  lab_retinopati_diabetik_proliferatif: { entryIndex: 54, relation: 'direct' },
  lab_otitis_media_supuratif_kronik_komplikata: { entryIndex: 57, relation: 'direct' },
  lab_mastoiditis_akut: {
    entryIndex: 57,
    relation: 'related',
    rationale: 'Komplikasi OMSK terkait, tetapi mastoiditis akut tidak mempunyai bab PPK sendiri.',
  },
  lab_tia_serangan_iskemik_sesaat: { entryIndex: 80, relation: 'direct' },
  lab_gagal_jantung_dekompensasi: { entryIndex: 63, relation: 'direct' },
  lab_hipertiroid_graves: { entryIndex: 140, relation: 'related', rationale: 'Bab tirotoksikosis, bukan Graves spesifik.' },
  lab_anemia_berat_perlu_transfusi: {
    entryIndex: 15,
    relation: 'related',
    rationale: 'Bab anemia defisiensi besi tidak identik dengan anemia berat etiologi belum pasti.',
  },
  lab_kaki_diabetik_infeksi: {
    entryIndex: 141,
    relation: 'related',
    rationale: 'Bab DM tipe 2 memberi konteks, bukan pedoman kaki diabetik terinfeksi lengkap.',
  },
  lab_tb_paru_putus_obat_suspek_mdr: { entryIndex: 0, relation: 'direct' },
  lab_hepatitis_b_kronik: {
    entryIndex: 30,
    relation: 'related',
    rationale: 'Bab PPK berjudul hepatitis B tanpa pemisahan kronik; PNPK hepatitis B menjadi sumber utama.',
  },
  lab_ppok_eksaserbasi_berat: { entryIndex: 99, relation: 'direct' },
  lab_hiperemesis_gravidarum_berat: {
    entryIndex: 151,
    relation: 'related',
    rationale: 'Bab PPK membahas hiperemesis ringan; kasus ini berat dengan ketosis dan wajib dirujuk.',
  },
  lab_fraktur_tertutup_antebrachii_anak: { entryIndex: 67, relation: 'direct' },
}

/** Diagnosis-specific PNPK/program crosswalk. Absence is reported, never inferred. */
export const PNPK_CROSSWALK: Record<string, PnpkCrosswalkEntry[]> = {
  lab_pneumonia_komunitas_dewasa: [{ slug: 'pneumonia-dewasa-2023', relation: 'direct' }],
  lab_bronkiolitis_berat: [{ slug: 'sepsis-anak', relation: 'related', rationale: 'Only for stabilization principles; not a bronchiolitis guideline.' }],
  lab_edema_paru_akut_hipertensif: [{ slug: 'hipertensi-dewasa-2026', relation: 'related' }],
  lab_pneumotoraks_spontan: [{ slug: 'trauma', relation: 'related' }],
  lab_abses_peritonsil: [{ slug: 'tonsilitis', relation: 'related' }],
  lab_perdarahan_gi_atas: [{ slug: 'perdarahan-saluran-cerna', relation: 'direct' }],
  lab_ileus_obstruktif: [{ slug: 'infeksi-intraabdominal', relation: 'related' }],
  lab_kejang_demam_sederhana: [{ slug: 'epilepsi-anak', relation: 'related' }],
  lab_gangguan_somatoform: [{ slug: 'kedokteran-jiwa-2015', relation: 'direct' }],
  lab_infeksi_umbilikus_neonatus: [{ slug: 'sepsis-anak', relation: 'related' }],
  lab_pielonefritis_tanpa_komplikasi: [{ slug: 'infeksi-saluran-kemih', relation: 'direct' }],
  lab_salpingitis_pid_ringan: [{ slug: 'komplikasi-kehamilan', relation: 'related' }],
  lab_abortus_spontan_komplit: [{ slug: 'komplikasi-kehamilan', relation: 'direct' }],
  lab_ruptur_perineum_derajat_1: [{ slug: 'komplikasi-kehamilan', relation: 'related' }],
  lab_mastitis_laktasi: [{ slug: 'komplikasi-kehamilan', relation: 'related' }],
  lab_puting_lecet: [{ slug: 'komplikasi-kehamilan', relation: 'related' }],
  lab_puting_tenggelam_laktasi: [{ slug: 'komplikasi-kehamilan', relation: 'related' }],
  lab_malnutrisi_energi_protein_sedang: [{ slug: 'stunting', relation: 'related' }],
  lab_anafilaksis_makanan: [{ slug: 'sepsis-dewasa', relation: 'related', rationale: 'Only general emergency stabilization context.' }],
  lab_kusta_pausibasiler: [{ slug: 'kusta', relation: 'direct' }],
  lab_dermatitis_seboroik_dewasa: [{ slug: 'dermatitis-seboroik', relation: 'direct' }],
  lab_vulnus_laseratum_lengan: [{ slug: 'trauma', relation: 'direct' }],
  lab_luka_bakar_derajat2_dangkal: [{ slug: 'trauma', relation: 'direct' }],
  lab_trauma_tumpul_kepala_ringan: [{ slug: 'trauma', relation: 'direct' }],
  lab_trauma_tajam_kulit_kepala: [{ slug: 'trauma', relation: 'direct' }],
  lab_hernia_inguinalis_inkarserata: [{ slug: 'infeksi-intraabdominal', relation: 'related' }],
  lab_kolesistitis_akut: [{ slug: 'infeksi-intraabdominal', relation: 'direct' }],
  lab_apendisitis_akut_anak: [{ slug: 'infeksi-intraabdominal', relation: 'direct' }],
  lab_peritonitis_generalisata: [{ slug: 'infeksi-intraabdominal', relation: 'direct' }],
  lab_kolik_ureter_obstruksi: [{ slug: 'batu-saluran-kemih', relation: 'direct' }],
  lab_trauma_abdomen_tumpul: [{ slug: 'trauma', relation: 'direct' }],
  lab_katarak_matur: [{ slug: 'katarak-dewasa-2026', relation: 'direct' }],
  lab_retinopati_diabetik_proliferatif: [{ slug: 'retinopati-diabetika', relation: 'direct' }],
  lab_otitis_media_supuratif_kronik_komplikata: [{ slug: 'omsk', relation: 'direct' }],
  lab_mastoiditis_akut: [{ slug: 'omsk', relation: 'related' }],
  lab_tia_serangan_iskemik_sesaat: [{ slug: 'stroke-2026', relation: 'related' }],
  lab_penyakit_ginjal_kronik_st3b: [{ slug: 'penyakit-ginjal-kronik', relation: 'direct' }],
  lab_gagal_jantung_dekompensasi: [{ slug: 'sindroma-koroner-akut', relation: 'related' }],
  lab_sirosis_hepatis_dekompensata: [{ slug: 'sirosis-hati', relation: 'direct' }],
  lab_kaki_diabetik_infeksi: [{ slug: 'dm-tipe2-dewasa-2026', relation: 'related' }],
  lab_tb_paru_putus_obat_suspek_mdr: [{ slug: 'tuberkulosis', relation: 'direct' }],
  lab_hepatitis_b_kronik: [{ slug: 'hepatitis-b', relation: 'direct' }],
  lab_ppok_eksaserbasi_berat: [{ slug: 'ppok', relation: 'direct' }],
  lab_kehamilan_ektopik_terganggu_suspek: [{ slug: 'komplikasi-kehamilan', relation: 'direct' }],
  lab_plasenta_previa: [{ slug: 'komplikasi-kehamilan', relation: 'direct' }],
  lab_penyakit_radang_panggul_berat: [{ slug: 'komplikasi-kehamilan', relation: 'related' }],
  lab_mola_hidatidosa: [{ slug: 'komplikasi-kehamilan', relation: 'direct' }],
  lab_hiperemesis_gravidarum_berat: [{ slug: 'komplikasi-kehamilan', relation: 'direct' }],
  lab_fraktur_tertutup_antebrachii_anak: [{ slug: 'trauma', relation: 'direct' }],
  lab_talasemia_beta_mayor_anak: [{ slug: 'talasemia-2018', relation: 'direct' }],
  lab_gizi_buruk_komplikasi: [
    { slug: 'stunting', relation: 'related' },
    { slug: 'sepsis-anak', relation: 'related' },
  ],
}

/** Exact/normalized phrases used to find traceable lines in Fornas 1199 text. */
export const FORNAS_QUERIES: Record<string, string[]> = {
  air_mata_buatan: ['hipromelosa'],
  amoxiclav_625: ['amoksisilin-asam klavulanat'],
  arv_tld: ['tenofovir', 'lamivudin', 'dolutegravir'],
  betametason_krim_005: ['betametason'],
  ctm_4: ['klorfeniramin'],
  isosorbid_dinitrat_5: ['isosorbid dinitrat'],
  kalamin_losion: ['kalamin'],
  klotrimazol_vaginal_100: ['klotrimazol'],
  nistatin_suspensi: ['nistatin'],
  oralit: ['garam oralit'],
  ringer_laktat_inf: ['ringer laktat'],
  tablet_fe: ['fero sulfat', 'asam folat'],
}

/**
 * Queries target KFA active-substance master data, not product templates.
 * Multiple components are intentional for combinations/program packs.
 */
export const KFA_QUERIES: Record<string, string[]> = {
  air_mata_buatan: ['Hypromellose'],
  albendazol_400: ['Albendazole'],
  amlodipine_5: ['Amlodipine'],
  amoxicillin_500: ['Amoxicillin'],
  amoxiclav_625: ['Amoxicillin', 'Clavulanate'],
  arv_tld: ['Tenofovir Disoproxil', 'Lamivudine', 'Dolutegravir'],
  asam_asetat_tetes_telinga_2: ['Acetic Acid'],
  asam_folat_5: ['Folic Acid'],
  asam_traneksamat_500_inj: ['Tranexamic Acid'],
  asiklovir_400: ['Acyclovir'],
  azitromisin_500: ['Azithromycin'],
  benzatin_penisilin_24juta: ['Benzathine Benzylpenicillin'],
  benzoyl_peroksida_25: ['Benzoyl Peroxide'],
  betametason_krim_005: ['Betamethasone Valerate'],
  captopril_25: ['Captopril'],
  cefadroxil_500: ['Cefadroxil'],
  cefadroxil_sirup_125: ['Cefadroxil'],
  ceftriaxone_1g_inj: ['Ceftriaxone'],
  cetirizine_10: ['Cetirizine'],
  ciprofloxacin_500: ['Ciprofloxacin'],
  ctm_4: ['Chlorpheniramine'],
  dietilkarbamazin_100: ['Diethylcarbamazine'],
  dimenhidrinat_50: ['Dimenhydrinate'],
  doksisiklin_100: ['Doxycycline'],
  emolien_petrolatum: ['Petrolatum'],
  flutikason_semprot_hidung: ['Fluticasone'],
  furosemid_40: ['Furosemide'],
  furosemid_inj_20: ['Furosemide'],
  griseofulvin_125: ['Griseofulvin'],
  griseofulvin_500: ['Griseofulvin'],
  hidrokortison_krim: ['Hydrocortisone'],
  hyoscine_butilbromida_20_inj: ['Butylscopolamine'],
  ibuprofen_400: ['Ibuprofen'],
  insulin_nph: ['Insulin Isophane, Human'],
  insulin_regular: ['Insulin, Regular, Human'],
  isosorbid_dinitrat_5: ['Isosorbide Dinitrate'],
  ivermektin_3: ['Ivermectin'],
  kalamin_losion: ['Calamine'],
  ketokonazol_krim: ['Ketoconazole'],
  ketorolak_30_inj: ['Ketorolac'],
  klindamisin_topikal_1: ['Clindamycin'],
  kloramfenikol_tetes_mata: ['Chloramphenicol'],
  klotrimazol_vaginal_100: ['Clotrimazole'],
  laktulosa_syr: ['Lactulose'],
  mdt_kusta_pb: ['Rifampicin', 'Dapsone'],
  metformin_500: ['Metformin'],
  metronidazol_500: ['Metronidazole'],
  metronidazol_inj_500: ['Metronidazole'],
  metronidazol_topikal_075: ['Metronidazole'],
  mikonazol_krim: ['Miconazole'],
  mupirosin_krim: ['Mupirocin'],
  nacl_09_inf: ['Sodium Chloride'],
  natrium_diklofenak_50: ['Diclofenac Sodium'],
  nistatin_suspensi: ['Nystatin'],
  ondansetron_4: ['Ondansetron'],
  oralit: ['Sodium Chloride', 'Potassium Chloride', 'Glucose', 'Sodium Citrate'],
  paracetamol_500: ['Paracetamol'],
  paracetamol_sirup: ['Paracetamol'],
  permetrin_losion_1: ['Permethrin'],
  prazikuantel_600: ['Praziquantel'],
  prednison_5: ['Prednisone'],
  propiltiourasil_100: ['Propylthiouracil'],
  propranolol_10: ['Propranolol'],
  ramipril_5: ['Ramipril'],
  ringer_laktat_inf: ['Sodium Chloride', 'Potassium Chloride', 'Calcium Chloride', 'Sodium Lactate'],
  simvastatin_20: ['Simvastatin'],
  spironolakton_25: ['Spironolactone'],
  tablet_fe: ['Ferrous Sulfate', 'Folic Acid'],
  tamsulosin_04: ['Tamsulosin'],
  tramadol_50: ['Tramadol'],
  triamcinolone_orabase: ['Triamcinolone Acetonide'],
  vitamin_a_kapsul: ['Retinol'],
  vitamin_b_kompleks: ['Thiamine', 'Riboflavin', 'Pyridoxine', 'Nicotinamide'],
  zinc_oxide_krim: ['Zinc Oxide'],
}

export const EXTERNAL_PNPK_SOURCES: Record<string, {
  title: string
  documentNumber: string
  officialUrl: string
  population: string
  facilityScope: string
}> = {
  'pneumonia-dewasa-2023': {
    title: 'PNPK Tata Laksana Pneumonia pada Dewasa',
    documentNumber: 'HK.01.07/MENKES/2147/2023',
    officialUrl: 'https://jdih.kemkes.go.id/common/dokumen/KMK%20No.%20HK.01.07-MENKES-2147-2023%20ttg%20Pedoman%20Nasional%20Pelayanan%20Kedokteran%20Tata%20Laksana%20Pneumonia%20Pada%20Dewasa-signed.pdf',
    population: 'Dewasa dengan pneumonia',
    facilityScope: 'Lintas tingkat fasilitas; relevansi rawat jalan/FKTP harus dibaca per bagian.',
  },
  'katarak-dewasa-2026': {
    title: 'PNPK Tatalaksana Katarak pada Dewasa',
    documentNumber: 'HK.01.07/MENKES/67/2026',
    officialUrl: 'https://keslan.kemkes.go.id/unduhan/fileunduhan1776933479_335376.pdf',
    population: 'Dewasa dengan katarak',
    facilityScope: 'Lintas tingkat fasilitas; FKTP berperan pada deteksi dan rujukan.',
  },
  'talasemia-2018': {
    title: 'PNPK Tata Laksana Talasemia',
    documentNumber: 'HK.01.07/MENKES/1/2018',
    officialUrl: 'https://kemkes.go.id/id/media/list/pedoman/pedoman-nasional-pelayanan-kedokteran-pnpk/pnpk-2018',
    population: 'Anak dan dewasa dengan talasemia',
    facilityScope: 'Lintas tingkat fasilitas; tata laksana definitif berada di jejaring rujukan.',
  },
}
