const EN_EXACT_LABELS = new Map([
    ['Darah Lengkap', 'Complete Blood Count'],
    ['Darah Lengkap (DL)', 'Complete Blood Count (CBC)'],
    ['Katalog Obat', 'Medicine Catalog'],
    ['Katalog Pemeriksaan', 'Test Catalog'],
    ['Gula Darah Sewaktu', 'Random Blood Glucose'],
    ['Gula Darah Sewaktu (GDS)', 'Random Blood Glucose (RBG)'],
    ['Golongan Darah + Rhesus', 'Blood Type + Rhesus'],
    ['Feses Lengkap', 'Complete Stool Test'],
    ['Apusan Darah Tepi', 'Peripheral Blood Smear'],
    ['Urinalisis', 'Urinalysis'],
    ['Kolesterol Total', 'Total Cholesterol'],
    ['Asam Urat', 'Uric Acid'],
    ['Rawat Luka (GV)', 'Wound Care (Dressing)'],
    ['Hecting (Jahit)', 'Suturing (Stitches)'],
    ['Aff Hecting (Lepas)', 'Suture Removal'],
    ['Debridement Luka', 'Wound Debridement'],
    ['Insisi Drainase Abses', 'Abscess Incision and Drainage'],
    ['Nebulizer / Uap', 'Nebulizer / Steam'],
    ['Oksigenasi / Kanul', 'Oxygen Therapy / Cannula'],
    ['Pasang Infus', 'IV Line / Fluids'],
    ['Injeksi IM', 'IM Injection'],
    ['Injeksi IV', 'IV Injection'],
    ['Toilet Telinga / Cerumen', 'Ear Toilet / Cerumen Removal'],
    ['Ekstraksi Benda Asing Hidung', 'Nasal Foreign Body Removal'],
    ['Ekstraksi Benda Asing Mata', 'Eye Foreign Body Removal'],
    ['Ekstraksi Gigi', 'Tooth Extraction'],
    ['Pasang Kateter', 'Urinary Catheter Insertion'],
    ['Pasang NGT', 'NGT Insertion'],
    ['Tampon Hidung', 'Nasal Packing'],
    ['Ekstraksi Benda Asing Telinga', 'Ear Foreign Body Removal'],
    ['Ekstraksi Kuku (Roserplasty)', 'Nail Extraction (Roserplasty)'],
    ['Bidai / Splinting', 'Splinting'],
    ['Persalinan Normal (APN)', 'Normal Delivery (APN)'],
    ['Dekompresi Jarum', 'Needle Decompression'],
    ['Resusitasi Neonatus', 'Neonatal Resuscitation'],
    ['Spirometri Dasar', 'Basic Spirometry'],
    ['Screening Kognitif (MMSE)', 'Cognitive Screening (MMSE)'],
    ['IVA Test', 'VIA Test'],
    ['Rekam Jantung (EKG)', 'ECG Recording'],
    ['Analgesik/Antipiretik', 'Analgesics / Antipyretics'],
    ['Anti-Infeksi (Antibiotik/Antifungi/Antivirus)', 'Anti-Infectives (Antibiotic/Antifungal/Antiviral)'],
    ['Antihipertensi/Kardiovaskular', 'Antihypertensive / Cardiovascular'],
    ['Antidiabetes', 'Antidiabetic'],
    ['Sistem Respirasi', 'Respiratory System'],
    ['Saluran Cerna', 'Gastrointestinal'],
    ['Dermatologi', 'Dermatology'],
    ['Vitamin/Suplemen/Obstetri', 'Vitamins / Supplements / Obstetrics'],
    ['Psikiatri & Neurologi', 'Psychiatry & Neurology'],
    ['Mata/Telinga/Hidung/Tenggorokan', 'Eye / Ear / Nose / Throat'],
    ['Alat Kesehatan Habis Pakai', 'Disposable Medical Supplies'],
    ['Peralatan Medis', 'Medical Equipment'],
    ['Reagensia Laboratorium', 'Laboratory Reagents'],
    ['Gawat Darurat / Injeksi', 'Emergency / Injection'],
    ['Obat Metabolik & Gout', 'Metabolic & Gout Medicines'],
    ['Keadaan Umum', 'General Condition'],
    ['Tanda Vital (TD, Nadi, Suhu, RR)', 'Vital Signs (BP, Pulse, Temp, RR)'],
    ['Kepala, Mata, THT', 'Head, Eyes, ENT'],
    ['Leher (KGB, Tiroid)', 'Neck (Lymph Nodes, Thyroid)'],
    ['Thorax (Jantung & Paru)', 'Thorax (Heart & Lungs)'],
    ['Ekstremitas', 'Extremities'],
    ['Kulit', 'Skin'],
    ['Neurologis Singkat', 'Brief Neurological Exam'],
    ['Rectal Touche (RT)', 'Digital Rectal Exam (DRE)'],
    ['Genitalia (dengan consent)', 'Genitalia (with consent)'],
    ['Pemeriksaan Payudara', 'Breast Examination'],
    ['Antropometri', 'Anthropometry'],
    ['Kepala', 'Head'],
    ['Leher', 'Neck'],
    ['Mammae', 'Breast'],
    ['Neurologi', 'Neurology'],
    ['Rektal', 'Rectal'],
    ['Penilaian Umum', 'General Assessment'],
    ['Kepala & Leher', 'Head & Neck'],
    ['Thorax & Kardio', 'Thorax & Cardio'],
    ['Abdomen & Pelvis', 'Abdomen & Pelvis'],
    ['Ekstremitas & Kulit', 'Extremities & Skin'],
    ['Dalam batas normal', 'Within normal limits'],
    ['Dalam batas normal.', 'Within normal limits.'],
    ['Dalam batas normal / Tidak ada kelainan.', 'Within normal limits / No abnormal findings.'],
    ['Tampak sakit sedang, wajah kemerahan (facial flushing).', 'Moderately ill appearing, facial flushing.']
]);

const EN_PHRASE_REPLACEMENTS = [
    [/Trombositopenia/gi, 'Thrombocytopenia'],
    [/Trombositosis/gi, 'Thrombocytosis'],
    [/Leukopenia/gi, 'Leukopenia'],
    [/Leukositosis/gi, 'Leukocytosis'],
    [/Leukosituria/gi, 'Leukocyturia'],
    [/Hemokonsentrasi/gi, 'Hemoconcentration'],
    [/Limfositosis/gi, 'Lymphocytosis'],
    [/Eritrosit/gi, 'Erythrocytes'],
    [/\bLeuko\b/gi, 'Leukocytes'],
    [/\bTrombo\b/gi, 'Platelets'],
    [/\bTD\s*([0-9])/gi, 'BP $1'],
    [/\bN\s*([0-9]+)\s*x\b/gi, 'Pulse $1/min'],
    [/\bRR\s*([0-9]+)\s*x\b/gi, 'RR $1/min'],
    [/\bS\s*([0-9]+(?:[.,][0-9]+)?\s*[\u00b0?]?C)\b/gi, 'Temp $1'],
    [/\bTD\s*-/gi, 'BP -'],
    [/Anak tampak lelah/gi, 'Child appears fatigued'],
    [/Anak tampak kurus/gi, 'Thin child appearing'],
    [/Anak tampak garuk-garuk/gi, 'Child scratching'],
    [/Anak tampak baik/gi, 'Child well appearing'],
    [/Bayi tampak rewel/gi, 'Infant appears fussy'],
    [/Neonatus tampak rewel/gi, 'Neonate appears fussy'],
    [/Bayi tampak biru\/pale/gi, 'Infant appears blue/pale'],
    [/Tampak sakit ringan/gi, 'Mildly ill appearing'],
    [/Tampak sakit sedang/gi, 'Moderately ill appearing'],
    [/Tampak sakit berat/gi, 'Severely ill appearing'],
    [/Tampak baik/gi, 'Well appearing'],
    [/Tampak lemah/gi, 'Weak appearing'],
    [/Tampak pucat/gi, 'Pale appearing'],
    [/Tampak cemas/gi, 'Anxious appearing'],
    [/wajah kemerahan\s*\(facial flushing\)/gi, 'facial flushing'],
    [/wajah memerah/gi, 'flushed face'],
    [/Tampak sakit akut/gi, 'Acutely ill appearing'],
    [/Tampak sakit kronik/gi, 'Chronically ill appearing'],
    [/Tampak tidak nyaman/gi, 'Appears uncomfortable'],
    [/Tampak kesakitan/gi, 'Appears in pain'],
    [/Tampak nyeri/gi, 'Appears in pain'],
    [/Tampak meringis menahan sakit/gi, 'Grimacing in pain'],
    [/Tampak sesak berat/gi, 'Severely short of breath'],
    [/Tampak sesak/gi, 'Appears short of breath'],
    [/Tampak lemas/gi, 'Weak appearing'],
    [/Tampak lelah/gi, 'Appears fatigued'],
    [/Tampak kurus/gi, 'Thin appearing'],
    [/Tampak ikterik/gi, 'Icteric appearing'],
    [/Tampak malu/gi, 'Embarrassed appearing'],
    [/Tampak sehat/gi, 'Healthy appearing'],
    [/garuk-garuk/gi, 'scratching'],
    [/tidak sesak/gi, 'not short of breath'],
    [/sesak napas/gi, 'shortness of breath'],
    [/dehidrasi ringan/gi, 'mild dehydration'],
    [/dehidrasi sedang/gi, 'moderate dehydration'],
    [/dehidrasi berat/gi, 'severe dehydration'],
    [/dehidrasi sangat berat/gi, 'profound dehydration'],
    [/sangat berat/gi, 'very severe'],
    [/sangat lemah/gi, 'very weak'],
    [/sangat kering/gi, 'very dry'],
    [/sangat berkurang/gi, 'markedly decreased'],
    [/pucat berat/gi, 'severely pale'],
    [/Sakit berat/gi, 'Severely ill'],
    [/Sakit sedang/gi, 'Moderately ill'],
    [/Sakit ringan/gi, 'Mildly ill'],
    [/Sesak berat/gi, 'Severe shortness of breath'],
    [/\bSesak\b/gi, 'Short of breath'],
    [/nyeri hebat/gi, 'severe pain'],
    [/kesakitan hebat/gi, 'severe pain'],
    [/menahan nyeri/gi, 'guarding from pain'],
    [/nyeri tekan difus ringan/gi, 'mild diffuse tenderness'],
    [/nyeri tekan difus/gi, 'diffuse tenderness'],
    [/nyeri tekan hebat/gi, 'severe tenderness'],
    [/nyeri ketok CVA/gi, 'CVA tenderness'],
    [/nyeri ringan/gi, 'mild pain'],
    [/Tidak ada kelainan/gi, 'No abnormal findings'],
    [/Tidak ada fluktuasi/gi, 'No fluctuance'],
    [/Tidak ada tanda/gi, 'No signs of'],
    [/tidak ada/gi, 'no'],
    [/Tidak diperiksa/gi, 'Not examined'],
    [/Dalam batas normal/gi, 'Within normal limits'],
    [/Ronkhi basah kasar/gi, 'coarse crackles'],
    [/Ronkhi basah/gi, 'crackles'],
    [/ronkhi/gi, 'crackles'],
    [/Retraksi dinding dada/gi, 'Chest wall retractions'],
    [/Rontgen Thorax/gi, 'Chest X-ray'],
    [/TB Paru/gi, 'Pulmonary TB'],
    [/paru kanan bawah/gi, 'right lower lung'],
    [/paru kanan/gi, 'right lung'],
    [/paru kiri/gi, 'left lung'],
    [/\bparu\b/gi, 'lung'],
    [/Akral hangat/gi, 'Warm extremities'],
    [/akral dingin/gi, 'cold extremities'],
    [/Akral/gi, 'Extremities'],
    [/mukosa bibir kering/gi, 'dry oral mucosa'],
    [/keringat dingin/gi, 'cold sweat'],
    [/bibir kering pecah-pecah/gi, 'dry cracked lips'],
    [/\bbibir\b/gi, 'lips'],
    [/kelopak mata/gi, 'eyelids'],
    [/mukosa/gi, 'mucosa'],
    [/mata agak cekung/gi, 'eyes mildly sunken'],
    [/cekung/gi, 'sunken'],
    [/turgor kembali lambat/gi, 'delayed skin turgor'],
    [/bising usus menurun/gi, 'decreased bowel sounds'],
    [/bising usus meningkat/gi, 'increased bowel sounds'],
    [/nyeri tekan/gi, 'tenderness'],
    [/bising usus/gi, 'bowel sounds'],
    [/\bBU meningkat\b/gi, 'increased bowel sounds'],
    [/\bBU normal\b/gi, 'normal bowel sounds'],
    [/\bBU \(\+\)/gi, 'bowel sounds present'],
    [/\bBU\b/gi, 'bowel sounds'],
    [/suara napas/gi, 'breath sounds'],
    [/murmur/gi, 'murmur'],
    [/ronki/gi, 'rhonchi'],
    [/wheezing/gi, 'wheezing'],
    [/pucat/gi, 'pale'],
    [/lemah/gi, 'weak'],
    [/gelisah/gi, 'restless'],
    [/somnolen/gi, 'somnolent'],
    [/sianosis/gi, 'cyanosis'],
    [/saat batuk/gi, 'while coughing'],
    [/batuk/gi, 'cough'],
    [/febris/gi, 'febrile'],
    [/demam berdarah dengue/gi, 'dengue hemorrhagic fever'],
    [/demam tifoid/gi, 'typhoid fever'],
    [/infeksi saluran kemih/gi, 'urinary tract infection'],
    [/khas/gi, 'typical for'],
    [/kemungkinan/gi, 'possible'],
    [/perlu transfusi trombosit/gi, 'platelet transfusion needed'],
    [/Datar, supel/gi, 'Flat, soft'],
    [/Datar/gi, 'Flat'],
    [/supel/gi, 'soft'],
    [/seluruh abdomen/gi, 'entire abdomen'],
    [/terutama/gi, 'especially'],
    [/tanda peritonitis/gi, 'peritonitis signs'],
    [/defans/gi, 'guarding'],
    [/Eritema merah terang/gi, 'Bright red erythema'],
    [/eritematosa/gi, 'erythematous'],
    [/edematosa/gi, 'edematous'],
    [/\bEritema\b/gi, 'Erythema'],
    [/hiperemis/gi, 'hyperemic'],
    [/maserasi/gi, 'maceration'],
    [/\bLesi\b/gi, 'Lesions'],
    [/\bRuam\b/gi, 'Rash'],
    [/\bMakula\b/gi, 'Macules'],
    [/hipopigmentasi/gi, 'hypopigmented'],
    [/merah halus/gi, 'smooth red'],
    [/\bmerah\b/gi, 'red'],
    [/\bLidah\b/gi, 'Tongue'],
    [/tidak gatal/gi, 'not itchy'],
    [/\bgatal\b/gi, 'itchy'],
    [/\bbengkak\b/gi, 'swelling'],
    [/\bhangat\b/gi, 'warm'],
    [/\bperih\b/gi, 'stinging pain'],
    [/\baktif\b/gi, 'active'],
    [/\btepi\b/gi, 'edge'],
    [/batang tubuh/gi, 'trunk'],
    [/dasar merah basah/gi, 'moist red base'],
    [/\bBula\b/gi, 'Bullae'],
    [/flaksid/gi, 'flaccid'],
    [/\bErosi\b/gi, 'Erosions'],
    [/\bluas\b/gi, 'extensive'],
    [/putih seperti lilin/gi, 'waxy white'],
    [/lengan kanan/gi, 'right arm'],
    [/dada anterior/gi, 'anterior chest'],
    [/\bperut\b/gi, 'abdomen'],
    [/Tidak nyeri/gi, 'Painless'],
    [/saat pinprick/gi, 'with pinprick'],
    [/\bsekitar\b/gi, 'surrounding'],
    [/\bderajat\b/gi, 'grade'],
    [/luka tusuk/gi, 'puncture wounds'],
    [/wound tusuk/gi, 'puncture wounds'],
    [/\bkedalaman\b/gi, 'depth'],
    [/perdarahan aktif minimal/gi, 'minimal active bleeding'],
    [/perdarahan aktif terkontrol/gi, 'controlled active bleeding'],
    [/perdarahan aktif/gi, 'active bleeding'],
    [/\bPerdarahan\b/gi, 'Bleeding'],
    [/Tidak dijahit/gi, 'Not sutured'],
    [/ujung tulang/gi, 'bone end'],
    [/\btulang\b/gi, 'bone'],
    [/terekspos/gi, 'exposed'],
    [/\bterbuka\b/gi, 'open'],
    [/terkontrol/gi, 'controlled'],
    [/teraba/gi, 'palpable'],
    [/menebal/gi, 'thickened'],
    [/\braba\b/gi, 'touch'],
    [/\bsuhu\b/gi, 'temperature'],
    [/limitasi karena nyeri/gi, 'limited due to pain'],
    [/karena nyeri/gi, 'due to pain'],
    [/saat bergerak/gi, 'with movement'],
    [/\bposisi\b/gi, 'position'],
    [/bicara kata per kata/gi, 'speaking word by word'],
    [/posisi setengah duduk/gi, 'semi-sitting position'],
    [/duduk tegak/gi, 'sitting upright'],
    [/diaforesis/gi, 'diaphoresis'],
    [/diaforetik/gi, 'diaphoretic'],
    [/takipneu/gi, 'tachypnea'],
    [/\bmual\b/gi, 'nausea'],
    [/sadar penuh/gi, 'fully conscious'],
    [/memegangi/gi, 'holding'],
    [/lukanya/gi, 'the wound'],
    [/Tampak tegang/gi, 'Appears tense'],
    [/Tampak bingung/gi, 'Appears confused'],
    [/Tampak toksik/gi, 'Toxic appearing'],
    [/Tampak sadar penuh/gi, 'Fully conscious'],
    [/Tampak edema/gi, 'Marked edema'],
    [/Tampak tenang/gi, 'Appears calm'],
    [/Tampak seizure/gi, 'Ongoing seizure'],
    [/Tampak somnolent/gi, 'Somnolent appearing'],
    [/Tampak blast cell dominan/gi, 'Dominant blast cells seen'],
    [/Tampak guarding from pain/gi, 'Guarding from pain'],
    [/Tampak menahan stinging pain/gi, 'Appears to be holding back stinging pain'],
    [/Tampak active/gi, 'Active appearing'],
    [/Tampak restless/gi, 'Restless appearing'],
    [/Tampak fully conscious/gi, 'Fully conscious'],
    [/\bTampak\b/gi, 'Appears'],
    [/multipel/gi, 'multiple'],
    [/berbagai ukuran/gi, 'variable sizes'],
    [/tersebar/gi, 'scattered'],
    [/menyebar/gi, 'spreading'],
    [/mulai dari/gi, 'starting from'],
    [/ekstremitas/gi, 'extremities'],
    [/badan/gi, 'trunk'],
    [/wajah/gi, 'face'],
    [/kulit kering/gi, 'dry skin'],
    [/obesitas sentral/gi, 'central obesity'],
    [/Pulsasi dorsalis pedis/gi, 'Dorsalis pedis pulse'],
    [/sensibilitas/gi, 'sensation'],
    [/menurun/gi, 'decreased'],
    [/meningkat/gi, 'increased'],
    [/Duh purulen/gi, 'purulent discharge'],
    [/Discharge mukopurulen/gi, 'mucopurulent discharge'],
    [/keputihan/gi, 'vaginal discharge'],
    [/Nyeri goyang serviks/gi, 'Cervical motion tenderness'],
    [/Nyeri suprapubik/gi, 'Suprapubic pain'],
    [/nyeri tarik pinna/gi, 'pain when pulling the pinna'],
    [/nyeri sentuh/gi, 'pain to touch'],
    [/\bnyeri\b/gi, 'pain'],
    [/\blemas\b/gi, 'weak'],
    [/\bkering\b/gi, 'dry'],
    [/\bkanan\b/gi, 'right'],
    [/\bkiri\b/gi, 'left'],
    [/\bumum\b/gi, 'generalized'],
    [/mulut berbusa/gi, 'foaming at the mouth'],
    [/tonik-klonik/gi, 'tonic-clonic'],
    [/tonus otot/gi, 'muscle tone'],
    [/Konjungtiva/gi, 'Conjunctiva'],
    [/Kornea/gi, 'Cornea'],
    [/Visus sulit dinilai/gi, 'Visual acuity difficult to assess'],
    [/anak kecil/gi, 'small child'],
    [/sedikit/gi, 'slight'],
    [/Funduskopi/gi, 'Fundoscopy'],
    [/fluktuasi/gi, 'fluctuance'],
    [/Liang ear/gi, 'Ear canal'],
    [/Serumen/gi, 'Cerumen'],
    [/coklat keras/gi, 'hard brown'],
    [/menutupi/gi, 'covering'],
    [/lateralisasi/gi, 'lateralization'],
    [/telinga sakit/gi, 'affected ear'],
    [/ear sakit/gi, 'affected ear'],
    [/Setelah tekan/gi, 'After compression'],
    [/berhenti/gi, 'stopped'],
    [/mengejan/gi, 'bearing down'],
    [/ketakutan/gi, 'frightened'],
    [/menangis/gi, 'crying'],
    [/pernapasan/gi, 'breathing'],
    [/BAU ASETON/gi, 'ACETONE ODOR'],
    [/koma/gi, 'coma'],
    [/paresis fasialis kiri sentral/gi, 'left central facial paresis'],
    [/disartria/gi, 'dysarthria'],
    [/kesakitan lokasi benturan/gi, 'pain at the impact site'],
    [/\bpada\b/gi, 'on'],
    [/dasar wound red basah/gi, 'moist red wound base'],
    [/\bbasah\b/gi, 'wet'],
    [/Estimasi/gi, 'Estimated'],
    [/\blengan\b/gi, 'arm'],
    [/\bdada\b/gi, 'chest'],
    [/parsial/gi, 'partial'],
    [/kemudian/gi, 'then'],
    [/hipersalivasi/gi, 'hypersalivation'],
    [/bau pestisida menyengat/gi, 'strong pesticide odor'],
    [/\bdengan\b/gi, 'with'],
    [/\bdari\b/gi, 'from'],
    [/\bdi\b/gi, 'in'],
    [/\bke\b/gi, 'to'],
    [/\bdan\b/gi, 'and'],
    [/kesadaran/gi, 'consciousness'],
    [/compos mentis/gi, 'alert and oriented'],
    [/Diet Rendah Garam/gi, 'Low-salt diet'],
    [/Diet Rendah Gula\/Karbohidrat/gi, 'Low-sugar / low-carbohydrate diet'],
    [/Diet Rendah Lemak\/Gorengan/gi, 'Low-fat / low-fried-food diet'],
    [/Diet Rendah Purin/gi, 'Low-purine diet'],
    [/Diet Rendah Kalori/gi, 'Low-calorie diet'],
    [/Diet Lunak\/Mudah Cerna/gi, 'Soft / easy-to-digest diet'],
    [/Pola Makan Seimbang/gi, 'Balanced diet'],
    [/Gizi Seimbang/gi, 'balanced nutrition'],
    [/Makan Porsi Kecil tapi Sering/gi, 'Eat small frequent meals'],
    [/Tingkatkan Serat/gi, 'Increase fiber'],
    [/Makan Tinggi Zat Besi/gi, 'Eat iron-rich foods'],
    [/Cukupi Cairan/gi, 'Maintain fluid intake'],
    [/Jaga Kebersihan Makanan & Minuman/gi, 'Keep food and drinks clean'],
    [/Olahraga Aerobik/gi, 'Aerobic exercise'],
    [/Turunkan Berat Badan Ideal/gi, 'Achieve ideal weight loss'],
    [/Berhenti Merokok/gi, 'Stop smoking'],
    [/Kelola Stres/gi, 'Manage stress'],
    [/Hindari Stres Berlebihan/gi, 'Avoid excessive stress'],
    [/Kurangi Kafein/gi, 'Reduce caffeine'],
    [/Istirahat Cukup & Teratur/gi, 'Get enough regular rest'],
    [/Istirahat Total di Tempat Tidur/gi, 'Strict bed rest'],
    [/Perbaiki Posisi Duduk\/Angkat Beban/gi, 'Improve sitting and lifting posture'],
    [/Batasi Screen Time\/Istirahatkan Mata/gi, 'Limit screen time / rest the eyes'],
    [/Istirahatkan Suara/gi, 'Voice rest'],
    [/Istirahat di Ruangan Gelap & Tenang/gi, 'Rest in a dark quiet room'],
    [/Hindari Perubahan Posisi Kepala Mendadak/gi, 'Avoid sudden head position changes'],
    [/Kompres Hangat/gi, 'Warm compress'],
    [/Kompres Dingin/gi, 'Cold compress'],
    [/Kumur Air Garam Hangat/gi, 'Gargle warm salt water'],
    [/Uap Air Panas/gi, 'Steam inhalation'],
    [/Jaga Luka Tetap Bersih & Kering/gi, 'Keep wound clean and dry'],
    [/Tidur Bantal Tinggi/gi, 'Sleep with head elevated'],
    [/Jangan Menggaruk Area Gatal/gi, 'Do not scratch itchy areas'],
    [/P3K Kejang/gi, 'Seizure first aid'],
    [/Cubit Pangkal Hidung/gi, 'Pinch the bridge of the nose'],
    [/Pijat Wajah Lembut/gi, 'Gentle facial massage'],
    [/Latihan Manuver Mandiri/gi, 'Self maneuver exercises'],
    [/Kosongkan Payudara Secara Teratur/gi, 'Empty breasts regularly'],
    [/Lanjutkan Menyusui/gi, 'Continue breastfeeding'],
    [/Cuci Tangan Pakai Sabun/gi, 'Wash hands with soap'],
    [/Pakai Masker/gi, 'Wear a mask'],
    [/Etika Batuk\/Bersin/gi, 'Cough / sneeze etiquette'],
    [/Hindari Pencetus Alergi\/Debu/gi, 'Avoid allergy / dust triggers'],
    [/Cegah Nyamuk/gi, 'Prevent mosquito breeding'],
    [/Lepas Lensa Kontak & Ganti Wadah/gi, 'Remove contact lenses and replace the case'],
    [/Basuh dari Depan ke Belakang/gi, 'Wipe front to back'],
    [/Jangan Menahan Buang Air Kecil/gi, 'Do not hold urine'],
    [/Isolasi di Rumah/gi, 'Home isolation'],
    [/Jangan Berbagi Handuk\/Pakaian/gi, 'Do not share towels / clothing'],
    [/Jangan Sentuh Luka Tanpa Cuci Tangan/gi, 'Do not touch wounds without washing hands'],
    [/Jaga Kulit Tetap Kering/gi, 'Keep skin dry'],
    [/Pakai Pakaian Longgar & Nyaman/gi, 'Wear loose comfortable clothing'],
    [/Hindari Kepanasan\/Tetap Sejuk/gi, 'Avoid overheating / stay cool'],
    [/Lindungi Mata dari Angin\/Debu/gi, 'Protect eyes from wind / dust'],
    [/Jangan Mengejan\/Angkat Berat/gi, 'Do not strain / lift heavy objects'],
    [/Jangan Garuk\/Korek Telinga/gi, 'Do not scratch / pick the ear'],
    [/Jangan Pakai Cotton Bud ke Dalam Telinga/gi, 'Do not insert cotton buds into the ear'],
    [/Jaga Kebersihan Telinga Luar/gi, 'Keep outer ear clean'],
    [/Jaga Kebersihan Kulit Kepala/gi, 'Keep scalp clean'],
    [/Minum Obat Teratur Sesuai Anjuran/gi, 'Take medication regularly as advised'],
    [/Kontrol Rutin Sesuai Jadwal/gi, 'Routine follow-up as scheduled'],
    [/Segera ke RS jika/gi, 'Go to hospital immediately if'],
    [/Skrining Kesehatan Keluarga Serumah/gi, 'Screen household family members'],
    [/Minum MDT Kusta Teratur/gi, 'Take leprosy MDT regularly'],
    [/Minum OAT TBC Teratur/gi, 'Take TB treatment regularly'],
    [/Minum ARV Seumur Hidup Tanpa Putus/gi, 'Take lifelong ARV without interruption'],
    [/Habiskan Antibiotik Sesuai Resep/gi, 'Finish antibiotics as prescribed'],
    [/Habiskan Obat Sesuai Resep/gi, 'Finish medication as prescribed'],
    [/Kontrol Ulang Sesuai Jadwal/gi, 'Follow up as scheduled'],
    [/Periksa Lab Ulang Setelah Pengobatan/gi, 'Repeat lab testing after treatment'],
    [/Periksa Kesehatan Tahunan/gi, 'Annual health check'],
    [/Periksa Mata Berkala ke Dokter/gi, 'Regular eye checks with a doctor'],
    [/Observasi Minimal/gi, 'Observe for at least'],
    [/Skrining Semua Kontak Erat/gi, 'Screen all close contacts'],
    [/Beritahu Kontak Dekat/gi, 'Notify close contacts'],
    [/Profilaksis untuk Kontak Erat/gi, 'Prophylaxis for close contacts'],
    [/Obati Seluruh Anggota Keluarga Bersamaan/gi, 'Treat all family members together'],
    [/Beritahu Pasangan/gi, 'Notify partner'],
    [/Pasangan Juga Harus Diobati/gi, 'Partner must also be treated'],
    [/Waspada Tanda/gi, 'Watch for signs of'],
    [/Kenali Tanda/gi, 'Recognize signs of'],
    [/Perlu Rujukan/gi, 'Referral needed for'],
    [/Rujuk ke Rumah Sakit/gi, 'Refer to hospital'],
    [/Rujuk ke/gi, 'Refer to'],
    [/\bPerlu\b/gi, 'Needs'],
    [/\bHindari\b/gi, 'Avoid'],
    [/\bJangan\b/gi, 'Do not'],
    [/\bJaga\b/gi, 'Maintain'],
    [/\bMinum\b/gi, 'Take'],
    [/\bMakan\b/gi, 'Eat'],
    [/\bCek\b/gi, 'Check'],
    [/\bPantau\b/gi, 'Monitor'],
    [/\bEdukasi\b/gi, 'Educate'],
    [/\bKonseling\b/gi, 'Counseling'],
    [/\bPemeriksaan\b/gi, 'Examination'],
    [/\bPerawatan\b/gi, 'Care'],
    [/\bPengambilan\b/gi, 'Removal'],
    [/\bPemasangan\b/gi, 'Insertion'],
    [/\bPasang\b/gi, 'Insert'],
    [/\bLuka Bakar\b/gi, 'burn wound'],
    [/\bLuka\b/gi, 'wound'],
    [/\bTanda Bahaya\b/gi, 'danger signs'],
    [/\bKebersihan\b/gi, 'hygiene'],
    [/\bKeluarga\b/gi, 'family'],
    [/\bRumah Sakit\b|\bRS\b/gi, 'hospital'],
    [/\bPuskesmas\b/gi, 'clinic'],
    [/\bTelinga\b/gi, 'ear'],
    [/\bHidung\b/gi, 'nose'],
    [/\bMata\b/gi, 'eye'],
    [/\bGigi\b/gi, 'tooth'],
    [/\bPayudara\b/gi, 'breast'],
    [/\bKulit\b/gi, 'skin'],
    [/\bDarah\b/gi, 'blood'],
    [/\bLeukosit\b/gi, 'Leukocytes'],
    [/\bTrombosit\b/gi, 'Platelets'],
    [/\bGlukosa\b/gi, 'Glucose'],
    [/\bGula\b/gi, 'glucose'],
    [/\bGaram\b/gi, 'salt'],
    [/\bJantung\b/gi, 'heart'],
    [/\bNapas\b/gi, 'breathing'],
    [/\bDemam\b/gi, 'fever'],
    [/\bKejang\b/gi, 'seizure'],
    [/\bKepala\b/gi, 'head'],
    [/\bBerat\b/gi, 'weight'],
    [/\bBadan\b/gi, 'body'],
    [/\bObat\b/gi, 'medicine'],
    [/\bMakanan\b/gi, 'food'],
    [/\bMinuman\b/gi, 'drinks'],
    [/\bCairan\b/gi, 'fluids'],
    [/\bKesehatan\b/gi, 'health'],
    [/<\s*1\s*sdt\/hari/gi, '< 1 tsp/day'],
    [/(\d+)-(\d+)\s*gelas\/hari/gi, '$1-$2 glasses/day'],
    [/(\d+)\s*jam/gi, '$1 hours'],
    [/(\d+)\s*Menit/gi, '$1 minutes'],
    [/(\d+)\s*menit/gi, '$1 minutes'],
    [/\bHari\b/gi, 'days']
];

export function isEnglishLocale(locale) {
    return String(locale || '').toLowerCase().startsWith('en');
}

function cleanEnglishLabel(text) {
    return String(text || '')
        .replace(/\s+/g, ' ')
        .replace(/\s+([,.)])/g, '$1')
        .replace(/\(\s+/g, '(')
        .trim();
}

export function localizeClinicalText(value, locale) {
    if (!isEnglishLocale(locale) || typeof value !== 'string') return value;

    const exact = EN_EXACT_LABELS.get(value);
    if (exact) return exact;

    let translated = value;
    EN_PHRASE_REPLACEMENTS.forEach(([pattern, replacement]) => {
        translated = translated.replace(pattern, replacement);
    });
    return cleanEnglishLabel(translated);
}

export function localizeClinicalOption(option, locale) {
    if (!option || typeof option !== 'object') return option;
    return {
        ...option,
        label: localizeClinicalText(option.label, locale),
        name: localizeClinicalText(option.name, locale),
        category: localizeClinicalText(option.category, locale)
    };
}

export function localizeClinicalOptions(options, locale) {
    return (options || []).map((option) => localizeClinicalOption(option, locale));
}
