import { FAMILY_MEDICAL_HISTORY, INDIVIDUAL_PROFILES } from '../src/data/VillageRegistry.js';
console.log('INDIVIDUAL_PROFILES:', !!INDIVIDUAL_PROFILES);
console.log('FAMILY_MEDICAL_HISTORY:', !!FAMILY_MEDICAL_HISTORY);
