import type {
  ClinicalClaimKind,
  DeltaAuditRecord,
  EvidenceBinding,
  EvidenceFacet,
  PhysicianSignoff,
} from './types'

export const M13_REQUIRED_CLAIM_KINDS: ClinicalClaimKind[] = [
  'diagnosis_threshold',
  'red_flags',
  'assessment',
  'regimen',
  'contraindication',
  'disposition',
  'follow_up',
  'formulary',
]

export const M13_CLAIM_FACET: Record<ClinicalClaimKind, EvidenceFacet> = {
  diagnosis_threshold: 'diagnosis',
  red_flags: 'anamnesis',
  assessment: 'assessment',
  regimen: 'regimen',
  contraindication: 'contraindication',
  disposition: 'disposition',
  follow_up: 'follow-up',
  formulary: 'formulary',
}

const REVIEWER = 'Codex technical source audit'
const REVIEWED_AT = '2026-07-14'
const PHYSICIAN_REVIEWER = 'dr. Anak Agung Bagus Wirayuda'
const PHYSICIAN_CREDENTIALS = 'Dokter; penanggung jawab klinis PRIMERA'

function physicianSignoff(
  decision: PhysicianSignoff['decision'],
  note: string,
): PhysicianSignoff {
  return {
    reviewer: PHYSICIAN_REVIEWER,
    credentials: PHYSICIAN_CREDENTIALS,
    signedAt: '2026-07-14',
    decision,
    note,
  }
}

export const M13_DELTA_AUDITS: DeltaAuditRecord[] = [
  {
    id: 'm13-0b:hipertensi_esensial',
    caseId: 'hipertensi_esensial',
    archetypeId: 'clinic:hipertensi_esensial',
    title: 'Hipertensi Esensial - delta PNPK 303/2026, PPK 1936/2022, dan Fornas 1199/2025',
    currentIcd10: 'I10',
    population: 'usia=45-65 tahun; diagnosis hipertensi sebelumnya; TD=160/95 mmHg; tanpa kegawatan akut eksplisit',
    reviewStatus: 'accepted_with_limitation',
    technicalReviewer: REVIEWER,
    reviewedAt: REVIEWED_AT,
    blockers: [],
    physicianSignoff: physicianSignoff(
      'approved_with_waiver',
      'Fungsi ginjal dan skrining kontraindikasi ditambahkan. Kombinasi dua obat dan no-referral dipertahankan untuk pasien stabil; elektrolit tidak diwajibkan pada slice ini dan konflik internal redaksi rujukan PNPK/PPK diterima sebagai waiver tertulis.',
    ),
    claims: [
      {
        claimKind: 'diagnosis_threshold',
        facet: 'diagnosis',
        source: 'pnpk:hipertensi-dewasa-303-2026',
        locator: 'PDF pp. 9-17: definisi, klasifikasi, dan pengukuran tekanan darah',
        claim: 'Riwayat diagnosis hipertensi dan TD 160/95 mmHg mendukung hipertensi derajat 2, setelah teknik pengukuran yang benar dan konfirmasi sesuai konteks.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.vital+anamnesis[ht_riwayat]+diagnosisBanding',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan I10 dan data utama; saat revisi berikutnya pertegas bahwa pengukuran ulang dilakukan dengan teknik benar.',
      },
      {
        claimKind: 'red_flags',
        facet: 'anamnesis',
        source: 'pnpk:hipertensi-dewasa-303-2026',
        locator: 'PDF pp. 9-17 dan 85-86: evaluasi kerusakan organ target dan kondisi rujukan',
        claim: 'Kasus stabil perlu membedakan keluhan nonspesifik dari tanda kerusakan organ target akut.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.anamnesis[ht_penyerta]+pemeriksaanFisik',
        finding: 'coverage_gap',
        materiality: 'minor',
        proposedResolution: 'Lengkapi satu pertanyaan red flag ringkas yang mencakup defisit neurologis, sesak akut, dan nyeri dada tanpa membuat vignette menjadi emergensi.',
      },
      {
        claimKind: 'assessment',
        facet: 'assessment',
        source: 'pnpk:hipertensi-dewasa-303-2026',
        locator: 'PDF p. 11: pemeriksaan penunjang dan penilaian risiko/organ target',
        claim: 'Penilaian awal sebelum ACE inhibitor atau diuretik perlu mengetahui fungsi ginjal dan, bila tersedia/berindikasi, elektrolit.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.lab',
        finding: 'coverage_gap',
        materiality: 'material',
        proposedResolution: 'Tambahkan hasil fungsi ginjal; putuskan bersama dokter apakah katalog elektrolit serum perlu ditambah atau dicatat sebagai keterbatasan jejaring FKTP.',
      },
      {
        claimKind: 'regimen',
        facet: 'regimen',
        source: 'pnpk:hipertensi-dewasa-303-2026',
        locator: 'PDF pp. 40-41: terapi kombinasi awal',
        claim: 'Hipertensi derajat 2 dapat dimulai dengan dua obat dari kelas yang saling melengkapi.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.tatalaksana.obatBenar+obatAlternatif',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan amlodipin ditambah kaptopril atau hidroklorotiazid setelah assessment keselamatan dilengkapi.',
        corroboratingEvidence: [
          { source: 'ppk:kmk-1936-2022', locator: 'PDF pp. 132-133: terapi farmakologis hipertensi di FKTP' },
        ],
      },
      {
        claimKind: 'contraindication',
        facet: 'contraindication',
        source: 'pnpk:hipertensi-dewasa-303-2026',
        locator: 'PDF pp. 11, 40-41: evaluasi awal dan pemilihan kombinasi obat',
        claim: 'Pemilihan ACE inhibitor/tiazid harus mempertimbangkan fungsi ginjal, elektrolit, kehamilan, dan kontraindikasi individual.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.lab+tatalaksana',
        finding: 'coverage_gap',
        materiality: 'material',
        proposedResolution: 'Tambahkan data renal dan pastikan demografi/anamnesis tidak membiarkan kontraindikasi penting menjadi tak terjawab.',
      },
      {
        claimKind: 'disposition',
        facet: 'disposition',
        source: 'pnpk:hipertensi-dewasa-303-2026',
        locator: 'PDF p. 86: kriteria rujukan; baca bersama pp. 40-41 dan 83-85',
        claim: 'Kasus stabil tanpa kerusakan organ akut saat ini dikelola di FKTP, tetapi teks kriteria rujukan sumber memasukkan komorbiditas secara terlalu luas dan tidak selaras dengan bagian tata laksana.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.harusDirujuk+panduanResmi',
        finding: 'source_conflict',
        materiality: 'material',
        proposedResolution: 'Pertahankan tata laksana FKTP hanya setelah physician waiver menjelaskan konflik internal pedoman dan alasan tidak merujuk otomatis untuk dislipidemia stabil.',
        corroboratingEvidence: [
          { source: 'ppk:kmk-1936-2022', locator: 'PDF p. 140: kriteria rujukan hipertensi' },
        ],
      },
      {
        claimKind: 'follow_up',
        facet: 'follow-up',
        source: 'pnpk:hipertensi-dewasa-303-2026',
        locator: 'PDF pp. 30 dan 83-85: target, pemantauan, dan tindak lanjut',
        claim: 'Kontrol ulang, kepatuhan, toleransi obat, dan pencapaian target harus menjadi bagian manajemen longitudinal.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.tatalaksana.edukasi+konsekuensi',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan edukasi kontrol/kepatuhan; interval kontrol dapat tetap naratif sampai kalender follow-up dimodelkan.',
      },
      {
        claimKind: 'formulary',
        facet: 'formulary',
        source: 'fornas:kmk-1199-2025',
        locator: 'PDF pp. 152-153: amlodipin, hidroklorotiazid, dan kaptopril pada FPKTP',
        claim: 'Amlodipin, hidroklorotiazid, dan kaptopril tersedia sebagai pilihan Fornas pada FPKTP sesuai restriksi entri.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#hipertensi_esensial.tatalaksana',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Tidak perlu perubahan formularium untuk tiga obat ini.',
      },
    ],
  },
  {
    id: 'm13-0b:dm_tipe2',
    caseId: 'dm_tipe2',
    archetypeId: 'clinic:dm_tipe2',
    title: 'Diabetes Melitus Tipe 2 - delta PNPK 302/2026, PPK 1936/2022, dan Fornas 1199/2025',
    currentIcd10: 'E11.9',
    population: 'usia=40-62 tahun; gejala klasik tanpa penurunan berat badan bermakna/dehidrasi; GDP=182 mg/dL; GDS=258 mg/dL; HbA1c=8,9%; keton negatif; fungsi ginjal normal',
    reviewStatus: 'accepted_with_limitation',
    technicalReviewer: REVIEWER,
    reviewedAt: REVIEWED_AT,
    blockers: [],
    physicianSignoff: physicianSignoff(
      'approved_with_waiver',
      'Vignette dinormalisasi menjadi nonkatabolik, fungsi ginjal dan edukasi hipoglikemia kritis ditambahkan. Glimepirid tetap preferred; glibenklamid diakui tersedia di Fornas tetapi dipertahankan sebagai non-preferred dengan penalti ringan karena risiko hipoglikemia lebih tinggi.',
    ),
    claims: [
      {
        claimKind: 'diagnosis_threshold',
        facet: 'diagnosis',
        source: 'pnpk:dm-tipe2-dewasa-302-2026',
        locator: 'PDF pp. 15-16: kriteria diagnosis dan evaluasi awal DM tipe 2',
        claim: 'Gejala klasik dengan GDS >=200 mg/dL, GDP >=126 mg/dL, dan HbA1c >=6,5% mendukung diagnosis DM.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.vital+anamnesis[dm_ku]+lab',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan E11.9 dan nilai diagnostik saat tanda dekompensasi dibersihkan.',
        corroboratingEvidence: [
          { source: 'ppk:kmk-1936-2022', locator: 'PDF p. 216: kriteria diagnosis DM di FKTP' },
        ],
      },
      {
        claimKind: 'red_flags',
        facet: 'anamnesis',
        source: 'pnpk:dm-tipe2-dewasa-302-2026',
        locator: 'PDF p. 16: dekompensasi metabolik berat, penurunan berat badan cepat, dan ketonuria sebagai alasan rujuk segera',
        claim: 'Penurunan berat badan bermakna dan gejala katabolik harus mengubah jalur terapi/rujukan, walaupun keton negatif.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.anamnesis[dm_bb]+pemeriksaanFisik[umum]+lab[urinalisis]',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Ubah jawaban menjadi tanpa penurunan berat badan bermakna dan hilangkan kesan dehidrasi bila tujuan kasus tetap kombinasi OAD stabil di FKTP.',
        corroboratingEvidence: [
          { source: 'ppk:kmk-1936-2022', locator: 'PDF p. 222: tanda dekompensasi metabolik' },
        ],
      },
      {
        claimKind: 'assessment',
        facet: 'assessment',
        source: 'pnpk:dm-tipe2-dewasa-302-2026',
        locator: 'PDF p. 15 dan pp. 92-93: kreatinin/LFG dan pemilihan obat menurut fungsi ginjal',
        claim: 'Fungsi ginjal diperlukan untuk pemilihan dan keamanan metformin.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.lab',
        finding: 'coverage_gap',
        materiality: 'material',
        proposedResolution: 'Tambahkan hasil fungsi ginjal yang membuat metformin aman dan tetap ajarkan jejaring pemeriksaan bila tidak tersedia setempat.',
      },
      {
        claimKind: 'regimen',
        facet: 'regimen',
        source: 'pnpk:dm-tipe2-dewasa-302-2026',
        locator: 'PDF pp. 32-34 dan 54-59: pemilihan OAD dan kombinasi berdasarkan HbA1c/dekompensasi',
        claim: 'HbA1c 8,9% tanpa dekompensasi dapat ditangani dengan kombinasi dua OAD; tanda katabolik mengubah jalur ini.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.tatalaksana.obatBenar',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Pertahankan metformin plus glimepirid hanya setelah cue dekompensasi dihapus dan fungsi ginjal tersedia.',
        corroboratingEvidence: [
          { source: 'ppk:kmk-1936-2022', locator: 'PDF pp. 222-223: jalur terapi oral versus injeksi pada DM baru' },
        ],
      },
      {
        claimKind: 'contraindication',
        facet: 'contraindication',
        source: 'pnpk:dm-tipe2-dewasa-302-2026',
        locator: 'PDF pp. 32-34 dan 93: hipoglikemia sulfonilurea dan pembatasan metformin menurut LFG',
        claim: 'Metformin memerlukan verifikasi LFG dan sulfonilurea memerlukan mitigasi serta edukasi hipoglikemia.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.lab+tatalaksana.edukasi',
        finding: 'coverage_gap',
        materiality: 'material',
        proposedResolution: 'Tambahkan fungsi ginjal dan topik edukasi kenali/tangani hipoglikemia sebagai edukasi kritis.',
      },
      {
        claimKind: 'disposition',
        facet: 'disposition',
        source: 'pnpk:dm-tipe2-dewasa-302-2026',
        locator: 'PDF p. 16: indikasi rujuk segera pada dekompensasi metabolik berat/penurunan berat badan cepat/ketonuria',
        claim: 'No-referral hanya konsisten bila kasus benar-benar stabil dan tanpa dekompensasi.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.harusDirujuk+anamnesis[dm_bb]+pemeriksaanFisik[umum]',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Normalisasi vignette menjadi nonkatabolik atau ubah seluruh archetype ke jalur rujuk/injeksi; pilihan minimal M13-0B adalah normalisasi vignette.',
      },
      {
        claimKind: 'follow_up',
        facet: 'follow-up',
        source: 'pnpk:dm-tipe2-dewasa-302-2026',
        locator: 'PDF pp. 54-59: evaluasi target dan intensifikasi; pp. 32-34: keselamatan OAD',
        claim: 'Pemantauan respons, efek samping, dan hipoglikemia harus menyertai kombinasi OAD.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.tatalaksana.edukasi',
        finding: 'coverage_gap',
        materiality: 'minor',
        proposedResolution: 'Pertahankan kontrol rutin dan tambahkan edukasi hipoglikemia yang spesifik.',
      },
      {
        claimKind: 'formulary',
        facet: 'formulary',
        source: 'fornas:kmk-1199-2025',
        locator: 'PDF p. 134: glibenklamid, glimepirid, dan metformin pada FPKTP',
        claim: 'Metformin, glimepirid, dan glibenklamid tercantum untuk FPKTP; alasan bahwa glibenklamid tidak ada di daftar Puskesmas tidak dapat dipertahankan.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#dm_tipe2.tatalaksana+src/content/katalog.ts#glibenclamide_5',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Hapus alasan ketidaktersediaan. Physician sign-off harus menentukan apakah glibenklamid menjadi alternatif yang diterima atau tetap non-preferred dengan alasan risiko hipoglikemia dan penalti yang proporsional.',
        corroboratingEvidence: [
          { source: 'doen:kmk-6477-2021', locator: 'PDF p. 29: glibenklamid 2,5/5 mg pada bagian Puskesmas; sumber historis sudah tidak berlaku' },
          { source: 'pnpk:dm-tipe2-dewasa-302-2026', locator: 'PDF pp. 54-59: pemilihan kombinasi dan preferensi obat berisiko hipoglikemia lebih rendah' },
        ],
      },
    ],
  },
  {
    id: 'm13-0b:stroke_iskemik',
    caseId: 'stroke_iskemik',
    archetypeId: 'clinic:stroke_iskemik',
    title: 'Stroke - delta PNPK 304/2026 dan PPK 1936/2022',
    currentIcd10: 'I64',
    population: 'dewasa dengan defisit neurologis akut saat bangun; last-known-well malam sebelumnya; belum ada CT kepala',
    reviewStatus: 'resolved',
    technicalReviewer: REVIEWER,
    reviewedAt: REVIEWED_AT,
    blockers: [],
    physicianSignoff: physicianSignoff(
      'approved',
      'Label klinis dan diagnosis primer diubah menjadi Suspek Stroke Akut/I64 sampai CT. Cairan dibuat kondisional, antitrombotik pra-pencitraan dan penurunan TD agresif dilarang, serta target keberangkatan rujukan <=30 menit ditambahkan.',
    ),
    claims: [
      {
        claimKind: 'diagnosis_threshold',
        facet: 'diagnosis',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF p. 15: CT kepala nonkontras untuk membedakan stroke iskemik dan hemoragik',
        claim: 'Tanpa pencitraan, FKTP dapat mengenali suspek stroke akut tetapi tidak menetapkan subtipe iskemik secara aman.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.nama+icd10+diagnosisBanding',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Pertahankan id teknis untuk kompatibilitas, tetapi ubah nama menjadi Suspek Stroke Akut, ICD menjadi I64, dan pilihan diagnosis primer menjadi I64 sampai CT.',
      },
      {
        claimKind: 'red_flags',
        facet: 'anamnesis',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF pp. 10-15: pengenalan klinis stroke, onset, dan diagnosis banding',
        claim: 'Defisit fokal akut, FAST, last-known-well, dan pemeriksaan glukosa adalah informasi pra-rujuk esensial.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.keluhanUtama+anamnesis+vital.gds',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan pola FAST, wake-up stroke, last-known-well, dan cek glukosa.',
      },
      {
        claimKind: 'assessment',
        facet: 'assessment',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF pp. 15 dan 28-29: pencitraan untuk subtipe serta assessment ABC/glukosa pra-rujuk',
        claim: 'Assessment FKTP berfokus pada ABC, glukosa, waktu onset/last-known-well, dan defisit neurologis; subtipe menunggu CT.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.pemeriksaanFisik+lab',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan assessment pra-rujuk, tetapi jangan menafsirkan ketiadaan CT sebagai bukti iskemik.',
      },
      {
        claimKind: 'regimen',
        facet: 'regimen',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF p. 28: stabilisasi pra-rumah sakit; kristaloid hanya bila dehidrasi, pre-syok, atau syok',
        claim: 'Tidak ada obat stroke definitif di FKTP sebelum pencitraan; cairan kristaloid bersifat kondisional, bukan rutin.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.tatalaksana+panduanResmi',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Ganti narasi cairan rutin dengan kristaloid hanya bila ada dehidrasi/pre-syok/syok; pertahankan nol obat definitif.',
        corroboratingEvidence: [
          { source: 'ppk:kmk-1936-2022', locator: 'PDF p. 147: regimen cairan rutin lama yang menimbulkan delta' },
        ],
      },
      {
        claimKind: 'contraindication',
        facet: 'contraindication',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF pp. 28-29: hindari antiplatelet/antikoagulan pra-rumah sakit dan hindari penurunan TD agresif',
        claim: 'Sebelum CT, jangan memberi antitrombotik dan jangan menurunkan TD agresif tanpa indikasi emergensi lain/protokol.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.tatalaksana.obatSalahUmum+clue',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Ganti ambang iskemik-spesifik dengan larangan pra-pencitraan yang netral subtipe dan tambahkan larangan antiplatelet/antikoagulan.',
      },
      {
        claimKind: 'disposition',
        facet: 'disposition',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF pp. 28-29: rujuk segera; persiapan keberangkatan maksimal 30 menit',
        claim: 'Suspek stroke akut harus distabilkan sambil mengaktifkan rujukan, dengan target keberangkatan tidak lebih dari 30 menit.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.harusDirujuk+clue+catatanRealita',
        finding: 'aligned',
        materiality: 'minor',
        proposedResolution: 'Pertahankan rujuk segera dan tambahkan target keberangkatan <=30 menit pada materi ajar.',
      },
      {
        claimKind: 'follow_up',
        facet: 'follow-up',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF pp. 28-29: dokumentasi, komunikasi, dan transfer ke fasilitas penerima',
        claim: 'Follow-up akut FKTP adalah handoff yang terdokumentasi; tata laksana definitif dan pencegahan sekunder mengikuti hasil pencitraan/fasilitas penerima.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.catatanRealita+konsekuensi',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan fokus pada handoff dan jangan memberi skor terapi sekunder sebelum diagnosis subtipe.',
      },
      {
        claimKind: 'formulary',
        facet: 'formulary',
        source: 'pnpk:stroke-304-2026',
        locator: 'PDF p. 28: tidak memberi antiplatelet/antikoagulan pra-rumah sakit; cairan kondisional',
        claim: 'Ketiadaan obat stroke definitif sebagai jawaban benar sesuai fase pra-pencitraan; isu utama adalah indikasi, bukan ketersediaan katalog.',
        contentLocator: 'src/content/kasus/kasusKronis.ts#stroke_iskemik.tatalaksana.obatBenar',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan obatBenar kosong dan pastikan UI tidak mendorong antitrombotik pra-CT.',
      },
    ],
  },
  {
    id: 'm13-0b:saraf_epilepsi_kejang',
    caseId: 'saraf_epilepsi_kejang',
    archetypeId: 'clinic:saraf_epilepsi_kejang',
    title: 'Epilepsi - pemisahan PNPK Dewasa 274/2026 dan PNPK Anak 367/2017',
    currentIcd10: 'G40.9',
    population: 'usia=18-30 tahun; tiga kejang tanpa provokasi dalam dua bulan; episode terakhir sekitar dua menit, telah berhenti, dan pasien stabil',
    reviewStatus: 'resolved',
    technicalReviewer: REVIEWER,
    reviewedAt: REVIEWED_AT,
    blockers: [],
    physicianSignoff: physicianSignoff(
      'approved',
      'Kasus dibatasi ke dewasa 18-30 tahun, bahasa pendamping dinetralkan, cue menatap dihapus, elektrolit dasar ditambahkan, dan diazepam rektal tidak lagi wajib setelah bangkitan berhenti. Rujuk tanpa memulai obat rumatan dipertahankan; archetype anak ditunda.',
    ),
    claims: [
      {
        claimKind: 'diagnosis_threshold',
        facet: 'diagnosis',
        source: 'pnpk:epilepsi-dewasa-274-2026',
        locator: 'PDF pp. 10-18: klasifikasi, diagnosis, dan evaluasi epilepsi dewasa',
        claim: 'Kejang tanpa provokasi berulang mendukung epilepsi, tetapi klasifikasi onset harus konsisten dengan deskripsi saksi dan populasi pedoman.',
        contentLocator: 'src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.nama+demografi+anamnesis',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Batasi kasus existing ke usia 18-30, netralkan sapaan pendamping, dan hapus cue menatap diam atau ubah klasifikasi secara eksplisit.',
        corroboratingEvidence: [
          { source: 'pnpk:epilepsi-anak-367-2017', locator: 'Bagian diagnosis dan klasifikasi epilepsi anak; populasi 12-17 tahun' },
        ],
      },
      {
        claimKind: 'red_flags',
        facet: 'anamnesis',
        source: 'pnpk:epilepsi-dewasa-274-2026',
        locator: 'PDF pp. 22-23: kejang aktif berkepanjangan atau berulang tanpa pulih sebagai kegawatan',
        claim: 'Benzodiazepin rescue diberikan saat bangkitan masih terjadi; kejang >5 menit atau berulang tanpa sadar penuh memicu rujuk segera, bukan pemberian otomatis setelah episode dua menit selesai.',
        contentLocator: 'src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.anamnesis+tatalaksana',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Pertahankan durasi dua menit dan status stabil; ajarkan rescue saat bangkitan masih aktif sesuai protokol, serta rujuk segera bila >5 menit/berulang tanpa pulih.',
      },
      {
        claimKind: 'assessment',
        facet: 'assessment',
        source: 'pnpk:epilepsi-dewasa-274-2026',
        locator: 'PDF pp. 17-18 dan 29-30: evaluasi penyebab, pemeriksaan dasar, dan peran FKTP',
        claim: 'Assessment mencakup glukosa dan, sesuai konteks, darah lengkap, elektrolit, fungsi ginjal, dan fungsi hati; interpretasi mengikuti populasi.',
        contentLocator: 'src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.lab+demografi',
        finding: 'coverage_gap',
        materiality: 'material',
        proposedResolution: 'Setelah populasi dewasa dikunci, tambahkan elektrolit serta fungsi ginjal/hati atau dokumentasikan keterbatasan pemeriksaan FKTP secara eksplisit.',
      },
      {
        claimKind: 'regimen',
        facet: 'regimen',
        source: 'pnpk:epilepsi-dewasa-274-2026',
        locator: 'PDF pp. 22-23 dan 29-30: rescue kejang aktif, rujukan, dan obat anti-bangkitan melalui layanan spesialis/rujuk balik',
        claim: 'Pasien stabil pascakejang tidak memerlukan diazepam rescue langsung; FKTP tidak memulai obat pemeliharaan tanpa jalur rujukan yang sesuai.',
        contentLocator: 'src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.tatalaksana.obatBenar+obatSalahUmum',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Hapus diazepam rektal dari obat wajib; pertahankan larangan memulai obat pemeliharaan dan rujuk untuk klasifikasi/terapi definitif.',
      },
      {
        claimKind: 'contraindication',
        facet: 'contraindication',
        source: 'pnpk:epilepsi-anak-367-2017',
        locator: 'Bagian tata laksana kejang berkepanjangan: benzodiazepin rescue dan pertimbangan rute pada anak yang lebih besar',
        claim: 'Rute, dosis, usia, status respirasi, dan apakah kejang masih aktif menentukan keamanan benzodiazepin; rute rektal bukan default universal usia 12-30.',
        contentLocator: 'src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.demografi+tatalaksana.obatBenar',
        finding: 'content_conflict',
        materiality: 'material',
        proposedResolution: 'Jangan menilai diazepam rektal sebagai tindakan rutin; defer archetype anak terpisah sampai regimen, rute, dan kewenangan lokal ditetapkan.',
      },
      {
        claimKind: 'disposition',
        facet: 'disposition',
        source: 'pnpk:epilepsi-dewasa-274-2026',
        locator: 'PDF pp. 29-30: rujukan diagnosis/terapi dan kelanjutan obat melalui rujuk balik',
        claim: 'Epilepsi baru memerlukan rujukan untuk klasifikasi dan rencana terapi; FKTP dapat melanjutkan obat melalui rujuk balik.',
        contentLocator: 'src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.harusDirujuk+tatalaksana',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan disposisi rujuk dan tidak memulai obat pemeliharaan di encounter ini.',
      },
      {
        claimKind: 'follow_up',
        facet: 'follow-up',
        source: 'pnpk:epilepsi-dewasa-274-2026',
        locator: 'PDF pp. 29-30: tindak lanjut dan rujuk balik epilepsi dewasa',
        claim: 'Tindak lanjut FKTP mencakup kepatuhan, efek samping, keselamatan kejang, dan obat dari rujuk balik, bukan improvisasi terapi awal.',
        contentLocator: 'src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.tatalaksana.edukasi+panduanResmi',
        finding: 'aligned',
        materiality: 'minor',
        proposedResolution: 'Pertahankan edukasi keselamatan dan pertegas mekanisme rujuk balik setelah populasi dewasa dikunci.',
      },
      {
        claimKind: 'formulary',
        facet: 'formulary',
        source: 'fornas:kmk-1199-2025',
        locator: 'PDF pp. 19-20: diazepam enema 5 mg dan 10 mg pada FPKTP, maksimal 2 tube/hari bila kejang',
        claim: 'Diazepam enema 10 mg tercantum untuk FPKTP; konflik kasus adalah indikasi pada episode yang sudah berhenti, bukan status formularium.',
        contentLocator: 'src/content/katalogM3.ts#diazepam_rektal_10+src/content/kasus/kasusSarafMataTht.ts#saraf_epilepsi_kejang.tatalaksana',
        finding: 'aligned',
        materiality: 'none',
        proposedResolution: 'Pertahankan fornas=true pada item; jangan jadikan enema jawaban wajib setelah kejang singkat telah berhenti.',
      },
    ],
  },
]

export function buildM13DeltaEvidenceBindings(): EvidenceBinding[] {
  return M13_DELTA_AUDITS.flatMap((record) =>
    record.claims.map((claim) => ({
      id: `evidence:${record.archetypeId}:m13-0b:${claim.claimKind}`,
      subject: { kind: 'encounter_archetype' as const, id: record.archetypeId },
      facet: claim.facet,
      icd10: claim.claimKind === 'diagnosis_threshold' ? record.currentIcd10 : undefined,
      source: claim.source,
      locator: claim.locator,
      population: record.population,
      reviewStatus: record.reviewStatus,
      audit: {
        deltaId: record.id,
        claimKind: claim.claimKind,
        claim: claim.claim,
        contentLocator: claim.contentLocator,
        finding: claim.finding,
        materiality: claim.materiality,
        technicalReviewer: record.technicalReviewer,
        reviewedAt: record.reviewedAt,
        proposedResolution: claim.proposedResolution,
        corroboratingEvidence: claim.corroboratingEvidence,
        physicianSignoff: record.physicianSignoff,
      },
    })),
  )
}

export function m13DeltaAuditByArchetype(archetypeId: string): DeltaAuditRecord | undefined {
  return M13_DELTA_AUDITS.find((record) => record.archetypeId === archetypeId)
}
