// Auto-generated
export const FAMILY_SDOH_EXPANDED = {
  "kk_31": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": true,
    "activity": "Active"
  },
  "kk_32": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Active"
  },
  "kk_33": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_34": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "University",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_35": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Active"
  },
  "kk_36": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_37": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Active"
  },
  "kk_38": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Active"
  },
  "kk_39": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Active"
  },
  "kk_40": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_41": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Elementary",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Active"
  },
  "kk_42": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": true,
    "activity": "Active"
  },
  "kk_43": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Active"
  },
  "kk_44": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_45": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_46": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_47": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_48": {
    "economy": "Very Low",
    "housing": "Semi-Permanent",
    "education": "No School",
    "water": "River",
    "sanitation": "Shared Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Active"
  },
  "kk_49": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": false,
    "activity": "Active"
  },
  "kk_50": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_51": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_52": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Active"
  },
  "kk_53": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Active"
  },
  "kk_54": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_55": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_56": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_57": {
    "economy": "High",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Active"
  },
  "kk_58": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_59": {
    "economy": "Very Low",
    "housing": "Make-shift/Bamboo",
    "education": "Elementary",
    "water": "Well",
    "sanitation": "River/Open",
    "diet": "Balanced",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_60": {
    "economy": "High",
    "housing": "Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_61": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Active"
  },
  "kk_62": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Active"
  },
  "kk_63": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_64": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_65": {
    "economy": "Low",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_66": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_67": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_68": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_69": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": false,
    "activity": "Active"
  },
  "kk_70": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_71": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_72": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_73": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_74": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Active"
  },
  "kk_75": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_76": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Active"
  },
  "kk_77": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_78": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_79": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_80": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_81": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_82": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_83": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_84": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Active"
  },
  "kk_85": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_86": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_87": {
    "economy": "High",
    "housing": "Permanent",
    "education": "University",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_88": {
    "economy": "Low",
    "housing": "Make-shift/Bamboo",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_89": {
    "economy": "Very Low",
    "housing": "Make-shift",
    "education": "Elementary",
    "water": "Well",
    "sanitation": "River/Open",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_90": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": true,
    "activity": "Active"
  },
  "kk_91": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_92": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_93": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_94": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Active"
  },
  "kk_95": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_96": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "University",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_97": {
    "economy": "Low",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_98": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "University",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_99": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_100": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Active"
  },
  "kk_101": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "Elementary",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_102": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_103": {
    "economy": "Low",
    "housing": "Make-shift",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Shared Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_104": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_105": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_106": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": true,
    "activity": "Active"
  },
  "kk_107": {
    "economy": "Very Low",
    "housing": "Semi-Permanent",
    "education": "Elementary",
    "water": "River",
    "sanitation": "River/Open",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_108": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Active"
  },
  "kk_109": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_110": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Active"
  },
  "kk_111": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_112": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_113": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_114": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_115": {
    "economy": "Low",
    "housing": "Old Permanent",
    "education": "Elementary",
    "water": "PDAM",
    "sanitation": "Shared Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_116": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_117": {
    "economy": "Low",
    "housing": "Make-shift",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_118": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_119": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Active"
  },
  "kk_120": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_121": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Elementary",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_122": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_123": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_124": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_125": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_126": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_127": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Active"
  },
  "kk_128": {
    "economy": "Low",
    "housing": "Make-shift",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_129": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Active"
  },
  "kk_130": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_131": {
    "economy": "Low",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Shared Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Active"
  },
  "kk_132": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_133": {
    "economy": "High",
    "housing": "Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_134": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_135": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Active"
  },
  "kk_136": {
    "economy": "Low",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Shared Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_137": {
    "economy": "Low",
    "housing": "Semi-Permanent",
    "education": "Elementary",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_138": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_139": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": true,
    "activity": "Active"
  },
  "kk_140": {
    "economy": "Low",
    "housing": "Make-shift/Bamboo",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Shared Latrine",
    "diet": "Poor Nutrition",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_141": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Active"
  },
  "kk_142": {
    "economy": "High",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_143": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_144": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Active"
  },
  "kk_145": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": false,
    "activity": "Active"
  },
  "kk_146": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_147": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_148": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_149": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_150": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Active"
  },
  "kk_151": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_152": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_153": {
    "economy": "Low",
    "housing": "Old Permanent",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Shared Latrine",
    "diet": "Instant Food",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_154": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_155": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_156": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_157": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_158": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_159": {
    "economy": "High",
    "housing": "Permanent",
    "education": "University",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Active"
  },
  "kk_160": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": true,
    "activity": "Active"
  },
  "kk_161": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_162": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_163": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_164": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Active"
  },
  "kk_165": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_166": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_167": {
    "economy": "High",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": true,
    "activity": "Active"
  },
  "kk_168": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Active"
  },
  "kk_169": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Active"
  },
  "kk_170": {
    "economy": "High",
    "housing": "Permanent (Large)",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": true,
    "activity": "Active"
  },
  "kk_171": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Active"
  },
  "kk_172": {
    "economy": "Low",
    "housing": "Make-shift",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Instant Food",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_173": {
    "economy": "Very Low",
    "housing": "Make-shift/Bamboo",
    "education": "Elementary",
    "water": "Well",
    "sanitation": "Shared Latrine",
    "diet": "Balanced",
    "smoking": true,
    "activity": "Active"
  },
  "kk_174": {
    "economy": "High",
    "housing": "Permanent",
    "education": "University",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Active"
  },
  "kk_175": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Elementary",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Deep Fried",
    "smoking": false,
    "activity": "Active"
  },
  "kk_176": {
    "economy": "High",
    "housing": "Permanent",
    "education": "University",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_177": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_178": {
    "economy": "Low",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_179": {
    "economy": "High",
    "housing": "Permanent",
    "education": "High School",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": true,
    "activity": "Active"
  },
  "kk_180": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Balanced",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_181": {
    "economy": "High",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_182": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_183": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_184": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": false,
    "activity": "Active"
  },
  "kk_185": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_186": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_187": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Traditional",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_188": {
    "economy": "Low",
    "housing": "Old Permanent",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Shared Latrine",
    "diet": "Traditional",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_189": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_190": {
    "economy": "Low",
    "housing": "Make-shift/Bamboo",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Fat",
    "smoking": true,
    "activity": "Active"
  },
  "kk_191": {
    "economy": "High",
    "housing": "Permanent",
    "education": "High School",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "Modern",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_192": {
    "economy": "Low-Middle",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_193": {
    "economy": "Low",
    "housing": "Make-shift/Bamboo",
    "education": "Junior High",
    "water": "River",
    "sanitation": "Shared Latrine",
    "diet": "Instant Food",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_194": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Low Sodium",
    "smoking": true,
    "activity": "Sedentary"
  },
  "kk_195": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Moderate"
  },
  "kk_196": {
    "economy": "Middle",
    "housing": "Permanent (Large)",
    "education": "Vocational",
    "water": "Well",
    "sanitation": "Private Latrine",
    "diet": "Low Protein",
    "smoking": true,
    "activity": "Active"
  },
  "kk_197": {
    "economy": "Low-Middle",
    "housing": "Old Permanent",
    "education": "High School",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "Poor Nutrition",
    "smoking": false,
    "activity": "Sedentary"
  },
  "kk_198": {
    "economy": "Low",
    "housing": "Semi-Permanent",
    "education": "Junior High",
    "water": "Well",
    "sanitation": "Shared Latrine",
    "diet": "High Sugar",
    "smoking": false,
    "activity": "Active"
  },
  "kk_199": {
    "economy": "Middle",
    "housing": "Permanent",
    "education": "Vocational",
    "water": "River",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": true,
    "activity": "Moderate"
  },
  "kk_200": {
    "economy": "Low-Middle",
    "housing": "Permanent",
    "education": "Junior High",
    "water": "PDAM",
    "sanitation": "Private Latrine",
    "diet": "High Salt",
    "smoking": false,
    "activity": "Active"
  }
};
export const FAMILY_INDICATORS_EXPANDED = {
  "kk_31": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_32": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_33": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_34": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_35": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_36": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_37": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_38": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_39": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_40": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_41": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_42": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_43": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_44": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_45": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_46": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_47": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_48": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": false,
    "jentik": true
  },
  "kk_49": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_50": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_51": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_52": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_53": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_54": {
    "kb": true,
    "persalinan": false,
    "imunisasi": false,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_55": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_56": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_57": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_58": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": false,
    "jiwa": false,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_59": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": true,
    "jamban": false,
    "jentik": false
  },
  "kk_60": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_61": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_62": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_63": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_64": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_65": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_66": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_67": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_68": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_69": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_70": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_71": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_72": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_73": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_74": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_75": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_76": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_77": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_78": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_79": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_80": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_81": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_82": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_83": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_84": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_85": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_86": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_87": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_88": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_89": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": false,
    "jentik": false
  },
  "kk_90": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_91": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_92": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_93": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_94": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_95": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_96": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_97": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_98": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_99": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_100": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_101": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_102": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_103": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": false,
    "jamban": false,
    "jentik": false
  },
  "kk_104": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_105": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_106": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": false,
    "rokok": false,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_107": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": false,
    "jentik": true
  },
  "kk_108": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_109": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_110": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_111": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_112": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_113": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_114": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_115": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": false,
    "jentik": true
  },
  "kk_116": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_117": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_118": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_119": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_120": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_121": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_122": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_123": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_124": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_125": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_126": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_127": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_128": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_129": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_130": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_131": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": false,
    "jentik": true
  },
  "kk_132": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_133": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_134": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_135": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_136": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": false,
    "jentik": true
  },
  "kk_137": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_138": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_139": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_140": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": false,
    "jentik": true
  },
  "kk_141": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_142": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_143": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_144": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_145": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_146": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_147": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_148": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_149": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_150": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_151": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_152": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_153": {
    "kb": false,
    "persalinan": true,
    "imunisasi": false,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": false,
    "jentik": true
  },
  "kk_154": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_155": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_156": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_157": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_158": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_159": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_160": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_161": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_162": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_163": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_164": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": false
  },
  "kk_165": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_166": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_167": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_168": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_169": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_170": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_171": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": false,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_172": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_173": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": false,
    "jentik": true
  },
  "kk_174": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_175": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_176": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_177": {
    "kb": false,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_178": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_179": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_180": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_181": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_182": {
    "kb": true,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_183": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_184": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_185": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_186": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_187": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_188": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": false,
    "jentik": false
  },
  "kk_189": {
    "kb": true,
    "persalinan": false,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_190": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": false,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_191": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_192": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_193": {
    "kb": false,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": false,
    "jamban": false,
    "jentik": false
  },
  "kk_194": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_195": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": true,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_196": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": false,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": true,
    "jamban": true,
    "jentik": true
  },
  "kk_197": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": false
  },
  "kk_198": {
    "kb": false,
    "persalinan": true,
    "imunisasi": false,
    "asi": true,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": false,
    "jentik": true
  },
  "kk_199": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": true,
    "jiwa": true,
    "rokok": false,
    "jkn": true,
    "air": false,
    "jamban": true,
    "jentik": true
  },
  "kk_200": {
    "kb": true,
    "persalinan": true,
    "imunisasi": true,
    "asi": false,
    "balita": true,
    "tb": true,
    "hipertensi": false,
    "jiwa": true,
    "rokok": true,
    "jkn": false,
    "air": true,
    "jamban": true,
    "jentik": true
  }
};
