/**
 * KATALOG — formularium obat, item laboratorium, dan topik edukasi Puskesmas.
 * Id KANONIK sesuai BUILD_SPECS; jangan menambah/mengubah id tanpa mengubah spec.
 * Harga dalam rupiah, wajar untuk Puskesmas 2026 (hargaBeli e-katalog < hargaJual
 * tarif retribusi pasien umum). Obat program (OAT) tetap diberi harga nominal
 * untuk pembukuan kapitasi.
 */

import type { Obat, ItemLab, TopikEdukasi } from './types'

/* ---------------------------------------------------------------------------
 * FORMULARIUM (36 item)
 * ------------------------------------------------------------------------- */

export const OBAT: Record<string, Obat> = {
  paracetamol_500: {
    id: 'paracetamol_500',
    nama: 'Parasetamol 500 mg',
    kelas: 'Analgetik-antipiretik',
    sediaan: 'Tablet 500 mg',
    hargaBeli: 150,
    hargaJual: 300,
    fornas: true,
  },
  paracetamol_sirup: {
    id: 'paracetamol_sirup',
    nama: 'Parasetamol Sirup 120 mg/5 mL',
    kelas: 'Analgetik-antipiretik',
    sediaan: 'Sirup 60 mL',
    hargaBeli: 3500,
    hargaJual: 6500,
    fornas: true,
  },
  ibuprofen_400: {
    id: 'ibuprofen_400',
    nama: 'Ibuprofen 400 mg',
    kelas: 'NSAID',
    golonganAlergi: 'nsaid',
    sediaan: 'Tablet 400 mg',
    hargaBeli: 250,
    hargaJual: 500,
    fornas: true,
  },
  amoxicillin_500: {
    id: 'amoxicillin_500',
    nama: 'Amoksisilin 500 mg',
    kelas: 'Antibiotik penisilin',
    golonganAlergi: 'penisilin',
    sediaan: 'Kaplet 500 mg',
    hargaBeli: 400,
    hargaJual: 750,
    fornas: true,
    antibiotik: true,
  },
  amoxicillin_sirup: {
    id: 'amoxicillin_sirup',
    nama: 'Amoksisilin Sirup Kering 125 mg/5 mL',
    kelas: 'Antibiotik penisilin',
    golonganAlergi: 'penisilin',
    sediaan: 'Sirup kering 60 mL',
    hargaBeli: 5000,
    hargaJual: 9000,
    fornas: true,
    antibiotik: true,
  },
  eritromisin_500: {
    id: 'eritromisin_500',
    nama: 'Eritromisin 500 mg',
    kelas: 'Antibiotik makrolida',
    golonganAlergi: 'makrolida',
    sediaan: 'Tablet 500 mg',
    hargaBeli: 900,
    hargaJual: 1600,
    fornas: true,
    antibiotik: true,
  },
  ciprofloxacin_500: {
    id: 'ciprofloxacin_500',
    nama: 'Siprofloksasin 500 mg',
    kelas: 'Antibiotik fluorokuinolon',
    golonganAlergi: 'kuinolon',
    sediaan: 'Tablet 500 mg',
    hargaBeli: 400,
    hargaJual: 750,
    fornas: true,
    antibiotik: true,
  },
  kloramfenikol_250: {
    id: 'kloramfenikol_250',
    nama: 'Kloramfenikol 250 mg',
    kelas: 'Antibiotik spektrum luas',
    golonganAlergi: 'amfenikol',
    sediaan: 'Kapsul 250 mg',
    hargaBeli: 450,
    hargaJual: 850,
    fornas: true,
    antibiotik: true,
  },
  cotrimoxazole_480: {
    id: 'cotrimoxazole_480',
    nama: 'Kotrimoksazol 480 mg',
    kelas: 'Antibiotik sulfonamid',
    golonganAlergi: 'sulfa',
    sediaan: 'Tablet 480 mg (SMZ 400/TMP 80)',
    hargaBeli: 300,
    hargaJual: 600,
    fornas: true,
    antibiotik: true,
  },
  metformin_500: {
    id: 'metformin_500',
    nama: 'Metformin 500 mg',
    kelas: 'Antidiabetik biguanid',
    sediaan: 'Tablet 500 mg',
    hargaBeli: 200,
    hargaJual: 400,
    fornas: true,
  },
  glibenclamide_5: {
    id: 'glibenclamide_5',
    nama: 'Glibenklamid 5 mg',
    kelas: 'Antidiabetik sulfonilurea',
    sediaan: 'Tablet 5 mg',
    hargaBeli: 150,
    hargaJual: 300,
    fornas: true,
  },
  amlodipine_5: {
    id: 'amlodipine_5',
    nama: 'Amlodipin 5 mg',
    kelas: 'Antihipertensi CCB',
    sediaan: 'Tablet 5 mg',
    hargaBeli: 200,
    hargaJual: 400,
    fornas: true,
  },
  amlodipine_10: {
    id: 'amlodipine_10',
    nama: 'Amlodipin 10 mg',
    kelas: 'Antihipertensi CCB',
    sediaan: 'Tablet 10 mg',
    hargaBeli: 250,
    hargaJual: 500,
    fornas: true,
  },
  captopril_25: {
    id: 'captopril_25',
    nama: 'Kaptopril 25 mg',
    kelas: 'Antihipertensi ACE inhibitor',
    sediaan: 'Tablet 25 mg',
    hargaBeli: 150,
    hargaJual: 300,
    fornas: true,
  },
  hct_25: {
    id: 'hct_25',
    nama: 'Hidroklorotiazid (HCT) 25 mg',
    kelas: 'Diuretik tiazid',
    sediaan: 'Tablet 25 mg',
    hargaBeli: 150,
    hargaJual: 300,
    fornas: true,
  },
  omeprazole_20: {
    id: 'omeprazole_20',
    nama: 'Omeprazol 20 mg',
    kelas: 'Penghambat pompa proton (PPI)',
    sediaan: 'Kapsul 20 mg',
    hargaBeli: 350,
    hargaJual: 700,
    fornas: true,
  },
  antasida_doen: {
    id: 'antasida_doen',
    nama: 'Antasida DOEN',
    sinonim: ['antacid','obat maag','aluminium magnesium hidroksida'],
    kelas: 'Antasida',
    sediaan: 'Tablet kunyah (Al(OH)3 200/Mg(OH)2 200)',
    hargaBeli: 150,
    hargaJual: 300,
    fornas: true,
  },
  ranitidin_150: {
    id: 'ranitidin_150',
    nama: 'Ranitidin 150 mg',
    kelas: 'Antagonis reseptor H2',
    sediaan: 'Tablet 150 mg',
    hargaBeli: 300,
    hargaJual: 600,
    fornas: true,
  },
  oralit: {
    id: 'oralit',
    nama: 'Oralit (Larutan Rehidrasi Oral)',
    sinonim: ['ORS','oral rehydration salt','larutan gula garam'],
    kelas: 'Rehidrasi oral',
    sediaan: 'Serbuk sachet 200 mL',
    hargaBeli: 600,
    hargaJual: 1200,
    fornas: true,
  },
  zinc_20: {
    id: 'zinc_20',
    nama: 'Zinc 20 mg',
    kelas: 'Suplemen terapi diare anak',
    sediaan: 'Tablet dispersibel 20 mg',
    hargaBeli: 400,
    hargaJual: 800,
    fornas: true,
  },
  salbutamol_2: {
    id: 'salbutamol_2',
    nama: 'Salbutamol 2 mg',
    kelas: 'Bronkodilator beta-2 agonis',
    sediaan: 'Tablet 2 mg',
    hargaBeli: 150,
    hargaJual: 300,
    fornas: true,
  },
  salbutamol_inhaler: {
    id: 'salbutamol_inhaler',
    nama: 'Salbutamol Inhaler 100 mcg',
    kelas: 'Bronkodilator beta-2 agonis',
    sediaan: 'MDI 100 mcg/semprot, 200 dosis',
    hargaBeli: 48000,
    hargaJual: 65000,
    fornas: true,
  },
  budesonide_inhaler: {
    id: 'budesonide_inhaler',
    nama: 'Budesonid Inhaler 200 mcg',
    kelas: 'Kortikosteroid inhalasi (ICS) — pengendali asma',
    sediaan: 'MDI/DPI 200 mcg/dosis',
    hargaBeli: 62000,
    hargaJual: 85000,
    fornas: true,
  },
  cetirizine_10: {
    id: 'cetirizine_10',
    nama: 'Setirizin 10 mg',
    kelas: 'Antihistamin generasi 2',
    sediaan: 'Tablet 10 mg',
    hargaBeli: 250,
    hargaJual: 500,
    fornas: true,
  },
  ctm_4: {
    id: 'ctm_4',
    nama: 'Klorfeniramin Maleat (CTM) 4 mg',
    sinonim: ['klorfeniramin','chlorpheniramine','chlorphenamine'],
    kelas: 'Antihistamin generasi 1',
    sediaan: 'Tablet 4 mg',
    hargaBeli: 100,
    hargaJual: 200,
    fornas: true,
  },
  dexamethasone_05: {
    id: 'dexamethasone_05',
    nama: 'Deksametason 0,5 mg',
    kelas: 'Kortikosteroid sistemik',
    sediaan: 'Tablet 0,5 mg',
    hargaBeli: 100,
    hargaJual: 250,
    fornas: true,
  },
  prednison_5: {
    id: 'prednison_5',
    nama: 'Prednison 5 mg',
    kelas: 'Kortikosteroid sistemik',
    sediaan: 'Tablet 5 mg',
    hargaBeli: 150,
    hargaJual: 300,
    fornas: true,
  },
  hidrokortison_krim: {
    id: 'hidrokortison_krim',
    nama: 'Hidrokortison Krim 2,5%',
    kelas: 'Kortikosteroid topikal',
    sediaan: 'Krim tube 5 g',
    hargaBeli: 4500,
    hargaJual: 8000,
    fornas: true,
  },
  permetrin_krim: {
    id: 'permetrin_krim',
    nama: 'Permetrin Krim 5%',
    kelas: 'Skabisida topikal',
    sediaan: 'Krim tube 30 g',
    hargaBeli: 13000,
    hargaJual: 20000,
    fornas: true,
  },
  ketokonazol_krim: {
    id: 'ketokonazol_krim',
    nama: 'Ketokonazol Krim 2%',
    kelas: 'Antijamur topikal',
    sediaan: 'Krim tube 10 g',
    hargaBeli: 6000,
    hargaJual: 10000,
    fornas: true,
  },
  kloramfenikol_tetes_mata: {
    id: 'kloramfenikol_tetes_mata',
    nama: 'Kloramfenikol Tetes Mata 0,5%',
    kelas: 'Antibiotik topikal mata',
    golonganAlergi: 'amfenikol',
    sediaan: 'Botol tetes 5 mL',
    hargaBeli: 7000,
    hargaJual: 12000,
    fornas: true,
    antibiotik: true,
  },
  oat_kdt: {
    id: 'oat_kdt',
    nama: 'OAT KDT Kategori 1 (RHZE)',
    sinonim: ['OAT','obat anti tuberkulosis','rifampisin isoniazid pirazinamid etambutol','FDC TB'],
    kelas: 'Anti-tuberkulosis (obat program)',
    sediaan: 'Paket KDT fase intensif, 28 blister',
    hargaBeli: 185000,
    hargaJual: 195000,
    fornas: true,
    antibiotik: true,
  },
  tablet_fe: {
    id: 'tablet_fe',
    nama: 'Tablet Tambah Darah (Fe)',
    sinonim: ['tablet tambah darah','TTD','sulfas ferosus','ferrous sulfate','zat besi'],
    kelas: 'Suplemen besi',
    sediaan: 'Tablet salut (Fe 60 mg + asam folat 0,4 mg)',
    hargaBeli: 200,
    hargaJual: 400,
    fornas: true,
  },
  asam_folat: {
    id: 'asam_folat',
    nama: 'Asam Folat 1 mg',
    sinonim: ['folic acid','folat'],
    kelas: 'Suplemen vitamin',
    sediaan: 'Tablet 1 mg',
    hargaBeli: 100,
    hargaJual: 250,
    fornas: true,
  },
  vitamin_b_kompleks: {
    id: 'vitamin_b_kompleks',
    nama: 'Vitamin B Kompleks',
    kelas: 'Suplemen vitamin',
    sediaan: 'Tablet',
    hargaBeli: 100,
    hargaJual: 250,
    fornas: true,
  },
  ambroxol_30: {
    id: 'ambroxol_30',
    nama: 'Ambroksol 30 mg',
    kelas: 'Mukolitik',
    sediaan: 'Tablet 30 mg',
    hargaBeli: 200,
    hargaJual: 400,
    fornas: true,
  },
  domperidon_10: {
    id: 'domperidon_10',
    nama: 'Domperidon 10 mg',
    kelas: 'Antiemetik prokinetik',
    sediaan: 'Tablet 10 mg',
    hargaBeli: 300,
    hargaJual: 600,
    fornas: true,
  },
}

/* ---------------------------------------------------------------------------
 * KATALOG LABORATORIUM (14 item — biaya tarif retribusi Puskesmas)
 * ------------------------------------------------------------------------- */

export const LAB: Record<string, ItemLab> = {
  darah_rutin: {
    id: 'darah_rutin',
    nama: 'Darah Rutin (Hb, leukosit, trombosit, hematokrit)',
    biaya: 25000,
    nilaiNormal: 'Hb 12–16 g/dL; leukosit 4.000–10.000/µL; trombosit 150.000–400.000/µL; Ht 37–47%',
  },
  widal: {
    id: 'widal',
    nama: 'Uji Widal',
    biaya: 30000,
    nilaiNormal: 'Titer O dan H < 1/160',
    hasilBesok: true,
  },
  ns1_dengue: {
    id: 'ns1_dengue',
    nama: 'NS1 Antigen Dengue',
    biaya: 90000,
    nilaiNormal: 'Negatif',
  },
  bta_sputum: {
    id: 'bta_sputum',
    nama: 'BTA Sputum (sewaktu-pagi)',
    biaya: 25000,
    nilaiNormal: 'Negatif',
    hasilBesok: true,
  },
  gds: {
    id: 'gds',
    nama: 'Gula Darah Sewaktu (GDS)',
    biaya: 15000,
    nilaiNormal: '< 200 mg/dL',
  },
  gdp: {
    id: 'gdp',
    nama: 'Gula Darah Puasa (GDP)',
    biaya: 15000,
    nilaiNormal: '70–100 mg/dL',
  },
  urinalisis: {
    id: 'urinalisis',
    nama: 'Urinalisis (carik celup + sedimen)',
    biaya: 20000,
    nilaiNormal: 'Protein (−), glukosa (−), leukosit 0–5/LPB, eritrosit 0–2/LPB',
  },
  tes_kehamilan: {
    id: 'tes_kehamilan',
    nama: 'Tes Kehamilan (hCG urine)',
    biaya: 15000,
    nilaiNormal: 'Negatif',
  },
  hb: {
    id: 'hb',
    nama: 'Hemoglobin (Hb)',
    biaya: 15000,
    nilaiNormal: 'Pria 13–17 g/dL; wanita 12–16 g/dL; bumil ≥ 11 g/dL',
  },
  golongan_darah: {
    id: 'golongan_darah',
    nama: 'Golongan Darah ABO + Rhesus',
    biaya: 15000,
    nilaiNormal: 'A/B/AB/O, Rh(+/−)',
  },
  // Bug live (2026-07-05): entri `asam_urat` (generik, tak dipakai kasus
  // manapun) DIHAPUS — near-duplikat `asam_urat_darah` (katalogM3.ts, dipakai
  // mm_gout_artritis_akut) dgn nama nyaris identik, gampang salah pilih saat
  // pesan lab (dapat hasil generik "normal" ketimbang narasi kasus 9.2 tinggi).
  // Jangan tambah lagi entri "Asam Urat" generik — pakai asam_urat_darah.
  kolesterol: {
    id: 'kolesterol',
    nama: 'Kolesterol Total',
    biaya: 25000,
    nilaiNormal: '< 200 mg/dL',
  },
  malaria_rdt: {
    id: 'malaria_rdt',
    nama: 'RDT Malaria',
    biaya: 30000,
    nilaiNormal: 'Negatif',
  },
  feses_rutin: {
    id: 'feses_rutin',
    nama: 'Feses Rutin (makroskopis + mikroskopis)',
    biaya: 20000,
    nilaiNormal: 'Tidak ditemukan telur cacing, amuba, darah, atau lendir',
  },
}

/* ---------------------------------------------------------------------------
 * KATALOG TOPIK EDUKASI (18 topik)
 * ------------------------------------------------------------------------- */

/**
 * M7 (34b): keyword front-loading — pembeda di DEPAN label agar bisa dipindai,
 * bukan dibaca utuh ("Blok K"). Pagar anti-bocor di doc TopikEdukasi.
 * Merger: kepatuhan_kontrol_ptm dilebur ke kontrol_rutin (kembar sejati).
 */
export const EDUKASI: Record<string, TopikEdukasi> = {
  kepatuhan_obat: {
    id: 'kepatuhan_obat', nama: 'Kepatuhan minum obat', kategori: 'kepatuhan',
    sinonim: ['adherence', 'compliance', 'rutin minum obat'],
  },
  diet_rendah_garam: {
    id: 'diet_rendah_garam', nama: 'Diet rendah garam', kategori: 'diet',
    sinonim: ['natrium', 'sodium', 'asin'],
  },
  diet_dm: {
    id: 'diet_dm', nama: 'Diet diabetes — 3J (jumlah, jadwal, jenis)', kategori: 'diet',
    sinonim: ['gula', 'kencing manis', 'pengaturan makan'],
  },
  cairan_oralit: {
    id: 'cairan_oralit', nama: 'Oralit — cara membuat & memberi', kategori: 'tindakan',
    sinonim: ['ORS', 'rehidrasi', 'larutan gula garam'],
  },
  tanda_bahaya: {
    id: 'tanda_bahaya', nama: 'Tanda bahaya — kapan harus segera kembali', kategori: 'kepatuhan',
    sinonim: ['red flag', 'warning sign', 'kembali ke puskesmas'],
  },
  psn_3m: {
    id: 'psn_3m', nama: 'PSN 3M Plus — berantas jentik', kategori: 'higiene',
    sinonim: ['nyamuk', 'jumantik', 'menguras menutup mendaur'],
  },
  kompres_demam: {
    id: 'kompres_demam', nama: '[Demam] Kompres hangat', kategori: 'tindakan',
    sinonim: ['panas', 'antipiretik non obat'],
  },
  etika_batuk: {
    id: 'etika_batuk', nama: 'Etika batuk & pakai masker', kategori: 'higiene',
    sinonim: ['droplet', 'penularan napas'],
  },
  cuci_tangan: {
    id: 'cuci_tangan', nama: 'Cuci tangan pakai sabun (CTPS)', kategori: 'higiene',
    sinonim: ['hand hygiene', 'handwash'],
  },
  asi_eksklusif: {
    id: 'asi_eksklusif', nama: '[Bayi] ASI eksklusif 6 bulan', kategori: 'kia',
    sinonim: ['menyusui', 'laktasi', 'breastfeeding'],
  },
  gizi_seimbang: {
    id: 'gizi_seimbang', nama: 'Gizi seimbang (Isi Piringku)', kategori: 'diet',
    sinonim: ['nutrisi', 'makanan sehat'],
  },
  berhenti_merokok: {
    id: 'berhenti_merokok', nama: 'Berhenti merokok', kategori: 'gaya_hidup',
    sinonim: ['rokok', 'tembakau', 'smoking cessation'],
  },
  aktivitas_fisik: {
    id: 'aktivitas_fisik', nama: 'Aktivitas fisik 30 menit/hari', kategori: 'gaya_hidup',
    sinonim: ['olahraga', 'exercise', 'gerak'],
  },
  kontrol_rutin: {
    id: 'kontrol_rutin', nama: 'Kontrol rutin sesuai jadwal & cegah komplikasi', kategori: 'kepatuhan',
    sinonim: ['kontrol PTM', 'kontrol berkala', 'check up', 'follow up'],
  },
  minum_oat_tuntas: {
    id: 'minum_oat_tuntas', nama: 'OAT tuntas 6 bulan + PMO', kategori: 'kepatuhan',
    sinonim: ['TB', 'tuberkulosis', 'pengawas minum obat'],
  },
  kebersihan_kulit: {
    id: 'kebersihan_kulit', nama: '[Kulit] Kebersihan kulit & pakaian', kategori: 'higiene',
    sinonim: ['mandi', 'ganti baju'],
  },
  hindari_alergen: {
    id: 'hindari_alergen', nama: '[Alergi] Kenali & hindari alergen pencetus', kategori: 'gaya_hidup',
    sinonim: ['alergen', 'pencetus alergi'],
  },
  istirahat_cukup: {
    id: 'istirahat_cukup', nama: 'Istirahat cukup', kategori: 'gaya_hidup',
    sinonim: ['rest', 'kurangi beban kerja'],
  },
}
