/**
 * NAMA WARGA — bank nama untuk generator pasien & keluarga.
 * Beragam etnis Nusantara (Jawa, Sunda, Bali, Batak, Minang, Bugis, Betawi,
 * Madura, Ambon, Papua, Dayak, Tionghoa) supaya desa terasa hidup dan majemuk.
 * Dipakai `buatPasienDariKasus` (director) sesuai jenis kelamin kasus.
 */

export const NAMA_WARGA: { pria: string[]; wanita: string[]; keluarga: string[] } = {
  pria: [
    'Budi',
    'Agus',
    'Slamet',
    'Joko',
    'Bambang',
    'Tono',
    'Wahyu',
    'Dedi',
    'Asep',
    'Ujang',
    'Cecep',
    'Made Putra',
    'Ketut Arta',
    'Wayan Sudira',
    'Nyoman Gede',
    'Hasan',
    'Usman',
    'Firman',
    'Rahmat',
    'Syahrul',
    'Togar',
    'Binsar',
    'Hotman',
    'Parlin',
    'Rizal',
    'Fauzi',
    'Andi Baso',
    'Daeng Naba',
    'La Ode',
    'Mateus',
    'Yohanes',
    'Petrus',
    'Yakobus',
    'Ahong',
    'Hendra',
    'Wira',
    'Galih',
    'Eko',
    'Sugeng',
    'Paiman',
    'Karta',
    'Dullah',
  ],
  wanita: [
    'Siti',
    'Sri',
    'Wati',
    'Ningsih',
    'Sumiati',
    'Painem',
    'Lastri',
    'Endang',
    'Euis',
    'Nyai',
    'Icih',
    'Made Ayu',
    'Ketut Sari',
    'Wayan Rini',
    'Nyoman Padmi',
    'Aminah',
    'Fatimah',
    'Halimah',
    'Nurhayati',
    'Rohani',
    'Tiur',
    'Butet',
    'Rosmaida',
    'Sondang',
    'Rahmi',
    'Yusnita',
    'Andi Tenri',
    'Daeng Kanang',
    'Wa Ode',
    'Maria',
    'Yohana',
    'Martha',
    'Fransina',
    'Aling',
    'Melati',
    'Dewi',
    'Ratna',
    'Lestari',
    'Sartika',
    'Murni',
    'Kartini',
    'Saodah',
  ],
  keluarga: [
    'Santoso',
    'Wibowo',
    'Prasetyo',
    'Hartono',
    'Nugroho',
    'Setiawan',
    'Raharjo',
    'Susanto',
    'Widodo',
    'Kusuma',
    'Suryana',
    'Permana',
    'Hidayat',
    'Ramdani',
    'Sutisna',
    'Sudirga',
    'Wirawan',
    'Adnyana',
    'Mahendra',
    'Siregar',
    'Simanjuntak',
    'Hutapea',
    'Nasution',
    'Harahap',
    'Chaniago',
    'Piliang',
    'Mangunsong',
    'Sikumbang',
    'Latuconsina',
    'Pattinama',
    'Wenda',
    'Kogoya',
    'Rumbewas',
    'Tjahjadi',
    'Gunawan',
    'Halim',
    'Wijaya',
    'Salim',
    'Pranata',
    'Atmaja',
    'Saputra',
    'Firdaus',
  ],
}
