/**
 * NAMA WARGA — bank nama untuk generator pasien & keluarga.
 * Beragam etnis Nusantara (Jawa, Sunda, Bali, Batak, Minang, Bugis, Betawi,
 * Madura, Ambon, Papua, Dayak, Tionghoa) supaya desa terasa hidup dan majemuk.
 * Dipakai `buatPasienDariKasus` (director) sesuai jenis kelamin kasus.
 *
 * M10.b (2026-07-06, dossier §43): pool pria/wanita WAJIB disjoint dari nama
 * anggota keluarga binaan (desaA-F) — dulu 17 nama tumpang tindih (termasuk
 * identitas karma "Lastri"/"Painem") sehingga pasien acak bisa bernama persis
 * anggota binaan aktif. Dijaga test `pack.test.ts` — kalau menambah nama di
 * sini ATAU anggota keluarga baru, test itu yang memberi tahu bila bentrok.
 * Pool `keluarga` (marga) TIDAK dipakai runtime mana pun saat ini (data mati,
 * dibiarkan utk kebutuhan masa depan) — tak tercakup guard.
 */

export const NAMA_WARGA: { pria: string[]; wanita: string[]; keluarga: string[] } = {
  pria: [
    'Budi',
    'Agus',
    'Tarjo',
    'Gilang',
    'Ramli',
    'Tono',
    'Wahyu',
    'Dedi',
    'Asep',
    'Ujang',
    'Cecep',
    'Made Putra',
    'Ketut Arta',
    'Wayan Sudira',
    'Nyoman Gede',
    'Hasan',
    'Usman',
    'Firman',
    'Rahmat',
    'Syahrul',
    'Togar',
    'Binsar',
    'Hotman',
    'Parlin',
    'Rizal',
    'Fauzi',
    'Andi Baso',
    'Daeng Naba',
    'La Ode',
    'Mateus',
    'Yohanes',
    'Petrus',
    'Yakobus',
    'Ahong',
    'Sadikin',
    'Wira',
    'Galih',
    'Kusnadi',
    'Sugeng',
    'Paiman',
    'Karta',
    'Dullah',
  ],
  wanita: [
    'Juminten',
    'Suparti',
    'Rukmini',
    'Ningsih',
    'Darsih',
    'Nurlela',
    'Hasanah',
    'Mimin',
    'Euis',
    'Nyai',
    'Icih',
    'Made Ayu',
    'Ketut Sari',
    'Wayan Rini',
    'Nyoman Padmi',
    'Enok',
    'Fatimah',
    'Halimah',
    'Nurhayati',
    'Rohani',
    'Tiur',
    'Butet',
    'Rosmaida',
    'Sondang',
    'Odah',
    'Yusnita',
    'Andi Tenri',
    'Daeng Kanang',
    'Wa Ode',
    'Maria',
    'Yohana',
    'Martha',
    'Fransina',
    'Aling',
    'Melati',
    'Narti',
    'Sulami',
    'Warsiti',
    'Sartika',
    'Murni',
    'Kartini',
    'Saodah',
  ],
  keluarga: [
    'Santoso',
    'Wibowo',
    'Prasetyo',
    'Hartono',
    'Nugroho',
    'Setiawan',
    'Raharjo',
    'Susanto',
    'Widodo',
    'Kusuma',
    'Suryana',
    'Permana',
    'Hidayat',
    'Ramdani',
    'Sutisna',
    'Sudirga',
    'Wirawan',
    'Adnyana',
    'Mahendra',
    'Siregar',
    'Simanjuntak',
    'Hutapea',
    'Nasution',
    'Harahap',
    'Chaniago',
    'Piliang',
    'Mangunsong',
    'Sikumbang',
    'Latuconsina',
    'Pattinama',
    'Wenda',
    'Kogoya',
    'Rumbewas',
    'Tjahjadi',
    'Gunawan',
    'Halim',
    'Wijaya',
    'Salim',
    'Pranata',
    'Atmaja',
    'Saputra',
    'Firdaus',
  ],
}
